import { computed, type ComputedRef } from "vue";
import { useNasaq } from "../../provider";

// Same strings as the React component (packages/web/src/components/desktop-locations).
export const STRINGS = {
  en: {
    title: "Locations on this computer",
    description: "Folders the desktop app can read and change for you. It cannot open anything outside them.",
    list: "Locations",
    add: "Add folder",
    count: (n: number) => (n === 1 ? "1 folder" : `${n} folders`),
    emptyTitle: "No folders yet",
    emptyBody: "Add the folders you work in. Until you do, the desktop app cannot read or write any files.",
    loading: "Loading locations",
    primary: "Default",
    makeDefault: (name: string) => `Make ${name} the default`,
    defaultHint: "Relative paths resolve against the default folder.",
    reindex: (name: string) => `Re-index ${name}`,
    remove: (name: string) => `Remove ${name}`,
    files: (n: number) => (n === 1 ? "1 file" : `${n} files`),
    indexed: "Indexed",
    notIndexed: "Not indexed",
    permissions: "Permissions",
    read: "Read",
    readHint: "List and open files",
    write: "Write",
    writeHint: "Create and change files",
    index: "Search index",
    indexHint: "Include in local search",
    status: {
      ready: "Ready",
      indexing: "Indexing",
      missing: "Folder not found",
      "not-directory": "Not a folder",
      denied: "Access denied by the system",
    },
    genericError: "Something went wrong. Try again.",
    // add
    addTitle: "Add a folder",
    addBody: "Choose a folder on this computer. The desktop app gets access to it and everything inside.",
    pathLabel: "Folder path",
    pathPlaceholder: "C:\\Users\\you\\projects\\app",
    browse: "Browse",
    problemEmpty: "Enter the folder path.",
    problemRelative: "Use a full path that starts at a drive, a share or the root.",
    problemDuplicate: "This folder is already on the list.",
    warnInside: (other: string) => `Already covered by ${other}.`,
    warnContains: (other: string) => `Includes ${other}, which is already on the list.`,
    cancel: "Cancel",
    save: "Add folder",
    // remove
    removeTitle: (name: string) => `Remove ${name}?`,
    removeBody: "The desktop app loses access to this folder and its search index is deleted. Your files are not touched.",
    removeConfirm: "Remove",
    // picker
    pick: "Choose a location",
    pickEmpty: "No usable locations",
    unavailable: "unavailable",
  },
  ar: {
    title: "المواقع على هذا الجهاز",
    description: "المجلدات التي يستطيع تطبيق سطح المكتب قراءتها وتعديلها نيابةً عنك. ولا يستطيع فتح أي شيء خارجها.",
    list: "المواقع",
    add: "إضافة مجلد",
    count: (n: number) => (n === 1 ? "مجلد واحد" : n === 2 ? "مجلدان" : n >= 3 && n <= 10 ? `${n} مجلدات` : `${n} مجلدًا`),
    emptyTitle: "لا توجد مجلدات بعد",
    emptyBody: "أضف المجلدات التي تعمل فيها. وإلى أن تفعل، لا يستطيع تطبيق سطح المكتب قراءة أو كتابة أي ملف.",
    loading: "جارٍ تحميل المواقع",
    primary: "الافتراضي",
    makeDefault: (name: string) => `جعل ${name} الافتراضي`,
    defaultHint: "تُحسم المسارات النسبية بالنسبة إلى المجلد الافتراضي.",
    reindex: (name: string) => `إعادة فهرسة ${name}`,
    remove: (name: string) => `إزالة ${name}`,
    files: (n: number) => (n === 1 ? "ملف واحد" : n === 2 ? "ملفان" : n >= 3 && n <= 10 ? `${n} ملفات` : `${n} ملفًا`),
    indexed: "آخر فهرسة",
    notIndexed: "غير مفهرس",
    permissions: "الصلاحيات",
    read: "قراءة",
    readHint: "عرض الملفات وفتحها",
    write: "كتابة",
    writeHint: "إنشاء الملفات وتعديلها",
    index: "فهرس البحث",
    indexHint: "تضمينه في البحث المحلي",
    status: {
      ready: "جاهز",
      indexing: "جارٍ الفهرسة",
      missing: "المجلد غير موجود",
      "not-directory": "ليس مجلدًا",
      denied: "رفض النظام الوصول",
    },
    genericError: "حدث خطأ ما. حاول مرة أخرى.",
    addTitle: "إضافة مجلد",
    addBody: "اختر مجلدًا على هذا الجهاز. سيحصل تطبيق سطح المكتب على صلاحية الوصول إليه وإلى كل ما بداخله.",
    pathLabel: "مسار المجلد",
    pathPlaceholder: "C:\\Users\\you\\projects\\app",
    browse: "استعراض",
    problemEmpty: "أدخل مسار المجلد.",
    problemRelative: "استخدم مسارًا كاملًا يبدأ من قرص أو مشاركة أو الجذر.",
    problemDuplicate: "هذا المجلد موجود في القائمة بالفعل.",
    warnInside: (other: string) => `مشمول بالفعل ضمن ${other}.`,
    warnContains: (other: string) => `يشمل ${other} وهو موجود في القائمة بالفعل.`,
    cancel: "إلغاء",
    save: "إضافة المجلد",
    removeTitle: (name: string) => `إزالة ${name}؟`,
    removeBody: "يفقد تطبيق سطح المكتب صلاحية الوصول إلى هذا المجلد ويُحذف فهرس البحث الخاص به. ملفاتك لا تتأثر.",
    removeConfirm: "إزالة",
    pick: "اختر موقعًا",
    pickEmpty: "لا توجد مواقع صالحة",
    unavailable: "غير متاح",
  },
};

export type DesktopLocationsLabels = { [K in keyof typeof STRINGS.en]: (typeof STRINGS.en)[K] };

/** The built-in strings for the active locale, with `labels` laid over them. */
export function useLabels(labels: () => Partial<DesktopLocationsLabels> | undefined): ComputedRef<DesktopLocationsLabels> {
  const nq = useNasaq();
  return computed(() => ({ ...(STRINGS[nq.locale.value.startsWith("ar") ? "ar" : "en"] as DesktopLocationsLabels), ...labels() }));
}
