import type { LeadAttribution, LeadSourceKind, LeadStatus } from "./leads-inbox-logic";

export const leadsInboxStrings = {
  en: {
    label: "Leads",
    search: "Search leads…",
    all: "All",
    statuses: { new: "New", contacted: "Contacted", qualified: "Qualified", converted: "Converted", spam: "Spam" } as Record<LeadStatus, string>,
    pipeline: "Pipeline",
    lead: "Lead",
    source: "Source",
    stage: "Stage",
    score: "Score",
    received: "Received",
    budget: "Budget",
    sources: { paid: "Paid", organic: "Organic", social: "Social", email: "Email", referral: "Referral", direct: "Direct" } as Record<LeadSourceKind, string>,
    direct: "Direct visit",
    moveTo: (stage: string) => `Move to ${stage}`,
    markSpam: "Mark as spam",
    notSpam: "Not spam",
    convert: "Convert to CRM",
    reply: "Reply",
    open: "Open",
    message: "Message",
    attribution: "Where it came from",
    attributionHint: "What the visitor's browser reported when they sent the form.",
    attrKeys: {
      utmSource: "UTM source",
      utmMedium: "UTM medium",
      utmCampaign: "UTM campaign",
      utmTerm: "UTM term",
      utmContent: "UTM content",
      referrer: "Referrer",
      gclid: "Google click ID",
      landingPage: "Landing page",
    } as Record<keyof LeadAttribution, string>,
    copy: "Copy",
    form: "Form",
    converted: "Converted to CRM",
    contactRef: "Contact",
    companyRef: "Company",
    dealRef: "Deal",
    convertHint: "Creates a contact from this lead. The lead stays here, marked as converted.",
    contactName: "Contact name",
    companyName: "Company",
    createCompany: "Create a company",
    createDeal: "Open a deal",
    dealTitle: "Deal title",
    convertAction: "Convert",
    cancel: "Cancel",
    replyLabel: "Your reply",
    replyPlaceholder: "Write a reply, or press the bolt for a canned reply…",
    cannedTrigger: "Canned replies",
    send: "Send reply",
    sent: "Reply sent",
    failed: "That did not work. Try again.",
    empty: "No leads yet",
    emptyHint: "Inquiries from your forms land here, with where they came from.",
    close: "Close",
  },
  ar: {
    label: "العملاء المحتملون",
    search: "ابحث في العملاء المحتملين…",
    all: "الكل",
    statuses: { new: "جديد", contacted: "تم التواصل", qualified: "مؤهَّل", converted: "محوَّل", spam: "مزعج" } as Record<LeadStatus, string>,
    pipeline: "المراحل",
    lead: "العميل المحتمل",
    source: "المصدر",
    stage: "المرحلة",
    score: "التقييم",
    received: "وصل",
    budget: "الميزانية",
    sources: { paid: "مدفوع", organic: "عضوي", social: "اجتماعي", email: "بريد", referral: "إحالة", direct: "مباشر" } as Record<LeadSourceKind, string>,
    direct: "زيارة مباشرة",
    moveTo: (stage: string) => `نقل إلى ${stage}`,
    markSpam: "تعليم كمزعج",
    notSpam: "ليس مزعجًا",
    convert: "تحويل إلى العملاء",
    reply: "رد",
    open: "فتح",
    message: "الرسالة",
    attribution: "من أين جاء",
    attributionHint: "ما أبلغ عنه متصفح الزائر عند إرسال النموذج.",
    attrKeys: {
      utmSource: "مصدر UTM",
      utmMedium: "وسيط UTM",
      utmCampaign: "حملة UTM",
      utmTerm: "كلمة UTM",
      utmContent: "محتوى UTM",
      referrer: "الموقع المُحيل",
      gclid: "معرّف نقرة جوجل",
      landingPage: "صفحة الوصول",
    } as Record<keyof LeadAttribution, string>,
    copy: "نسخ",
    form: "النموذج",
    converted: "تم التحويل إلى العملاء",
    contactRef: "جهة الاتصال",
    companyRef: "الشركة",
    dealRef: "الصفقة",
    convertHint: "ينشئ جهة اتصال من هذا الطلب. يبقى الطلب هنا وعليه علامة محوَّل.",
    contactName: "اسم جهة الاتصال",
    companyName: "الشركة",
    createCompany: "إنشاء شركة",
    createDeal: "فتح صفقة",
    dealTitle: "عنوان الصفقة",
    convertAction: "تحويل",
    cancel: "إلغاء",
    replyLabel: "ردك",
    replyPlaceholder: "اكتب ردًا، أو اضغط على البرق لرد جاهز…",
    cannedTrigger: "الردود الجاهزة",
    send: "إرسال الرد",
    sent: "تم إرسال الرد",
    failed: "لم تنجح العملية. حاول مرة أخرى.",
    empty: "لا يوجد عملاء محتملون بعد",
    emptyHint: "تصل هنا استفسارات نماذجك، مع مصدر كل واحد.",
    close: "إغلاق",
  },
};
export type LeadsInboxLabels = typeof leadsInboxStrings.en;
export type LeadsInboxLabelOverrides = Partial<LeadsInboxLabels>;

/** The words for a locale with the host's overrides on top. */
export function leadsInboxWords(locale: string, labels?: LeadsInboxLabelOverrides): LeadsInboxLabels {
  return { ...leadsInboxStrings[locale.startsWith("ar") ? "ar" : "en"], ...labels };
}
