import { computed, type ComputedRef } from "vue";
import { useNasaq } from "../../provider";
import type { FirewallError, FirewallProtocol, HttpError, HttpRuleType, RuleState } from "./format";

export type NetworkRulesResult = void | { error?: string };

export const NETWORK_STRINGS = {
  en: {
    firewall: "Firewall",
    http: "HTTP rules",
    firewallBody: "Rules run from the top and the first match wins. Changes stay staged until you apply them.",
    httpBody: "Redirects, headers, passwords and IP limits for web requests. Changes stay staged until you apply them.",
    addRule: "Add rule",
    tableFirewall: "Firewall rules",
    tableHttp: "HTTP rules",
    emptyFirewall: "No firewall rules. All traffic follows the default policy.",
    emptyHttp: "No HTTP rules yet.",
    cols: { order: "#", action: "Action", protocol: "Protocol and port", source: "Source", note: "Note", type: "Type", path: "Path", detail: "Detail", state: "State" },
    allow: "Allow",
    deny: "Deny",
    anySource: "Any",
    protocols: { tcp: "TCP", udp: "UDP", icmp: "ICMP", any: "Any" } satisfies Record<FirewallProtocol, string>,
    httpTypes: { redirect: "Redirect", header: "Set header", "basic-auth": "Password", "ip-allow": "Allow IPs", "ip-deny": "Block IPs" } satisfies Record<HttpRuleType, string>,
    states: { unchanged: "", added: "New", changed: "Edited", removed: "Removed" } satisfies Record<RuleState, string>,
    edit: "Edit",
    moveUp: "Move up",
    moveDown: "Move down",
    remove: "Remove",
    restore: "Undo remove",
    rowActionsFor: (name: string) => `Actions for ${name}`,
    staged: (n: number) => (n === 1 ? "1 change staged" : `${n} changes staged`),
    stagedHint: "Nothing has changed on the server yet.",
    upToDate: "Everything is applied.",
    apply: "Apply changes",
    discard: "Discard",
    applied: "Changes applied.",
    lockout: "A deny rule for SSH (port 22) from any address comes before every allow rule. Applying it can lock you out.",
    ruleTitleNew: "New rule",
    ruleTitleEdit: "Edit rule",
    ruleBody: "Saved to the staged list. It only takes effect when you apply.",
    fields: {
      action: "Action",
      protocol: "Protocol",
      port: "Port",
      portHint: "A port like 443, or a range like 8000-8100.",
      source: "Source",
      sourceHint: "An IP address, a block like 10.0.0.0/24, or any.",
      note: "Note",
      type: "Rule type",
      path: "Path",
      pathHint: "Starts with a slash. Use / for the whole site.",
      target: "Redirect to",
      status: "Status code",
      name: "Header name",
      value: "Header value",
      username: "Username",
      password: "Password",
      passwordHint: "At least 8 characters. Never shown again.",
      passwordKeep: "Leave empty to keep the current password.",
      cidr: "IP address or block",
    },
    statusLabels: { 301: "301 Moved permanently", 302: "302 Found", 307: "307 Temporary redirect", 308: "308 Permanent redirect" } as Record<number, string>,
    fwErrors: { port: "Enter a port from 1 to 65535, or a range.", portForProtocol: "This protocol has no port. Leave it empty.", source: "Enter an IP address, a block like 10.0.0.0/24, or any." } satisfies Record<FirewallError, string>,
    httpErrors: {
      path: "Start with a slash and use no spaces.",
      target: "Enter a full URL or a path.",
      name: "Use letters, digits and dashes.",
      value: "Enter a value.",
      username: "Enter a username.",
      password: "Use at least 8 characters.",
      cidr: "Enter an IP address or a block like 10.0.0.0/24.",
    } satisfies Record<HttpError, string>,
    save: "Save to staged",
    cancel: "Cancel",
    passwordSet: "Password set",
    genericError: "Something went wrong. Try again.",
    loading: "Loading rules",
  },
  ar: {
    firewall: "جدار الحماية",
    http: "قواعد HTTP",
    firewallBody: "تُنفَّذ القواعد من الأعلى وتنطبق أول قاعدة مطابقة. تبقى التغييرات مرحلية حتى تطبّقها.",
    httpBody: "إعادة توجيه ورؤوس وكلمات مرور وقيود عناوين لطلبات الويب. تبقى التغييرات مرحلية حتى تطبّقها.",
    addRule: "إضافة قاعدة",
    tableFirewall: "قواعد جدار الحماية",
    tableHttp: "قواعد HTTP",
    emptyFirewall: "لا توجد قواعد. تتبع كل الحركة السياسة الافتراضية.",
    emptyHttp: "لا توجد قواعد HTTP بعد.",
    cols: { order: "#", action: "الإجراء", protocol: "البروتوكول والمنفذ", source: "المصدر", note: "ملاحظة", type: "النوع", path: "المسار", detail: "التفاصيل", state: "الحالة" },
    allow: "سماح",
    deny: "رفض",
    anySource: "أي مصدر",
    protocols: { tcp: "TCP", udp: "UDP", icmp: "ICMP", any: "الكل" } satisfies Record<FirewallProtocol, string>,
    httpTypes: { redirect: "إعادة توجيه", header: "ضبط رأس", "basic-auth": "كلمة مرور", "ip-allow": "السماح لعناوين", "ip-deny": "حظر عناوين" } satisfies Record<HttpRuleType, string>,
    states: { unchanged: "", added: "جديدة", changed: "معدّلة", removed: "محذوفة" } satisfies Record<RuleState, string>,
    edit: "تعديل",
    moveUp: "نقل لأعلى",
    moveDown: "نقل لأسفل",
    remove: "إزالة",
    restore: "تراجع عن الإزالة",
    rowActionsFor: (name: string) => `إجراءات ${name}`,
    staged: (n: number) => (n === 1 ? "تغيير واحد مرحلي" : n === 2 ? "تغييران مرحليان" : n <= 10 ? `${n} تغييرات مرحلية` : `${n} تغييرًا مرحليًا`),
    stagedHint: "لم يتغير شيء على الخادم بعد.",
    upToDate: "كل شيء مطبَّق.",
    apply: "تطبيق التغييرات",
    discard: "تجاهل",
    applied: "تم تطبيق التغييرات.",
    lockout: "توجد قاعدة رفض لـ SSH (المنفذ 22) من أي عنوان قبل كل قواعد السماح. قد يؤدي تطبيقها إلى إغلاق الوصول عليك.",
    ruleTitleNew: "قاعدة جديدة",
    ruleTitleEdit: "تعديل القاعدة",
    ruleBody: "تُحفظ في القائمة المرحلية ولا تسري إلا عند التطبيق.",
    fields: {
      action: "الإجراء",
      protocol: "البروتوكول",
      port: "المنفذ",
      portHint: "منفذ مثل 443 أو نطاق مثل 8000-8100.",
      source: "المصدر",
      sourceHint: "عنوان IP أو نطاق مثل 10.0.0.0/24 أو any.",
      note: "ملاحظة",
      type: "نوع القاعدة",
      path: "المسار",
      pathHint: "يبدأ بشرطة مائلة. استخدم / للموقع كله.",
      target: "إعادة التوجيه إلى",
      status: "رمز الحالة",
      name: "اسم الرأس",
      value: "قيمة الرأس",
      username: "اسم المستخدم",
      password: "كلمة المرور",
      passwordHint: "8 أحرف على الأقل. لا تُعرض مرة أخرى.",
      passwordKeep: "اتركها فارغة للإبقاء على الحالية.",
      cidr: "عنوان IP أو نطاق",
    },
    statusLabels: { 301: "301 نقل دائم", 302: "302 موجود", 307: "307 إعادة مؤقتة", 308: "308 إعادة دائمة" } as Record<number, string>,
    fwErrors: { port: "أدخل منفذًا من 1 إلى 65535 أو نطاقًا.", portForProtocol: "هذا البروتوكول بلا منفذ. اترك الحقل فارغًا.", source: "أدخل عنوان IP أو نطاقًا مثل 10.0.0.0/24 أو any." } satisfies Record<FirewallError, string>,
    httpErrors: {
      path: "ابدأ بشرطة مائلة ولا تستخدم مسافات.",
      target: "أدخل رابطًا كاملًا أو مسارًا.",
      name: "استخدم أحرفًا وأرقامًا وشرطات.",
      value: "أدخل قيمة.",
      username: "أدخل اسم مستخدم.",
      password: "استخدم 8 أحرف على الأقل.",
      cidr: "أدخل عنوان IP أو نطاقًا مثل 10.0.0.0/24.",
    } satisfies Record<HttpError, string>,
    save: "حفظ في المرحلي",
    cancel: "إلغاء",
    passwordSet: "كلمة المرور محددة",
    genericError: "حدث خطأ ما. حاول مرة أخرى.",
    loading: "جارٍ تحميل القواعد",
  },
};

export type NetworkStrings = (typeof NETWORK_STRINGS)["en"];
export type NetworkRulesLabels = Partial<NetworkStrings>;

/** The strings for the current Nasaq locale, with the caller's overrides on top. */
export function useNetworkStrings(labels: () => NetworkRulesLabels | undefined): ComputedRef<NetworkStrings> {
  const nasaq = useNasaq();
  return computed(() => ({ ...NETWORK_STRINGS[nasaq.locale.value.startsWith("ar") ? "ar" : "en"], ...labels() }));
}
