// Words of the report editor and viewer, in English and Arabic. Strings with a function take the already formatted numbers.
import { computed, type ComputedRef } from "vue";
import { useNasaq } from "../../provider";

export const STRINGS = {
  en: {
    editor: "Report editor",
    viewer: "Report",
    reportTitle: "Report title",
    titlePlaceholder: "Untitled report",
    subtitle: "Subtitle",
    author: "Author",
    date: "Date",
    edit: "Edit",
    preview: "Preview",
    view: "View",
    blocks: "Blocks",
    insert: "Insert block",
    addText: "Add text block",
    blockType: "Block type",
    typeHeading: "Heading",
    typeText: "Text",
    typeMetrics: "Key figures",
    typeChart: "Chart",
    typeTable: "Table",
    typeCallout: "Callout",
    typeDivider: "Divider",
    untitledBlock: "Empty block",
    // heading
    headingText: "Heading text",
    headingLevel: "Level",
    level1: "Large",
    level2: "Medium",
    level3: "Small",
    // text
    textLabel: "Text",
    textPlaceholder: "Write the paragraph. Use the toolbar for lists, links and headings.",
    // metrics
    metricLabel: "Label",
    metricValue: "Value",
    metricDelta: "Change in percent",
    metricDeltaLabel: "Change note",
    metricCurrency: "Currency code",
    metricCurrencyHint: "Leave empty for a plain number.",
    addMetric: "Add figure",
    removeMetric: (n: string) => `Remove figure ${n}`,
    figureN: (n: string) => `Figure ${n}`,
    // chart
    chartTitle: "Chart title",
    chartKind: "Chart type",
    kindBar: "Bars",
    kindLine: "Lines",
    kindArea: "Area",
    caption: "Caption",
    seriesName: (n: string) => `Series ${n} name`,
    addSeries: "Add series",
    removeSeries: (n: string) => `Remove series ${n}`,
    rowLabel: "Label",
    rowValue: (series: string) => `Value of ${series}`,
    addRow: "Add row",
    removeRow: (n: string) => `Remove row ${n}`,
    defaultSeries: (n: string) => `Series ${n}`,
    chartSummary: (title: string, kind: string, points: string, series: string) => `${title || kind}: ${points} points, ${series} series`,
    // table
    tableTitle: "Table title",
    column: (n: string) => `Column ${n} heading`,
    cell: (row: string, col: string) => `Row ${row}, column ${col}`,
    addColumn: "Add column",
    removeColumn: (n: string) => `Remove column ${n}`,
    // callout
    calloutTone: "Tone",
    toneInfo: "Note",
    toneSuccess: "Good news",
    toneWarning: "Watch out",
    toneDanger: "Problem",
    calloutTitle: "Title",
    calloutText: "Message",
    // status and actions
    save: "Save",
    saving: "Saving",
    saved: "Saved",
    unsaved: "Unsaved changes",
    saveFailed: "Could not save",
    print: "Print",
    words: (n: string) => `${n} words`,
    minutes: (n: string) => `${n} min read`,
    issues: (n: string) => `${n} blocks need content`,
    contents: "Contents",
    emptyReport: "This report is empty.",
    previewEmpty: "Nothing to preview yet. Add a block in Edit.",
    by: (name: string) => `By ${name}`,
    // one line per issue kind
    issueEmptyHeading: "Heading is empty",
    issueEmptyText: "Text is empty",
    issueEmptyMetric: "A figure has no label",
    issueEmptyChart: "A chart row has no label",
    issueEmptyTable: "Table has no headings",
  },
  ar: {
    editor: "محرر التقارير",
    viewer: "التقرير",
    reportTitle: "عنوان التقرير",
    titlePlaceholder: "تقرير بلا عنوان",
    subtitle: "عنوان فرعي",
    author: "الكاتب",
    date: "التاريخ",
    edit: "تحرير",
    preview: "معاينة",
    view: "عرض",
    blocks: "الكتل",
    insert: "إدراج كتلة",
    addText: "إضافة كتلة نص",
    blockType: "نوع الكتلة",
    typeHeading: "عنوان",
    typeText: "نص",
    typeMetrics: "أرقام رئيسية",
    typeChart: "رسم بياني",
    typeTable: "جدول",
    typeCallout: "تنبيه",
    typeDivider: "فاصل",
    untitledBlock: "كتلة فارغة",
    headingText: "نص العنوان",
    headingLevel: "المستوى",
    level1: "كبير",
    level2: "متوسط",
    level3: "صغير",
    textLabel: "النص",
    textPlaceholder: "اكتب الفقرة. استخدم شريط الأدوات للقوائم والروابط والعناوين.",
    metricLabel: "التسمية",
    metricValue: "القيمة",
    metricDelta: "التغيّر بالنسبة المئوية",
    metricDeltaLabel: "ملاحظة التغيّر",
    metricCurrency: "رمز العملة",
    metricCurrencyHint: "اتركه فارغًا لعرض رقم عادي.",
    addMetric: "إضافة رقم",
    removeMetric: (n: string) => `حذف الرقم ${n}`,
    figureN: (n: string) => `الرقم ${n}`,
    chartTitle: "عنوان الرسم",
    chartKind: "نوع الرسم",
    kindBar: "أعمدة",
    kindLine: "خطوط",
    kindArea: "مساحة",
    caption: "التعليق",
    seriesName: (n: string) => `اسم السلسلة ${n}`,
    addSeries: "إضافة سلسلة",
    removeSeries: (n: string) => `حذف السلسلة ${n}`,
    rowLabel: "التسمية",
    rowValue: (series: string) => `قيمة ${series}`,
    addRow: "إضافة صف",
    removeRow: (n: string) => `حذف الصف ${n}`,
    defaultSeries: (n: string) => `السلسلة ${n}`,
    chartSummary: (title: string, kind: string, points: string, series: string) => `${title || kind}: ${points} نقاط، ${series} سلاسل`,
    tableTitle: "عنوان الجدول",
    column: (n: string) => `عنوان العمود ${n}`,
    cell: (row: string, col: string) => `الصف ${row}، العمود ${col}`,
    addColumn: "إضافة عمود",
    removeColumn: (n: string) => `حذف العمود ${n}`,
    calloutTone: "النوع",
    toneInfo: "ملاحظة",
    toneSuccess: "خبر جيد",
    toneWarning: "تنبيه",
    toneDanger: "مشكلة",
    calloutTitle: "العنوان",
    calloutText: "الرسالة",
    save: "حفظ",
    saving: "جارٍ الحفظ",
    saved: "تم الحفظ",
    unsaved: "تغييرات غير محفوظة",
    saveFailed: "تعذر الحفظ",
    print: "طباعة",
    words: (n: string) => `${n} كلمة`,
    minutes: (n: string) => `قراءة ${n} د`,
    issues: (n: string) => `${n} كتل تحتاج محتوى`,
    contents: "المحتويات",
    emptyReport: "هذا التقرير فارغ.",
    previewEmpty: "لا شيء للمعاينة بعد. أضف كتلة في وضع التحرير.",
    by: (name: string) => `بقلم ${name}`,
    issueEmptyHeading: "العنوان فارغ",
    issueEmptyText: "النص فارغ",
    issueEmptyMetric: "رقم بلا تسمية",
    issueEmptyChart: "صف في الرسم بلا تسمية",
    issueEmptyTable: "الجدول بلا عناوين",
  },
};

export type ReportText = typeof STRINGS.en;
export type ReportLabels = Partial<ReportText>;

export function reportText(locale: string, labels?: ReportLabels): ReportText {
  return { ...STRINGS[locale.startsWith("ar") ? "ar" : "en"], ...labels } as ReportText;
}

export function useReportStrings(labels?: () => ReportLabels | undefined): { locale: ComputedRef<string>; t: ComputedRef<ReportText> } {
  const nq = useNasaq();
  const locale = computed(() => nq.locale.value);
  return { locale, t: computed(() => reportText(locale.value, labels?.())) };
}
