export const TEST_RUN_STRINGS = {
  en: {
    title: "Test run",
    description: "Runs once without publishing anything, and shows each step as it happens.",
    run: "Run test",
    runAgain: "Run again",
    stop: "Stop",
    clear: "Clear",
    idleTitle: "No test run yet",
    idleBody: "Run a test to watch each step as it happens.",
    steps: "Steps",
    results: "Saved",
    running: "Running",
    stepsCount: "{n} steps",
    finished: "Finished in {time}",
    stopped: "Stopped after {time}",
    failed: "Failed after {time}",
    waiting: "Waiting for the first step…",
    status: { running: "Running", ok: "Passed", error: "Failed", skipped: "Skipped" },
    summary: { ok: "{n} passed", error: "{n} failed", skipped: "{n} skipped" },
    items: "{n} items",
    untitled: "Untitled",
    opensNewTab: "(opens in a new tab)",
    showRaw: "Show raw data",
    hideRaw: "Hide raw data",
    raw: "Raw data",
    noResults: "Nothing was saved.",
  },
  ar: {
    title: "تشغيل تجريبي",
    description: "يعمل مرة واحدة دون نشر أي شيء، ويعرض كل خطوة لحظة حدوثها.",
    run: "تشغيل الاختبار",
    runAgain: "تشغيل مرة أخرى",
    stop: "إيقاف",
    clear: "مسح",
    idleTitle: "لا يوجد تشغيل تجريبي بعد",
    idleBody: "شغّل اختبارًا لمتابعة كل خطوة لحظة حدوثها.",
    steps: "الخطوات",
    results: "المحفوظ",
    running: "قيد التشغيل",
    stepsCount: "{n} خطوات",
    finished: "انتهى خلال {time}",
    stopped: "توقف بعد {time}",
    failed: "فشل بعد {time}",
    waiting: "في انتظار الخطوة الأولى…",
    status: { running: "قيد التشغيل", ok: "نجحت", error: "فشلت", skipped: "تخطّي" },
    summary: { ok: "{n} نجحت", error: "{n} فشلت", skipped: "{n} تخطّي" },
    items: "{n} عناصر",
    untitled: "بلا عنوان",
    opensNewTab: "(يفتح في علامة تبويب جديدة)",
    showRaw: "عرض البيانات الخام",
    hideRaw: "إخفاء البيانات الخام",
    raw: "البيانات الخام",
    noResults: "لم يُحفظ شيء.",
  },
};

export type TestRunStreamLabels = (typeof TEST_RUN_STRINGS)["en"];

/** Fills `{n}`-style placeholders. */
export const fillTestRun = (text: string, values: Record<string, string>) => text.replace(/\{(\w+)\}/g, (_, k: string) => values[k] ?? "");
