// Strings of the members manager, English and Arabic. Pass `labels` to override any of them.
export const MEMBERS_MANAGER_STRINGS = {
  en: {
    title: "Members",
    members: "Members",
    pending: "Pending invites",
    invite: "Invite people",
    search: "Search name or email…",
    member: "Member",
    role: "Role",
    joined: "Joined",
    lastActive: "Last active",
    never: "Never",
    you: "You",
    owner: "Owner",
    table: "Workspace members",
    empty: "No members yet",
    emptyHint: "Invite the first person to get started.",
    roleFor: (name: string) => `Role of ${name}`,
    // blocked reasons
    blockLastOwner: "A workspace needs an owner. Transfer ownership first.",
    blockOwnerOnly: "Only an owner can change another owner.",
    blockNotGrantable: "You cannot change this role.",
    blockSelf: "Use Leave workspace to remove yourself.",
    // actions
    transfer: "Transfer ownership…",
    remove: "Remove from workspace…",
    resend: "Resend",
    revoke: "Revoke",
    // pending
    invitedBy: (name: string) => `Invited by ${name}`,
    sent: "Sent",
    expiresIn: "Expires",
    expired: "Expired",
    noInvites: "No pending invites",
    noInvitesHint: "People you invite show up here until they accept.",
    inviteList: "Pending invites",
    // dialogs
    inviteTitle: "Invite people",
    inviteBody: "They get an email with a link to join. Invites expire after a while.",
    emails: "Email addresses",
    emailsHint: "Press Enter or comma after each address.",
    emailsPlaceholder: "name@example.com",
    emailsRequired: "Add at least one email address.",
    emailInvalid: (v: string) => `${v} is not a valid email address.`,
    emailDuplicate: (v: string) => `${v} is already added.`,
    roleField: "Role",
    send: "Send invites",
    cancel: "Cancel",
    removeTitle: (name: string) => `Remove ${name}?`,
    removeBody: "They lose access to this workspace at once. Their work stays here.",
    removeConfirm: "Remove member",
    transferTitle: (name: string) => `Make ${name} the owner?`,
    transferBody: "They become the owner and you lose owner rights. Only they can give ownership back.",
    transferConfirm: "Transfer ownership",
    leave: "Leave workspace",
    leaveTitle: "Leave this workspace?",
    leaveBody: "You lose access until someone invites you again.",
    leaveBlocked: "You are the only owner. Transfer ownership to another member before you leave.",
    leaveConfirm: "Leave workspace",
    leaveHint: "You can rejoin only if someone invites you again.",
    // outcomes
    invitedOk: (n: string) => (n === "1" ? "1 invite sent." : `${n} invites sent.`),
    roleOk: (name: string) => `Role updated for ${name}.`,
    removedOk: (name: string) => `${name} was removed.`,
    resentOk: (email: string) => `Invite sent again to ${email}.`,
    revokedOk: (email: string) => `Invite to ${email} was revoked.`,
    transferredOk: (name: string) => `${name} is now the owner.`,
    failed: "That did not work. Try again.",
    dismiss: "Dismiss",
  },
  ar: {
    title: "الأعضاء",
    members: "الأعضاء",
    pending: "الدعوات المعلّقة",
    invite: "دعوة أشخاص",
    search: "ابحث بالاسم أو البريد…",
    member: "العضو",
    role: "الدور",
    joined: "تاريخ الانضمام",
    lastActive: "آخر نشاط",
    never: "أبدًا",
    you: "أنت",
    owner: "المالك",
    table: "أعضاء مساحة العمل",
    empty: "لا يوجد أعضاء بعد",
    emptyHint: "ادعُ أول شخص للبدء.",
    roleFor: (name: string) => `دور ${name}`,
    blockLastOwner: "تحتاج مساحة العمل إلى مالك. انقل الملكية أولًا.",
    blockOwnerOnly: "المالك وحده يستطيع تغيير مالك آخر.",
    blockNotGrantable: "لا يمكنك تغيير هذا الدور.",
    blockSelf: "استخدم «مغادرة مساحة العمل» لإزالة نفسك.",
    transfer: "نقل الملكية…",
    remove: "إزالة من مساحة العمل…",
    resend: "إعادة الإرسال",
    revoke: "إلغاء الدعوة",
    invitedBy: (name: string) => `دعاه ${name}`,
    sent: "أُرسلت",
    expiresIn: "تنتهي",
    expired: "منتهية",
    noInvites: "لا توجد دعوات معلّقة",
    noInvitesHint: "يظهر من تدعوهم هنا إلى أن يقبلوا.",
    inviteList: "الدعوات المعلّقة",
    inviteTitle: "دعوة أشخاص",
    inviteBody: "يصلهم بريد برابط للانضمام. تنتهي الدعوات بعد فترة.",
    emails: "عناوين البريد",
    emailsHint: "اضغط Enter أو الفاصلة بعد كل عنوان.",
    emailsPlaceholder: "name@example.com",
    emailsRequired: "أضف عنوان بريد واحدًا على الأقل.",
    emailInvalid: (v: string) => `${v} ليس بريدًا إلكترونيًا صالحًا.`,
    emailDuplicate: (v: string) => `${v} مضاف بالفعل.`,
    roleField: "الدور",
    send: "إرسال الدعوات",
    cancel: "إلغاء",
    removeTitle: (name: string) => `إزالة ${name}؟`,
    removeBody: "يفقد وصوله إلى مساحة العمل فورًا. يبقى عمله هنا.",
    removeConfirm: "إزالة العضو",
    transferTitle: (name: string) => `جعل ${name} المالك؟`,
    transferBody: "يصبح هو المالك وتفقد أنت صلاحيات المالك. هو وحده يستطيع إعادة الملكية إليك.",
    transferConfirm: "نقل الملكية",
    leave: "مغادرة مساحة العمل",
    leaveTitle: "مغادرة مساحة العمل هذه؟",
    leaveBody: "تفقد الوصول إلى أن يدعوك أحد مرة أخرى.",
    leaveBlocked: "أنت المالك الوحيد. انقل الملكية إلى عضو آخر قبل أن تغادر.",
    leaveConfirm: "مغادرة مساحة العمل",
    leaveHint: "لا تستطيع العودة إلا إذا دعاك أحد مرة أخرى.",
    invitedOk: (n: string) => (n === "1" ? "أُرسلت دعوة واحدة." : `أُرسلت ${n} دعوات.`),
    roleOk: (name: string) => `تم تحديث دور ${name}.`,
    removedOk: (name: string) => `تمت إزالة ${name}.`,
    resentOk: (email: string) => `أُعيد إرسال الدعوة إلى ${email}.`,
    revokedOk: (email: string) => `أُلغيت الدعوة إلى ${email}.`,
    transferredOk: (name: string) => `أصبح ${name} المالك.`,
    failed: "لم تنجح العملية. حاول مرة أخرى.",
    dismiss: "تجاهل",
  },
};
export const membersManagerStrings = (locale: string) => MEMBERS_MANAGER_STRINGS[locale.startsWith("ar") ? "ar" : "en"];
export type MembersManagerLabels = Partial<typeof MEMBERS_MANAGER_STRINGS.en>;
