export const WHATSAPP_QR_STRINGS = {
  en: {
    title: "Connect WhatsApp",
    description: "Link a WhatsApp number by scanning a code from the phone.",
    stepsLabel: "How to link",
    step1: "Open WhatsApp on your phone.",
    step2: "Go to Settings, then Linked devices.",
    step3: "Tap Link a device and point the camera at this code.",
    start: "Show QR code",
    starting: "Preparing the code…",
    qrLabel: "WhatsApp link QR code",
    expiresIn: (s: number) => `Code expires in ${s}s`,
    expired: "This code expired",
    refresh: "New code",
    refreshing: "Refreshing…",
    autoRefresh: "A new code appears automatically when this one expires.",
    connected: "Connected",
    disconnected: "Not connected",
    connectedAs: (name: string) => `Linked to ${name}`,
    since: (when: string) => `Since ${when}`,
    disconnect: "Disconnect",
    disconnectTitle: "Disconnect WhatsApp?",
    disconnectBody: "Messages will stop until you scan a new code.",
    confirm: "Yes, disconnect",
    cancel: "Cancel",
    failed: "Could not get a code. Check the connection and try again.",
    retry: "Try again",
    connectingStatus: "Waiting for the scan",
  },
  ar: {
    title: "ربط واتساب",
    description: "اربط رقم واتساب بمسح رمز من الهاتف.",
    stepsLabel: "طريقة الربط",
    step1: "افتح واتساب على هاتفك.",
    step2: "اذهب إلى الإعدادات ثم الأجهزة المرتبطة.",
    step3: "اضغط «ربط جهاز» ووجّه الكاميرا إلى هذا الرمز.",
    start: "إظهار رمز QR",
    starting: "جارٍ تجهيز الرمز…",
    qrLabel: "رمز QR لربط واتساب",
    expiresIn: (s: number) => `ينتهي الرمز خلال ${s} ثانية`,
    expired: "انتهت صلاحية هذا الرمز",
    refresh: "رمز جديد",
    refreshing: "جارٍ التحديث…",
    autoRefresh: "يظهر رمز جديد تلقائيًا عند انتهاء هذا الرمز.",
    connected: "متصل",
    disconnected: "غير متصل",
    connectedAs: (name: string) => `مرتبط بالرقم ${name}`,
    since: (when: string) => `منذ ${when}`,
    disconnect: "قطع الاتصال",
    disconnectTitle: "قطع اتصال واتساب؟",
    disconnectBody: "ستتوقف الرسائل إلى أن تمسح رمزًا جديدًا.",
    confirm: "نعم، اقطع الاتصال",
    cancel: "إلغاء",
    failed: "تعذر الحصول على رمز. تحقق من الاتصال وحاول مرة أخرى.",
    retry: "حاول مرة أخرى",
    connectingStatus: "بانتظار المسح",
  },
};

export type WhatsappQrConnectLabels = (typeof WHATSAPP_QR_STRINGS)["en"];
export type WhatsappConnectStatus = "disconnected" | "qr" | "connected";
