// Strings of the plan catalog editor, English and Arabic. Pass `labels` to override any of them.
export const PLAN_CATALOG_STRINGS = {
  en: {
    tabs: "Catalog sections",
    plans: "Plans",
    features: "Features",
    apps: "Apps",
    payg: "Pay as you go",
    bundles: "Bundles",
    unpublished: (n: string) => (n === "1" ? "1 unpublished change" : `${n} unpublished changes`),
    upToDate: "The catalog matches what is live.",
    review: "Review and apply",
    discard: "Discard changes",
    previewTitle: "Sync preview",
    previewBody: "This is a dry run. Nothing goes live until you apply.",
    previewLoading: "Checking the changes",
    previewFailed: "The preview could not be built. Try again.",
    nothing: "There is nothing to apply.",
    added: "Added",
    updated: "Updated",
    removed: "Removed",
    counts: (a: string, u: string, r: string) => `${a} added, ${u} updated, ${r} removed`,
    fields: "Changed",
    warnings: "Warnings from the dry run",
    issues: "Fix these before applying",
    issueName: (e: string, id: string) => `${e}: ${id} has no name.`,
    issueDuplicate: (e: string, id: string) => `${e}: the id ${id} is used twice.`,
    issueMissingApp: (e: string, id: string) => `${e}: ${id} points to an app that does not exist.`,
    cancel: "Cancel",
    apply: (n: string) => `Apply ${n} changes`,
    applyOne: "Apply 1 change",
    applied: "Catalog applied. The changes are live.",
    applyFailed: "The catalog could not be applied. Nothing was changed.",
    dismiss: "Dismiss",
    appName: "App name",
    appId: "App id",
    appEnabled: "On sale",
    addApp: "Add app",
    appsList: "Apps",
    app: "App",
    featureName: "Feature name",
    featureId: "Feature key",
    featureApp: "Belongs to",
    noApp: "Whole platform",
    addFeature: "Add feature",
    featuresList: "Features",
    feature: "Feature",
    paygName: "Meter name",
    paygId: "Meter key",
    paygUnit: "Unit",
    paygPrice: "Price per unit",
    paygFree: "Free units per month",
    addPayg: "Add price",
    paygList: "Pay as you go prices",
    payg1: "Price",
    bundleName: "Bundle name",
    bundleId: "Bundle id",
    bundlePrice: "Monthly price",
    includedApps: "Included apps",
    addBundle: "Add bundle",
    bundlesList: "Bundles",
    bundle: "Bundle",
    plansHint: "Plan changes show up in the sync preview with everything else.",
    empty: "Nothing here yet.",
  },
  ar: {
    tabs: "أقسام الكتالوج",
    plans: "الباقات",
    features: "الميزات",
    apps: "التطبيقات",
    payg: "الدفع حسب الاستخدام",
    bundles: "الحزم",
    unpublished: (n: string) => (n === "1" ? "تغيير واحد غير منشور" : `${n} تغييرات غير منشورة`),
    upToDate: "الكتالوج مطابق للنسخة المنشورة.",
    review: "مراجعة وتطبيق",
    discard: "تجاهل التغييرات",
    previewTitle: "معاينة المزامنة",
    previewBody: "هذه تجربة بلا أثر. لن يُنشر شيء حتى تضغط تطبيق.",
    previewLoading: "جارٍ فحص التغييرات",
    previewFailed: "تعذّر إنشاء المعاينة. حاول مرة أخرى.",
    nothing: "لا يوجد ما يُطبَّق.",
    added: "مُضاف",
    updated: "مُعدَّل",
    removed: "محذوف",
    counts: (a: string, u: string, r: string) => `${a} مضاف، ${u} معدَّل، ${r} محذوف`,
    fields: "المتغيّر",
    warnings: "تحذيرات من التجربة",
    issues: "أصلِح هذه قبل التطبيق",
    issueName: (e: string, id: string) => `${e}: العنصر ${id} بلا اسم.`,
    issueDuplicate: (e: string, id: string) => `${e}: المعرّف ${id} مستخدم مرتين.`,
    issueMissingApp: (e: string, id: string) => `${e}: العنصر ${id} يشير إلى تطبيق غير موجود.`,
    cancel: "إلغاء",
    apply: (n: string) => `تطبيق ${n} تغييرات`,
    applyOne: "تطبيق تغيير واحد",
    applied: "تم تطبيق الكتالوج. التغييرات منشورة.",
    applyFailed: "تعذّر تطبيق الكتالوج. لم يتغيّر شيء.",
    dismiss: "تجاهل",
    appName: "اسم التطبيق",
    appId: "معرّف التطبيق",
    appEnabled: "معروض للبيع",
    addApp: "إضافة تطبيق",
    appsList: "التطبيقات",
    app: "تطبيق",
    featureName: "اسم الميزة",
    featureId: "مفتاح الميزة",
    featureApp: "تتبع",
    noApp: "المنصّة كلها",
    addFeature: "إضافة ميزة",
    featuresList: "الميزات",
    feature: "ميزة",
    paygName: "اسم العدّاد",
    paygId: "مفتاح العدّاد",
    paygUnit: "الوحدة",
    paygPrice: "السعر للوحدة",
    paygFree: "وحدات مجانية شهريًا",
    addPayg: "إضافة سعر",
    paygList: "أسعار الدفع حسب الاستخدام",
    payg1: "سعر",
    bundleName: "اسم الحزمة",
    bundleId: "معرّف الحزمة",
    bundlePrice: "السعر الشهري",
    includedApps: "التطبيقات المضمّنة",
    addBundle: "إضافة حزمة",
    bundlesList: "الحزم",
    bundle: "حزمة",
    plansHint: "تظهر تعديلات الباقات في معاينة المزامنة مع بقية التغييرات.",
    empty: "لا شيء هنا بعد.",
  },
};

export type PlanCatalogEditorLabels = Partial<typeof PLAN_CATALOG_STRINGS.en>;

export const planCatalogStrings = (locale: string) => PLAN_CATALOG_STRINGS[locale.startsWith("ar") ? "ar" : "en"];
