// Strings of the tenants console, English and Arabic. Pass `labels` to override any of them.
export const ADMIN_TENANTS_STRINGS = {
  en: {
    // workspaces
    workspaces: "Workspaces",
    search: "Search workspace or owner…",
    total: "Workspaces",
    trials: "On trial",
    suspendedStat: "Suspended",
    mrr: "Monthly revenue",
    workspace: "Workspace",
    owner: "Owner",
    plan: "Plan",
    seats: "Seats",
    status: "Status",
    created: "Created",
    unlimited: "Unlimited",
    statusActive: "Active",
    statusTrial: "Trial",
    statusSuspended: "Suspended",
    trialEnds: "Trial ends",
    open: "Open workspace",
    changePlan: "Change plan…",
    suspend: "Suspend…",
    reactivate: "Reactivate",
    seatsOf: (used: string, max: string) => `${used} of ${max} seats`,
    seatsUsed: (used: string) => `${used} seats`,
    empty: "No workspaces yet",
    // outcomes
    planOk: (name: string, plan: string) => `${name} is now on ${plan}.`,
    suspendOk: (name: string) => `${name} was suspended.`,
    reactivateOk: (name: string) => `${name} was reactivated.`,
    planSavedOk: (name: string) => `${name} was saved.`,
    planCreatedOk: (name: string) => `${name} was created.`,
    failed: "That did not work. Try again.",
    dismiss: "Dismiss",
    cancel: "Cancel",
    // change plan dialog
    changeTitle: (name: string) => `Change plan for ${name}`,
    changeBody: "The new plan applies at once. Billing is prorated by your payment provider.",
    newPlan: "New plan",
    overSeats: (used: string, max: string) => `This plan allows ${max} seats but the workspace uses ${used}.`,
    saveChange: "Change plan",
    // suspend
    suspendTitle: (name: string) => `Suspend ${name}?`,
    suspendBody: "Members cannot sign in to this workspace until you reactivate it. Nothing is deleted.",
    suspendConfirm: "Suspend workspace",
    // plans
    plans: "Plans",
    newPlanButton: "New plan",
    editPlan: "Edit plan",
    perMonth: "month",
    subscribers: (n: string) => (n === "1" ? "1 workspace" : `${n} workspaces`),
    storage: (n: string) => `${n} GB storage`,
    storageUnlimited: "Unlimited storage",
    seatsLimit: (n: string) => `Up to ${n} seats`,
    seatsUnlimited: "Unlimited seats",
    inactive: "Hidden",
    visible: "Visible on the pricing page",
    visibleHint: "Hidden plans can still be assigned by an admin.",
    plansEmpty: "No plans yet",
    plansEmptyHint: "Create your first plan to start selling.",
    // plan dialog
    createPlanTitle: "New plan",
    editPlanTitle: (name: string) => `Edit ${name}`,
    planBody: "Limits apply per workspace. Leave a limit empty for unlimited.",
    planName: "Plan name",
    planDescription: "Who it is for",
    price: "Price per month",
    seatLimit: "Seat limit",
    storageLimit: "Storage limit (GB)",
    features: "Features",
    addFeature: "Add feature",
    feature: "Feature",
    nameRequired: "Enter a plan name.",
    priceInvalid: "Enter a price of 0 or more.",
    limitInvalid: "Enter a whole number above 0, or leave empty.",
    savePlan: "Save plan",
    createPlan: "Create plan",
    featuresList: "Plan features",
  },
  ar: {
    workspaces: "مساحات العمل",
    search: "ابحث بمساحة العمل أو المالك…",
    total: "مساحات العمل",
    trials: "تجريبية",
    suspendedStat: "موقوفة",
    mrr: "الإيراد الشهري",
    workspace: "مساحة العمل",
    owner: "المالك",
    plan: "الباقة",
    seats: "المقاعد",
    status: "الحالة",
    created: "تاريخ الإنشاء",
    unlimited: "غير محدود",
    statusActive: "نشطة",
    statusTrial: "تجريبية",
    statusSuspended: "موقوفة",
    trialEnds: "تنتهي التجربة",
    open: "فتح مساحة العمل",
    changePlan: "تغيير الباقة…",
    suspend: "إيقاف…",
    reactivate: "إعادة التفعيل",
    seatsOf: (used: string, max: string) => `${used} من ${max} مقعد`,
    seatsUsed: (used: string) => `${used} مقعد`,
    empty: "لا توجد مساحات عمل بعد",
    planOk: (name: string, plan: string) => `أصبحت ${name} على باقة ${plan}.`,
    suspendOk: (name: string) => `تم إيقاف ${name}.`,
    reactivateOk: (name: string) => `أُعيد تفعيل ${name}.`,
    planSavedOk: (name: string) => `تم حفظ ${name}.`,
    planCreatedOk: (name: string) => `تم إنشاء ${name}.`,
    failed: "لم تنجح العملية. حاول مرة أخرى.",
    dismiss: "تجاهل",
    cancel: "إلغاء",
    changeTitle: (name: string) => `تغيير باقة ${name}`,
    changeBody: "تسري الباقة الجديدة فورًا. تُحتسب الفوترة تناسبيًا لدى مزوّد الدفع.",
    newPlan: "الباقة الجديدة",
    overSeats: (used: string, max: string) => `تسمح هذه الباقة بـ ${max} مقعد بينما تستخدم مساحة العمل ${used}.`,
    saveChange: "تغيير الباقة",
    suspendTitle: (name: string) => `إيقاف ${name}؟`,
    suspendBody: "لن يستطيع الأعضاء الدخول إلى مساحة العمل حتى تعيد تفعيلها. لا يُحذف أي شيء.",
    suspendConfirm: "إيقاف مساحة العمل",
    plans: "الباقات",
    newPlanButton: "باقة جديدة",
    editPlan: "تعديل الباقة",
    perMonth: "شهر",
    subscribers: (n: string) => (n === "1" ? "مساحة عمل واحدة" : `${n} مساحات عمل`),
    storage: (n: string) => `${n} جيجابايت تخزين`,
    storageUnlimited: "تخزين غير محدود",
    seatsLimit: (n: string) => `حتى ${n} مقعد`,
    seatsUnlimited: "مقاعد غير محدودة",
    inactive: "مخفية",
    visible: "ظاهرة في صفحة الأسعار",
    visibleHint: "يمكن للمسؤول تعيين الباقات المخفية.",
    plansEmpty: "لا توجد باقات بعد",
    plansEmptyHint: "أنشئ أول باقة لبدء البيع.",
    createPlanTitle: "باقة جديدة",
    editPlanTitle: (name: string) => `تعديل ${name}`,
    planBody: "تنطبق الحدود على كل مساحة عمل. اترك الحد فارغًا لعدم التقييد.",
    planName: "اسم الباقة",
    planDescription: "لمن هذه الباقة",
    price: "السعر شهريًا",
    seatLimit: "حد المقاعد",
    storageLimit: "حد التخزين (جيجابايت)",
    features: "المزايا",
    addFeature: "إضافة ميزة",
    feature: "ميزة",
    nameRequired: "أدخل اسم الباقة.",
    priceInvalid: "أدخل سعرًا يساوي 0 أو أكثر.",
    limitInvalid: "أدخل عددًا صحيحًا أكبر من 0، أو اتركه فارغًا.",
    savePlan: "حفظ الباقة",
    createPlan: "إنشاء الباقة",
    featuresList: "مزايا الباقة",
  },
};
export const adminTenantsStrings = (locale: string) => ADMIN_TENANTS_STRINGS[locale.startsWith("ar") ? "ar" : "en"];

export type AdminTenantsLabels = Partial<typeof ADMIN_TENANTS_STRINGS.en>;
