export const STRINGS = {
  en: {
    actions: "Actions for {name}",
    edit: "Edit…",
    impersonate: "Impersonate…",
    password: "Password…",
    magicLink: "Send sign-in link",
    delete: "Delete…",
    cancel: "Cancel",
    failed: "That did not work. Try again.",
    editTitle: "Edit {name}",
    editBody: "Changes apply on their next request.",
    email: "Email address",
    emailInvalid: "Enter a valid email address.",
    roles: "Roles",
    permissions: "Permissions",
    tagPlaceholder: "Type and press Enter",
    save: "Save changes",
    impersonateTitle: "Impersonate {name}?",
    impersonateBody: "You will see the app exactly as they do. Everything you do is recorded in the audit log under both names.",
    impersonateConfirm: "Start impersonating",
    passwordTitle: "Password for {name}",
    passwordBody: "Set a new password yourself, or send them a link to choose one.",
    newPassword: "New password",
    passwordShort: "Use at least {min} characters.",
    setPassword: "Set password",
    sendReset: "Send reset link",
    passwordSet: "The password was changed. Tell them through a channel you trust.",
    resetLinkTitle: "Password reset link",
    magicLinkTitle: "Sign-in link",
    working: "Creating the link…",
    emailed: "We emailed the link to {email}.",
    shareOnce: "It works once. Share it only with this person.",
    link: "Link",
    noLink: "The server did not return a link.",
    done: "Done",
    deleteTitle: "Delete {name}?",
    deleteBody: "Their account and access go away at once. This cannot be undone.",
    deleteConfirm: "Delete user",
  },
  ar: {
    actions: "إجراءات {name}",
    edit: "تعديل…",
    impersonate: "انتحال الهوية…",
    password: "كلمة المرور…",
    magicLink: "إرسال رابط تسجيل الدخول",
    delete: "حذف…",
    cancel: "إلغاء",
    failed: "لم ينجح ذلك. حاول مرة أخرى.",
    editTitle: "تعديل {name}",
    editBody: "تسري التغييرات عند طلبه التالي.",
    email: "البريد الإلكتروني",
    emailInvalid: "أدخل بريدًا إلكترونيًا صالحًا.",
    roles: "الأدوار",
    permissions: "الصلاحيات",
    tagPlaceholder: "اكتب واضغط Enter",
    save: "حفظ التغييرات",
    impersonateTitle: "انتحال هوية {name}؟",
    impersonateBody: "سترى التطبيق كما يراه تمامًا. كل ما تفعله يُسجَّل في سجل التدقيق باسمكما معًا.",
    impersonateConfirm: "بدء انتحال الهوية",
    passwordTitle: "كلمة مرور {name}",
    passwordBody: "عيّن كلمة مرور جديدة بنفسك، أو أرسل له رابطًا ليختار واحدة.",
    newPassword: "كلمة المرور الجديدة",
    passwordShort: "استخدم {min} أحرف على الأقل.",
    setPassword: "تعيين كلمة المرور",
    sendReset: "إرسال رابط إعادة التعيين",
    passwordSet: "تم تغيير كلمة المرور. أبلغه بها عبر قناة موثوقة.",
    resetLinkTitle: "رابط إعادة تعيين كلمة المرور",
    magicLinkTitle: "رابط تسجيل الدخول",
    working: "جارٍ إنشاء الرابط…",
    emailed: "أرسلنا الرابط إلى {email}.",
    shareOnce: "يعمل مرة واحدة. شاركه مع هذا الشخص فقط.",
    link: "الرابط",
    noLink: "لم يُرجع الخادم رابطًا.",
    done: "تم",
    deleteTitle: "حذف {name}؟",
    deleteBody: "يُحذف حسابه وصلاحياته فورًا. لا يمكن التراجع عن ذلك.",
    deleteConfirm: "حذف المستخدم",
  },
};

export type UserActionsMenuLabels = typeof STRINGS.en;

export const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;

/** Replace `{key}` placeholders. */
export const fill = (text: string, values: Record<string, string>) => text.replace(/\{(\w+)\}/g, (m, k: string) => values[k] ?? m);
