import { computed } from "vue";
import { useNasaq } from "../../provider";
import type { QuestionError, ReviewFieldError } from "./review-logic";
const EN_PLURAL = new Intl.PluralRules("en");
const AR_PLURAL = new Intl.PluralRules("ar");

/** Counts read as the number in the count position ("1 answer", "2 answers"); pass the raw count so the noun agrees. */
const en = (count: number | undefined, one: string, other: string): string => (count !== undefined && EN_PLURAL.select(count) === "one" ? one : other);

/** Arabic nouns take six forms. Without a count the plain plural is used. */
function ar(count: number | undefined, forms: { one: string; two: string; few: string; many: string; other: string }): string {
  return count === undefined ? forms.many : forms[AR_PLURAL.select(count) as keyof typeof forms] ?? forms.other;
}

/** English and Arabic copy for reviews and Q&A. Every entry can be overridden with the `labels` prop. */
export const REVIEW_STRINGS = {
  en: {
    reviews: "Customer reviews",
    basedOn: (n: string, count?: number) => `Based on ${n} ${en(count, "review", "reviews")}`,
    reviewsCount: "reviews",
    starsRow: (n: string) => `${n} stars`,
    filterByStars: (n: string, count: string) => `Show only ${n}-star reviews (${count})`,
    stars: "Stars",
    histogram: "Rating breakdown. Choose a row to filter the reviews.",
    writeReview: "Write a review",
    sort: "Sort by",
    sortHelpful: "Most helpful",
    sortNewest: "Newest",
    sortOldest: "Oldest",
    sortHighest: "Highest rating",
    sortLowest: "Lowest rating",
    withPhotos: "With photos",
    verifiedOnly: "Verified purchases",
    clearFilters: "Clear filters",
    filters: "Filter reviews",
    search: "Search reviews",
    showing: (shown: string, total: string) => `Showing ${shown} of ${total} reviews`,
    showMore: "Show more reviews",
    noReviews: "No reviews yet",
    noReviewsHint: "Be the first to share what you think.",
    noMatches: "No reviews match these filters",
    photosTitle: "Photos from customers",
    photoOf: (n: string, total: string) => `Photo ${n} of ${total}`,
    viewPhoto: "View customer photo",
    prevPhoto: "Previous photo",
    nextPhoto: "Next photo",
    morePhotos: (n: string) => `+${n}`,
    verified: "Verified purchase",
    boughtVariant: (v: string) => `Bought: ${v}`,
    fitLabel: "Fit",
    fitSmall: "Runs small",
    fitTrue: "True to size",
    fitLarge: "Runs large",
    fitSummary: (n: string) => `Fit, from ${n} reviewers`,
    readMore: "Read more",
    readLess: "Read less",
    sellerReply: "Reply from the seller",
    helpful: "Helpful",
    helpfulCount: (n: string) => `Helpful (${n})`,
    helpfulUndo: "Marked helpful. Select to undo.",
    report: "Report",
    reported: "Reported",
    reportTitle: "Report this review",
    reportDescription: "Tell us what is wrong. We look at every report.",
    reportReason: "Reason",
    reasonSpam: "Spam or advertising",
    reasonOffensive: "Offensive or abusive",
    reasonFake: "Looks fake",
    reasonIrrelevant: "Not about this product",
    reasonOther: "Something else",
    reportNote: "Details (optional)",
    reportSend: "Send report",
    reportThanks: "Thanks. We will review it.",
    cancel: "Cancel",
    actions: "Review actions",
    loading: "Loading reviews",
    loadFailed: "Could not load the reviews.",
    retry: "Try again",
    voteFailed: "Could not save your vote. Try again.",
    // form
    formTitle: "Write a review",
    formDescription: "Share what you liked or did not, to help other shoppers.",
    yourRating: "Your rating",
    ratingStar: (n: string) => `${n} out of 5`,
    ratingWord: ["", "Poor", "Fair", "Good", "Very good", "Excellent"],
    reviewTitle: "Title (optional)",
    reviewTitleHint: "Sum it up in a few words.",
    reviewBody: "Your review",
    reviewBodyHint: (n: string) => `At least ${n} characters.`,
    yourName: "Name",
    fitQuestion: "How does it fit?",
    addPhotos: "Add photos",
    photosHint: (n: string) => `Up to ${n} photos.`,
    removePhoto: "Remove photo",
    submitReview: "Submit review",
    submitting: "Sending your review",
    reviewThanks: "Thanks for your review",
    reviewThanksHint: "It will appear after we check it.",
    submitFailed: "Could not send your review. Try again.",
    errors: {
      "rating-required": "Choose a star rating.",
      "title-required": "Add a title.",
      "title-too-long": "The title is too long.",
      "body-required": "Write your review.",
      "body-too-short": "Add a little more detail.",
      "body-too-long": "The review is too long.",
      "name-required": "Enter your name.",
      "too-many-photos": "You added too many photos.",
    } satisfies Record<ReviewFieldError, string>,
    // Q&A
    qaTitle: "Questions and answers",
    qaCount: (n: string, count?: number) => `${n} ${en(count, "question", "questions")}`,
    askTitle: "Ask a question",
    askPlaceholder: "Ask about size, materials, delivery…",
    askSubmit: "Post question",
    asking: "Posting your question",
    askThanks: "Your question was posted.",
    searchQuestions: "Search questions",
    noQuestions: "No questions yet",
    noQuestionsHint: "Ask the first one.",
    noQuestionMatches: "No questions match your search",
    answer: "Answer",
    answerPlaceholder: "Write your answer",
    answerSubmit: "Post answer",
    answers: (n: string, count?: number) => `${n} ${en(count, "answer", "answers")}`,
    noAnswers: "No answers yet",
    showAnswers: (n: string, count?: number) => `Show ${n} more ${en(count, "answer", "answers")}`,
    hideAnswers: "Show fewer answers",
    fromSeller: "Seller",
    upvote: "Upvote",
    upvoted: "Upvoted",
    upvoteCount: (n: string, count?: number) => `${n} ${en(count, "upvote", "upvotes")}`,
    askedBy: (name: string) => `Asked by ${name}`,
    questionErrors: {
      "question-required": "Write your question.",
      "question-too-short": "Add a little more detail.",
      "question-too-long": "The question is too long.",
    } satisfies Record<QuestionError, string>,
    answerRequired: "Write an answer first.",
    sortQuestions: "Sort questions",
    sortVotes: "Most upvoted",
    sortAnswered: "Most answered",
  },
  ar: {
    reviews: "تقييمات العملاء",
    basedOn: (n: string) => `بناءً على ${n} تقييم`,
    reviewsCount: "تقييم",
    starsRow: (n: string) => `${n} نجوم`,
    filterByStars: (n: string, count: string) => `عرض تقييمات ${n} نجوم فقط (${count})`,
    stars: "النجوم",
    histogram: "توزيع التقييمات. اختر صفًا لتصفية التقييمات.",
    writeReview: "اكتب تقييمًا",
    sort: "الترتيب",
    sortHelpful: "الأكثر فائدة",
    sortNewest: "الأحدث",
    sortOldest: "الأقدم",
    sortHighest: "الأعلى تقييمًا",
    sortLowest: "الأقل تقييمًا",
    withPhotos: "بها صور",
    verifiedOnly: "مشتريات موثّقة",
    clearFilters: "مسح التصفية",
    filters: "تصفية التقييمات",
    search: "ابحث في التقييمات",
    showing: (shown: string, total: string) => `عرض ${shown} من ${total} تقييم`,
    showMore: "عرض المزيد من التقييمات",
    noReviews: "لا توجد تقييمات بعد",
    noReviewsHint: "كن أول من يشارك رأيه.",
    noMatches: "لا توجد تقييمات تطابق هذه التصفية",
    photosTitle: "صور من العملاء",
    photoOf: (n: string, total: string) => `الصورة ${n} من ${total}`,
    viewPhoto: "عرض صورة العميل",
    prevPhoto: "الصورة السابقة",
    nextPhoto: "الصورة التالية",
    morePhotos: (n: string) => `+${n}`,
    verified: "شراء موثّق",
    boughtVariant: (v: string) => `اشترى: ${v}`,
    fitLabel: "المقاس",
    fitSmall: "ضيّق قليلًا",
    fitTrue: "المقاس مضبوط",
    fitLarge: "واسع قليلًا",
    fitSummary: (n: string) => `المقاس، حسب ${n} مقيّم`,
    readMore: "اقرأ المزيد",
    readLess: "عرض أقل",
    sellerReply: "رد البائع",
    helpful: "مفيد",
    helpfulCount: (n: string) => `مفيد (${n})`,
    helpfulUndo: "تم التعليم كمفيد. اضغط للتراجع.",
    report: "إبلاغ",
    reported: "تم الإبلاغ",
    reportTitle: "الإبلاغ عن هذا التقييم",
    reportDescription: "أخبرنا ما المشكلة. نراجع كل بلاغ.",
    reportReason: "السبب",
    reasonSpam: "محتوى دعائي أو مزعج",
    reasonOffensive: "مسيء أو مهين",
    reasonFake: "يبدو مزيفًا",
    reasonIrrelevant: "لا يخص هذا المنتج",
    reasonOther: "سبب آخر",
    reportNote: "تفاصيل (اختياري)",
    reportSend: "إرسال البلاغ",
    reportThanks: "شكرًا لك. سنراجعه.",
    cancel: "إلغاء",
    actions: "إجراءات التقييم",
    loading: "جارٍ تحميل التقييمات",
    loadFailed: "تعذّر تحميل التقييمات.",
    retry: "حاول مرة أخرى",
    voteFailed: "تعذّر حفظ تصويتك. حاول مرة أخرى.",
    formTitle: "اكتب تقييمًا",
    formDescription: "شاركنا ما أعجبك أو لم يعجبك لتساعد غيرك من المتسوّقين.",
    yourRating: "تقييمك",
    ratingStar: (n: string) => `${n} من 5`,
    ratingWord: ["", "سيئ", "مقبول", "جيد", "جيد جدًا", "ممتاز"],
    reviewTitle: "العنوان (اختياري)",
    reviewTitleHint: "لخّص رأيك في بضع كلمات.",
    reviewBody: "تقييمك",
    reviewBodyHint: (n: string) => `على الأقل ${n} حرفًا.`,
    yourName: "الاسم",
    fitQuestion: "كيف كان المقاس؟",
    addPhotos: "أضف صورًا",
    photosHint: (n: string) => `حتى ${n} صور.`,
    removePhoto: "إزالة الصورة",
    submitReview: "إرسال التقييم",
    submitting: "جارٍ إرسال تقييمك",
    reviewThanks: "شكرًا على تقييمك",
    reviewThanksHint: "سيظهر بعد مراجعته.",
    submitFailed: "تعذّر إرسال تقييمك. حاول مرة أخرى.",
    errors: {
      "rating-required": "اختر عدد النجوم.",
      "title-required": "أضف عنوانًا.",
      "title-too-long": "العنوان طويل جدًا.",
      "body-required": "اكتب تقييمك.",
      "body-too-short": "أضف مزيدًا من التفاصيل.",
      "body-too-long": "التقييم طويل جدًا.",
      "name-required": "أدخل اسمك.",
      "too-many-photos": "أضفت صورًا أكثر من المسموح.",
    } satisfies Record<ReviewFieldError, string>,
    qaTitle: "الأسئلة والأجوبة",
    qaCount: (n: string, count?: number) => ar(count, { one: "سؤال واحد", two: "سؤالان", few: `${n} أسئلة`, many: `${n} سؤالًا`, other: `${n} سؤال` }),
    askTitle: "اطرح سؤالًا",
    askPlaceholder: "اسأل عن المقاس أو الخامة أو التوصيل…",
    askSubmit: "نشر السؤال",
    asking: "جارٍ نشر سؤالك",
    askThanks: "تم نشر سؤالك.",
    searchQuestions: "ابحث في الأسئلة",
    noQuestions: "لا توجد أسئلة بعد",
    noQuestionsHint: "اطرح السؤال الأول.",
    noQuestionMatches: "لا توجد أسئلة تطابق بحثك",
    answer: "أجب",
    answerPlaceholder: "اكتب إجابتك",
    answerSubmit: "نشر الإجابة",
    answers: (n: string, count?: number) => ar(count, { one: "إجابة واحدة", two: "إجابتان", few: `${n} إجابات`, many: `${n} إجابة`, other: `${n} إجابة` }),
    noAnswers: "لا توجد إجابات بعد",
    showAnswers: (n: string, count?: number) => ar(count, { one: "عرض إجابة أخرى", two: "عرض إجابتين أخريين", few: `عرض ${n} إجابات أخرى`, many: `عرض ${n} إجابة أخرى`, other: `عرض ${n} إجابة أخرى` }),
    hideAnswers: "عرض إجابات أقل",
    fromSeller: "البائع",
    upvote: "تأييد",
    upvoted: "تم التأييد",
    upvoteCount: (n: string, count?: number) => ar(count, { one: "تأييد واحد", two: "تأييدان", few: `${n} تأييدات`, many: `${n} تأييدًا`, other: `${n} تأييد` }),
    askedBy: (name: string) => `سأل ${name}`,
    questionErrors: {
      "question-required": "اكتب سؤالك.",
      "question-too-short": "أضف مزيدًا من التفاصيل.",
      "question-too-long": "السؤال طويل جدًا.",
    } satisfies Record<QuestionError, string>,
    answerRequired: "اكتب إجابة أولًا.",
    sortQuestions: "ترتيب الأسئلة",
    sortVotes: "الأكثر تأييدًا",
    sortAnswered: "الأكثر إجابة",
  },
} as const;

export type ReviewStrings = { [K in keyof typeof REVIEW_STRINGS.en]: (typeof REVIEW_STRINGS.en)[K] extends (...a: infer A) => string ? (...a: A) => string : (typeof REVIEW_STRINGS.en)[K] extends readonly string[] ? readonly string[] : (typeof REVIEW_STRINGS.en)[K] extends string ? string : (typeof REVIEW_STRINGS.en)[K] };
export type ProductReviewsLabels = Partial<ReviewStrings>;

export type ReviewActionResult = void | { error?: string };

export function useReviewStrings(labels?: () => ProductReviewsLabels | undefined) {
  const nasaq = useNasaq();
  const isAr = computed(() => nasaq.locale.value.startsWith("ar"));
  const t = computed(() => ({ ...REVIEW_STRINGS[isAr.value ? "ar" : "en"], ...labels?.() }) as unknown as ReviewStrings);
  return { t, ar: isAr, locale: nasaq.locale };
}
