import { computed, type ComputedRef } from "vue";
import { useNasaq } from "../../provider";
import { formatNumber } from "../numeric";

export const HR_ATTENDANCE_STRINGS = {
  en: {
    attendance: "Attendance",
    today: "Today",
    clockedOut: "Clocked out",
    clockedIn: "Working",
    onBreak: "On break",
    since: (time: string) => `Since ${time}`,
    workedToday: "Worked today",
    shift: (start: string, end: string) => `Shift ${start} to ${end}`,
    clockIn: "Clock in",
    clockOut: "Clock out",
    startBreak: "Start break",
    endBreak: "End break",
    late: (min: string) => `Clocked in ${min} late`,
    onTime: "On time",
    noPunches: "No punches yet today.",
    punchIn: "Clocked in",
    punchOut: "Clocked out",
    punchBreakStart: "Break started",
    punchBreakEnd: "Break ended",
    punches: "Today's punches",
    failed: "That did not go through. Try again.",
    hoursShort: "h",
    minutesShort: "m",
    balances: "Leave balances",
    remaining: "days left",
    unlimited: "No limit",
    daysTaken: (n: string) => `${n} taken`,
    entitled: "Entitled",
    used: "Used",
    pendingDays: "Pending",
    available: "Available now",
    accrues: "Earned monthly",
    carry: (n: string) => `Up to ${n} carry over`,
    requestLeave: "Request leave",
    requestTitle: "Request leave",
    requestDescription: "Pick the type and dates. Weekends and public holidays are not counted.",
    leaveType: "Leave type",
    from: "From",
    to: "To",
    halfFirst: "Half day on the first day",
    halfLast: "Half day on the last day",
    reason: "Reason",
    reasonHint: "Optional. Your manager sees this.",
    workingDays: (n: string) => `${n} working days`,
    afterRequest: (n: string) => `${n} left after this request`,
    submit: "Send request",
    cancel: "Cancel",
    problems: {
      range: "The end date is before the start date.",
      none: "These dates have no working days.",
      overlap: "You already have leave on some of these days.",
      balance: "You do not have enough days available for this.",
      missing: "Pick both dates.",
    },
    leaveRequests: "Leave requests",
    employee: "Employee",
    type: "Type",
    dates: "Dates",
    days: "Days",
    status: "Status",
    search: "Search requests",
    approve: "Approve",
    reject: "Reject",
    withdraw: "Withdraw",
    statuses: { pending: "Pending", approved: "Approved", rejected: "Rejected", cancelled: "Withdrawn" },
    rejectTitle: "Reject this request?",
    rejectDescription: (who: string) => `${who} will see your note.`,
    note: "Note",
    noteHint: "Say why, so they can plan.",
    confirmReject: "Reject request",
    emptyRequests: "No leave requests",
    emptyRequestsDescription: "Requests will show here.",
    actionsFor: (name: string) => `Actions for ${name}`,
    payroll: "Payroll runs",
    period: "Period",
    employees: "Employees",
    gross: "Gross",
    deductions: "Deductions",
    net: "Net pay",
    payDate: "Pay date",
    runStatuses: { draft: "Draft", approved: "Approved", paid: "Paid" },
    approveRun: "Approve run",
    markPaid: "Mark as paid",
    viewRun: "View details",
    runTitle: (period: string) => `Payroll for ${period}`,
    runDescription: (count: string) => `${count} employees. Amounts are what each person is owed for the period.`,
    basic: "Basic",
    allowances: "Allowances",
    additions: "Additions",
    days2: "Days worked",
    total: "Total",
    emptyRuns: "No payroll runs yet",
    emptyRunsDescription: "Runs appear here once you start one.",
    close: "Close",
    runsLabel: "Payroll runs",
    linesLabel: "Payroll lines",
  },
  ar: {
    attendance: "الحضور",
    today: "اليوم",
    clockedOut: "تم تسجيل الانصراف",
    clockedIn: "على رأس العمل",
    onBreak: "في استراحة",
    since: (time: string) => `منذ ${time}`,
    workedToday: "ساعات العمل اليوم",
    shift: (start: string, end: string) => `الدوام من ${start} إلى ${end}`,
    clockIn: "تسجيل حضور",
    clockOut: "تسجيل انصراف",
    startBreak: "بدء استراحة",
    endBreak: "إنهاء الاستراحة",
    late: (min: string) => `سُجّل الحضور بتأخر ${min}`,
    onTime: "في الموعد",
    noPunches: "لا توجد بصمات اليوم بعد.",
    punchIn: "تسجيل حضور",
    punchOut: "تسجيل انصراف",
    punchBreakStart: "بدء استراحة",
    punchBreakEnd: "انتهاء استراحة",
    punches: "بصمات اليوم",
    failed: "لم تتم العملية. حاول مرة أخرى.",
    hoursShort: "س",
    minutesShort: "د",
    balances: "أرصدة الإجازات",
    remaining: "يومًا متبقيًا",
    unlimited: "بلا حد",
    daysTaken: (n: string) => `${n} مستخدمة`,
    entitled: "الاستحقاق",
    used: "المستخدم",
    pendingDays: "قيد الموافقة",
    available: "المتاح الآن",
    accrues: "يُكتسب شهريًا",
    carry: (n: string) => `يُرحّل حتى ${n}`,
    requestLeave: "طلب إجازة",
    requestTitle: "طلب إجازة",
    requestDescription: "اختر النوع والتواريخ. لا تُحتسب العطلات الأسبوعية والرسمية.",
    leaveType: "نوع الإجازة",
    from: "من",
    to: "إلى",
    halfFirst: "نصف يوم في اليوم الأول",
    halfLast: "نصف يوم في اليوم الأخير",
    reason: "السبب",
    reasonHint: "اختياري. يراه مديرك.",
    workingDays: (n: string) => `${n} أيام عمل`,
    afterRequest: (n: string) => `يتبقى ${n} بعد هذا الطلب`,
    submit: "إرسال الطلب",
    cancel: "إلغاء",
    problems: {
      range: "تاريخ النهاية قبل تاريخ البداية.",
      none: "لا توجد أيام عمل ضمن هذه التواريخ.",
      overlap: "لديك إجازة في بعض هذه الأيام.",
      balance: "رصيدك المتاح لا يكفي لهذا الطلب.",
      missing: "اختر التاريخين.",
    },
    leaveRequests: "طلبات الإجازة",
    employee: "الموظف",
    type: "النوع",
    dates: "التواريخ",
    days: "الأيام",
    status: "الحالة",
    search: "ابحث في الطلبات",
    approve: "موافقة",
    reject: "رفض",
    withdraw: "سحب الطلب",
    statuses: { pending: "قيد الموافقة", approved: "موافق عليها", rejected: "مرفوضة", cancelled: "مسحوبة" },
    rejectTitle: "رفض هذا الطلب؟",
    rejectDescription: (who: string) => `سيرى ${who} ملاحظتك.`,
    note: "ملاحظة",
    noteHint: "اذكر السبب ليتمكن من التخطيط.",
    confirmReject: "رفض الطلب",
    emptyRequests: "لا توجد طلبات إجازة",
    emptyRequestsDescription: "ستظهر الطلبات هنا.",
    actionsFor: (name: string) => `إجراءات ${name}`,
    payroll: "مسيرات الرواتب",
    period: "الفترة",
    employees: "الموظفون",
    gross: "الإجمالي",
    deductions: "الخصومات",
    net: "صافي الراتب",
    payDate: "تاريخ الصرف",
    runStatuses: { draft: "مسودة", approved: "معتمدة", paid: "مصروفة" },
    approveRun: "اعتماد المسيرة",
    markPaid: "تحديد كمصروفة",
    viewRun: "عرض التفاصيل",
    runTitle: (period: string) => `رواتب ${period}`,
    runDescription: (count: string) => `${count} موظفين. المبالغ هي المستحق لكل شخص عن الفترة.`,
    basic: "الأساسي",
    allowances: "البدلات",
    additions: "الإضافات",
    days2: "أيام العمل",
    total: "الإجمالي",
    emptyRuns: "لا توجد مسيرات رواتب بعد",
    emptyRunsDescription: "تظهر المسيرات هنا عند بدء أول واحدة.",
    close: "إغلاق",
    runsLabel: "مسيرات الرواتب",
    linesLabel: "بنود الرواتب",
  },
};

type Strings = typeof HR_ATTENDANCE_STRINGS.en;
export type HrAttendanceLabels = Partial<Omit<Strings, "problems" | "statuses" | "runStatuses">> & {
  problems?: Partial<Strings["problems"]>;
  statuses?: Partial<Strings["statuses"]>;
  runStatuses?: Partial<Strings["runStatuses"]>;
};

/** The strings for the locale (English or Arabic) with `labels` laid over them, plus number and duration formatters. */
export function useHrStrings(labels?: () => HrAttendanceLabels | undefined) {
  const nq = useNasaq();
  const locale = computed(() => nq.locale.value);
  const t: ComputedRef<Strings> = computed(() => {
    const base = HR_ATTENDANCE_STRINGS[locale.value.startsWith("ar") ? "ar" : "en"];
    const l = labels?.();
    return {
      ...base,
      ...l,
      problems: { ...base.problems, ...l?.problems },
      statuses: { ...base.statuses, ...l?.statuses },
      runStatuses: { ...base.runStatuses, ...l?.runStatuses },
    } as Strings;
  });
  const n = (value: number) => formatNumber(value, locale.value, { maximumFractionDigits: 1 });
  /** Whole minutes as "7h 05m" / "7 س 05 د". */
  const duration = (minutes: number) => {
    const h = Math.floor(minutes / 60);
    const m = minutes % 60;
    return `${formatNumber(h, locale.value)}${t.value.hoursShort} ${formatNumber(m, locale.value, { minimumIntegerDigits: 2 })}${t.value.minutesShort}`;
  };
  return { t, locale, n, duration };
}

/** The message of a rejected promise, or the fallback. */
export const hrFail = (e: unknown, fallback: string) => (e instanceof Error && e.message ? e.message : fallback);
