export const STRINGS = {
  en: {
    stepOf: "Step {current} of {total}",
    back: "Back",
    next: "Continue",
    skip: "Skip for now",
    finish: "Finish setup",
    optional: "Optional",
    steps: "Setup steps",
    gate: "Finish these steps first",
    failed: "Something went wrong. Try again.",
    doneTitle: "You are all set",
    doneDescription: "Setup is complete.",
    waiting: "Waiting for your agent to connect",
    waitingHint: "Run the command on the machine you want to connect. This page updates by itself.",
    connected: "Agent connected",
    timeout: "No agent has connected yet",
    timeoutHint: "Check that the command finished without errors and that the machine can reach us, then try again.",
    failedEnroll: "The agent could not enroll",
    retry: "Check again",
    command: "Install command",
    elapsed: "Waiting {time}",
    host: "Host",
    version: "Version",
    system: "System",
  },
  ar: {
    stepOf: "الخطوة {current} من {total}",
    back: "رجوع",
    next: "متابعة",
    skip: "تخطَّ الآن",
    finish: "إنهاء الإعداد",
    optional: "اختيارية",
    steps: "خطوات الإعداد",
    gate: "أكمل هذه الخطوات أولًا",
    failed: "حدث خطأ ما. حاول مرة أخرى.",
    doneTitle: "كل شيء جاهز",
    doneDescription: "اكتمل الإعداد.",
    waiting: "بانتظار اتصال الوكيل",
    waitingHint: "شغّل الأمر على الجهاز الذي تريد ربطه. تتحدّث هذه الصفحة تلقائيًا.",
    connected: "تم اتصال الوكيل",
    timeout: "لم يتصل أي وكيل بعد",
    timeoutHint: "تأكد من انتهاء الأمر بلا أخطاء ومن أن الجهاز يصل إلينا، ثم حاول مرة أخرى.",
    failedEnroll: "تعذّر تسجيل الوكيل",
    retry: "تحقق مرة أخرى",
    command: "أمر التثبيت",
    elapsed: "بانتظار منذ {time}",
    host: "المضيف",
    version: "الإصدار",
    system: "النظام",
  },
};

export type SetupWizardLabels = (typeof STRINGS)["en"];

export const fill = (template: string, values: Record<string, string | number>) => template.replace(/\{(\w+)\}/g, (_, k: string) => String(values[k] ?? ""));
