// Built-in English and Arabic strings, copied from packages/web/src/components/wallet/wallet.tsx.

export const STRINGS = {
  en: {
    balance: "Available balance",
    pending: "Pending",
    topUp: "Add funds",
    payout: "Withdraw",
    show: "Show balance",
    hide: "Hide balance",
    hidden: "Balance hidden",
    trend: "Balance over the last 30 days",
    transactions: "Transactions",
    all: "All",
    incoming: "Money in",
    outgoing: "Money out",
    filter: "Filter transactions",
    emptyTitle: "No transactions yet",
    emptyDescription: "Top-ups, payments and withdrawals will show here.",
    completed: "Completed",
    pendingStatus: "Pending",
    failed: "Failed",
    topup: "Top-up",
    payoutType: "Withdrawal",
    payment: "Payment",
    refund: "Refund",
    fee: "Fee",
    reference: "Reference",
    topUpTitle: "Add funds",
    topUpDescription: "Choose an amount and where the money comes from.",
    payoutTitle: "Withdraw to your bank",
    payoutDescription: (available: string) => `You can withdraw up to ${available}.`,
    amount: "Amount",
    quick: "Quick amounts",
    source: "Pay with",
    destination: "Withdraw to",
    max: "Withdraw all",
    confirmTopUp: (amount: string) => `Add ${amount}`,
    confirmPayout: (amount: string) => `Withdraw ${amount}`,
    add: "Add",
    withdraw: "Withdraw",
    cancel: "Cancel",
    invalid: "Enter an amount greater than zero.",
    min: (min: string) => `The minimum is ${min}.`,
    max2: (max: string) => `The maximum is ${max}.`,
    failedRequest: "That did not go through. Try again.",
    noAccounts: "Add a payment source first.",
    fees: (fee: string) => `A fee of ${fee} applies.`,
    today: "Today",
    yesterday: "Yesterday",
  },
  ar: {
    balance: "الرصيد المتاح",
    pending: "قيد المعالجة",
    topUp: "إضافة رصيد",
    payout: "سحب",
    show: "إظهار الرصيد",
    hide: "إخفاء الرصيد",
    hidden: "الرصيد مخفي",
    trend: "الرصيد خلال آخر 30 يومًا",
    transactions: "المعاملات",
    all: "الكل",
    incoming: "الوارد",
    outgoing: "الصادر",
    filter: "تصفية المعاملات",
    emptyTitle: "لا توجد معاملات بعد",
    emptyDescription: "ستظهر هنا عمليات الشحن والمدفوعات والسحب.",
    completed: "مكتملة",
    pendingStatus: "قيد المعالجة",
    failed: "فاشلة",
    topup: "شحن",
    payoutType: "سحب",
    payment: "دفعة",
    refund: "استرداد",
    fee: "رسوم",
    reference: "المرجع",
    topUpTitle: "إضافة رصيد",
    topUpDescription: "اختر المبلغ ومصدر الأموال.",
    payoutTitle: "السحب إلى حسابك البنكي",
    payoutDescription: (available: string) => `يمكنك سحب حتى ${available}.`,
    amount: "المبلغ",
    quick: "مبالغ سريعة",
    source: "الدفع عبر",
    destination: "السحب إلى",
    max: "سحب الكل",
    confirmTopUp: (amount: string) => `إضافة ${amount}`,
    confirmPayout: (amount: string) => `سحب ${amount}`,
    add: "إضافة",
    withdraw: "سحب",
    cancel: "إلغاء",
    invalid: "أدخل مبلغًا أكبر من الصفر.",
    min: (min: string) => `الحد الأدنى ${min}.`,
    max2: (max: string) => `الحد الأقصى ${max}.`,
    failedRequest: "لم تتم العملية. حاول مرة أخرى.",
    noAccounts: "أضف مصدر دفع أولًا.",
    fees: (fee: string) => `تُطبَّق رسوم قدرها ${fee}.`,
    today: "اليوم",
    yesterday: "أمس",
  },
};

type Strings = typeof STRINGS.en;
export type WalletLabels = Partial<Strings>;

export type WalletStrings = Strings;

/** Merged strings for a locale plus `labels`. */
export function walletStrings(locale: string, labels?: WalletLabels): WalletStrings {
  const ar = locale.startsWith("ar");
  return { ...STRINGS[ar ? "ar" : "en"], ...labels } as WalletStrings;
}
