import { computed } from "vue";
import { useNasaq } from "../../provider";
import type { NoteColor, NoteExportFormat, NoteGroupKind, NoteSort } from "./notes-model";

export const NOTES_STRINGS = {
  en: {
    // list
    notes: "Notes",
    search: "Search notes",
    searchPlaceholder: "Search title, tags and text",
    newNote: "New note",
    creating: "Creating…",
    sortBy: "Sort by",
    sort: { updated: "Last updated", created: "Newest", title: "Title" } as Record<NoteSort, string>,
    viewList: "List",
    viewGrid: "Board",
    viewMode: "View",
    groups: { pinned: "Pinned", today: "Today", yesterday: "Yesterday", week: "Previous 7 days", earlier: "Earlier", all: "All notes" } as Record<NoteGroupKind, string>,
    untitled: "Untitled",
    empty: "No notes yet",
    emptyHint: "Write your first note, or start from a notebook.",
    emptyArchive: "Nothing archived",
    emptyArchiveHint: "Archived notes stay here until you restore them.",
    emptySealed: "No sealed notes",
    emptySealedHint: "Seal a note with a password to hide its text.",
    emptyPinned: "No pinned notes",
    emptyPinnedHint: "Pin a note to keep it at the top.",
    noMatches: "No notes match",
    noMatchesHint: "Try another word, or clear the search.",
    clearSearch: "Clear search",
    loading: "Loading notes",
    retry: "Try again",
    resultCount: (n: string) => `${n} notes`,
    sealedNote: "Sealed note",
    sealedHint: "Unlock to read",
    pinnedBadge: "Pinned",
    actionsFor: (title: string) => `Actions for ${title}`,
    listActions: "Notes actions",
    // scopes
    scopes: "Notebooks and filters",
    all: "All notes",
    pinned: "Pinned",
    sealed: "Sealed",
    archive: "Archive",
    notebooks: "Notebooks",
    tags: "Tags",
    noNotebooks: "No notebooks",
    newNotebook: "New notebook",
    renameNotebook: "Rename notebook",
    deleteNotebook: "Delete notebook",
    notebookName: "Notebook name",
    notebookNamePlaceholder: "For example, Work",
    notebookParent: "Inside",
    notebookRoot: "Top level",
    notebookDeleteTitle: "Delete this notebook?",
    notebookDeleteBody: "Its notes are kept and move out of the notebook.",
    create: "Create",
    save: "Save",
    cancel: "Cancel",
    // note actions
    open: "Open",
    pin: "Pin",
    unpin: "Unpin",
    color: "Colour…",
    colorTitle: "Note colour",
    noColor: "No colour",
    colorNames: { gray: "Gray", red: "Red", orange: "Orange", amber: "Amber", green: "Green", teal: "Teal", blue: "Blue", violet: "Violet", pink: "Pink" } as Record<NoteColor, string>,
    editTags: "Tags…",
    tagsTitle: "Note tags",
    tagsPlaceholder: "Add a tag and press Enter",
    move: "Move to…",
    moveTitle: "Move to a notebook",
    moveNone: "No notebook",
    duplicate: "Duplicate",
    copySuffix: "copy",
    share: "Share…",
    export: "Export…",
    exportTitle: "Export note",
    exportHint: "Choose a file format.",
    exportFormats: { markdown: "Markdown (.md)", html: "Web page (.html)", text: "Plain text (.txt)" } as Record<NoteExportFormat, string>,
    exportDownload: "Download",
    exportAll: "Export notes…",
    exportColumns: { title: "Title", notebook: "Notebook", tags: "Tags", pinned: "Pinned", created: "Created", updated: "Updated", text: "Text" },
    seal: "Seal with password…",
    removeSeal: "Remove the seal…",
    lockNow: "Lock now",
    archiveNote: "Archive",
    restore: "Restore",
    deleteNote: "Delete",
    deleteTitle: "Delete this note?",
    deleteBody: "It is removed for good. Archive it instead to keep a copy.",
    deleteConfirm: "Delete note",
    lockedNoAction: "Unlock the note first",
    // seal dialogs
    sealTitle: "Seal this note",
    sealBody: "The text stays hidden until you enter the password. There is no way to recover a lost password.",
    unsealTitle: "Remove the seal",
    unsealBody: "Enter the password to make this note readable again.",
    password: "Password",
    passwordConfirm: "Repeat the password",
    passwordMismatch: "The passwords do not match.",
    passwordShort: "Use at least 4 characters.",
    sealAction: "Seal note",
    unsealAction: "Remove seal",
    // editor
    back: "All notes",
    titlePlaceholder: "Title",
    titleLabel: "Note title",
    bodyLabel: "Note text",
    bodyPlaceholder: "Write something…",
    write: "Write",
    preview: "Preview",
    nothingToPreview: "Nothing to preview.",
    format: "Format",
    formatTitle: "Format the selection",
    formats: {
      bold: "Bold",
      italic: "Italic",
      strike: "Strikethrough",
      code: "Code",
      link: "Link",
      wikilink: "Link to a note",
      h1: "Heading 1",
      h2: "Heading 2",
      h3: "Heading 3",
      quote: "Quote",
      bullet: "Bulleted list",
      ordered: "Numbered list",
      task: "Task list",
    },
    saving: "Saving…",
    saved: "Saved",
    savedAt: (when: string) => `Saved ${when}`,
    unsaved: "Unsaved changes",
    saveFailed: "Couldn't save",
    saveNow: "Save now",
    words: (n: string) => `${n} words`,
    readMinutes: (n: string) => `${n} min read`,
    created: (when: string) => `Created ${when}`,
    updated: (when: string) => `Updated ${when}`,
    notebook: "Notebook",
    properties: "Properties",
    noteActions: "Note actions",
    backlinks: "Linked from",
    noBacklinks: "No note links here yet. Type [[Title]] to link a note.",
    linksTo: "Links to",
    noLinks: "This note links to nothing yet.",
    openNote: (title: string) => `Open ${title}`,
    pickOne: "Pick a note",
    pickOneHint: "Choose a note from the list, or start a new one.",
    formatRich: "Rich text",
    formatMarkdown: "Markdown",
    // unlock
    locked: "This note is sealed",
    lockedHint: "Enter its password to read and edit it.",
    unlock: "Unlock",
    wrongPassword: "That password is not right.",
    unlockedBanner: "Unlocked for this session",
    shortcuts: "Shortcuts",
    failed: "Something went wrong",
  },
  ar: {
    notes: "الملاحظات",
    search: "بحث في الملاحظات",
    searchPlaceholder: "ابحث في العنوان والوسوم والنص",
    newNote: "ملاحظة جديدة",
    creating: "جارٍ الإنشاء…",
    sortBy: "ترتيب حسب",
    sort: { updated: "آخر تحديث", created: "الأحدث", title: "العنوان" } as Record<NoteSort, string>,
    viewList: "قائمة",
    viewGrid: "لوحة",
    viewMode: "العرض",
    groups: { pinned: "المثبّتة", today: "اليوم", yesterday: "أمس", week: "آخر 7 أيام", earlier: "أقدم", all: "كل الملاحظات" } as Record<NoteGroupKind, string>,
    untitled: "بلا عنوان",
    empty: "لا توجد ملاحظات بعد",
    emptyHint: "اكتب ملاحظتك الأولى، أو ابدأ من دفتر.",
    emptyArchive: "لا شيء في الأرشيف",
    emptyArchiveHint: "تبقى الملاحظات المؤرشفة هنا حتى تستعيدها.",
    emptySealed: "لا توجد ملاحظات مختومة",
    emptySealedHint: "اختم ملاحظة بكلمة مرور لإخفاء نصها.",
    emptyPinned: "لا توجد ملاحظات مثبّتة",
    emptyPinnedHint: "ثبّت ملاحظة لإبقائها في الأعلى.",
    noMatches: "لا توجد ملاحظات مطابقة",
    noMatchesHint: "جرّب كلمة أخرى، أو امسح البحث.",
    clearSearch: "مسح البحث",
    loading: "جارٍ تحميل الملاحظات",
    retry: "حاول مرة أخرى",
    resultCount: (n: string) => `${n} ملاحظات`,
    sealedNote: "ملاحظة مختومة",
    sealedHint: "افتح القفل للقراءة",
    pinnedBadge: "مثبّتة",
    actionsFor: (title: string) => `إجراءات ${title}`,
    listActions: "إجراءات الملاحظات",
    scopes: "الدفاتر والمرشّحات",
    all: "كل الملاحظات",
    pinned: "المثبّتة",
    sealed: "المختومة",
    archive: "الأرشيف",
    notebooks: "الدفاتر",
    tags: "الوسوم",
    noNotebooks: "لا توجد دفاتر",
    newNotebook: "دفتر جديد",
    renameNotebook: "إعادة تسمية الدفتر",
    deleteNotebook: "حذف الدفتر",
    notebookName: "اسم الدفتر",
    notebookNamePlaceholder: "مثلًا: العمل",
    notebookParent: "داخل",
    notebookRoot: "المستوى الأعلى",
    notebookDeleteTitle: "حذف هذا الدفتر؟",
    notebookDeleteBody: "تبقى ملاحظاته وتخرج من الدفتر.",
    create: "إنشاء",
    save: "حفظ",
    cancel: "إلغاء",
    open: "فتح",
    pin: "تثبيت",
    unpin: "إلغاء التثبيت",
    color: "اللون…",
    colorTitle: "لون الملاحظة",
    noColor: "بلا لون",
    colorNames: { gray: "رمادي", red: "أحمر", orange: "برتقالي", amber: "كهرماني", green: "أخضر", teal: "تركوازي", blue: "أزرق", violet: "بنفسجي", pink: "وردي" } as Record<NoteColor, string>,
    editTags: "الوسوم…",
    tagsTitle: "وسوم الملاحظة",
    tagsPlaceholder: "أضف وسمًا واضغط Enter",
    move: "نقل إلى…",
    moveTitle: "نقل إلى دفتر",
    moveNone: "بلا دفتر",
    duplicate: "تكرار",
    copySuffix: "نسخة",
    share: "مشاركة…",
    export: "تصدير…",
    exportTitle: "تصدير الملاحظة",
    exportHint: "اختر صيغة الملف.",
    exportFormats: { markdown: "Markdown ‏(.md)", html: "صفحة ويب ‏(.html)", text: "نص عادي ‏(.txt)" } as Record<NoteExportFormat, string>,
    exportDownload: "تنزيل",
    exportAll: "تصدير الملاحظات…",
    exportColumns: { title: "العنوان", notebook: "الدفتر", tags: "الوسوم", pinned: "مثبّتة", created: "أُنشئت", updated: "حُدّثت", text: "النص" },
    seal: "ختم بكلمة مرور…",
    removeSeal: "إزالة الختم…",
    lockNow: "قفل الآن",
    archiveNote: "أرشفة",
    restore: "استعادة",
    deleteNote: "حذف",
    deleteTitle: "حذف هذه الملاحظة؟",
    deleteBody: "ستُحذف نهائيًا. أرشفها بدلًا من ذلك إن أردت الاحتفاظ بنسخة.",
    deleteConfirm: "حذف الملاحظة",
    lockedNoAction: "افتح قفل الملاحظة أولًا",
    sealTitle: "ختم هذه الملاحظة",
    sealBody: "يبقى النص مخفيًا حتى تُدخل كلمة المرور. لا يمكن استرجاع كلمة مرور ضائعة.",
    unsealTitle: "إزالة الختم",
    unsealBody: "أدخل كلمة المرور لتصبح الملاحظة مقروءة من جديد.",
    password: "كلمة المرور",
    passwordConfirm: "أعد كتابة كلمة المرور",
    passwordMismatch: "كلمتا المرور غير متطابقتين.",
    passwordShort: "استخدم 4 أحرف على الأقل.",
    sealAction: "ختم الملاحظة",
    unsealAction: "إزالة الختم",
    back: "كل الملاحظات",
    titlePlaceholder: "العنوان",
    titleLabel: "عنوان الملاحظة",
    bodyLabel: "نص الملاحظة",
    bodyPlaceholder: "اكتب شيئًا…",
    write: "كتابة",
    preview: "معاينة",
    nothingToPreview: "لا شيء للمعاينة.",
    format: "تنسيق",
    formatTitle: "تنسيق التحديد",
    formats: {
      bold: "غامق",
      italic: "مائل",
      strike: "يتوسطه خط",
      code: "شيفرة",
      link: "رابط",
      wikilink: "رابط إلى ملاحظة",
      h1: "عنوان 1",
      h2: "عنوان 2",
      h3: "عنوان 3",
      quote: "اقتباس",
      bullet: "قائمة نقطية",
      ordered: "قائمة مرقّمة",
      task: "قائمة مهام",
    },
    saving: "جارٍ الحفظ…",
    saved: "تم الحفظ",
    savedAt: (when: string) => `تم الحفظ ${when}`,
    unsaved: "تغييرات غير محفوظة",
    saveFailed: "تعذّر الحفظ",
    saveNow: "احفظ الآن",
    words: (n: string) => `${n} كلمة`,
    readMinutes: (n: string) => `${n} د للقراءة`,
    created: (when: string) => `أُنشئت ${when}`,
    updated: (when: string) => `حُدّثت ${when}`,
    notebook: "الدفتر",
    properties: "الخصائص",
    noteActions: "إجراءات الملاحظة",
    backlinks: "مرتبطة من",
    noBacklinks: "لا ملاحظات تربط هنا بعد. اكتب [[العنوان]] لربط ملاحظة.",
    linksTo: "ترتبط بـ",
    noLinks: "لا ترتبط هذه الملاحظة بشيء بعد.",
    openNote: (title: string) => `فتح ${title}`,
    pickOne: "اختر ملاحظة",
    pickOneHint: "اختر ملاحظة من القائمة، أو ابدأ ملاحظة جديدة.",
    formatRich: "نص منسّق",
    formatMarkdown: "Markdown",
    locked: "هذه الملاحظة مختومة",
    lockedHint: "أدخل كلمة مرورها لقراءتها وتعديلها.",
    unlock: "فتح القفل",
    wrongPassword: "كلمة المرور غير صحيحة.",
    unlockedBanner: "مفتوحة لهذه الجلسة",
    shortcuts: "الاختصارات",
    failed: "حدث خطأ",
  },
};

export type NotesLabels = typeof NOTES_STRINGS.en;

/** The notes' words for the page language, with `labels` laid over them. */
export function useNotesLabels(labels: () => Partial<NotesLabels> | undefined) {
  const nq = useNasaq();
  const locale = computed(() => nq.locale.value);
  const t = computed(() => ({ ...NOTES_STRINGS[locale.value.startsWith("ar") ? "ar" : "en"], ...labels() }) as NotesLabels);
  return { locale, t };
}
