import type { LogLevel } from "./log-viewer-format";

export const LOG_VIEWER_STRINGS = {
  en: {
    title: "Logs",
    list: "Log entries",
    search: "Search logs",
    searchPlaceholder: "Search logs",
    regex: "Use regular expression",
    invalidRegex: "Invalid regular expression",
    levels: "Filter by level",
    level: { trace: "Trace", debug: "Debug", info: "Info", warn: "Warn", error: "Error", fatal: "Fatal" } as Record<LogLevel, string>,
    timestamps: "Show timestamps",
    follow: "Follow new logs",
    jump: "Jump to latest",
    streaming: "Live",
    copy: "Copy visible logs",
    copied: "Logs copied to clipboard",
    download: "Download logs",
    count: (shown: number, total: number) => (shown === total ? `${total} entries` : `${shown} of ${total} entries`),
    emptyTitle: "No logs yet",
    emptyBody: "New entries show up here as they arrive.",
    noMatchTitle: "No entries match",
    noMatchBody: "Try a different search or turn on more levels.",
    resetFilters: "Reset filters",
    detail: "Entry details",
    closeDetail: "Close details",
    copyEntry: "Copy entry",
    entryCopied: "Entry copied to clipboard",
    time: "Time",
    source: "Source",
    message: "Message",
    fields: "Fields",
  },
  ar: {
    title: "السجلات",
    list: "مدخلات السجل",
    search: "بحث في السجلات",
    searchPlaceholder: "ابحث في السجلات",
    regex: "استخدام تعبير نمطي",
    invalidRegex: "تعبير نمطي غير صالح",
    levels: "تصفية حسب المستوى",
    level: { trace: "تتبّع", debug: "تصحيح", info: "معلومات", warn: "تحذير", error: "خطأ", fatal: "حرج" } as Record<LogLevel, string>,
    timestamps: "إظهار الطوابع الزمنية",
    follow: "تتبّع السجلات الجديدة",
    jump: "الانتقال إلى الأحدث",
    streaming: "مباشر",
    copy: "نسخ السجلات الظاهرة",
    copied: "تم نسخ السجلات إلى الحافظة",
    download: "تنزيل السجلات",
    count: (shown: number, total: number) => (shown === total ? `${total} مدخلات` : `${shown} من ${total} مدخلات`),
    emptyTitle: "لا توجد سجلات بعد",
    emptyBody: "تظهر المدخلات الجديدة هنا فور وصولها.",
    noMatchTitle: "لا توجد مدخلات مطابقة",
    noMatchBody: "جرّب بحثًا آخر أو فعّل مستويات أكثر.",
    resetFilters: "إعادة ضبط المرشحات",
    detail: "تفاصيل المدخل",
    closeDetail: "إغلاق التفاصيل",
    copyEntry: "نسخ المدخل",
    entryCopied: "تم نسخ المدخل إلى الحافظة",
    time: "الوقت",
    source: "المصدر",
    message: "الرسالة",
    fields: "الحقول",
  },
};

export type LogViewerLabels = (typeof LOG_VIEWER_STRINGS)["en"];
