import type { SubscriptionIssue } from "./subscription-landing-logic";

// The built-in strings of packages/web/src/components/subscription-landing/subscription-landing.tsx.
const STRINGS = {
  en: {
    subscribeTitle: "Stay in the loop",
    subscribeBody: "Product news and new articles, once in a while. No spam.",
    name: "Name",
    optional: "optional",
    email: "Email address",
    consent: "Yes, send me emails. I can unsubscribe at any time.",
    subscribe: "Subscribe",
    pendingTitle: "Check your inbox",
    pendingBody: (email: string) => `We sent a confirmation link to ${email}. Your subscription starts when you open it.`,
    pendingWrong: "Wrong address? Start over",
    confirmTitle: "Confirm your subscription",
    confirmBody: (email: string) => `Confirm that ${email} should get our emails.`,
    confirm: "Yes, confirm",
    confirmedTitle: "You are subscribed",
    confirmedBody: "Thanks. Your first email is on its way soon.",
    unsubscribeTitle: "Unsubscribe",
    unsubscribeBody: (email: string) => `Stop emails to ${email}.`,
    reasonLabel: "Would you tell us why? (optional)",
    reasons: { too_many: "I get too many emails", not_relevant: "The emails are not relevant", never_signed: "I never signed up", other: "Something else" } as Record<string, string>,
    note: "Anything to add",
    unsubscribe: "Unsubscribe",
    unsubscribedTitle: "You are unsubscribed",
    unsubscribedBody: (email: string) => `${email} will not get any more emails from us.`,
    resubscribe: "That was a mistake. Subscribe again",
    resubscribedTitle: "Welcome back",
    resubscribedBody: "You are subscribed again.",
    failed: "That did not work. Try again.",
    issues: { "email-empty": "Enter your email address.", "email-invalid": "That does not look like an email address.", "consent-missing": "Tick the box to agree." } as Record<SubscriptionIssue, string>,
    privacy: "We keep your address private and never sell it.",
  },
  ar: {
    subscribeTitle: "ابقَ على اطلاع",
    subscribeBody: "أخبار المنتج ومقالات جديدة بين حين وآخر. بلا إزعاج.",
    name: "الاسم",
    optional: "اختياري",
    email: "البريد الإلكتروني",
    consent: "نعم، أرسلوا لي رسائل بريدية. يمكنني إلغاء الاشتراك في أي وقت.",
    subscribe: "اشتراك",
    pendingTitle: "تحقق من بريدك",
    pendingBody: (email: string) => `أرسلنا رابط تأكيد إلى ${email}. يبدأ اشتراكك عند فتحه.`,
    pendingWrong: "العنوان خاطئ؟ ابدأ من جديد",
    confirmTitle: "أكّد اشتراكك",
    confirmBody: (email: string) => `أكّد أن ${email} يريد استلام رسائلنا.`,
    confirm: "نعم، أكّد",
    confirmedTitle: "تم اشتراكك",
    confirmedBody: "شكرًا. رسالتك الأولى في الطريق.",
    unsubscribeTitle: "إلغاء الاشتراك",
    unsubscribeBody: (email: string) => `إيقاف الرسائل إلى ${email}.`,
    reasonLabel: "هل تخبرنا بالسبب؟ (اختياري)",
    reasons: { too_many: "تصلني رسائل كثيرة", not_relevant: "الرسائل لا تعنيني", never_signed: "لم أشترك أصلًا", other: "سبب آخر" } as Record<string, string>,
    note: "أي إضافة",
    unsubscribe: "إلغاء الاشتراك",
    unsubscribedTitle: "تم إلغاء اشتراكك",
    unsubscribedBody: (email: string) => `لن يصل ${email} أي بريد آخر منا.`,
    resubscribe: "كان هذا خطأ. اشترك من جديد",
    resubscribedTitle: "أهلًا بعودتك",
    resubscribedBody: "تم اشتراكك من جديد.",
    failed: "لم تنجح العملية. حاول مرة أخرى.",
    issues: { "email-empty": "أدخل بريدك الإلكتروني.", "email-invalid": "لا يبدو هذا بريدًا إلكترونيًا.", "consent-missing": "ضع علامة للموافقة." } as Record<SubscriptionIssue, string>,
    privacy: "نحافظ على خصوصية عنوانك ولا نبيعه أبدًا.",
  },
};

export type SubscriptionLandingLabels = typeof STRINGS.en;
export { STRINGS };
