// The report's words, en and ar, copied from the React HealthReport.
import type { ReportMetric } from "./math";

export const STRINGS = {
  en: {
    title: "Reports",
    lede: "Your recent days, in counts and averages. Days with no reading are left out, never counted as zero.",
    period: "Period",
    periodOption: (days: number) => `${days} days`,
    export: "Export CSV",
    exporting: "Exporting",
    exportFailed: "The export failed.",
    averages: "Averages",
    averagesDescription: (n: number) => `Across the ${n} days that reported each figure.`,
    avgWater: "Average water",
    avgSteps: "Average steps",
    avgSleep: "Average sleep",
    avgHeartRate: "Average resting heart rate",
    weightChange: "Weight change",
    notEnough: "Not enough readings",
    trend: "Trend",
    metrics: { waterMl: "Water", steps: "Steps", sleepMinutes: "Sleep", weightKg: "Weight", restingHeartRate: "Resting heart rate", activeEnergyKcal: "Active energy" } as Record<ReportMetric, string>,
    metricPicker: "Figure to chart",
    trendSummary: (label: string, days: number) => `${label} over the last ${days} days`,
    noReadings: "No readings in this period for this figure.",
    meals: "Meals",
    mealsDescription: "Meals per day by safety.",
    caffeine: "Caffeine",
    caffeineDescription: "Caffeine drinks per day, counted.",
    safe: "Safe",
    unsafe: "Unsafe",
    clean: "Clean",
    sugar: "With sugar",
    adherence: "Protocol days",
    adherenceDescription: "For each engine that judges days: days on protocol, off it, and days it declined to judge.",
    engine: "Engine",
    onProtocol: "On protocol",
    offProtocol: "Off protocol",
    notJudged: "Not judged",
    currentStreak: "Current streak",
    bestStreak: "Best streak",
    loadError: "The report could not be loaded.",
    retry: "Try again",
    empty: "No days in this period",
    emptyHint: "Log something or sync a device to build a report.",
    shutdownDays: "Days with shutdown violations",
    tableCaption: "Protocol days per engine",
  },
  ar: {
    title: "التقارير",
    lede: "أيامك الأخيرة بالأعداد والمتوسطات. الأيام بلا قراءة تُستبعد ولا تُحسب صفرًا.",
    period: "الفترة",
    periodOption: (days: number) => `${days} يومًا`,
    export: "تصدير CSV",
    exporting: "جارٍ التصدير",
    exportFailed: "فشل التصدير.",
    averages: "المتوسطات",
    averagesDescription: (n: number) => `على مدى ${n} يومًا أبلغ كل رقم فيها.`,
    avgWater: "متوسط الماء",
    avgSteps: "متوسط الخطوات",
    avgSleep: "متوسط النوم",
    avgHeartRate: "متوسط نبض الراحة",
    weightChange: "تغيّر الوزن",
    notEnough: "قراءات غير كافية",
    trend: "الاتجاه",
    metrics: { waterMl: "الماء", steps: "الخطوات", sleepMinutes: "النوم", weightKg: "الوزن", restingHeartRate: "نبض الراحة", activeEnergyKcal: "الطاقة النشطة" } as Record<ReportMetric, string>,
    metricPicker: "الرقم المعروض",
    trendSummary: (label: string, days: number) => `${label} خلال آخر ${days} يومًا`,
    noReadings: "لا قراءات في هذه الفترة لهذا الرقم.",
    meals: "الوجبات",
    mealsDescription: "الوجبات في اليوم حسب الأمان.",
    caffeine: "الكافيين",
    caffeineDescription: "مشروبات الكافيين في اليوم، معدودة.",
    safe: "آمنة",
    unsafe: "غير آمنة",
    clean: "بدون سكر",
    sugar: "مع سكر",
    adherence: "أيام البروتوكول",
    adherenceDescription: "لكل محرّك يحكم على الأيام: أيام ضمن البروتوكول وخارجه وأيام امتنع عن تقييمها.",
    engine: "المحرّك",
    onProtocol: "ضمن البروتوكول",
    offProtocol: "خارج البروتوكول",
    notJudged: "لم تُقيَّم",
    currentStreak: "السلسلة الحالية",
    bestStreak: "أفضل سلسلة",
    loadError: "تعذّر تحميل التقرير.",
    retry: "حاول مرة أخرى",
    empty: "لا أيام في هذه الفترة",
    emptyHint: "سجّل شيئًا أو زامن جهازًا لبناء تقرير.",
    shutdownDays: "أيام فيها مخالفات إغلاق",
    tableCaption: "أيام البروتوكول لكل محرّك",
  },
};

export type HealthReportLabels = typeof STRINGS.en;
