import type { AccessLevel } from "./access-rules";

export const ACCESS_GRANTS_STRINGS = {
  en: {
    appsTitle: "Authorized apps and agents",
    appsBody: "Apps and AI agents you have allowed to act on your behalf. Revoking cuts their access at once.",
    appsLabel: "Authorized apps and agents",
    workspace: "Workspace",
    allWorkspaces: "All workspaces",
    agent: "Agent",
    app: "App",
    readOnly: "Read only",
    scopesMore: (n: string) => `+${n} more`,
    noScopes: "No permissions",
    authorized: "Authorized",
    lastUsed: "Last used",
    neverUsed: "Never used",
    revoke: "Revoke",
    revokeTitle: (name: string) => `Revoke ${name}?`,
    revokeBody: "It loses access immediately and must ask you again to get it back. Its agent keys stop working.",
    revokeFailed: "Access could not be revoked. Try again.",
    revoked: (name: string) => `${name} was revoked.`,
    appsEmpty: "No apps or agents yet",
    appsEmptyHint: "When you approve an app or connect an agent, it appears here.",
    keysTitle: "Agent keys",
    keysBody: "Keys an agent uses to act for you. Each carries only the scopes you pick.",
    keysCreate: "Create agent key",
    keysEmptyTitle: "No agent keys yet",
    keysEmptyBody: "Create a key to let an agent act on your behalf.",
    keysCreateTitle: "Create an agent key",
    grantsTitle: "What agents can reach",
    grantsBody: "Choose, per agent, which resources it can read and which it can change. Write includes read.",
    grantsLabel: "Agent access by resource",
    agentColumn: "Agent",
    levels: { none: "No access", read: "Read", write: "Read and write" } as Record<AccessLevel, string>,
    cell: (agent: string, resource: string) => `${agent}: ${resource}`,
    summary: (r: string, w: string) => `Reads ${r}, writes ${w}`,
    grantsEmpty: "No agents connected",
    grantsEmptyHint: "Connect an agent to control what it can reach.",
    grantFailed: "That change did not save, so it was put back. Try again.",
    dismiss: "Dismiss",
  },
  ar: {
    appsTitle: "التطبيقات والوكلاء المصرّح لهم",
    appsBody: "تطبيقات ووكلاء ذكاء اصطناعي سمحت لهم بالتصرف نيابةً عنك. الإلغاء يقطع وصولهم فورًا.",
    appsLabel: "التطبيقات والوكلاء المصرّح لهم",
    workspace: "مساحة العمل",
    allWorkspaces: "كل مساحات العمل",
    agent: "وكيل",
    app: "تطبيق",
    readOnly: "قراءة فقط",
    scopesMore: (n: string) => `+${n} أخرى`,
    noScopes: "بلا صلاحيات",
    authorized: "تاريخ التصريح",
    lastUsed: "آخر استخدام",
    neverUsed: "لم يُستخدم",
    revoke: "إلغاء الوصول",
    revokeTitle: (name: string) => `إلغاء وصول ${name}؟`,
    revokeBody: "يفقد وصوله فورًا وعليه أن يطلب منك من جديد ليستعيده. وتتوقف مفاتيح الوكيل عن العمل.",
    revokeFailed: "تعذّر إلغاء الوصول. حاول مرة أخرى.",
    revoked: (name: string) => `تم إلغاء وصول ${name}.`,
    appsEmpty: "لا توجد تطبيقات أو وكلاء بعد",
    appsEmptyHint: "عندما توافق على تطبيق أو تربط وكيلًا سيظهر هنا.",
    keysTitle: "مفاتيح الوكلاء",
    keysBody: "مفاتيح يستخدمها الوكيل ليتصرف نيابةً عنك. يحمل كل مفتاح الصلاحيات التي تختارها فقط.",
    keysCreate: "إنشاء مفتاح وكيل",
    keysEmptyTitle: "لا توجد مفاتيح وكلاء بعد",
    keysEmptyBody: "أنشئ مفتاحًا ليتصرف وكيل نيابةً عنك.",
    keysCreateTitle: "إنشاء مفتاح وكيل",
    grantsTitle: "ما يستطيع الوكلاء الوصول إليه",
    grantsBody: "اختر لكل وكيل الموارد التي يقرأها والتي يغيّرها. الكتابة تشمل القراءة.",
    grantsLabel: "وصول الوكلاء حسب المورد",
    agentColumn: "الوكيل",
    levels: { none: "بلا وصول", read: "قراءة", write: "قراءة وكتابة" } as Record<AccessLevel, string>,
    cell: (agent: string, resource: string) => `${agent}: ${resource}`,
    summary: (r: string, w: string) => `يقرأ ${r}، ويكتب ${w}`,
    grantsEmpty: "لا يوجد وكلاء مرتبطون",
    grantsEmptyHint: "اربط وكيلًا لتتحكم فيما يصل إليه.",
    grantFailed: "لم يُحفظ هذا التغيير فأُعيد كما كان. حاول مرة أخرى.",
    dismiss: "إغلاق",
  },
};
export const accessGrantsStrings = (locale: string) => ACCESS_GRANTS_STRINGS[locale.startsWith("ar") ? "ar" : "en"];
export type AccessGrantsLabels = Partial<typeof ACCESS_GRANTS_STRINGS.en>;
