import type { CampaignChannel, CampaignIssue } from "./campaign-logic";

export const STRINGS = {
  en: {
    channel: "Channel",
    channels: { email: "Email", whatsapp: "WhatsApp" } as Record<CampaignChannel, string>,
    audience: "Audience",
    audiencePlaceholder: "Choose who gets it",
    reach: "Will reach",
    people: (n: number): string => (n === 1 ? "person" : "people"),
    counting: "Counting…",
    countFailed: "Could not count this audience.",
    subject: "Subject",
    subjectHint: "What they see before opening.",
    body: "Message",
    whatsappBody: "Message text",
    whatsappHint: "Plain text. WhatsApp allows up to 1,024 characters.",
    variables: "Variables",
    variablesHint: "Filled in for each person.",
    insert: (label: string) => `Insert ${label}`,
    copyVariable: (label: string) => `Copy ${label} variable`,
    preview: "Preview",
    footerEmail: "You get this because you subscribed. Unsubscribe any time.",
    footerWhatsapp: "Reply STOP to unsubscribe.",
    sendTest: "Send a test",
    testTitle: "Send a test",
    testEmail: "Send the test to this address. It uses sample values for the variables.",
    testWhatsapp: "Send the test to your own workspace number only. It uses sample values for the variables.",
    testTo: (c: CampaignChannel): string => (c === "email" ? "Email address" : "WhatsApp number"),
    testSent: "Test sent",
    testInvalid: "Enter a valid address or number.",
    send: "Send campaign",
    sendTitle: (n: number) => `Send to ${n.toLocaleString("en")} ${n === 1 ? "person" : "people"}?`,
    sendBody: "This goes out right away and cannot be recalled. Send a test first if you have not.",
    cancel: "Cancel",
    confirmSend: "Send now",
    checks: "Before you send",
    issues: {
      "audience-none": "Choose an audience.",
      "audience-empty": "This audience has no one reachable on this channel.",
      "subject-empty": "Add a subject.",
      "body-empty": "Write the message.",
      "body-too-long": "The message is over the WhatsApp limit.",
      "variable-unknown": "The message uses a variable that does not exist.",
    } as Record<CampaignIssue, string>,
    ready: "Ready to send.",
    failed: "That did not work. Try again.",
    sending: "Sending",
    sentOf: (s: number, t: number) => `${s.toLocaleString("en")} of ${t.toLocaleString("en")} sent`,
    failedCount: (n: number) => `${n.toLocaleString("en")} failed`,
    done: "Sent to everyone.",
    partial: "Finished, but some did not go through.",
    stop: "Stop sending",
    characters: (n: number, max: number) => `${n.toLocaleString("en")} / ${max.toLocaleString("en")}`,
    noPreview: "Nothing to preview yet",
  },
  ar: {
    channel: "القناة",
    channels: { email: "بريد إلكتروني", whatsapp: "واتساب" } as Record<CampaignChannel, string>,
    audience: "الجمهور",
    audiencePlaceholder: "اختر من سيستلم",
    reach: "سيصل إلى",
    people: (n: number): string => (n === 1 ? "شخص" : "شخصًا"),
    counting: "جارٍ العدّ…",
    countFailed: "تعذّر عدّ هذا الجمهور.",
    subject: "الموضوع",
    subjectHint: "ما يراه المستلم قبل الفتح.",
    body: "الرسالة",
    whatsappBody: "نص الرسالة",
    whatsappHint: "نص عادي. يسمح واتساب بحتى 1024 حرفًا.",
    variables: "المتغيرات",
    variablesHint: "تُملأ لكل شخص.",
    insert: (label: string) => `إدراج ${label}`,
    copyVariable: (label: string) => `نسخ متغير ${label}`,
    preview: "معاينة",
    footerEmail: "وصلتك هذه الرسالة لأنك اشتركت. يمكنك إلغاء الاشتراك في أي وقت.",
    footerWhatsapp: "أرسل STOP لإلغاء الاشتراك.",
    sendTest: "إرسال تجربة",
    testTitle: "إرسال تجربة",
    testEmail: "أرسل التجربة إلى هذا العنوان. تُستخدم قيم تجريبية للمتغيرات.",
    testWhatsapp: "أرسل التجربة إلى رقم مساحة عملك فقط. تُستخدم قيم تجريبية للمتغيرات.",
    testTo: (c: CampaignChannel): string => (c === "email" ? "عنوان البريد" : "رقم واتساب"),
    testSent: "تم إرسال التجربة",
    testInvalid: "أدخل عنوانًا أو رقمًا صحيحًا.",
    send: "إرسال الحملة",
    sendTitle: (n: number) => `الإرسال إلى ${n.toLocaleString("ar")} ${n === 1 ? "شخص" : "شخصًا"}؟`,
    sendBody: "يُرسل فورًا ولا يمكن استرجاعه. أرسل تجربة أولًا إن لم تفعل.",
    cancel: "إلغاء",
    confirmSend: "أرسل الآن",
    checks: "قبل الإرسال",
    issues: {
      "audience-none": "اختر جمهورًا.",
      "audience-empty": "لا أحد في هذا الجمهور يمكن الوصول إليه عبر هذه القناة.",
      "subject-empty": "أضف موضوعًا.",
      "body-empty": "اكتب الرسالة.",
      "body-too-long": "الرسالة أطول من حد واتساب.",
      "variable-unknown": "تستخدم الرسالة متغيرًا غير موجود.",
    } as Record<CampaignIssue, string>,
    ready: "جاهزة للإرسال.",
    failed: "لم تنجح العملية. حاول مرة أخرى.",
    sending: "جارٍ الإرسال",
    sentOf: (s: number, t: number) => `أُرسلت ${s.toLocaleString("ar")} من ${t.toLocaleString("ar")}`,
    failedCount: (n: number) => `فشلت ${n.toLocaleString("ar")}`,
    done: "أُرسلت للجميع.",
    partial: "انتهى الإرسال، لكن بعض الرسائل لم تصل.",
    stop: "إيقاف الإرسال",
    characters: (n: number, max: number) => `${n.toLocaleString("ar")} / ${max.toLocaleString("ar")}`,
    noPreview: "لا شيء للمعاينة بعد",
  },
};
export type CampaignComposerLabels = typeof STRINGS.en;
