// The built-in words of BookingManage and BookingTicket (English and Arabic), same as the React component's STRINGS.
export const STRINGS = {
  en: {
    ticket: "Booking ticket",
    scan: "Show this code at reception.",
    code: "Booking code",
    when: "When",
    who: "Patient",
    provider: "With",
    where: "Where",
    phone: "Phone",
    payment: "Payment",
    payOnline: "Paid online",
    payOnlinePending: "To pay online",
    payVisit: "Pay at the visit",
    addToCalendar: "Add to calendar",
    downloadIcs: "Download .ics",
    google: "Google Calendar",
    qrLabel: (code: string) => `QR code for booking ${code}`,
    reschedule: "Reschedule",
    cancel: "Cancel booking",
    rescheduleTitle: "Choose a new time",
    rescheduleText: "Your booking moves to the time you pick. The old time is released.",
    confirmMove: "Move my booking",
    close: "Keep current time",
    cancelTitle: "Cancel this booking?",
    freeCancel: (hours: number) => `You can cancel for free up to ${hours} hours before the visit.`,
    lateFee: (pct: number) => `Cancelling now is late: ${pct}% of the price is charged.`,
    lateNoFee: "Cancelling now is late, but it is not charged.",
    tooLate: "This booking can no longer be changed online. Call the clinic.",
    noReschedule: (hours: number) => `Rescheduling closes ${hours} hours before the visit.`,
    cancelConfirm: "Yes, cancel it",
    cancelledNote: "This booking was cancelled.",
    failed: "That did not work. Try again.",
    loading: "Loading times",
  },
  ar: {
    ticket: "تذكرة الحجز",
    scan: "أظهر هذا الرمز عند الاستقبال.",
    code: "رمز الحجز",
    when: "الموعد",
    who: "المريض",
    provider: "مع",
    where: "المكان",
    phone: "الهاتف",
    payment: "الدفع",
    payOnline: "تم الدفع إلكترونيًا",
    payOnlinePending: "الدفع إلكترونيًا",
    payVisit: "الدفع عند الزيارة",
    addToCalendar: "أضف إلى التقويم",
    downloadIcs: "تنزيل ملف ‎.ics",
    google: "تقويم Google",
    qrLabel: (code: string) => `رمز QR للحجز ${code}`,
    reschedule: "تغيير الموعد",
    cancel: "إلغاء الحجز",
    rescheduleTitle: "اختر موعدًا جديدًا",
    rescheduleText: "سينتقل حجزك إلى الموعد الذي تختاره، ويُحرَّر الموعد القديم.",
    confirmMove: "انقل حجزي",
    close: "إبقاء الموعد الحالي",
    cancelTitle: "إلغاء هذا الحجز؟",
    freeCancel: (hours: number) => `يمكنك الإلغاء مجانًا حتى ${hours} ساعة قبل الزيارة.`,
    lateFee: (pct: number) => `الإلغاء الآن متأخر: تُحتسب ${pct}% من السعر.`,
    lateNoFee: "الإلغاء الآن متأخر، لكن لا رسوم عليه.",
    tooLate: "لم يعد ممكنًا تعديل هذا الحجز عبر الإنترنت. تواصل مع العيادة.",
    noReschedule: (hours: number) => `يُغلق تغيير الموعد قبل الزيارة بـ ${hours} ساعة.`,
    cancelConfirm: "نعم، ألغِ الحجز",
    cancelledNote: "تم إلغاء هذا الحجز.",
    failed: "لم تنجح العملية. حاول مجددًا.",
    loading: "جارٍ تحميل المواعيد",
  },
};

export type BookingManageLabels = (typeof STRINGS)["en"];
