// Writes src/alpine/index.ts: one entry per component module, so ports never edit a shared file.
// A module is src/alpine/<name>.ts exporting `const <camelName>: Register`; other files there (shared helpers) are skipped.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";

const root = new URL("../src/alpine/", import.meta.url);
const skip = new Set(["index", "types", "presence"]);
const camel = (n) => n.replace(/-(\w)/g, (_, c) => c.toUpperCase());
const registers = (n) => new RegExp(`export const ${camel(n)}\\s*:\\s*Register\\b`).test(readFileSync(new URL(`${n}.ts`, root), "utf8"));
const names = readdirSync(root)
  .filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts") && !f.endsWith(".d.ts"))
  .map((f) => f.slice(0, -3))
  .filter((n) => !skip.has(n) && registers(n))
  .sort();
writeFileSync(
  new URL("index.ts", root),
  `// Generated by scripts/gen-index.mjs. Do not edit.
import type { Register } from "./types";
${names.map((n) => `import { ${camel(n)} } from "./${n}";`).join("\n")}

/** Every component's Alpine.data registration, keyed by component folder name. */
export const components: Record<string, Register> = {
${names.map((n) => `  ${JSON.stringify(n)}: ${camel(n)},`).join("\n")}
};
`,
);
console.log(`alpine: ${names.length} components`);
