import type { AuditChannel } from "./audit-rules";

export const AUDIT_LOG_STRINGS = {
  en: {
    table: "Audit log",
    search: "Search actor, action or entity",
    actor: "Actor",
    action: "Action",
    entity: "Entity",
    channel: "Channel",
    when: "When",
    system: "System",
    dates: "Dates",
    datePlaceholder: "Any date",
    clearDates: "Clear dates",
    channels: { web: "Web", api: "API", mcp: "MCP" } as Record<AuditChannel, string>,
    empty: "No activity yet",
    emptyHint: "Actions taken in this workspace will appear here.",
    noMatch: "Nothing matches these filters",
    noMatchHint: "Widen the dates or clear a filter.",
    refresh: "Refresh",
    details: "Details",
    detailsFor: (action: string) => `Details of ${action}`,
    at: "Time",
    ip: "IP address",
    changes: "Changes",
    noChanges: "No field changes were recorded for this action.",
    field: "Field",
    before: "Before",
    after: "After",
    added: "Added",
    removed: "Removed",
    changed: "Changed",
    empty_value: "empty",
    fieldCount: (n: string) => (n === "1" ? "1 field" : `${n} fields`),
    // retention
    retention: "Retention",
    retentionHint: "How long entries are kept before they are deleted for good.",
    retentionAria: "Retention period",
    forever: "Keep forever",
    days: (n: string) => `${n} days`,
    year: "1 year",
    years: (n: string) => `${n} years`,
    retentionExpiring: (n: string) => (n === "1" ? "1 entry is older than this and will be deleted." : `${n} entries are older than this and will be deleted.`),
    retentionSaved: "Retention updated.",
    retentionFailed: "Retention could not be changed. Try again.",
  },
  ar: {
    table: "سجل التدقيق",
    search: "ابحث بالمنفّذ أو الإجراء أو الكيان",
    actor: "المنفّذ",
    action: "الإجراء",
    entity: "الكيان",
    channel: "القناة",
    when: "الوقت",
    system: "النظام",
    dates: "التواريخ",
    datePlaceholder: "أي تاريخ",
    clearDates: "مسح التواريخ",
    channels: { web: "الويب", api: "واجهة API", mcp: "MCP" } as Record<AuditChannel, string>,
    empty: "لا يوجد نشاط بعد",
    emptyHint: "ستظهر هنا الإجراءات التي تتم في مساحة العمل هذه.",
    noMatch: "لا شيء يطابق هذه المرشحات",
    noMatchHint: "وسّع التواريخ أو امسح أحد المرشحات.",
    refresh: "تحديث",
    details: "التفاصيل",
    detailsFor: (action: string) => `تفاصيل ${action}`,
    at: "الوقت",
    ip: "عنوان IP",
    changes: "التغييرات",
    noChanges: "لم تُسجَّل تغييرات في الحقول لهذا الإجراء.",
    field: "الحقل",
    before: "قبل",
    after: "بعد",
    added: "أُضيف",
    removed: "أُزيل",
    changed: "تغيّر",
    empty_value: "فارغ",
    fieldCount: (n: string) => (n === "1" ? "حقل واحد" : `${n} حقول`),
    retention: "مدة الاحتفاظ",
    retentionHint: "المدة التي تُحفظ فيها السجلات قبل حذفها نهائيًا.",
    retentionAria: "مدة الاحتفاظ",
    forever: "الاحتفاظ دائمًا",
    days: (n: string) => `${n} يومًا`,
    year: "سنة واحدة",
    years: (n: string) => `${n} سنوات`,
    retentionExpiring: (n: string) => (n === "1" ? "سجل واحد أقدم من ذلك وسيُحذف." : `${n} سجلات أقدم من ذلك وستُحذف.`),
    retentionSaved: "تم تحديث مدة الاحتفاظ.",
    retentionFailed: "تعذّر تغيير مدة الاحتفاظ. حاول مرة أخرى.",
  },
};
export const auditLogStrings = (locale: string) => AUDIT_LOG_STRINGS[locale.startsWith("ar") ? "ar" : "en"];

export type AuditLogLabels = Partial<typeof AUDIT_LOG_STRINGS.en>;
export type AuditLogStrings = typeof AUDIT_LOG_STRINGS.en;
