// The summary's own words, en and ar, copied from the React DailySummary.
export const STRINGS = {
  en: {
    previous: "Previous day",
    next: "Next day",
    today: "Today",
    protocol: "Protocol",
    body: "Body and activity",
    water: "Water",
    waterOfGoal: "of your goal",
    meals: "Meals",
    caffeine: "Caffeine",
    shutdown: "Shutdown violations",
    pomodoros: "Focus sessions",
    steps: "Steps",
    sleep: "Sleep",
    activeEnergy: "Active energy",
    restingHeartRate: "Resting heart rate",
    weight: "Weight",
    safe: "Safe",
    unsafe: "Unsafe",
    unclassified: "Not classified",
    clean: "Clean",
    sugar: "With sugar",
    none: "None",
    violationsN: (n: number) => (n === 1 ? "1 violation" : `${n} violations`),
    mealsN: (n: number) => (n === 1 ? "1 meal" : `${n} meals`),
    drinksN: (n: number) => (n === 1 ? "1 drink" : `${n} drinks`),
    sessionsN: (n: number) => (n === 1 ? "1 session" : `${n} sessions`),
    notSynced: "Not synced",
    source: "Source",
    sources: { ios: "iPhone", android: "Android", watch: "Apple Watch", wearos: "Wear OS", web: "Web" } as Record<string, string>,
    empty: "Nothing recorded for this day",
    emptyHint: "Log something, or sync a device, and it appears here.",
    loadError: "This day could not be loaded.",
    retry: "Try again",
    goalLabel: "Water against your goal",
  },
  ar: {
    previous: "اليوم السابق",
    next: "اليوم التالي",
    today: "اليوم",
    protocol: "البروتوكول",
    body: "الجسم والنشاط",
    water: "الماء",
    waterOfGoal: "من هدفك",
    meals: "الوجبات",
    caffeine: "الكافيين",
    shutdown: "مخالفات الإغلاق",
    pomodoros: "جلسات التركيز",
    steps: "الخطوات",
    sleep: "النوم",
    activeEnergy: "الطاقة النشطة",
    restingHeartRate: "نبض الراحة",
    weight: "الوزن",
    safe: "آمنة",
    unsafe: "غير آمنة",
    unclassified: "غير مصنّفة",
    clean: "بدون سكر",
    sugar: "مع سكر",
    none: "لا شيء",
    violationsN: (n: number) => (n === 0 ? "لا مخالفات" : n === 1 ? "مخالفة واحدة" : n === 2 ? "مخالفتان" : n <= 10 ? `${n} مخالفات` : `${n} مخالفة`),
    mealsN: (n: number) => (n === 0 ? "لا وجبات" : n === 1 ? "وجبة واحدة" : n === 2 ? "وجبتان" : n <= 10 ? `${n} وجبات` : `${n} وجبة`),
    drinksN: (n: number) => (n === 0 ? "لا مشروبات" : n === 1 ? "مشروب واحد" : n === 2 ? "مشروبان" : n <= 10 ? `${n} مشروبات` : `${n} مشروبًا`),
    sessionsN: (n: number) => (n === 0 ? "لا جلسات" : n === 1 ? "جلسة واحدة" : n === 2 ? "جلستان" : n <= 10 ? `${n} جلسات` : `${n} جلسة`),
    notSynced: "لم تتم المزامنة",
    source: "المصدر",
    sources: { ios: "آيفون", android: "أندرويد", watch: "ساعة آبل", wearos: "Wear OS", web: "الويب" } as Record<string, string>,
    empty: "لا شيء مسجّل لهذا اليوم",
    emptyHint: "سجّل شيئًا أو زامن جهازًا فيظهر هنا.",
    loadError: "تعذّر تحميل هذا اليوم.",
    retry: "حاول مرة أخرى",
    goalLabel: "الماء مقابل هدفك",
  },
};

export type DailySummaryLabels = typeof STRINGS.en;
