import type { StoreOrderStatus } from "./store-commerce";

const ORDER_STATUS_EN: Record<StoreOrderStatus, string> = {
  pending: "Pending",
  paid: "Paid",
  processing: "Processing",
  "partially-fulfilled": "Partly fulfilled",
  fulfilled: "Fulfilled",
  shipped: "Shipped",
  "out-for-delivery": "Out for delivery",
  delivered: "Delivered",
  cancelled: "Cancelled",
  refunded: "Refunded",
  "partially-refunded": "Partly refunded",
  returned: "Returned",
};

const ORDER_STATUS_AR: Record<StoreOrderStatus, string> = {
  pending: "قيد الانتظار",
  paid: "مدفوع",
  processing: "قيد التجهيز",
  "partially-fulfilled": "منفّذ جزئيًا",
  fulfilled: "تم التجهيز",
  shipped: "تم الشحن",
  "out-for-delivery": "خرج للتوصيل",
  delivered: "تم التسليم",
  cancelled: "ملغي",
  refunded: "مُسترد",
  "partially-refunded": "مُسترد جزئيًا",
  returned: "مُرتجع",
};

export const ORDER_STATUS_VARIANT: Record<StoreOrderStatus, "neutral" | "success" | "warning" | "danger" | "info"> = {
  pending: "warning",
  paid: "info",
  processing: "info",
  "partially-fulfilled": "info",
  fulfilled: "success",
  shipped: "info",
  "out-for-delivery": "info",
  delivered: "success",
  cancelled: "danger",
  refunded: "neutral",
  "partially-refunded": "neutral",
  returned: "neutral",
};

export const STRINGS = {
  en: {
    region: "Store dashboard",
    kpis: "Key figures",
    sales: "Sales",
    orders: "Orders",
    aov: "Average order value",
    conversion: "Conversion rate",
    returning: "Returning customers",
    live: "Live visitors",
    liveHint: "on the site right now",
    liveBadge: "Live",
    vsPrevious: "vs previous period",
    salesSpark: (label: string) => `${label}, trend over the period`,
    widgets: {
      sales: "Sales over time",
      funnel: "Conversion funnel",
      topProducts: "Top products",
      categories: "Top categories",
      channels: "Sales by channel",
      cities: "Sales by city",
      lowStock: "Low stock",
      recentOrders: "Recent orders",
    },
    widgetHints: {
      sales: "Sales, orders and sessions with the previous period behind them",
      funnel: "Sessions to purchase, and where shoppers leave",
      topProducts: "Best sellers by revenue",
      categories: "Revenue by product category",
      channels: "Where the sales came from",
      cities: "Where the orders were delivered",
      lowStock: "Variants at or under the stock threshold",
      recentOrders: "The latest orders placed",
    },
    metrics: { sales: "Sales", orders: "Orders", sessions: "Sessions" },
    funnelSteps: { sessions: "Sessions", addToCart: "Added to cart", checkout: "Started checkout", purchase: "Purchased" },
    dimension: { category: "Category", channel: "Channel", city: "City" },
    revenue: "Revenue",
    units: (n: number) => (n === 1 ? "1 sold" : `${n} sold`),
    outOfStock: "Out of stock",
    left: (n: number) => `${n} left`,
    restock: "Restock",
    restockItem: (name: string) => `Restock ${name}`,
    openProduct: "Open product",
    openOrder: "Open order",
    noLowStock: "Every variant is well stocked",
    noLowStockHint: (n: number) => `Nothing at ${n} or fewer.`,
    noOrders: "No orders yet",
    noRows: "No data for this period",
    order: "Order",
    customer: "Customer",
    status: "Status",
    total: "Total",
    placed: "Placed",
    ordersTable: "Recent orders",
    orderStatus: ORDER_STATUS_EN,
    emptyTitle: "No sales in this period",
    emptyBody: "When customers start ordering, your figures, top sellers and funnel show up here.",
    errorTitle: "The dashboard could not be loaded.",
    retry: "Try again",
    productImage: "No image",
  },
  ar: {
    region: "لوحة المتجر",
    kpis: "الأرقام الرئيسية",
    sales: "المبيعات",
    orders: "الطلبات",
    aov: "متوسط قيمة الطلب",
    conversion: "معدل التحويل",
    returning: "العملاء العائدون",
    live: "الزوار الآن",
    liveHint: "على المتجر في هذه اللحظة",
    liveBadge: "مباشر",
    vsPrevious: "مقارنة بالفترة السابقة",
    salesSpark: (label: string) => `${label}، الاتجاه خلال الفترة`,
    widgets: {
      sales: "المبيعات عبر الزمن",
      funnel: "قمع التحويل",
      topProducts: "أفضل المنتجات",
      categories: "أفضل الأقسام",
      channels: "المبيعات حسب القناة",
      cities: "المبيعات حسب المدينة",
      lowStock: "مخزون منخفض",
      recentOrders: "أحدث الطلبات",
    },
    widgetHints: {
      sales: "المبيعات والطلبات والجلسات مع الفترة السابقة خلفها",
      funnel: "من الزيارة إلى الشراء، وأين يغادر المتسوقون",
      topProducts: "الأكثر مبيعًا حسب الإيراد",
      categories: "الإيراد حسب قسم المنتج",
      channels: "من أين جاءت المبيعات",
      cities: "إلى أين وصلت الطلبات",
      lowStock: "الأصناف التي وصلت إلى حد المخزون أو أقل",
      recentOrders: "آخر الطلبات الواردة",
    },
    metrics: { sales: "المبيعات", orders: "الطلبات", sessions: "الجلسات" },
    funnelSteps: { sessions: "الجلسات", addToCart: "أضافوا إلى السلة", checkout: "بدأوا الدفع", purchase: "أتمّوا الشراء" },
    dimension: { category: "القسم", channel: "القناة", city: "المدينة" },
    revenue: "الإيراد",
    units: (n: number) => (n === 1 ? "بيعت قطعة" : n === 2 ? "بيعت قطعتان" : n <= 10 ? `بيعت ${n} قطع` : `بيعت ${n} قطعة`),
    outOfStock: "نفد المخزون",
    left: (n: number) => (n === 1 ? "بقيت قطعة" : n === 2 ? "بقيت قطعتان" : `بقيت ${n} قطع`),
    restock: "إعادة التوريد",
    restockItem: (name: string) => `إعادة توريد ${name}`,
    openProduct: "فتح المنتج",
    openOrder: "فتح الطلب",
    noLowStock: "كل الأصناف بمخزون جيد",
    noLowStockHint: (n: number) => `لا شيء عند ${n} أو أقل.`,
    noOrders: "لا توجد طلبات بعد",
    noRows: "لا بيانات لهذه الفترة",
    order: "الطلب",
    customer: "العميل",
    status: "الحالة",
    total: "الإجمالي",
    placed: "وقت الطلب",
    ordersTable: "أحدث الطلبات",
    orderStatus: ORDER_STATUS_AR,
    emptyTitle: "لا مبيعات في هذه الفترة",
    emptyBody: "عندما يبدأ العملاء بالطلب ستظهر هنا أرقامك وأكثر المنتجات مبيعًا وقمع التحويل.",
    errorTitle: "تعذّر تحميل اللوحة.",
    retry: "حاول مرة أخرى",
    productImage: "بلا صورة",
  },
};

export type StoreDashboardLabels = typeof STRINGS.en;

