// Built-in English and Arabic strings of loyalty and promo.
export const LOYALTY_STRINGS = {
  en: {
    points: "points",
    pointsBalance: "Points balance",
    member: "Member",
    memberSince: (d: string) => `Member since ${d}`,
    tier: "Tier",
    toNext: (n: string, tier: string) => `${n} points to ${tier}`,
    topTier: "You are at the top tier",
    expiring: (n: string, d: string) => `${n} points expire on ${d}`,
    memberCode: "Member code",
    rewards: "Rewards",
    claim: "Redeem",
    noRewards: "No rewards yet",
    history: "Points activity",
    kinds: { earn: "Earned", redeem: "Redeemed", expire: "Expired", adjust: "Adjusted" },
    balanceAfter: (n: string) => `Balance ${n}`,
    noHistory: "No points activity",
    noHistoryHint: "Points show here after the first visit.",
    all: "All",
    promoCode: "Promo code",
    promoPlaceholder: "Enter a code",
    apply: "Apply",
    remove: "Remove code",
    applied: (code: string) => `${code} applied`,
    saves: (amount: string) => `You save ${amount}`,
    failed: "That did not go through. Try again.",
    problems: {
      format: "A code is 3 to 24 letters or digits.",
      empty: "Enter a code.",
      unknown: "We do not know that code.",
      inactive: "This code is switched off.",
      "not-started": "This code is not active yet.",
      expired: "This code has expired.",
      "min-subtotal": "Your order is below the minimum for this code.",
      exhausted: "This code has been used up.",
      "per-customer": "You have already used this code.",
      "first-order": "This code is for a first order only.",
    },
    promos: "Promo codes",
    newPromo: "New promo code",
    editPromo: "Edit promo code",
    code: "Code",
    codeHint: "Letters, digits, dashes. Shown to customers exactly as typed, in capitals.",
    type: "Type",
    percent: "Percent off",
    fixed: "Amount off",
    value: "Value",
    percentValue: "Percent",
    maxDiscount: "Largest discount",
    minSubtotal: "Smallest order",
    startsOn: "Starts",
    endsOn: "Ends",
    maxRedemptions: "Total uses",
    perCustomer: "Uses per customer",
    unlimited: "Unlimited",
    firstOrderOnly: "First order only",
    active: "Active",
    save: "Save code",
    cancel: "Cancel",
    discountCol: "Discount",
    validity: "Valid",
    usesCol: "Used",
    statusCol: "Status",
    search: "Search codes",
    statuses: { live: "Live", scheduled: "Scheduled", ended: "Ended", off: "Off", full: "Used up" },
    copyCode: "Copy code",
    edit: "Edit",
    deactivate: "Turn off",
    activate: "Turn on",
    delete: "Delete",
    deleteTitle: "Delete this code?",
    deleteDescription: (code: string) => `${code} stops working. Past orders keep their discount.`,
    noPromos: "No promo codes",
    noPromosHint: "Create a code to run an offer.",
    promoLabel: "Promo codes",
    visits: "Visits",
    date: "Date",
    place: "Place",
    spend: "Spend",
    earned: "Points",
    visitStatus: { completed: "Completed", "no-show": "No show", cancelled: "Cancelled" },
    visitCount: "Visits",
    totalSpend: "Total spend",
    average: "Average visit",
    lastVisit: "Last visit",
    noVisits: "No visits yet",
    noVisitsHint: "Visits show here after the first booking.",
    visitLabel: "Visit history",
    close: "Close",
    actions: "Actions",
  },
  ar: {
    points: "نقطة",
    pointsBalance: "رصيد النقاط",
    member: "العضو",
    memberSince: (d: string) => `عضو منذ ${d}`,
    tier: "المستوى",
    toNext: (n: string, tier: string) => `${n} نقطة للوصول إلى ${tier}`,
    topTier: "أنت في أعلى مستوى",
    expiring: (n: string, d: string) => `${n} نقطة تنتهي في ${d}`,
    memberCode: "رمز العضوية",
    rewards: "المكافآت",
    claim: "استبدال",
    noRewards: "لا توجد مكافآت بعد",
    history: "نشاط النقاط",
    kinds: { earn: "مكتسبة", redeem: "مستبدلة", expire: "منتهية", adjust: "تعديل" },
    balanceAfter: (n: string) => `الرصيد ${n}`,
    noHistory: "لا يوجد نشاط للنقاط",
    noHistoryHint: "تظهر النقاط هنا بعد أول زيارة.",
    all: "الكل",
    promoCode: "كود الخصم",
    promoPlaceholder: "أدخل الكود",
    apply: "تطبيق",
    remove: "إزالة الكود",
    applied: (code: string) => `تم تطبيق ${code}`,
    saves: (amount: string) => `توفّر ${amount}`,
    failed: "لم تتم العملية. حاول مرة أخرى.",
    problems: {
      format: "الكود من 3 إلى 24 حرفًا أو رقمًا.",
      empty: "أدخل الكود.",
      unknown: "لا نعرف هذا الكود.",
      inactive: "هذا الكود متوقف.",
      "not-started": "هذا الكود لم يبدأ بعد.",
      expired: "انتهت صلاحية هذا الكود.",
      "min-subtotal": "طلبك أقل من الحد الأدنى لهذا الكود.",
      exhausted: "استُهلك هذا الكود بالكامل.",
      "per-customer": "لقد استخدمت هذا الكود من قبل.",
      "first-order": "هذا الكود للطلب الأول فقط.",
    },
    promos: "أكواد الخصم",
    newPromo: "كود خصم جديد",
    editPromo: "تعديل كود الخصم",
    code: "الكود",
    codeHint: "حروف وأرقام وشرطات. يظهر للعملاء كما كُتب، بأحرف كبيرة.",
    type: "النوع",
    percent: "نسبة خصم",
    fixed: "مبلغ خصم",
    value: "القيمة",
    percentValue: "النسبة",
    maxDiscount: "أقصى خصم",
    minSubtotal: "أقل طلب",
    startsOn: "يبدأ",
    endsOn: "ينتهي",
    maxRedemptions: "إجمالي الاستخدامات",
    perCustomer: "الاستخدامات لكل عميل",
    unlimited: "غير محدود",
    firstOrderOnly: "الطلب الأول فقط",
    active: "مفعّل",
    save: "حفظ الكود",
    cancel: "إلغاء",
    discountCol: "الخصم",
    validity: "الصلاحية",
    usesCol: "الاستخدام",
    statusCol: "الحالة",
    search: "ابحث في الأكواد",
    statuses: { live: "ساري", scheduled: "مجدول", ended: "منتهٍ", off: "متوقف", full: "مستهلك" },
    copyCode: "نسخ الكود",
    edit: "تعديل",
    deactivate: "إيقاف",
    activate: "تشغيل",
    delete: "حذف",
    deleteTitle: "حذف هذا الكود؟",
    deleteDescription: (code: string) => `سيتوقف ${code} عن العمل. الطلبات السابقة تحتفظ بخصمها.`,
    noPromos: "لا توجد أكواد خصم",
    noPromosHint: "أنشئ كودًا لإطلاق عرض.",
    promoLabel: "أكواد الخصم",
    visits: "الزيارات",
    date: "التاريخ",
    place: "المكان",
    spend: "الإنفاق",
    earned: "النقاط",
    visitStatus: { completed: "مكتملة", "no-show": "لم يحضر", cancelled: "ملغاة" },
    visitCount: "الزيارات",
    totalSpend: "إجمالي الإنفاق",
    average: "متوسط الزيارة",
    lastVisit: "آخر زيارة",
    noVisits: "لا توجد زيارات بعد",
    noVisitsHint: "تظهر الزيارات هنا بعد أول حجز.",
    visitLabel: "سجل الزيارات",
    close: "إغلاق",
    actions: "الإجراءات",
  },
};
export type LoyaltyStrings = (typeof LOYALTY_STRINGS)["en"];
export type LoyaltyPromoLabels = Partial<Omit<LoyaltyStrings, "kinds" | "problems" | "statuses" | "visitStatus">> & {
  kinds?: Partial<LoyaltyStrings["kinds"]>;
  problems?: Partial<LoyaltyStrings["problems"]>;
  statuses?: Partial<LoyaltyStrings["statuses"]>;
  visitStatus?: Partial<LoyaltyStrings["visitStatus"]>;
};

import { computed, type ComputedRef } from "vue";
import { useNasaq } from "../../provider";
import { formatNumber } from "../numeric";

/** Merged strings for the active locale plus `labels`, the locale and a number formatter. */
export function useLoyaltyStrings(labels?: () => LoyaltyPromoLabels | undefined): { t: ComputedRef<LoyaltyStrings>; locale: ComputedRef<string>; n: (v: number) => string } {
  const nq = useNasaq();
  return {
    t: computed(() => {
      const base = LOYALTY_STRINGS[nq.locale.value.startsWith("ar") ? "ar" : "en"];
      const l = labels?.();
      return {
        ...base,
        ...l,
        kinds: { ...base.kinds, ...l?.kinds },
        problems: { ...base.problems, ...l?.problems },
        statuses: { ...base.statuses, ...l?.statuses },
        visitStatus: { ...base.visitStatus, ...l?.visitStatus },
      } as LoyaltyStrings;
    }),
    locale: computed(() => nq.locale.value),
    n: (v: number) => formatNumber(v, nq.locale.value),
  };
}

export type LoyaltyResult = void | { error?: string };
export const failMessage = (e: unknown, fallback: string): string => (e instanceof Error && e.message ? e.message : fallback);
/** Day-key helpers: noon local time so a time zone never moves the day. */
export const dayOf = (key: string): Date => new Date(`${key}T12:00:00`);
export const keyOf = (d: Date): string => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
export const todayKey = (): string => keyOf(new Date());
