// Strings of the data privacy screens, English and Arabic. Pass `labels` to override any of them.
import type { ExportStatus } from "./privacy-rules";

export const DATA_PRIVACY_STRINGS = {
  en: {
    exportTitle: "Export your data",
    exportBody: "Get a copy of everything we hold about you, as a file you can keep or move elsewhere.",
    includes: "The file includes",
    request: "Request export",
    requesting: "Requesting",
    status: { queued: "Waiting in line", processing: "Preparing your file", ready: "Ready to download", failed: "Failed", expired: "Expired" } as Record<ExportStatus, string>,
    requestedAt: "Requested",
    readyAt: "Ready",
    size: "Size",
    expiresAt: "Download available until",
    download: "Download",
    downloading: "Downloading",
    requestAgain: "Request a new export",
    retryCheck: "Check again",
    emailNote: "We also email you when it is ready. This can take a few minutes.",
    failedBody: "The export could not be prepared. Try again.",
    expiredBody: "This export is no longer available. Request a new one.",
    checkFailed: "We could not check the status. It may still be running.",
    requestFailed: "The export could not be requested. Try again.",
    downloadFailed: "The download did not start. Try again.",
    progressLabel: "Export progress",
    // deletion
    deleteTitle: "Delete account",
    deleteHeading: "Delete your account",
    deleteBody: (days: string) => `Your account and its data are permanently deleted after ${days} days. Until then you can sign in and cancel.`,
    deleteButton: "Delete my account",
    deleteConfirmTitle: "Delete your account?",
    deleteConfirmBody: (days: string) => `You are signed out everywhere. After ${days} days everything is removed for good. You can cancel any time before then.`,
    deletePrompt: (text: string) => `Type ${text} to confirm`,
    deleteAction: "Schedule deletion",
    cancel: "Cancel",
    deleteFailed: "The deletion could not be scheduled. Try again.",
    scheduledTitle: "Your account is scheduled for deletion",
    scheduledOn: "It will be deleted on",
    daysLeft: (n: string) => (n === "1" ? "1 day left" : `${n} days left`),
    lessThanDay: "Less than a day left",
    scheduledBody: "Everything is removed for good on that date. Cancel now to keep your account exactly as it is.",
    cancelDeletion: "Cancel deletion",
    cancelling: "Cancelling",
    cancelFailed: "Deletion could not be cancelled. Try again.",
    cancelledOk: "Deletion cancelled. Your account stays as it was.",
    dueTitle: "Your account is being deleted",
    dueBody: "The grace period has ended. It can no longer be cancelled here. Contact support if this is a mistake.",
    graceProgress: "Grace period used",
    // cancel page
    pageReadyTitle: "Keep your account?",
    pageReadyBody: (date: string) => `Your account is scheduled for deletion on ${date}. Cancel it and nothing is lost.`,
    keep: "Keep my account",
    pageDoneTitle: "Your account is safe",
    pageDoneBody: "The deletion was cancelled. You can sign in as usual.",
    pageExpiredTitle: "This account has been deleted",
    pageExpiredBody: "The grace period ended and the data was removed. It cannot be recovered. You can create a new account any time.",
    pageInvalidTitle: "This link does not work",
    pageInvalidBody: "It may be wrong, already used, or from an older request. Sign in to check your account.",
    signIn: "Sign in",
    signUp: "Create a new account",
    goHome: "Go to the home page",
  },
  ar: {
    exportTitle: "صدّر بياناتك",
    exportBody: "احصل على نسخة من كل ما نحتفظ به عنك، في ملف تحتفظ به أو تنقله إلى مكان آخر.",
    includes: "يتضمن الملف",
    request: "طلب التصدير",
    requesting: "جارٍ الطلب",
    status: { queued: "في الانتظار", processing: "جارٍ تجهيز ملفك", ready: "جاهز للتنزيل", failed: "فشل", expired: "منتهي" } as Record<ExportStatus, string>,
    requestedAt: "تاريخ الطلب",
    readyAt: "تاريخ الجاهزية",
    size: "الحجم",
    expiresAt: "التنزيل متاح حتى",
    download: "تنزيل",
    downloading: "جارٍ التنزيل",
    requestAgain: "طلب تصدير جديد",
    retryCheck: "تحقق مرة أخرى",
    emailNote: "سنراسلك أيضًا عندما يجهز. قد يستغرق ذلك بضع دقائق.",
    failedBody: "تعذّر تجهيز التصدير. حاول مرة أخرى.",
    expiredBody: "لم يعد هذا التصدير متاحًا. اطلب تصديرًا جديدًا.",
    checkFailed: "تعذّر التحقق من الحالة. قد يكون ما زال قيد التنفيذ.",
    requestFailed: "تعذّر طلب التصدير. حاول مرة أخرى.",
    downloadFailed: "لم يبدأ التنزيل. حاول مرة أخرى.",
    progressLabel: "تقدّم التصدير",
    deleteTitle: "حذف الحساب",
    deleteHeading: "احذف حسابك",
    deleteBody: (days: string) => `يُحذف حسابك وبياناته نهائيًا بعد ${days} يومًا. حتى ذلك الحين يمكنك تسجيل الدخول والإلغاء.`,
    deleteButton: "احذف حسابي",
    deleteConfirmTitle: "حذف حسابك؟",
    deleteConfirmBody: (days: string) => `يتم تسجيل خروجك من كل مكان. بعد ${days} يومًا يُزال كل شيء نهائيًا. يمكنك الإلغاء في أي وقت قبل ذلك.`,
    deletePrompt: (text: string) => `اكتب ${text} للتأكيد`,
    deleteAction: "جدولة الحذف",
    cancel: "إلغاء",
    deleteFailed: "تعذّرت جدولة الحذف. حاول مرة أخرى.",
    scheduledTitle: "حسابك مجدول للحذف",
    scheduledOn: "سيُحذف في",
    daysLeft: (n: string) => (n === "1" ? "بقي يوم واحد" : `بقي ${n} أيام`),
    lessThanDay: "بقي أقل من يوم",
    scheduledBody: "يُزال كل شيء نهائيًا في ذلك التاريخ. ألغِ الآن لتبقى حسابك كما هو تمامًا.",
    cancelDeletion: "إلغاء الحذف",
    cancelling: "جارٍ الإلغاء",
    cancelFailed: "تعذّر إلغاء الحذف. حاول مرة أخرى.",
    cancelledOk: "أُلغي الحذف. يبقى حسابك كما كان.",
    dueTitle: "جارٍ حذف حسابك",
    dueBody: "انتهت فترة السماح ولم يعد ممكنًا الإلغاء من هنا. تواصل مع الدعم إن كان ذلك خطأ.",
    graceProgress: "المستهلك من فترة السماح",
    pageReadyTitle: "هل تريد الإبقاء على حسابك؟",
    pageReadyBody: (date: string) => `حسابك مجدول للحذف في ${date}. ألغِ الحذف ولن يضيع شيء.`,
    keep: "أبقِ على حسابي",
    pageDoneTitle: "حسابك في أمان",
    pageDoneBody: "أُلغي الحذف. يمكنك تسجيل الدخول كالمعتاد.",
    pageExpiredTitle: "تم حذف هذا الحساب",
    pageExpiredBody: "انتهت فترة السماح وأُزيلت البيانات. لا يمكن استعادتها. يمكنك إنشاء حساب جديد في أي وقت.",
    pageInvalidTitle: "هذا الرابط لا يعمل",
    pageInvalidBody: "قد يكون خاطئًا أو مستخدمًا من قبل أو من طلب أقدم. سجّل الدخول لتتحقق من حسابك.",
    signIn: "تسجيل الدخول",
    signUp: "إنشاء حساب جديد",
    goHome: "الذهاب إلى الصفحة الرئيسية",
  },
};
export const dataPrivacyStrings = (locale: string) => DATA_PRIVACY_STRINGS[locale.startsWith("ar") ? "ar" : "en"];

export type DataPrivacyLabels = Partial<typeof DATA_PRIVACY_STRINGS.en>;
