// Built-in English and Arabic strings, copied from the React AgentSteps.
export const STRINGS = {
  en: {
    steps: "Agent steps",
    running: "Working",
    stepOf: (n: number, total: number) => `Step ${n} of ${total}`,
    awaiting: "Waiting for your approval",
    failed: "A step failed",
    done: "All steps done",
    idle: "No steps yet",
    pending: "Queued",
    stepRunning: "Running",
    stepAwaiting: "Needs approval",
    stepDone: "Done",
    stepError: "Failed",
    stepSkipped: "Skipped",
    arguments: "Arguments",
    result: "Result",
    error: "Error",
    noDetails: "No details for this step",
    retry: "Retry",
    showDetails: "Show details",
    hideDetails: "Hide details",
    // confirm
    confirmTitle: "Review before applying",
    confirmBody: "The agent wants to make these changes. Nothing changes until you apply them.",
    apply: (n: number) => `Apply ${n}`,
    applyAll: "Apply all",
    reject: "Reject",
    rejectTitle: "Reject these changes",
    rejectBody: "Tell the agent why, so it can try again. The reason is optional.",
    reasonLabel: "Reason",
    reasonPlaceholder: "For example, keep the old retry limit",
    reasonRequired: "Give a reason so the agent can adjust",
    cancel: "Cancel",
    confirmReject: "Reject changes",
    selectChange: (title: string) => `Apply ${title}`,
    selected: (n: number, total: number) => `${n} of ${total} selected`,
    nothingSelected: "Select at least one change to apply",
    viewDiff: "Show changes",
    hideDiff: "Hide changes",
    created: "New",
    edited: "Edit",
    deleted: "Delete",
    added: (n: number) => `${n} added`,
    removed: (n: number) => `${n} removed`,
    lineAdded: "Added line",
    lineRemoved: "Removed line",
    unchanged: (n: number) => `${n} unchanged lines`,
    diffLabel: "Changes",
    noChange: "No differences.",
    riskLow: "Low risk",
    riskMedium: "Medium risk",
    riskHigh: "High risk",
    reviewedRisk: "I reviewed these changes and understand they are hard to undo",
    riskRequired: "Confirm you reviewed the high risk changes",
    applying: "Applying",
    applied: "Changes applied",
    appliedBody: (n: number) => (n === 1 ? "1 change was applied." : `${n} changes were applied.`),
    rejected: "Changes rejected",
    rejectedBody: "The agent was told and nothing changed.",
    failedApply: "Could not apply the changes. Nothing was changed.",
    undo: "Review again",
  },
  ar: {
    steps: "خطوات الوكيل",
    running: "جارٍ العمل",
    stepOf: (n: number, total: number) => `الخطوة ${n} من ${total}`,
    awaiting: "بانتظار موافقتك",
    failed: "فشلت إحدى الخطوات",
    done: "اكتملت كل الخطوات",
    idle: "لا توجد خطوات بعد",
    pending: "في الانتظار",
    stepRunning: "قيد التنفيذ",
    stepAwaiting: "تحتاج موافقة",
    stepDone: "تمّت",
    stepError: "فشلت",
    stepSkipped: "تم التخطي",
    arguments: "المعاملات",
    result: "النتيجة",
    error: "الخطأ",
    noDetails: "لا توجد تفاصيل لهذه الخطوة",
    retry: "إعادة المحاولة",
    showDetails: "عرض التفاصيل",
    hideDetails: "إخفاء التفاصيل",
    confirmTitle: "راجع قبل التطبيق",
    confirmBody: "يريد الوكيل إجراء هذه التغييرات. لن يتغير شيء حتى تطبّقها.",
    apply: (n: number) => `تطبيق ${n}`,
    applyAll: "تطبيق الكل",
    reject: "رفض",
    rejectTitle: "رفض هذه التغييرات",
    rejectBody: "أخبر الوكيل بالسبب ليحاول من جديد. السبب اختياري.",
    reasonLabel: "السبب",
    reasonPlaceholder: "مثلًا، أبقِ حد إعادة المحاولة القديم",
    reasonRequired: "اذكر سببًا ليتمكن الوكيل من التعديل",
    cancel: "إلغاء",
    confirmReject: "رفض التغييرات",
    selectChange: (title: string) => `تطبيق ${title}`,
    selected: (n: number, total: number) => `تم تحديد ${n} من ${total}`,
    nothingSelected: "حدّد تغييرًا واحدًا على الأقل للتطبيق",
    viewDiff: "عرض التغييرات",
    hideDiff: "إخفاء التغييرات",
    created: "جديد",
    edited: "تعديل",
    deleted: "حذف",
    added: (n: number) => `${n} مضاف`,
    removed: (n: number) => `${n} محذوف`,
    lineAdded: "سطر مضاف",
    lineRemoved: "سطر محذوف",
    unchanged: (n: number) => `${n} أسطر دون تغيير`,
    diffLabel: "التغييرات",
    noChange: "لا اختلافات.",
    riskLow: "خطورة منخفضة",
    riskMedium: "خطورة متوسطة",
    riskHigh: "خطورة عالية",
    reviewedRisk: "راجعت هذه التغييرات وأدرك أن التراجع عنها صعب",
    riskRequired: "أكّد أنك راجعت التغييرات عالية الخطورة",
    applying: "جارٍ التطبيق",
    applied: "تم تطبيق التغييرات",
    appliedBody: (n: number) => (n === 1 ? "تم تطبيق تغيير واحد." : n === 2 ? "تم تطبيق تغييرين." : `تم تطبيق ${n} تغييرات.`),
    rejected: "تم رفض التغييرات",
    rejectedBody: "أُبلغ الوكيل ولم يتغير شيء.",
    failedApply: "تعذّر تطبيق التغييرات. لم يتغير شيء.",
    undo: "مراجعة مرة أخرى",
  },
};

export type AgentStepsLabels = (typeof STRINGS)["en"];

export function agentStepsStrings(locale: string, labels?: Partial<AgentStepsLabels>): AgentStepsLabels {
  return { ...STRINGS[locale.startsWith("ar") ? "ar" : "en"], ...labels };
}
