import type { ToolAccess } from "./format";

export const STRINGS = {
  en: {
    tools: "Tools",
    search: "Search tools",
    all: "All",
    catalog: "Catalog",
    reference: "Reference",
    view: "View",
    access: "Access",
    accessLevels: { read: "Read only", write: "Changes data", destructive: "Destructive" } satisfies Record<ToolAccess, string>,
    accessAll: "Any access",
    scope: "Scope",
    minRole: "Minimum role",
    arguments: "Arguments",
    noArguments: "This tool takes no arguments.",
    name: "Name",
    type: "Type",
    required: "Required",
    optional: "Optional",
    defaultValue: "Default",
    description: "Description",
    returns: "Returns",
    examples: "Example",
    call: "Call",
    result: "Result",
    deprecated: "Deprecated",
    since: (v: string) => `Since ${v}`,
    copyName: "Copy tool name",
    back: "All tools",
    emptyTitle: "No tools match",
    emptyBody: "Try another word or clear the filters.",
    clear: "Clear filters",
    results: (n: string) => `${n} tools`,
    permissions: "Permissions",
    values: "One of",
  },
  ar: {
    tools: "الأدوات",
    search: "ابحث في الأدوات",
    all: "الكل",
    catalog: "الفهرس",
    reference: "المرجع",
    view: "العرض",
    access: "الوصول",
    accessLevels: { read: "قراءة فقط", write: "يغيّر البيانات", destructive: "مدمّر" } satisfies Record<ToolAccess, string>,
    accessAll: "أي وصول",
    scope: "النطاق",
    minRole: "أدنى دور",
    arguments: "المعاملات",
    noArguments: "هذه الأداة لا تأخذ معاملات.",
    name: "الاسم",
    type: "النوع",
    required: "مطلوب",
    optional: "اختياري",
    defaultValue: "الافتراضي",
    description: "الوصف",
    returns: "ما تُرجعه",
    examples: "مثال",
    call: "الاستدعاء",
    result: "النتيجة",
    deprecated: "متقادمة",
    since: (v: string) => `منذ ${v}`,
    copyName: "نسخ اسم الأداة",
    back: "كل الأدوات",
    emptyTitle: "لا أدوات مطابقة",
    emptyBody: "جرّب كلمة أخرى أو امسح التصفية.",
    clear: "مسح التصفية",
    results: (n: string) => `${n} أداة`,
    permissions: "الصلاحيات",
    values: "إحدى القيم",
  },
};
export type ApiReferenceLabels = typeof STRINGS.en;
