// Strings of the notification preferences, English and Arabic. Pass `labels` to override any of them.
import type { Batching, NotificationChannel } from "./notification-rules";

export const NOTIFICATION_STRINGS = {
  en: {
    matrixTitle: "What to notify me about",
    matrixBody: "Choose where each kind of notification reaches you.",
    matrixLabel: "Notifications by kind and channel",
    kind: "Notification",
    channels: { email: "Email", push: "Push", whatsapp: "WhatsApp", desktop: "Desktop" } as Record<NotificationChannel, string>,
    cell: (kind: string, channel: string) => `${kind}: ${channel}`,
    all: (channel: string) => `Turn ${channel} on or off for every kind`,
    locked: "Always on, it cannot be turned off",
    unavailable: "Not available",
    // push
    pushAsking: "Waiting for your browser to answer",
    pushBlocked: "Browser notifications are blocked. Allow them in your browser's site settings, then try again.",
    pushDenied: "Push was not turned on because the browser permission was not granted.",
    pushUnsupported: "This browser does not support push notifications.",
    pushNeeded: "The browser will ask for permission the first time you turn push on.",
    // saving
    saving: "Saving",
    saved: "Saved",
    failed: "That did not save, so it was put back. Try again.",
    dismiss: "Dismiss",
    // quiet hours
    quietTitle: "Quiet hours",
    quietBody: "Hold notifications while you are away. They arrive when the quiet hours end.",
    quietSwitch: "Turn on quiet hours",
    from: "From",
    to: "Until",
    quietLength: (h: string) => `${h} quiet each day`,
    quietOvernight: "Ends the next day",
    quietNone: "Start and end are the same, so nothing is held.",
    quietUrgent: "Security notices always come through.",
    // limits
    limitsTitle: "Volume",
    limitsBody: "Keep the number of notifications under control.",
    capSwitch: "Limit notifications per day",
    capLabel: "Most per day",
    capHelp: "Beyond this, the rest wait for your digest.",
    capError: "Enter a whole number from 1 to 1,000.",
    batching: "Delivery",
    batchingOptions: { instant: "Send each one at once", hourly: "Group them every hour", daily: "Group them once a day" } as Record<Batching, string>,
    // digest
    digestTitle: "Digest",
    digestBody: "One summary of what you missed.",
    digestSwitch: "Send me a digest",
    frequency: "How often",
    daily: "Every day",
    weekly: "Every week",
    day: "Day",
    at: "Time",
    weekdays: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    nextDigest: "Next digest",
    // destinations
    destTitle: "Delivery destinations",
    destBody: "Send notifications to an extra email address or a webhook.",
    destEmpty: "No extra destinations yet.",
    destKind: "Type",
    destTarget: "Address",
    destEmail: "Email",
    destWebhook: "Webhook",
    destEmailPlaceholder: "team@example.com",
    destWebhookPlaceholder: "https://hooks.example.com/nasaq",
    add: "Add destination",
    remove: "Remove",
    removeTitle: (target: string) => `Remove ${target}?`,
    removeBody: "Notifications stop going there right away.",
    verified: "Verified",
    pending: "Waiting for confirmation",
    test: "Send a test",
    testing: "Sending",
    testOk: "The test was delivered.",
    testFailed: "The test failed.",
    problem: {
      empty: "Enter an address.",
      email: "Enter a valid email address.",
      url: "Enter a valid URL.",
      https: "Webhooks must use https.",
    } as Record<string, string>,
    destFailed: "That destination could not be changed. Try again.",
  },
  ar: {
    matrixTitle: "بماذا نُنبّهك",
    matrixBody: "اختر أين يصلك كل نوع من الإشعارات.",
    matrixLabel: "الإشعارات حسب النوع والقناة",
    kind: "الإشعار",
    channels: { email: "البريد", push: "الدفع", whatsapp: "واتساب", desktop: "سطح المكتب" } as Record<NotificationChannel, string>,
    cell: (kind: string, channel: string) => `${kind}: ${channel}`,
    all: (channel: string) => `تشغيل أو إيقاف ${channel} لكل الأنواع`,
    locked: "مفعّل دائمًا ولا يمكن إيقافه",
    unavailable: "غير متاح",
    pushAsking: "بانتظار ردّ المتصفح",
    pushBlocked: "إشعارات المتصفح محظورة. اسمح بها من إعدادات الموقع في متصفحك ثم حاول مرة أخرى.",
    pushDenied: "لم يُفعَّل الدفع لأن إذن المتصفح لم يُمنح.",
    pushUnsupported: "هذا المتصفح لا يدعم إشعارات الدفع.",
    pushNeeded: "سيطلب المتصفح الإذن أول مرة تفعّل فيها الدفع.",
    saving: "جارٍ الحفظ",
    saved: "تم الحفظ",
    failed: "لم يُحفظ ذلك فأُعيد كما كان. حاول مرة أخرى.",
    dismiss: "إغلاق",
    quietTitle: "ساعات الهدوء",
    quietBody: "احتفظ بالإشعارات أثناء غيابك. تصلك عند انتهاء ساعات الهدوء.",
    quietSwitch: "تشغيل ساعات الهدوء",
    from: "من",
    to: "حتى",
    quietLength: (h: string) => `${h} هدوء كل يوم`,
    quietOvernight: "تنتهي في اليوم التالي",
    quietNone: "البداية والنهاية متساويتان فلا يُحتجز شيء.",
    quietUrgent: "إشعارات الأمان تصل دائمًا.",
    limitsTitle: "الكمية",
    limitsBody: "تحكّم في عدد الإشعارات.",
    capSwitch: "تحديد عدد الإشعارات يوميًا",
    capLabel: "الحد الأقصى يوميًا",
    capHelp: "ما زاد عن ذلك ينتظر ملخّصك.",
    capError: "أدخل عددًا صحيحًا من 1 إلى 1000.",
    batching: "طريقة التسليم",
    batchingOptions: { instant: "أرسل كل إشعار فورًا", hourly: "اجمعها كل ساعة", daily: "اجمعها مرة في اليوم" } as Record<Batching, string>,
    digestTitle: "الملخّص",
    digestBody: "ملخص واحد لما فاتك.",
    digestSwitch: "أرسل لي ملخصًا",
    frequency: "التكرار",
    daily: "كل يوم",
    weekly: "كل أسبوع",
    day: "اليوم",
    at: "الوقت",
    weekdays: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
    nextDigest: "الملخّص القادم",
    destTitle: "وجهات التسليم",
    destBody: "أرسل الإشعارات إلى بريد إضافي أو إلى webhook.",
    destEmpty: "لا توجد وجهات إضافية بعد.",
    destKind: "النوع",
    destTarget: "العنوان",
    destEmail: "بريد إلكتروني",
    destWebhook: "Webhook",
    destEmailPlaceholder: "team@example.com",
    destWebhookPlaceholder: "https://hooks.example.com/nasaq",
    add: "إضافة وجهة",
    remove: "إزالة",
    removeTitle: (target: string) => `إزالة ${target}؟`,
    removeBody: "تتوقف الإشعارات عن الذهاب إليها فورًا.",
    verified: "موثّق",
    pending: "بانتظار التأكيد",
    test: "إرسال اختبار",
    testing: "جارٍ الإرسال",
    testOk: "وصل الاختبار.",
    testFailed: "فشل الاختبار.",
    problem: {
      empty: "أدخل عنوانًا.",
      email: "أدخل بريدًا إلكترونيًا صحيحًا.",
      url: "أدخل رابطًا صحيحًا.",
      https: "يجب أن يستخدم الـ webhook بروتوكول https.",
    } as Record<string, string>,
    destFailed: "تعذّر تغيير هذه الوجهة. حاول مرة أخرى.",
  },
};

export type NotificationPreferencesLabels = Partial<(typeof NOTIFICATION_STRINGS)["en"]>;
export const notificationStrings = (locale: string) => NOTIFICATION_STRINGS[locale.startsWith("ar") ? "ar" : "en"];
