import type { LandingSectionType } from "./landing-page";

export const STRINGS = {
  en: {
    editor: "Landing page editor",
    sections: "Sections",
    addSection: "Add section",
    noSections: "No sections yet",
    noSectionsHint: "Add a hero to start the page.",
    types: { hero: "Hero", features: "Features", faq: "FAQ", cta: "Call to action", text: "Text" },
    hidden: "Hidden",
    sectionActions: (n: string) => `Actions for ${n}`,
    moveUp: "Move up",
    moveDown: "Move down",
    hide: "Hide section",
    show: "Show section",
    duplicate: "Duplicate",
    remove: "Delete",
    section: "Section",
    page: "Page",
    edit: "Edit",
    preview: "Preview",
    desktop: "Desktop",
    mobile: "Mobile",
    selectHint: "Select a section to edit it.",
    pageTitle: "Page title",
    slug: "Address",
    slugHint: "Lowercase letters, numbers and hyphens.",
    slugInvalid: "Use lowercase letters, numbers and hyphens only.",
    seoTitle: "Search title",
    seoDescription: "Search description",
    characters: (n: string, max: string) => `${n} of ${max} characters`,
    direction: "Page direction",
    ltr: "Left to right",
    rtl: "Right to left",
    eyebrow: "Small label above",
    headline: "Headline",
    subheadline: "Subheadline",
    primaryLabel: "Main button text",
    primaryHref: "Main button link",
    secondaryLabel: "Second button text",
    secondaryHref: "Second button link",
    align: "Alignment",
    alignStart: "Start",
    alignCenter: "Center",
    title: "Title",
    subtitle: "Subtitle",
    items: "Items",
    itemTitle: "Title",
    itemDescription: "Description",
    feature: (n: string) => `Feature ${n}`,
    question: "Question",
    answer: "Answer",
    faqItem: (n: string) => `Question ${n}`,
    addFeature: "Add feature",
    addQuestion: "Add question",
    body: "Text",
    buttonLabel: "Button text",
    buttonHref: "Button link",
    linkInvalid: "Use https://, a path starting with /, or #.",
    draft: "Draft",
    published: "Published",
    unsaved: "Unsaved changes",
    saveDraft: "Save draft",
    publish: "Publish",
    update: "Publish changes",
    saved: "Draft saved.",
    publishedOk: "Page published.",
    failed: "Something went wrong. Try again.",
    blockers: {
      title: "Give the page a title.",
      slug: "Set a valid address for the page.",
      sections: "Show at least one section.",
      href: "Fix the invalid button links.",
    },
    previewLabel: "Page preview",
    previewSelect: (n: string) => `Edit ${n}`,
    untitled: "Untitled page",
  },
  ar: {
    editor: "محرر صفحة الهبوط",
    sections: "الأقسام",
    addSection: "إضافة قسم",
    noSections: "لا توجد أقسام بعد",
    noSectionsHint: "أضف قسمًا رئيسيًا لتبدأ الصفحة.",
    types: { hero: "الواجهة الرئيسية", features: "المزايا", faq: "الأسئلة الشائعة", cta: "دعوة لاتخاذ إجراء", text: "نص" },
    hidden: "مخفي",
    sectionActions: (n: string) => `إجراءات ${n}`,
    moveUp: "نقل لأعلى",
    moveDown: "نقل لأسفل",
    hide: "إخفاء القسم",
    show: "إظهار القسم",
    duplicate: "تكرار",
    remove: "حذف",
    section: "القسم",
    page: "الصفحة",
    edit: "تحرير",
    preview: "معاينة",
    desktop: "حاسوب",
    mobile: "جوال",
    selectHint: "اختر قسمًا لتحريره.",
    pageTitle: "عنوان الصفحة",
    slug: "العنوان",
    slugHint: "حروف لاتينية صغيرة وأرقام وشرطات.",
    slugInvalid: "استخدم حروفًا لاتينية صغيرة وأرقامًا وشرطات فقط.",
    seoTitle: "عنوان البحث",
    seoDescription: "وصف البحث",
    characters: (n: string, max: string) => `${n} من ${max} حرفًا`,
    direction: "اتجاه الصفحة",
    ltr: "من اليسار إلى اليمين",
    rtl: "من اليمين إلى اليسار",
    eyebrow: "عبارة صغيرة أعلاه",
    headline: "العنوان الرئيسي",
    subheadline: "العنوان الفرعي",
    primaryLabel: "نص الزر الرئيسي",
    primaryHref: "رابط الزر الرئيسي",
    secondaryLabel: "نص الزر الثاني",
    secondaryHref: "رابط الزر الثاني",
    align: "المحاذاة",
    alignStart: "البداية",
    alignCenter: "الوسط",
    title: "العنوان",
    subtitle: "العنوان الفرعي",
    items: "العناصر",
    itemTitle: "العنوان",
    itemDescription: "الوصف",
    feature: (n: string) => `الميزة ${n}`,
    question: "السؤال",
    answer: "الإجابة",
    faqItem: (n: string) => `السؤال ${n}`,
    addFeature: "إضافة ميزة",
    addQuestion: "إضافة سؤال",
    body: "النص",
    buttonLabel: "نص الزر",
    buttonHref: "رابط الزر",
    linkInvalid: "استخدم https:// أو مسارًا يبدأ بـ / أو #.",
    draft: "مسودة",
    published: "منشورة",
    unsaved: "تغييرات غير محفوظة",
    saveDraft: "حفظ المسودة",
    publish: "نشر",
    update: "نشر التغييرات",
    saved: "تم حفظ المسودة.",
    publishedOk: "تم نشر الصفحة.",
    failed: "حدث خطأ. حاول مرة أخرى.",
    blockers: {
      title: "أعطِ الصفحة عنوانًا.",
      slug: "حدّد عنوانًا صالحًا للصفحة.",
      sections: "أظهر قسمًا واحدًا على الأقل.",
      href: "صحّح روابط الأزرار غير الصالحة.",
    },
    previewLabel: "معاينة الصفحة",
    previewSelect: (n: string) => `تحرير ${n}`,
    untitled: "صفحة بلا عنوان",
  },
};

export type LandingPageEditorLabels = Omit<typeof STRINGS.en, "types" | "blockers"> & {
  types: Record<LandingSectionType, string>;
  blockers: Record<"title" | "slug" | "sections" | "href", string>;
};
export type LandingPageEditorLabelOverrides = Partial<Omit<LandingPageEditorLabels, "types" | "blockers">> & {
  types?: Partial<LandingPageEditorLabels["types"]>;
  blockers?: Partial<LandingPageEditorLabels["blockers"]>;
};

export function landingStrings(locale: string, labels?: LandingPageEditorLabelOverrides): LandingPageEditorLabels {
  const base = STRINGS[locale.startsWith("ar") ? "ar" : "en"];
  return { ...base, ...labels, types: { ...base.types, ...labels?.types }, blockers: { ...base.blockers, ...labels?.blockers } } as LandingPageEditorLabels;
}
