import { computed, type ComputedRef } from "vue";
import { useNasaq } from "../../provider";

// Same strings as the React component (packages/web/src/components/model-routing-editor).
export const STRINGS = {
  en: {
    auto: "Automatic routing",
    autoHint: "Pick the best model for each task class. Your routes below are the preferred choices.",
    routes: "Routes",
    routesHint: "Which model handles each kind of task, and what to try if it fails.",
    task: "Task class",
    model: "Model",
    fallback: "Fallback",
    none: "None",
    choose: "Choose a model",
    missing: "Choose a model for this task.",
    same: "The fallback must differ from the model.",
    unknown: "This model is no longer available.",
    providers: "Providers and nodes",
    providersHint: "Where models run. Register a cloud provider or a self-hosted node and say what it can do.",
    backend: "Active backend",
    add: "Register provider",
    remove: (n: string) => `Remove ${n}`,
    online: "Online",
    offline: "Offline",
    cloud: "Cloud",
    node: "Node",
    noProviders: "No providers yet. Register one to route tasks.",
    dialogTitle: "Register a provider",
    dialogBody: "Add a cloud API or a self-hosted node and choose which kinds of work it can take.",
    name: "Name",
    kind: "Type",
    endpoint: "Endpoint URL",
    endpointHint: "The address the provider is reached at.",
    modalities: "Modalities",
    modalitiesHint: "What it can handle.",
    text: "Text",
    vision: "Vision",
    audio: "Audio",
    image: "Image",
    embedding: "Embedding",
    nameRequired: "Enter a name.",
    nameDuplicate: "A provider with this name already exists.",
    endpointRequired: "Enter the endpoint URL.",
    endpointInvalid: "Enter a full address starting with http:// or https://.",
    modalitiesRequired: "Choose at least one modality.",
    cancel: "Cancel",
    register: "Register",
    dirty: "Unsaved routing changes",
    saved: "Saved",
    save: "Save routing",
    discard: "Discard changes",
    failed: "Could not save. Try again.",
    registerFailed: "Could not register the provider. Try again.",
    fixIssues: "Fix the routes marked below to save.",
    modalitiesOf: (n: string) => `Modalities of ${n}`,
  },
  ar: {
    auto: "التوجيه التلقائي",
    autoHint: "اختيار أفضل نموذج لكل فئة مهام. المسارات أدناه هي الخيارات المفضّلة.",
    routes: "المسارات",
    routesHint: "أي نموذج يتولى كل نوع من المهام، وماذا يُجرَّب إذا فشل.",
    task: "فئة المهمة",
    model: "النموذج",
    fallback: "البديل",
    none: "بدون",
    choose: "اختر نموذجًا",
    missing: "اختر نموذجًا لهذه المهمة.",
    same: "يجب أن يختلف البديل عن النموذج.",
    unknown: "هذا النموذج لم يعد متاحًا.",
    providers: "المزوّدون والعُقد",
    providersHint: "أين تعمل النماذج. سجّل مزوّدًا سحابيًا أو عقدة مستضافة ذاتيًا وحدّد ما تستطيع فعله.",
    backend: "الواجهة الخلفية النشطة",
    add: "تسجيل مزوّد",
    remove: (n: string) => `إزالة ${n}`,
    online: "متصل",
    offline: "غير متصل",
    cloud: "سحابي",
    node: "عقدة",
    noProviders: "لا يوجد مزوّدون بعد. سجّل واحدًا لتوجيه المهام.",
    dialogTitle: "تسجيل مزوّد",
    dialogBody: "أضف واجهة سحابية أو عقدة مستضافة ذاتيًا واختر أنواع العمل التي تتولاها.",
    name: "الاسم",
    kind: "النوع",
    endpoint: "رابط نقطة الاتصال",
    endpointHint: "العنوان الذي يُتصل به بالمزوّد.",
    modalities: "الوسائط",
    modalitiesHint: "ما يستطيع معالجته.",
    text: "نص",
    vision: "رؤية",
    audio: "صوت",
    image: "صورة",
    embedding: "تضمين",
    nameRequired: "أدخل اسمًا.",
    nameDuplicate: "يوجد مزوّد بهذا الاسم.",
    endpointRequired: "أدخل رابط نقطة الاتصال.",
    endpointInvalid: "أدخل عنوانًا كاملًا يبدأ بـ http:// أو https://.",
    modalitiesRequired: "اختر وسيطًا واحدًا على الأقل.",
    cancel: "إلغاء",
    register: "تسجيل",
    dirty: "تغييرات توجيه غير محفوظة",
    saved: "تم الحفظ",
    save: "حفظ التوجيه",
    discard: "تجاهل التغييرات",
    failed: "تعذّر الحفظ. حاول مرة أخرى.",
    registerFailed: "تعذّر تسجيل المزوّد. حاول مرة أخرى.",
    fixIssues: "أصلح المسارات المعلَّمة أدناه للحفظ.",
    modalitiesOf: (n: string) => `وسائط ${n}`,
  },
};

export type ModelRoutingEditorLabels = Partial<typeof STRINGS.en>;

/** The built-in strings for the active locale, with `labels` laid over them. */
export function useLabels(labels: () => ModelRoutingEditorLabels | undefined): ComputedRef<typeof STRINGS.en> {
  const nq = useNasaq();
  return computed(() => ({ ...STRINGS[nq.locale.value.startsWith("ar") ? "ar" : "en"], ...labels() }));
}
