// Strings of the workspace screens, English and Arabic. Pass `labels` to override any of them.
import { SLUG_MAX, SLUG_MIN, type SlugProblem } from "./workspace-slug";

export const WORKSPACE_STRINGS = {
  en: {
    // create
    onboardTitle: "Create your workspace",
    onboardBody: "A workspace is where your team keeps everything. You can invite people next.",
    createTitle: "Create a workspace",
    createBody: "A separate space for a team, a client or a project.",
    name: "Workspace name",
    namePlaceholder: "Sahab Studio",
    nameRequired: "Enter a name for the workspace.",
    slug: "Workspace address",
    slugHelp: "Letters, numbers and dashes. You can change it later.",
    slugChecking: "Checking availability",
    slugAvailable: "This address is available.",
    slugTaken: "That address is taken. Try another one.",
    slugCheckFailed: "Availability could not be checked. It will be verified when you create it.",
    problem: {
      empty: "Enter an address for the workspace.",
      short: `Use at least ${SLUG_MIN} characters.`,
      long: `Use at most ${SLUG_MAX} characters.`,
      format: "Use lowercase letters, numbers and dashes. Start and end with a letter or number.",
    } as Record<SlugProblem, string>,
    create: "Create workspace",
    cancel: "Cancel",
    failed: "That did not work. Try again.",
    // list
    listTitle: "Your workspaces",
    listLabel: "Workspaces",
    open: "Open",
    current: "Current",
    members: (n: string) => (n === "1" ? "1 member" : `${n} members`),
    newWorkspace: "New workspace",
    listEmpty: "You are not in any workspace yet",
    listEmptyHint: "Create one, or ask a teammate to invite you.",
    roleOwner: "Owner",
    // settings
    generalTitle: "General",
    generalBody: "The name and address people see for this workspace.",
    picture: "Workspace picture",
    save: "Save changes",
    saved: "Workspace updated.",
    readOnly: "Only owners and admins can change these settings.",
    leaveTitle: "Leave workspace",
    leaveBody: "You lose access until someone invites you again.",
    leaveButton: "Leave workspace",
    leaveConfirmTitle: (name: string) => `Leave ${name}?`,
    leaveConfirmBody: "You lose access to everything in this workspace. You can rejoin only if someone invites you.",
    leaveBlocked: "You are the only owner. Transfer ownership to another member first.",
    deleteTitle: "Delete workspace",
    deleteHeading: "Delete this workspace",
    deleteBody: "Permanently delete the workspace and everything in it for every member. This cannot be undone.",
    deleteButton: "Delete workspace",
    deleteConfirmTitle: (name: string) => `Delete ${name}?`,
    deleteConfirmBody: "Every member loses access and all of its data is removed for good.",
    deletePrompt: (text: string) => `Type ${text} to confirm`,
    deleteAction: "Delete this workspace",
    deleteFailed: "The workspace could not be deleted. Try again.",
  },
  ar: {
    onboardTitle: "أنشئ مساحة عملك",
    onboardBody: "مساحة العمل هي المكان الذي يحفظ فيه فريقك كل شيء. يمكنك دعوة الآخرين بعدها.",
    createTitle: "إنشاء مساحة عمل",
    createBody: "مساحة منفصلة لفريق أو عميل أو مشروع.",
    name: "اسم مساحة العمل",
    namePlaceholder: "سحاب ستوديو",
    nameRequired: "أدخل اسمًا لمساحة العمل.",
    slug: "عنوان مساحة العمل",
    slugHelp: "أحرف وأرقام وشرطات. يمكنك تغييره لاحقًا.",
    slugChecking: "جارٍ التحقق من التوفر",
    slugAvailable: "هذا العنوان متاح.",
    slugTaken: "هذا العنوان مستخدم. جرّب عنوانًا آخر.",
    slugCheckFailed: "تعذّر التحقق من التوفر. سيُتحقق منه عند الإنشاء.",
    problem: {
      empty: "أدخل عنوانًا لمساحة العمل.",
      short: `استخدم ${SLUG_MIN} أحرف على الأقل.`,
      long: `استخدم ${SLUG_MAX} حرفًا على الأكثر.`,
      format: "استخدم أحرفًا لاتينية صغيرة وأرقامًا وشرطات. ابدأ وانتهِ بحرف أو رقم.",
    } as Record<SlugProblem, string>,
    create: "إنشاء مساحة العمل",
    cancel: "إلغاء",
    failed: "لم تنجح العملية. حاول مرة أخرى.",
    listTitle: "مساحات عملك",
    listLabel: "مساحات العمل",
    open: "فتح",
    current: "الحالية",
    members: (n: string) => (n === "1" ? "عضو واحد" : `${n} أعضاء`),
    newWorkspace: "مساحة عمل جديدة",
    listEmpty: "لست في أي مساحة عمل بعد",
    listEmptyHint: "أنشئ واحدة، أو اطلب من زميل دعوتك.",
    roleOwner: "المالك",
    generalTitle: "عام",
    generalBody: "الاسم والعنوان اللذان يراهما الناس لمساحة العمل هذه.",
    picture: "صورة مساحة العمل",
    save: "حفظ التغييرات",
    saved: "تم تحديث مساحة العمل.",
    readOnly: "المالكون والمشرفون وحدهم يستطيعون تغيير هذه الإعدادات.",
    leaveTitle: "مغادرة مساحة العمل",
    leaveBody: "تفقد الوصول إلى أن يدعوك أحد مرة أخرى.",
    leaveButton: "مغادرة مساحة العمل",
    leaveConfirmTitle: (name: string) => `مغادرة ${name}؟`,
    leaveConfirmBody: "تفقد الوصول إلى كل شيء في مساحة العمل هذه. لا تستطيع العودة إلا إذا دعاك أحد.",
    leaveBlocked: "أنت المالك الوحيد. انقل الملكية إلى عضو آخر أولًا.",
    deleteTitle: "حذف مساحة العمل",
    deleteHeading: "احذف مساحة العمل هذه",
    deleteBody: "احذف مساحة العمل وكل ما فيها نهائيًا لجميع الأعضاء. لا يمكن التراجع عن ذلك.",
    deleteButton: "حذف مساحة العمل",
    deleteConfirmTitle: (name: string) => `حذف ${name}؟`,
    deleteConfirmBody: "يفقد كل الأعضاء وصولهم وتُحذف كل بياناتها نهائيًا.",
    deletePrompt: (text: string) => `اكتب ${text} للتأكيد`,
    deleteAction: "احذف مساحة العمل هذه",
    deleteFailed: "تعذّر حذف مساحة العمل. حاول مرة أخرى.",
  },
};
export const workspaceStrings = (locale: string) => WORKSPACE_STRINGS[locale.startsWith("ar") ? "ar" : "en"];
export type WorkspaceSettingsLabels = Partial<typeof WORKSPACE_STRINGS.en>;
