import type { RankBucket } from "./rank-math";

export const KEYWORD_STRINGS = {
  en: {
    // header and tiles
    tracked: "Tracked keywords",
    avgPosition: "Average position",
    inTop10: "In the top 10",
    visibility: "Visibility",
    comparison: "vs previous check",
    // distribution
    distributionTitle: "Ranking distribution",
    distributionDescription: "How many keywords sit in each band of the results.",
    bucket: { top3: "Top 3", top10: "4 to 10", top100: "11 to 100", unranked: "Not ranking" } as Record<RankBucket, string>,
    bucketCount: (label: string, n: number, share: string) => `${label}: ${n} keywords, ${share}`,
    historyTitle: "Position history",
    historyDescription: "Average position of ranked keywords over time.",
    avgPositionShort: "Avg. position",
    inTop10Short: "In top 10",
    // movers
    moversTitle: "Biggest movers",
    gainers: "Gained",
    losers: "Lost",
    noMovers: "No movement yet",
    places: (n: number) => (n === 1 ? "1 place" : `${n} places`),
    // table
    keywordsTitle: "Keywords",
    keywordsDescription: "Each keyword's position in the results, how it moved and what it could bring.",
    keyword: "Keyword",
    position: "Position",
    best: "Best",
    trend: "Trend",
    url: "Ranking URL",
    urlEmpty: "No page ranks",
    volume: "Volume",
    volumePerMonth: "Searches a month",
    difficulty: "Difficulty",
    features: "SERP features",
    filter: "Filter keywords…",
    empty: "No keywords tracked",
    emptyBody: "Add keywords to start tracking where you rank.",
    notRanking: "Not in top 100",
    up: (n: number) => `Up ${n}`,
    down: (n: number) => `Down ${n}`,
    same: "No change",
    newRank: "New",
    lostRank: "Lost",
    difficultyBand: { easy: "Easy", medium: "Medium", hard: "Hard" } as Record<"easy" | "medium" | "hard", string>,
    feature: {
      snippet: "Snippet",
      paa: "People also ask",
      images: "Images",
      video: "Video",
      local: "Local pack",
      sitelinks: "Sitelinks",
      reviews: "Reviews",
      ads: "Ads",
    } as Record<string, string>,
    // actions
    add: "Add keywords",
    refresh: "Check now",
    refreshRow: "Check again",
    openSerp: "Open the results",
    remove: "Stop tracking",
    removeTitle: (n: number) => (n === 1 ? "Stop tracking this keyword?" : `Stop tracking ${n} keywords?`),
    removeBody: "Its history is kept for 30 days in case you add it back.",
    cancel: "Cancel",
    actionFailed: "Could not complete this. Try again.",
    // add dialog
    addTitle: "Add keywords",
    addBody: "One keyword per line, or separated by commas. They are checked for the location and device you pick.",
    keywordsLabel: "Keywords",
    keywordsPlaceholder: "rtl react components\nnasaq design system",
    locationLabel: "Location",
    deviceLabel: "Device",
    desktop: "Desktop",
    mobile: "Mobile",
    keywordCount: (n: number) => (n === 0 ? "No keywords yet" : n === 1 ? "1 keyword" : `${n} keywords`),
    keywordsRequired: "Add at least one keyword.",
    addSubmit: (n: number) => (n > 1 ? `Add ${n} keywords` : "Add keyword"),
    // competitors
    competitorsTitle: "Competitors",
    competitorsDescription: "Where you and your competitors rank for the same keywords.",
    domain: "Domain",
    you: "You",
    avgPos: "Avg. position",
    top10Count: "Top 10",
    share: "Visibility",
    matrixTitle: "Keyword by keyword",
    ahead: (n: number) => (n === 1 ? "1 keyword ahead of you" : `${n} keywords ahead of you`),
    tabKeywords: "Keywords",
    tabCompetitors: "Competitors",
    noCompetitors: "No competitors added",
    lowerIsBetter: "Lower is better",
  },
  ar: {
    tracked: "الكلمات المتابَعة",
    avgPosition: "متوسط الترتيب",
    inTop10: "ضمن أول 10",
    visibility: "الظهور",
    comparison: "مقابل الفحص السابق",
    distributionTitle: "توزيع الترتيب",
    distributionDescription: "عدد الكلمات في كل شريحة من نتائج البحث.",
    bucket: { top3: "أول 3", top10: "من 4 إلى 10", top100: "من 11 إلى 100", unranked: "خارج الترتيب" } as Record<RankBucket, string>,
    bucketCount: (label: string, n: number, share: string) => `${label}: ${n} كلمة، ${share}`,
    historyTitle: "سجل الترتيب",
    historyDescription: "متوسط ترتيب الكلمات المصنّفة عبر الزمن.",
    avgPositionShort: "متوسط الترتيب",
    inTop10Short: "ضمن أول 10",
    moversTitle: "أكبر التغيّرات",
    gainers: "صعدت",
    losers: "هبطت",
    noMovers: "لا تغيّر بعد",
    places: (n: number) => (n === 1 ? "مرتبة واحدة" : n === 2 ? "مرتبتان" : n <= 10 ? `${n} مراتب` : `${n} مرتبة`),
    keywordsTitle: "الكلمات المفتاحية",
    keywordsDescription: "ترتيب كل كلمة في النتائج وكيف تحرّك وما يمكن أن تجلبه.",
    keyword: "الكلمة",
    position: "الترتيب",
    best: "الأفضل",
    trend: "الاتجاه",
    url: "الرابط في النتائج",
    urlEmpty: "لا صفحة مصنّفة",
    volume: "حجم البحث",
    volumePerMonth: "عمليات البحث شهريًا",
    difficulty: "الصعوبة",
    features: "ميزات النتائج",
    filter: "تصفية الكلمات…",
    empty: "لا كلمات متابَعة",
    emptyBody: "أضف كلمات لتبدأ بمتابعة ترتيبك.",
    notRanking: "خارج أول 100",
    up: (n: number) => `صعود ${n}`,
    down: (n: number) => `هبوط ${n}`,
    same: "بلا تغيير",
    newRank: "جديد",
    lostRank: "فُقد",
    difficultyBand: { easy: "سهلة", medium: "متوسطة", hard: "صعبة" } as Record<"easy" | "medium" | "hard", string>,
    feature: {
      snippet: "مقتطف",
      paa: "أسئلة ذات صلة",
      images: "صور",
      video: "فيديو",
      local: "الخريطة المحلية",
      sitelinks: "روابط فرعية",
      reviews: "تقييمات",
      ads: "إعلانات",
    } as Record<string, string>,
    add: "إضافة كلمات",
    refresh: "فحص الآن",
    refreshRow: "فحص مرة أخرى",
    openSerp: "فتح النتائج",
    remove: "إيقاف المتابعة",
    removeTitle: (n: number) => (n === 1 ? "إيقاف متابعة هذه الكلمة؟" : `إيقاف متابعة ${n} كلمات؟`),
    removeBody: "يُحفظ سجلها 30 يومًا إن أعدت إضافتها.",
    cancel: "إلغاء",
    actionFailed: "تعذّر إكمال هذا. حاول مرة أخرى.",
    addTitle: "إضافة كلمات",
    addBody: "كلمة في كل سطر أو مفصولة بفواصل. يتم فحصها للموقع والجهاز اللذين تختارهما.",
    keywordsLabel: "الكلمات",
    keywordsPlaceholder: "مكونات ريأكت عربية\nنظام تصميم نسق",
    locationLabel: "الموقع",
    deviceLabel: "الجهاز",
    desktop: "سطح المكتب",
    mobile: "الجوال",
    keywordCount: (n: number) => (n === 0 ? "لا كلمات بعد" : n === 1 ? "كلمة واحدة" : `${n} كلمات`),
    keywordsRequired: "أضف كلمة واحدة على الأقل.",
    addSubmit: (n: number) => (n > 1 ? `إضافة ${n} كلمات` : "إضافة الكلمة"),
    competitorsTitle: "المنافسون",
    competitorsDescription: "أين تصنَّف أنت ومنافسوك للكلمات نفسها.",
    domain: "النطاق",
    you: "أنت",
    avgPos: "متوسط الترتيب",
    top10Count: "أول 10",
    share: "الظهور",
    matrixTitle: "كلمة بكلمة",
    ahead: (n: number) => (n === 1 ? "كلمة واحدة متقدمة عليك" : `${n} كلمات متقدمة عليك`),
    tabKeywords: "الكلمات",
    tabCompetitors: "المنافسون",
    noCompetitors: "لم تُضَف منافسات",
    lowerIsBetter: "الأقل أفضل",
  },
};

export type KeywordTrackerLabels = typeof KEYWORD_STRINGS.en;
export type SerpFeature = "snippet" | "paa" | "images" | "video" | "local" | "sitelinks" | "reviews" | "ads";
