import { computed, type ComputedRef } from "vue";
import { useNasaq } from "../../provider";
import type { FormDefinition, FormFieldKind } from "../public-form/form-model";

export const FORM_BUILDER_STRINGS = {
  en: {
    tabs: { fields: "Fields", logic: "Logic", settings: "Settings", embed: "Embed" },
    name: "Form name",
    enabled: "Accepting responses",
    save: "Save form",
    addField: "Add a field",
    kinds: { text: "Short text", email: "Email", phone: "Phone", number: "Number", textarea: "Long text", select: "Dropdown", radio: "Choice", checkbox: "Checkbox" } satisfies Record<FormFieldKind, string>,
    untitled: "Untitled field",
    required: "Required",
    moveUp: "Move up",
    moveDown: "Move down",
    duplicate: "Duplicate",
    remove: "Remove field",
    fieldList: "Form fields",
    noFields: "No fields yet. Add one to start.",
    editing: "Field settings",
    labelEn: "Label (English)",
    labelAr: "Label (Arabic)",
    kind: "Type",
    isRequired: "Visitors must fill this in",
    placeholder: "Placeholder",
    help: "Help text",
    options: "Options",
    optionsHint: "One per line. Write the Arabic after a bar: Riyadh | الرياض",
    preview: "Live preview",
    logicIntro: "Show, hide or require a field depending on what the visitor answered.",
    addRule: "Add a rule",
    removeRule: "Remove rule",
    rule: (n: string) => `Rule ${n}`,
    noRules: "No rules. Every field always shows.",
    event: "An answer changes",
    show: "Show field",
    hide: "Hide field",
    requireField: "Require field",
    target: "Field",
    origins: "Allowed sites",
    originsHint: "Where this form may be embedded. Separate with a comma or Enter, for example https://example.com or https://*.example.com.",
    originsAdd: "https://example.com",
    originsInvalid: "Use a full address that starts with http:// or https://.",
    originsClosed: "Closed: no site can embed this form until you add its address.",
    originsOpen: (n: string) => `Open to ${n} site(s).`,
    originTest: "Try an address",
    originTestAllowed: "Allowed",
    originTestBlocked: "Blocked",
    thanksEn: "Thank-you message (English)",
    thanksAr: "Thank-you message (Arabic)",
    honeypot: "Hide a trap field from bots",
    honeypotHint: "Bots fill it in, people never see it. Those submissions are dropped without telling the sender.",
    embedIntro: "Paste this where the form should appear.",
    iframe: "Iframe",
    script: "Script",
    copyLink: "Copy public link",
    embedClosed: "This form is closed. Add the site under Settings first, or the snippet will be refused.",
    ruleFieldsMissing: "Add fields first to build rules.",
  },
  ar: {
    tabs: { fields: "الحقول", logic: "المنطق", settings: "الإعدادات", embed: "التضمين" },
    name: "اسم النموذج",
    enabled: "يستقبل الردود",
    save: "حفظ النموذج",
    addField: "إضافة حقل",
    kinds: { text: "نص قصير", email: "بريد إلكتروني", phone: "هاتف", number: "رقم", textarea: "نص طويل", select: "قائمة منسدلة", radio: "اختيار", checkbox: "خانة اختيار" } satisfies Record<FormFieldKind, string>,
    untitled: "حقل بلا عنوان",
    required: "مطلوب",
    moveUp: "نقل لأعلى",
    moveDown: "نقل لأسفل",
    duplicate: "تكرار",
    remove: "حذف الحقل",
    fieldList: "حقول النموذج",
    noFields: "لا حقول بعد. أضف حقلًا للبدء.",
    editing: "إعدادات الحقل",
    labelEn: "العنوان (بالإنجليزية)",
    labelAr: "العنوان (بالعربية)",
    kind: "النوع",
    isRequired: "يجب على الزائر تعبئته",
    placeholder: "النص الإرشادي",
    help: "نص مساعد",
    options: "الخيارات",
    optionsHint: "خيار في كل سطر. اكتب العربية بعد شرطة: Riyadh | الرياض",
    preview: "معاينة مباشرة",
    logicIntro: "أظهر حقلًا أو أخفِه أو اجعله مطلوبًا بحسب ما أجاب به الزائر.",
    addRule: "إضافة قاعدة",
    removeRule: "حذف القاعدة",
    rule: (n: string) => `القاعدة ${n}`,
    noRules: "لا قواعد. كل الحقول تظهر دائمًا.",
    event: "تغيّرت إجابة",
    show: "إظهار الحقل",
    hide: "إخفاء الحقل",
    requireField: "جعل الحقل مطلوبًا",
    target: "الحقل",
    origins: "المواقع المسموح بها",
    originsHint: "المواقع التي يجوز تضمين النموذج فيها. افصل بفاصلة أو Enter، مثل https://example.com أو https://*.example.com.",
    originsAdd: "https://example.com",
    originsInvalid: "استخدم عنوانًا كاملًا يبدأ بـ http:// أو https://.",
    originsClosed: "مغلق: لا يستطيع أي موقع تضمين النموذج حتى تضيف عنوانه.",
    originsOpen: (n: string) => `مفتوح لـ ${n} موقع.`,
    originTest: "جرّب عنوانًا",
    originTestAllowed: "مسموح",
    originTestBlocked: "محظور",
    thanksEn: "رسالة الشكر (بالإنجليزية)",
    thanksAr: "رسالة الشكر (بالعربية)",
    honeypot: "إخفاء حقل فخ عن الروبوتات",
    honeypotHint: "تعبئه الروبوتات ولا يراه الناس. تُهمل هذه الردود دون إخبار المرسل.",
    embedIntro: "الصق هذا حيث يجب أن يظهر النموذج.",
    iframe: "إطار iframe",
    script: "سكربت",
    copyLink: "نسخ الرابط العام",
    embedClosed: "هذا النموذج مغلق. أضف الموقع من الإعدادات أولًا وإلا سيُرفض التضمين.",
    ruleFieldsMissing: "أضف حقولًا أولًا لبناء القواعد.",
  },
} as const;

type En = (typeof FORM_BUILDER_STRINGS)["en"];
export type FormBuilderLabels = Partial<{ [K in keyof En]: En[K] extends string ? string : En[K] }>;

export function useFormBuilderStrings(locale: () => string | undefined, labels: () => FormBuilderLabels | undefined): { locale: ComputedRef<string>; ar: ComputedRef<boolean>; t: ComputedRef<En> } {
  const nq = useNasaq();
  const loc = computed(() => locale() ?? nq.locale.value ?? "en");
  const ar = computed(() => loc.value.startsWith("ar"));
  const t = computed(() => ({ ...FORM_BUILDER_STRINGS[ar.value ? "ar" : "en"], ...labels() }) as En);
  return { locale: loc, ar, t };
}

/** A blank inquiry form. */
export const FORM_BUILDER_BLANK: FormDefinition = {
  name: "",
  kind: "inquiry",
  fields: [],
  rules: [],
  allowedOrigins: [],
  enabled: true,
  thanksEn: "Thank you!",
  thanksAr: "شكرًا لك!",
  honeypot: true,
};
