const clusterCount = (n: number) => (n === 2 ? "مكانان" : n <= 10 ? `${n} أماكن` : `${n} مكانًا`);

export const STRINGS = {
  en: {
    map: "Map",
    layers: "Layers",
    routes: "Routes",
    areas: "Areas",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    fit: "Show everything",
    close: "Close",
    copyCoordinates: "Copy coordinates",
    coordinates: "Coordinates",
    hint: "Drag to move. Use the arrow keys to pan, plus and minus to zoom, Home to show everything.",
    pins: (n: number) => (n === 1 ? "1 place" : `${n} places`),
    routeLength: (km: string) => `${km} km`,
    showLayer: (name: string) => `Show ${name}`,
    noPins: "Nothing to show on the map",
    selected: (name: string) => `${name}, selected`,
    clusterZoom: (n: number) => `${n} pins, zoom in`,
    clusterList: (n: number) => `${n} pins, show the list`,
    clusterPins: (n: number) => `${n} pins`,
    clusterHint: "These pins share one spot. Choose one to see it.",
    pickedPoint: "Chosen location",
    pickedHint: "Drag to move. Arrow keys nudge it, Shift for bigger steps.",
    vertex: (n: number) => `Point ${n}`,
    vertexHint: "Drag to move. Arrow keys nudge it. Delete removes it.",
    shape: "Shape being edited",
    removeLast: "Remove last point",
    finishShape: "Finish shape",
    editHint: "Click the map, or press Enter, to add a point.",
  },
  ar: {
    map: "الخريطة",
    layers: "الطبقات",
    routes: "المسارات",
    areas: "المناطق",
    zoomIn: "تكبير",
    zoomOut: "تصغير",
    fit: "عرض كل شيء",
    close: "إغلاق",
    copyCoordinates: "نسخ الإحداثيات",
    coordinates: "الإحداثيات",
    hint: "اسحب للتحريك. استخدم الأسهم للتنقل، وعلامتي الزائد والناقص للتكبير، وHome لعرض كل شيء.",
    pins: (n: number) => (n === 1 ? "مكان واحد" : n === 2 ? "مكانان" : n <= 10 ? `${n} أماكن` : `${n} مكانًا`),
    routeLength: (km: string) => `${km} كم`,
    showLayer: (name: string) => `إظهار ${name}`,
    noPins: "لا شيء لعرضه على الخريطة",
    selected: (name: string) => `${name}، محدد`,
    clusterZoom: (n: number) => `${clusterCount(n)}، كبّر للتفصيل`,
    clusterList: (n: number) => `${clusterCount(n)}، عرض القائمة`,
    clusterPins: (n: number) => clusterCount(n),
    clusterHint: "هذه الأماكن في نقطة واحدة. اختر مكانًا لعرضه.",
    pickedPoint: "الموقع المختار",
    pickedHint: "اسحب للتحريك. الأسهم تحرّكه خطوة خطوة، ومع Shift خطوة أكبر.",
    vertex: (n: number) => `النقطة ${n}`,
    vertexHint: "اسحب للتحريك. الأسهم تحرّكها. Delete يحذفها.",
    shape: "الشكل قيد التعديل",
    removeLast: "حذف آخر نقطة",
    finishShape: "إنهاء الشكل",
    editHint: "انقر على الخريطة، أو اضغط Enter، لإضافة نقطة.",
  },
};
export type MapViewLabels = Partial<(typeof STRINGS)["en"]>;
