export const STRINGS = {
  en: {
    list: "Sections",
    add: "Add section",
    edit: (title: string) => `Edit ${title}`,
    remove: (title: string) => `Remove ${title}`,
    reorder: (title: string) => `Move ${title}`,
    reorderHint: "Drag, or press the arrow keys, Home or End, to move a section.",
    moved: (title: string, at: string, of: string) => `${title} is now at position ${at} of ${of}`,
    removed: (title: string) => `${title} removed`,
    saved: (title: string) => `${title} saved`,
    editTitle: "Edit section",
    editDescription: "The prompt and model that generate this section, and any settings it needs.",
    name: "Title",
    badge: "Tag",
    prompt: "Prompt",
    promptHint: "What should this section show? Write it as an instruction.",
    model: "Model",
    defaultModel: "Default model",
    settings: "Settings",
    key: "Key",
    value: "Value",
    removeSetting: (key: string) => (key ? `Remove setting ${key}` : "Remove setting"),
    addSetting: "Add setting",
    duplicateKey: (key: string) => `"${key}" is used more than once. Keys must be unique.`,
    needTitle: "Give the section a title.",
    cancel: "Cancel",
    save: "Save",
    emptyContent: "Nothing to show yet.",
    emptyTitle: "No sections",
    empty: "Add a section to start building this page.",
  },
  ar: {
    list: "الأقسام",
    add: "إضافة قسم",
    edit: (title: string) => `تعديل ${title}`,
    remove: (title: string) => `حذف ${title}`,
    reorder: (title: string) => `نقل ${title}`,
    reorderHint: "اسحب، أو استخدم مفاتيح الأسهم أو Home أو End، لنقل القسم.",
    moved: (title: string, at: string, of: string) => `${title} الآن في الموضع ${at} من ${of}`,
    removed: (title: string) => `تم حذف ${title}`,
    saved: (title: string) => `تم حفظ ${title}`,
    editTitle: "تعديل القسم",
    editDescription: "التوجيه والنموذج اللذان ينتجان هذا القسم، وأي إعدادات يحتاجها.",
    name: "العنوان",
    badge: "الوسم",
    prompt: "التوجيه",
    promptHint: "ماذا يعرض هذا القسم؟ اكتبه كتعليمات.",
    model: "النموذج",
    defaultModel: "النموذج الافتراضي",
    settings: "الإعدادات",
    key: "المفتاح",
    value: "القيمة",
    removeSetting: (key: string) => (key ? `حذف الإعداد ${key}` : "حذف الإعداد"),
    addSetting: "إضافة إعداد",
    duplicateKey: (key: string) => `"${key}" مستخدم أكثر من مرة. يجب أن تكون المفاتيح فريدة.`,
    needTitle: "أعطِ القسم عنوانًا.",
    cancel: "إلغاء",
    save: "حفظ",
    emptyContent: "لا شيء لعرضه بعد.",
    emptyTitle: "لا توجد أقسام",
    empty: "أضف قسمًا لبدء بناء هذه الصفحة.",
  },
};

export type SectionBoardLabels = (typeof STRINGS)["en"];

export const sectionBoardStrings = (locale: string): SectionBoardLabels => STRINGS[locale.startsWith("ar") ? "ar" : "en"];
