// Built-in English and Arabic strings of the onboarding flow.
export const STRINGS = {
  en: {
    title: "Set up your account",
    description: "A few quick steps and you are ready. You can skip the optional ones and finish them later.",
    welcome: "Welcome",
    welcomeDescription: "Here is what we will do together.",
    welcomeHeading: "Welcome, {name}",
    welcomeHeadingAnon: "Welcome aboard",
    welcomeLead: "Setting up takes about three minutes. Your progress is saved, so you can leave and come back.",
    welcomeProfile: "Tell us who you are",
    welcomeWorkspace: "Create or join a workspace",
    welcomeInvite: "Bring your team",
    welcomePrefs: "Choose how it looks and feels",
    welcomeConnect: "Connect your first tool",
    resumed: "Welcome back. We saved your place.",
    startOver: "Start over",
    profile: "Your profile",
    profileDescription: "This is how teammates see you.",
    photo: "Profile photo",
    fullName: "Full name",
    nameRequired: "Enter your name.",
    role: "Your role",
    rolePlaceholder: "Choose a role",
    workspace: "Your workspace",
    workspaceDescription: "Create a new one or join your team's.",
    create: "Create a workspace",
    join: "Join with a code",
    workspaceName: "Workspace name",
    workspaceNameHint: "Your company or team. You can rename it later.",
    workspaceNameRequired: "Enter a workspace name.",
    inviteCode: "Invite code",
    inviteCodeHint: "Ask a workspace admin. It looks like ABCD-1234.",
    inviteCodeRequired: "Enter the invite code.",
    invite: "Invite teammates",
    inviteDescription: "They get an email with a link to join.",
    emails: "Email addresses",
    emailsHint: "Press Enter or comma after each one. Pasting a list works too.",
    emailsPlaceholder: "name@company.com",
    inviteRole: "Invite them as",
    invalidEmail: "{email} is not an email address.",
    duplicateEmail: "{email} is already added.",
    invitesCount: "{count} to invite",
    preferences: "Preferences",
    preferencesDescription: "Change these any time in settings.",
    language: "Language",
    theme: "Theme",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "System",
    notifications: "Notifications",
    notifyEmail: "Email me about activity",
    notifyPush: "Push notifications on this device",
    notifyDigest: "Send a weekly summary",
    integration: "Connect a tool",
    integrationDescription: "Pick the first place your work comes from.",
    connect: "Connect",
    connected: "Connected",
    connectFailed: "Could not connect. Try again.",
    finish: "All set",
    finishDescription: "Review what you did.",
    review: "Your setup",
    stepDone: "Done",
    stepSkipped: "Skipped",
    stepOpen: "Not done",
    later: "You can finish skipped steps from the Get started checklist.",
    doneTitle: "You are ready",
    doneDescription: "Your workspace is set up. Head in and look around.",
    optional: "Optional",
    errorTitle: "Fix these to continue",
    failed: "Something went wrong. Try again.",
    roles: { design: "Design", engineering: "Engineering", product: "Product", marketing: "Marketing", operations: "Operations", other: "Other" },
    inviteRoles: { member: "Member", admin: "Admin", viewer: "Viewer" },
    googleDesc: "Calendar and contacts",
    githubDesc: "Repositories and pull requests",
    microsoftDesc: "Outlook and Teams",
  },
  ar: {
    title: "أعدّ حسابك",
    description: "بضع خطوات سريعة وتصبح جاهزًا. يمكنك تخطي الاختيارية وإكمالها لاحقًا.",
    welcome: "أهلًا بك",
    welcomeDescription: "هذا ما سنفعله معًا.",
    welcomeHeading: "أهلًا بك يا {name}",
    welcomeHeadingAnon: "أهلًا بك معنا",
    welcomeLead: "يستغرق الإعداد نحو ثلاث دقائق. تقدّمك محفوظ، فيمكنك المغادرة والعودة.",
    welcomeProfile: "عرّفنا بنفسك",
    welcomeWorkspace: "أنشئ مساحة عمل أو انضم إلى واحدة",
    welcomeInvite: "ادعُ فريقك",
    welcomePrefs: "اختر شكل التطبيق وسلوكه",
    welcomeConnect: "اربط أول أداة",
    resumed: "أهلًا بعودتك. حفظنا مكانك.",
    startOver: "ابدأ من جديد",
    profile: "ملفك الشخصي",
    profileDescription: "هكذا يراك زملاؤك.",
    photo: "الصورة الشخصية",
    fullName: "الاسم الكامل",
    nameRequired: "أدخل اسمك.",
    role: "دورك",
    rolePlaceholder: "اختر دورًا",
    workspace: "مساحة عملك",
    workspaceDescription: "أنشئ مساحة جديدة أو انضم إلى مساحة فريقك.",
    create: "أنشئ مساحة عمل",
    join: "انضم برمز",
    workspaceName: "اسم مساحة العمل",
    workspaceNameHint: "شركتك أو فريقك. يمكنك تغييره لاحقًا.",
    workspaceNameRequired: "أدخل اسم مساحة العمل.",
    inviteCode: "رمز الدعوة",
    inviteCodeHint: "اطلبه من مسؤول مساحة العمل. يبدو هكذا ABCD-1234.",
    inviteCodeRequired: "أدخل رمز الدعوة.",
    invite: "ادعُ زملاءك",
    inviteDescription: "يصلهم بريد فيه رابط الانضمام.",
    emails: "عناوين البريد",
    emailsHint: "اضغط Enter أو الفاصلة بعد كل عنوان. ولصق قائمة يعمل أيضًا.",
    emailsPlaceholder: "name@company.com",
    inviteRole: "ادعُهم بصفة",
    invalidEmail: "{email} ليس عنوان بريد صالحًا.",
    duplicateEmail: "{email} مضاف بالفعل.",
    invitesCount: "{count} دعوة",
    preferences: "التفضيلات",
    preferencesDescription: "غيّرها في أي وقت من الإعدادات.",
    language: "اللغة",
    theme: "المظهر",
    themeLight: "فاتح",
    themeDark: "داكن",
    themeSystem: "النظام",
    notifications: "الإشعارات",
    notifyEmail: "راسلني عن النشاط",
    notifyPush: "إشعارات فورية على هذا الجهاز",
    notifyDigest: "أرسل ملخصًا أسبوعيًا",
    integration: "اربط أداة",
    integrationDescription: "اختر أول مكان يأتي منه عملك.",
    connect: "اربط",
    connected: "مربوط",
    connectFailed: "تعذّر الربط. حاول مرة أخرى.",
    finish: "كل شيء جاهز",
    finishDescription: "راجع ما أنجزته.",
    review: "إعدادك",
    stepDone: "تم",
    stepSkipped: "تم تخطيها",
    stepOpen: "لم تتم",
    later: "يمكنك إكمال الخطوات المتخطاة من قائمة ابدأ.",
    doneTitle: "أنت جاهز",
    doneDescription: "تم إعداد مساحة عملك. ادخل وتجوّل.",
    optional: "اختياري",
    errorTitle: "أصلح هذه الحقول للمتابعة",
    failed: "حدث خطأ ما. حاول مرة أخرى.",
    roles: { design: "التصميم", engineering: "الهندسة", product: "المنتج", marketing: "التسويق", operations: "العمليات", other: "أخرى" },
    inviteRoles: { member: "عضو", admin: "مسؤول", viewer: "مشاهد" },
    googleDesc: "التقويم وجهات الاتصال",
    githubDesc: "المستودعات وطلبات الدمج",
    microsoftDesc: "Outlook وTeams",
  },
};

export type OnboardingFlowLabels = (typeof STRINGS)["en"];

export const fill = (template: string, values: Record<string, string | number>) => template.replace(/\{(\w+)\}/g, (_, k: string) => String(values[k] ?? ""));
