// Writes src/components/index.ts: one export line per component folder, so ports never edit a shared file.
import { readdirSync, existsSync, writeFileSync } from "node:fs";

const root = new URL("../src/components/", import.meta.url);
const names = readdirSync(root, { withFileTypes: true })
  .filter((d) => d.isDirectory() && existsSync(new URL(`${d.name}/index.ts`, root)))
  .map((d) => d.name)
  .sort();
writeFileSync(
  new URL("index.ts", root),
  `// Generated by scripts/gen-index.mjs. Do not edit.\n${names.map((n) => `export * from "./${n}";`).join("\n")}\n`,
);
console.log(`vue: ${names.length} components`);
