export const STRINGS = {
  en: {
    title: "Order tracking",
    order: "Order",
    placed: "Order placed",
    assigned: "Courier assigned",
    "picked-up": "Picked up",
    "on-the-way": "On the way",
    delivered: "Delivered",
    cancelled: "Order cancelled",
    failed: "Delivery failed",
    arrivingIn: "Arriving in",
    eta: "Estimated arrival",
    delivering: "Delivered",
    courier: "Your courier",
    call: "Call",
    message: "Message",
    reason: "Reason",
    steps: "Delivery progress",
    done: "done",
    current: "current step",
    stopped: "stopped here",
    pending: "not yet",
  },
  ar: {
    title: "تتبّع الطلب",
    order: "الطلب",
    placed: "تم استلام الطلب",
    assigned: "تم تعيين السائق",
    "picked-up": "تم استلام الطلب من المتجر",
    "on-the-way": "في الطريق إليك",
    delivered: "تم التوصيل",
    cancelled: "أُلغي الطلب",
    failed: "تعذّر التوصيل",
    arrivingIn: "يصل خلال",
    eta: "الوصول المتوقع",
    delivering: "تم التوصيل",
    courier: "سائقك",
    call: "اتصال",
    message: "رسالة",
    reason: "السبب",
    steps: "مراحل التوصيل",
    done: "تم",
    current: "المرحلة الحالية",
    stopped: "توقف هنا",
    pending: "لم يحدث بعد",
  },
};
export type DeliveryTrackerLabels = Partial<(typeof STRINGS)["en"]>;
