import { computed, type ComputedRef } from "vue";
import { useNasaq } from "../../provider";
import type { CheckResult, IncidentImpact, IncidentStatus, MonitorStatus, OverallStatus, UptimePeriod } from "./format";

export const UPTIME_STRINGS = {
  en: {
    title: "Uptime monitors",
    description: "Checks that run against your sites and services, and the incidents they raise.",
    add: "Add monitor",
    search: "Search monitors",
    table: "Monitors",
    period: "Period",
    periods: { "24h": "24 hours", "7d": "7 days", "30d": "30 days" } satisfies Record<UptimePeriod, string>,
    periodShort: { "24h": "24h", "7d": "7d", "30d": "30d" } satisfies Record<UptimePeriod, string>,
    cols: { monitor: "Monitor", status: "Status", uptime: "Uptime", history: "Recent checks", response: "Response", checked: "Last check" },
    status: { up: "Up", degraded: "Slow", down: "Down", paused: "Paused", unknown: "No data" } satisfies Record<MonitorStatus, string>,
    checkNames: { up: "Up", degraded: "Slow", down: "Down", none: "No check" } satisfies Record<CheckResult, string>,
    historyFor: (name: string, up: number, total: number) => `${name}: ${up} of ${total} recent checks were up`,
    uptimeFor: (pct: string, period: string) => `${pct} uptime over ${period}`,
    kinds: { http: "HTTP", tcp: "TCP port", ping: "Ping", keyword: "Keyword" } as Record<string, string>,
    every: (s: number) => (s % 60 === 0 ? `Every ${s / 60} min` : `Every ${s} s`),
    empty: "No monitors yet. Add one to start checking a site.",
    checkNow: "Check now",
    pause: "Pause",
    resume: "Resume",
    edit: "Edit",
    remove: "Delete",
    deleteTitle: (name: string) => `Delete ${name}?`,
    deleteBody: "Checks stop and its uptime history is removed.",
    cancel: "Cancel",
    dialogNew: "New monitor",
    dialogEdit: "Edit monitor",
    dialogBody: "Checks the address at a fixed interval and raises an incident after failures in a row.",
    name: "Name",
    target: "Address",
    targetHint: "A URL for HTTP and keyword monitors, or host:port for TCP.",
    kind: "Type",
    interval: "Check every",
    intervals: { 30: "30 seconds", 60: "1 minute", 300: "5 minutes", 900: "15 minutes" } as Record<number, string>,
    required: "This field is required.",
    save: "Save monitor",
    incidents: "Incidents",
    incidentsEmpty: "No incidents in this period.",
    open: "Open",
    resolved: "Resolved",
    incidentStatus: { investigating: "Investigating", identified: "Identified", monitoring: "Monitoring", resolved: "Resolved" } satisfies Record<IncidentStatus, string>,
    impact: { minor: "Minor", major: "Major", maintenance: "Maintenance" } satisfies Record<IncidentImpact, string>,
    duration: { d: "d", h: "h", m: "min" },
    lasted: (d: string) => `Lasted ${d}`,
    started: "Started",
    updates: "Updates",
    genericError: "Something went wrong. Try again.",
    overall: { operational: "All systems operational", degraded: "Degraded performance", "partial-outage": "Partial outage", "major-outage": "Major outage", maintenance: "Maintenance in progress" } satisfies Record<OverallStatus, string>,
  },
  ar: {
    title: "مراقبة التشغيل",
    description: "فحوص تعمل على مواقعك وخدماتك، والحوادث التي تنتج عنها.",
    add: "إضافة مراقب",
    search: "بحث في المراقبين",
    table: "المراقبون",
    period: "الفترة",
    periods: { "24h": "24 ساعة", "7d": "7 أيام", "30d": "30 يومًا" } satisfies Record<UptimePeriod, string>,
    periodShort: { "24h": "24س", "7d": "7أ", "30d": "30ي" } satisfies Record<UptimePeriod, string>,
    cols: { monitor: "المراقب", status: "الحالة", uptime: "وقت التشغيل", history: "آخر الفحوص", response: "الاستجابة", checked: "آخر فحص" },
    status: { up: "يعمل", degraded: "بطيء", down: "متوقف", paused: "موقوف مؤقتًا", unknown: "لا بيانات" } satisfies Record<MonitorStatus, string>,
    checkNames: { up: "يعمل", degraded: "بطيء", down: "متوقف", none: "لا فحص" } satisfies Record<CheckResult, string>,
    historyFor: (name: string, up: number, total: number) => `${name}: ${up} من ${total} فحوص حديثة كانت ناجحة`,
    uptimeFor: (pct: string, period: string) => `${pct} وقت تشغيل خلال ${period}`,
    kinds: { http: "HTTP", tcp: "منفذ TCP", ping: "Ping", keyword: "كلمة مفتاحية" } as Record<string, string>,
    every: (s: number) => (s % 60 === 0 ? `كل ${s / 60} دقيقة` : `كل ${s} ثانية`),
    empty: "لا يوجد مراقبون بعد. أضف واحدًا لبدء فحص موقع.",
    checkNow: "افحص الآن",
    pause: "إيقاف مؤقت",
    resume: "استئناف",
    edit: "تعديل",
    remove: "حذف",
    deleteTitle: (name: string) => `حذف ${name}؟`,
    deleteBody: "تتوقف الفحوص ويُحذف سجل وقت التشغيل.",
    cancel: "إلغاء",
    dialogNew: "مراقب جديد",
    dialogEdit: "تعديل المراقب",
    dialogBody: "يفحص العنوان بفاصل ثابت ويرفع حادثة بعد عدة إخفاقات متتالية.",
    name: "الاسم",
    target: "العنوان",
    targetHint: "رابط لمراقبات HTTP والكلمات المفتاحية، أو host:port لمراقبة TCP.",
    kind: "النوع",
    interval: "الفحص كل",
    intervals: { 30: "30 ثانية", 60: "دقيقة", 300: "5 دقائق", 900: "15 دقيقة" } as Record<number, string>,
    required: "هذا الحقل مطلوب.",
    save: "حفظ المراقب",
    incidents: "الحوادث",
    incidentsEmpty: "لا حوادث في هذه الفترة.",
    open: "مفتوحة",
    resolved: "محلولة",
    incidentStatus: { investigating: "قيد التحقق", identified: "تم تحديد السبب", monitoring: "تحت المراقبة", resolved: "تم الحل" } satisfies Record<IncidentStatus, string>,
    impact: { minor: "طفيف", major: "كبير", maintenance: "صيانة" } satisfies Record<IncidentImpact, string>,
    duration: { d: "ي", h: "س", m: "د" },
    lasted: (d: string) => `استمرت ${d}`,
    started: "بدأت",
    updates: "التحديثات",
    genericError: "حدث خطأ ما. حاول مرة أخرى.",
    overall: { operational: "كل الأنظمة تعمل", degraded: "أداء متدهور", "partial-outage": "انقطاع جزئي", "major-outage": "انقطاع كبير", maintenance: "صيانة جارية" } satisfies Record<OverallStatus, string>,
  },
};

export type UptimeStrings = (typeof UPTIME_STRINGS)["en"];
export type UptimeMonitorsLabels = Partial<UptimeStrings>;

/** The strings for the current Nasaq locale, with the caller's overrides on top. */
export function useUptimeStrings(labels: () => UptimeMonitorsLabels | undefined): ComputedRef<UptimeStrings> {
  const nasaq = useNasaq();
  return computed(() => ({ ...UPTIME_STRINGS[nasaq.locale.value.startsWith("ar") ? "ar" : "en"], ...labels() }));
}
