import type { CertStatus } from "./format";

export const CERT_STRINGS = {
  en: {
    title: "TLS certificates",
    description: "When each certificate expires, so none lapses unnoticed.",
    table: "Certificates",
    search: "Search hosts",
    host: "Host",
    issuer: "Issuer",
    expires: "Expires",
    left: "Days left",
    status: { valid: "Valid", expiring: "Expiring soon", critical: "Expires very soon", expired: "Expired", error: "Check failed" } satisfies Record<CertStatus, string>,
    leftLabel: (d: number | null) => (d === null ? "Unknown" : d < 0 ? `Expired ${-d} d ago` : d === 0 ? "Today" : `${d} d`),
    leftAria: (host: string, d: number | null) => (d === null ? `${host}: could not be checked` : d < 0 ? `${host}: expired ${-d} days ago` : `${host}: ${d} days left`),
    autoRenew: "Auto renew",
    manual: "Manual",
    recheck: "Check again",
    renew: "Renew now",
    remove: "Stop monitoring",
    removeTitle: (h: string) => `Stop monitoring ${h}?`,
    removeBody: "The certificate itself is not touched. You just stop getting alerts about it.",
    cancel: "Cancel",
    add: "Add host",
    addLabel: "Host to monitor",
    invalid: "Enter a hostname like app.example.com.",
    empty: "No certificates monitored yet. Add a host to check its TLS certificate.",
    summary: (n: number, e: number) => `${n} monitored, ${e} need attention`,
    genericError: "Something went wrong. Try again.",
  },
  ar: {
    title: "شهادات TLS",
    description: "موعد انتهاء كل شهادة، حتى لا تنتهي دون أن يلاحظ أحد.",
    table: "الشهادات",
    search: "بحث في المضيفين",
    host: "المضيف",
    issuer: "الجهة المصدرة",
    expires: "تنتهي",
    left: "الأيام المتبقية",
    status: { valid: "صالحة", expiring: "تنتهي قريبًا", critical: "تنتهي خلال أيام", expired: "منتهية", error: "فشل الفحص" } satisfies Record<CertStatus, string>,
    leftLabel: (d: number | null) => (d === null ? "غير معروف" : d < 0 ? `منتهية منذ ${-d} ي` : d === 0 ? "اليوم" : `${d} ي`),
    leftAria: (host: string, d: number | null) => (d === null ? `${host}: تعذّر الفحص` : d < 0 ? `${host}: منتهية منذ ${-d} يومًا` : `${host}: متبقٍ ${d} يومًا`),
    autoRenew: "تجديد تلقائي",
    manual: "يدوي",
    recheck: "افحص مجددًا",
    renew: "جدّد الآن",
    remove: "إيقاف المراقبة",
    removeTitle: (h: string) => `إيقاف مراقبة ${h}؟`,
    removeBody: "لا تتأثر الشهادة نفسها. فقط تتوقف التنبيهات الخاصة بها.",
    cancel: "إلغاء",
    add: "إضافة مضيف",
    addLabel: "المضيف المراد مراقبته",
    invalid: "أدخل اسم مضيف مثل app.example.com.",
    empty: "لا توجد شهادات مراقبة بعد. أضف مضيفًا لفحص شهادة TLS الخاصة به.",
    summary: (n: number, e: number) => `${n} مراقبة، ${e} تحتاج انتباهًا`,
    genericError: "حدث خطأ ما. حاول مرة أخرى.",
  },
};
export type CertMonitorLabels = Partial<(typeof CERT_STRINGS)["en"]>;
