import { computed } from "vue";
import { useNasaq } from "../../provider";
import type { IssuePriority, IssueType } from "./issue-logic";

/** Every built-in word of IssueView, IssueProperties and the pickers: the view, then the names of priorities and types, then the properties. */
export const ISSUE_VIEW_STRINGS = {
  en: {
    back: "Back",
    close: "Close",
    copyKey: "Copy issue key",
    description: "Description",
    noDescription: "No description yet.",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    editTitle: "Edit title",
    titleEmpty: "A title is required",
    subIssues: "Sub-issues",
    subIssuePlaceholder: "Add a sub-issue",
    addSubIssue: "Add",
    noSubIssues: "No sub-issues",
    open: "Open",
    copyKeyAction: "Copy key",
    actions: "Actions",
    development: "Development",
    comments: "Comments",
    activity: "Activity",
    time: "Time",
    ai: "AI cost",
    timerRunning: "Timer running",
    created: "Created",
    updated: "Updated",
    loading: "Loading",
    details: "Details",
    priorities: { urgent: "Urgent", high: "High", medium: "Medium", low: "Low", none: "No priority" } satisfies Record<IssuePriority, string>,
    types: { bug: "Bug", feature: "Feature", improvement: "Improvement", task: "Task", chore: "Chore" } satisfies Record<IssueType, string>,
    none: "None",
    unassigned: "Unassigned",
    noParent: "No parent",
    noDue: "No due date",
    noEstimate: "No estimate",
    noLabels: "No labels",
    overdue: "Overdue",
    dueToday: "Due today",
    dueSoon: "Due soon",
    status: "Status",
    priority: "Priority",
    type: "Type",
    assignee: "Assignee",
    labels: "Labels",
    estimate: "Estimate",
    estimateHint: "Hours, for example 2 or 1h 30m",
    due: "Due date",
    project: "Project",
    parent: "Parent",
    logged: (v: string) => `${v} logged`,
    over: "Over the estimate",
    pickLabels: "Choose labels",
    saving: "Saving…",
  },
  ar: {
    back: "رجوع",
    close: "إغلاق",
    copyKey: "نسخ رمز المهمة",
    description: "الوصف",
    noDescription: "لا يوجد وصف بعد.",
    edit: "تعديل",
    save: "حفظ",
    cancel: "إلغاء",
    editTitle: "تعديل العنوان",
    titleEmpty: "العنوان مطلوب",
    subIssues: "المهام الفرعية",
    subIssuePlaceholder: "أضف مهمة فرعية",
    addSubIssue: "إضافة",
    noSubIssues: "لا مهام فرعية",
    open: "فتح",
    copyKeyAction: "نسخ الرمز",
    actions: "إجراءات",
    development: "التطوير",
    comments: "التعليقات",
    activity: "النشاط",
    time: "الوقت",
    ai: "تكلفة الذكاء الاصطناعي",
    timerRunning: "المؤقت يعمل",
    created: "أُنشئت",
    updated: "حُدّثت",
    loading: "جارٍ التحميل",
    details: "التفاصيل",
    priorities: { urgent: "عاجلة", high: "عالية", medium: "متوسطة", low: "منخفضة", none: "بلا أولوية" } satisfies Record<IssuePriority, string>,
    types: { bug: "خطأ", feature: "ميزة", improvement: "تحسين", task: "مهمة", chore: "صيانة" } satisfies Record<IssueType, string>,
    none: "لا شيء",
    unassigned: "غير مسند",
    noParent: "بلا أصل",
    noDue: "بلا موعد",
    noEstimate: "بلا تقدير",
    noLabels: "بلا وسوم",
    overdue: "متأخرة",
    dueToday: "تستحق اليوم",
    dueSoon: "تستحق قريبًا",
    status: "الحالة",
    priority: "الأولوية",
    type: "النوع",
    assignee: "المسؤول",
    labels: "الوسوم",
    estimate: "التقدير",
    estimateHint: "ساعات، مثل 2 أو 1h 30m",
    due: "موعد الاستحقاق",
    project: "المشروع",
    parent: "الأصل",
    logged: (v: string) => `سُجّل ${v}`,
    over: "تجاوز التقدير",
    pickLabels: "اختر الوسوم",
    saving: "جارٍ الحفظ…",
  },
};

export type IssueViewLabels = Partial<typeof ISSUE_VIEW_STRINGS.en>;
export type IssueViewStrings = typeof ISSUE_VIEW_STRINGS.en;

/** The merged strings (locale + overrides) and whether the locale is Arabic. */
export function useIssueStrings(labels: () => IssueViewLabels | undefined) {
  const nq = useNasaq();
  const ar = computed(() => nq.locale.value.startsWith("ar"));
  const t = computed(() => ({ ...ISSUE_VIEW_STRINGS[ar.value ? "ar" : "en"], ...labels() }) as IssueViewStrings);
  return { ar, t, locale: computed(() => nq.locale.value) };
}
