export const STRINGS = {
  en: {
    export: "Export",
    title: "Export data",
    description: "Choose a format, the rows and the columns to include.",
    format: "Format",
    scope: "Rows",
    columns: "Columns",
    selectAllColumns: "All columns",
    csv: "CSV",
    csvHint: "Plain text, opens anywhere",
    xlsx: "Excel",
    xlsxHint: "A .xlsx workbook",
    json: "JSON",
    jsonHint: "Records for developers",
    pdf: "PDF",
    pdfHint: "A formatted document",
    selected: "Selected rows",
    filtered: "Current filter",
    all: "All rows",
    rowCount: (n: string) => `${n} rows`,
    rowCountOne: "1 row",
    cancel: "Cancel",
    close: "Close",
    done: "Done",
    run: "Export",
    preparing: "Preparing the file…",
    loadingRows: "Loading rows…",
    building: (pct: string) => `Building the file… ${pct}`,
    ready: (name: string) => `${name} is ready`,
    downloadAgain: "Download again",
    failed: "The export failed",
    retry: "Try again",
    noColumns: "Choose at least one column.",
    noRows: "There are no rows to export.",
    menuMore: "Export options…",
    menuLabel: "Export data",
    cancelled: "Export cancelled",
  },
  ar: {
    export: "تصدير",
    title: "تصدير البيانات",
    description: "اختر الصيغة والصفوف والأعمدة المراد تضمينها.",
    format: "الصيغة",
    scope: "الصفوف",
    columns: "الأعمدة",
    selectAllColumns: "كل الأعمدة",
    csv: "CSV",
    csvHint: "نص عادي يُفتح في أي مكان",
    xlsx: "Excel",
    xlsxHint: "مصنّف بصيغة xlsx",
    json: "JSON",
    jsonHint: "سجلات للمطوّرين",
    pdf: "PDF",
    pdfHint: "مستند منسّق",
    selected: "الصفوف المحددة",
    filtered: "نتيجة التصفية الحالية",
    all: "كل الصفوف",
    rowCount: (n: string) => `${n} صف`,
    rowCountOne: "صف واحد",
    cancel: "إلغاء",
    close: "إغلاق",
    done: "تم",
    run: "تصدير",
    preparing: "جارٍ تجهيز الملف…",
    loadingRows: "جارٍ تحميل الصفوف…",
    building: (pct: string) => `جارٍ إنشاء الملف… ${pct}`,
    ready: (name: string) => `الملف ${name} جاهز`,
    downloadAgain: "تنزيل مرة أخرى",
    failed: "تعذّر التصدير",
    retry: "إعادة المحاولة",
    noColumns: "اختر عمودًا واحدًا على الأقل.",
    noRows: "لا توجد صفوف للتصدير.",
    menuMore: "خيارات التصدير…",
    menuLabel: "تصدير البيانات",
    cancelled: "أُلغي التصدير",
  },
};
export const strings = (locale: string) => STRINGS[locale.startsWith("ar") ? "ar" : "en"];

export type Strings = typeof STRINGS.en;
export type Labels = Partial<Strings>;
