// The strings of SchemaForm, English and Arabic. Any of them can be overridden with `labels`.

export const SCHEMA_FORM_STRINGS = {
  en: {
    submit: "Save",
    saving: "Saving…",
    reset: "Reset",
    select: "Select…",
    saved: "Saved.",
    failed: "Could not save.",
    fix: (n: number) => (n === 1 ? "Fix 1 field to continue." : `Fix ${n} fields to continue.`),
    optional: "Optional",
    add: (name: string) => `Add ${name}`,
    remove: (name: string) => `Remove ${name}`,
    moveUp: (name: string) => `Move ${name} up`,
    moveDown: (name: string) => `Move ${name} down`,
    drag: (name: string) => `Drag to reorder ${name}`,
    collapse: (name: string) => `Collapse ${name}`,
    expand: (name: string) => `Expand ${name}`,
    expandAll: "Expand all",
    collapseAll: "Collapse all",
    count: (n: string) => `${n} items`,
    countMax: (n: string, max: string) => `${n} of ${max} items`,
    empty: (name: string) => `No ${name} yet.`,
    minReached: (n: string) => `At least ${n} required.`,
    maxReached: (n: string) => `Limit of ${n} reached.`,
    issues: (n: string) => (n === "1" ? "1 issue" : `${n} issues`),
    removeTitle: (name: string) => `Remove ${name}?`,
    removeBody: "It has data that will be lost.",
    removeConfirm: "Remove",
    cancel: "Cancel",
    unmatched: "The server reported problems that do not belong to a field.",
    goTo: "Fields to fix",
  },
  ar: {
    submit: "حفظ",
    saving: "جارٍ الحفظ…",
    reset: "إعادة ضبط",
    select: "اختر…",
    saved: "تم الحفظ.",
    failed: "تعذر الحفظ.",
    fix: (n: number) => (n === 1 ? "صحّح حقلًا واحدًا للمتابعة." : n === 2 ? "صحّح حقلين للمتابعة." : `صحّح ${n} حقول للمتابعة.`),
    optional: "اختياري",
    add: (name: string) => `إضافة ${name}`,
    remove: (name: string) => `حذف ${name}`,
    moveUp: (name: string) => `نقل ${name} لأعلى`,
    moveDown: (name: string) => `نقل ${name} لأسفل`,
    drag: (name: string) => `اسحب لإعادة ترتيب ${name}`,
    collapse: (name: string) => `طيّ ${name}`,
    expand: (name: string) => `توسيع ${name}`,
    expandAll: "توسيع الكل",
    collapseAll: "طيّ الكل",
    count: (n: string) => `${n} عناصر`,
    countMax: (n: string, max: string) => `${n} من ${max} عناصر`,
    empty: (name: string) => `لا يوجد ${name} بعد.`,
    minReached: (n: string) => `مطلوب ${n} على الأقل.`,
    maxReached: (n: string) => `تم بلوغ الحد الأقصى ${n}.`,
    issues: (n: string) => (n === "1" ? "مشكلة واحدة" : `${n} مشكلات`),
    removeTitle: (name: string) => `حذف ${name}؟`,
    removeBody: "يحتوي على بيانات ستفقد.",
    removeConfirm: "حذف",
    cancel: "إلغاء",
    unmatched: "أبلغ الخادم عن مشكلات لا تخص حقلًا محددًا.",
    goTo: "حقول تحتاج تصحيحًا",
  },
};
export type SchemaFormStrings = (typeof SCHEMA_FORM_STRINGS)["en"];
