import type { RuleOperator } from "./rule-model";

export const RULE_STRINGS = {
  en: {
    summary: "This rule",
    when: "When",
    whenHelp: "The event that starts the rule.",
    chooseEvent: "Choose an event",
    ifTitle: "If",
    ifHelp: "Only continue when these conditions hold. Leave empty to always continue.",
    thenTitle: "Then",
    thenHelp: "What to do, in order.",
    matchAll: "All of these",
    matchAny: "Any of these",
    match: "Match",
    addCondition: "Add condition",
    addGroup: "Add group",
    removeGroup: "Remove group",
    removeCondition: "Remove condition",
    groupLabel: (join: string) => `Group: ${join}`,
    noConditions: "No conditions: the rule always continues.",
    field: "Field",
    operator: "Operator",
    value: "Value",
    chooseField: "Choose a field",
    yes: "True",
    no: "False",
    actions: "Actions",
    addAction: "Add action",
    actionType: "Action",
    chooseAction: "Choose an action",
    actionRow: (n: string) => `Action ${n}`,
    actionsEmpty: "No actions yet.",
    problems: (n: string) => `${n} to fix`,
    issueEvent: "Choose the event that starts the rule",
    issueActions: "Add at least one action",
    issueField: "A condition has no field",
    issueValue: "A condition has no value",
    issueActionField: (field: string) => `An action is missing "${field}"`,
    required: "Required",
    sentence: {
      when: (e: string) => `When ${e}`,
      ifWord: "if",
      then: "then",
      noConditions: "always",
      and: "and",
      or: "or",
    },
    ops: { is: "is", isNot: "is not", contains: "contains", startsWith: "starts with", isEmpty: "is empty", isNotEmpty: "is not empty", gt: "is greater than", gte: "is at least", lt: "is less than", lte: "is at most" } as Record<RuleOperator, string>,
  },
  ar: {
    summary: "هذه القاعدة",
    when: "عندما",
    whenHelp: "الحدث الذي يبدأ القاعدة.",
    chooseEvent: "اختر حدثًا",
    ifTitle: "إذا",
    ifHelp: "تابع فقط عندما تتحقق هذه الشروط. اتركها فارغة للمتابعة دائمًا.",
    thenTitle: "إذن",
    thenHelp: "ما يجب فعله، بالترتيب.",
    matchAll: "كل هذه",
    matchAny: "أي من هذه",
    match: "المطابقة",
    addCondition: "إضافة شرط",
    addGroup: "إضافة مجموعة",
    removeGroup: "حذف المجموعة",
    removeCondition: "حذف الشرط",
    groupLabel: (join: string) => `مجموعة: ${join}`,
    noConditions: "لا شروط: تتابع القاعدة دائمًا.",
    field: "الحقل",
    operator: "المعامل",
    value: "القيمة",
    chooseField: "اختر حقلًا",
    yes: "صحيح",
    no: "خطأ",
    actions: "الإجراءات",
    addAction: "إضافة إجراء",
    actionType: "الإجراء",
    chooseAction: "اختر إجراءً",
    actionRow: (n: string) => `الإجراء ${n}`,
    actionsEmpty: "لا إجراءات بعد.",
    problems: (n: string) => `${n} للإصلاح`,
    issueEvent: "اختر الحدث الذي يبدأ القاعدة",
    issueActions: "أضف إجراءً واحدًا على الأقل",
    issueField: "شرط بلا حقل",
    issueValue: "شرط بلا قيمة",
    issueActionField: (field: string) => `إجراء ينقصه "${field}"`,
    required: "مطلوب",
    sentence: {
      when: (e: string) => `عندما ${e}`,
      ifWord: "وإذا",
      then: "فـ",
      noConditions: "دائمًا",
      and: "و",
      or: "أو",
    },
    ops: { is: "يساوي", isNot: "لا يساوي", contains: "يحتوي", startsWith: "يبدأ بـ", isEmpty: "فارغ", isNotEmpty: "غير فارغ", gt: "أكبر من", gte: "لا يقل عن", lt: "أصغر من", lte: "لا يزيد عن" } as Record<RuleOperator, string>,
  },
};

export type RuleBuilderLabels = Partial<(typeof RULE_STRINGS)["en"]>;

export const ruleStrings = (locale: string) => RULE_STRINGS[locale.startsWith("ar") ? "ar" : "en"];
