import { computed, type ComputedRef } from "vue";
import { useNasaq } from "../../provider";

export const TIME_TRACKER_STRINGS = {
  en: {
    timer: "Timer",
    project: "Project",
    task: "Task",
    noTask: "No task",
    pickProject: "Choose a project",
    pickTask: "Choose a task",
    note: "What are you working on?",
    start: "Start timer",
    stop: "Stop timer",
    running: "Timer running",
    stopped: "Timer stopped",
    needProject: "Choose a project to start the timer.",
    failed: "That did not go through. Try again.",
    entries: "Time entries",
    addEntry: "Add time",
    edit: "Edit entry",
    remove: "Delete entry",
    emptyTitle: "No time logged yet",
    emptyDescription: "Start the timer or add time by hand.",
    dayTotal: "Day total",
    entryTitle: "Add time",
    editTitle: "Edit time entry",
    entryDescription: "Log time you already spent.",
    date: "Date",
    duration: "Duration",
    durationHint: "For example 1:30, 1.5h or 90m.",
    invalidDuration: "Enter a duration such as 1:30 or 45m.",
    tooLong: "An entry cannot be longer than 24 hours.",
    needProjectField: "Choose a project.",
    save: "Save",
    cancel: "Cancel",
    timesheet: "Timesheet",
    day: "Day",
    week: "Week",
    view: "Timesheet view",
    previous: "Previous",
    next: "Next",
    today: "Today",
    total: "Total",
    row: "Project and task",
    gridLabel: "Timesheet grid, hours per day",
    emptyGrid: "No time logged in this period.",
    hoursShort: "h",
  },
  ar: {
    timer: "المؤقّت",
    project: "المشروع",
    task: "المهمة",
    noTask: "بدون مهمة",
    pickProject: "اختر مشروعًا",
    pickTask: "اختر مهمة",
    note: "على ماذا تعمل؟",
    start: "ابدأ المؤقّت",
    stop: "أوقف المؤقّت",
    running: "المؤقّت يعمل",
    stopped: "توقّف المؤقّت",
    needProject: "اختر مشروعًا لبدء المؤقّت.",
    failed: "لم تتم العملية. حاول مرة أخرى.",
    entries: "سجلّ الوقت",
    addEntry: "إضافة وقت",
    edit: "تعديل السجل",
    remove: "حذف السجل",
    emptyTitle: "لا يوجد وقت مسجّل بعد",
    emptyDescription: "ابدأ المؤقّت أو أضف وقتًا يدويًا.",
    dayTotal: "مجموع اليوم",
    entryTitle: "إضافة وقت",
    editTitle: "تعديل سجل الوقت",
    entryDescription: "سجّل وقتًا قضيته بالفعل.",
    date: "التاريخ",
    duration: "المدة",
    durationHint: "مثل 1:30 أو 1.5h أو 90m.",
    invalidDuration: "أدخل مدة مثل 1:30 أو 45m.",
    tooLong: "لا يمكن أن يتجاوز السجل 24 ساعة.",
    needProjectField: "اختر مشروعًا.",
    save: "حفظ",
    cancel: "إلغاء",
    timesheet: "الجدول الزمني",
    day: "يوم",
    week: "أسبوع",
    view: "عرض الجدول الزمني",
    previous: "السابق",
    next: "التالي",
    today: "اليوم",
    total: "المجموع",
    row: "المشروع والمهمة",
    gridLabel: "شبكة الجدول الزمني، الساعات لكل يوم",
    emptyGrid: "لا يوجد وقت مسجّل في هذه الفترة.",
    hoursShort: "س",
  },
};

export type TimeTrackerLabels = Partial<(typeof TIME_TRACKER_STRINGS)["en"]>;

export function useTimeTrackerStrings(labels?: () => TimeTrackerLabels | undefined): ComputedRef<(typeof TIME_TRACKER_STRINGS)["en"]> {
  const nq = useNasaq();
  return computed(() => ({ ...TIME_TRACKER_STRINGS[nq.locale.value.startsWith("ar") ? "ar" : "en"], ...labels?.() }));
}
