export const STRINGS = {
  en: {
    tracking: "Order progress",
    placed: "Order placed",
    paid: "Payment confirmed",
    confirmed: "Order confirmed",
    shipped: "Shipped",
    "out-for-delivery": "Out for delivery",
    delivered: "Delivered",
    done: "Done",
    current: "In progress",
    upcoming: "Next",
    skipped: "Did not happen",
    partlyShipped: "Part of this order has shipped",
    cancelled: "Order cancelled",
    refunded: "Order refunded",
    returned: "Order returned",
    "partially-refunded": "Partly refunded",
    trackShipment: "Track shipment",
    carrier: "Carrier",
    trackingNumber: "Tracking number",
    activity: "Activity",
    noActivity: "Nothing has happened to this order yet.",
    addNote: "Add a note",
    notePlaceholder: "Only your team can see notes.",
    saveNote: "Add note",
    internal: "Internal",
    by: "by",
    cod: "Pay the courier when it arrives",
  },
  ar: {
    tracking: "تقدّم الطلب",
    placed: "تم إنشاء الطلب",
    paid: "تأكيد الدفع",
    confirmed: "تأكيد الطلب",
    shipped: "تم الشحن",
    "out-for-delivery": "في الطريق إليك",
    delivered: "تم التسليم",
    done: "تمّ",
    current: "جارٍ الآن",
    upcoming: "التالي",
    skipped: "لم يحدث",
    partlyShipped: "تم شحن جزء من هذا الطلب",
    cancelled: "تم إلغاء الطلب",
    refunded: "تم استرداد الطلب",
    returned: "تم إرجاع الطلب",
    "partially-refunded": "استرداد جزئي",
    trackShipment: "تتبّع الشحنة",
    carrier: "شركة الشحن",
    trackingNumber: "رقم التتبع",
    activity: "النشاط",
    noActivity: "لم يحدث شيء لهذا الطلب بعد.",
    addNote: "أضف ملاحظة",
    notePlaceholder: "الملاحظات يراها فريقك فقط.",
    saveNote: "إضافة ملاحظة",
    internal: "داخلية",
    by: "بواسطة",
    cod: "ادفع للمندوب عند الوصول",
  },
} as const;

type Strings = { [K in keyof (typeof STRINGS)["en"]]: string };
export type StoreOrderTimelineLabels = Partial<Strings>;
export type { Strings as StoreOrderTimelineStrings };
