// Strings of the user management suite, English and Arabic. Pass `labels` to override any of them.
export const ADMIN_USERS_STRINGS = {
  en: {
    table: "Users",
    search: "Search name or email…",
    addUser: "Add user",
    total: "Total users",
    active: "Active",
    unverified: "Unverified",
    disabled: "Disabled",
    user: "User",
    roles: "Roles",
    status: "Status",
    email: "Email",
    workspace: "Workspace",
    lastActive: "Last active",
    joined: "Joined",
    never: "Never",
    verified: "Verified",
    notVerified: "Unverified",
    statusActive: "Active",
    statusDisabled: "Disabled",
    statusInvited: "Invited",
    noRoles: "No roles",
    you: "You",
    verify: "Verify email",
    editRoles: "Edit roles…",
    resetPassword: "Reset password…",
    impersonate: "Impersonate…",
    disable: "Disable account…",
    enable: "Enable account",
    selectedVerify: "Verify",
    selectedDisable: "Disable",
    empty: "No users yet",
    emptyHint: "Add the first user to get started.",
    // outcomes
    verifiedOk: (name: string) => `${name} was verified.`,
    enabledOk: (name: string) => `${name} was enabled.`,
    disabledOk: (name: string) => `${name} was disabled.`,
    resetOk: (name: string) => `A reset link was sent to ${name}.`,
    impersonateOk: (name: string) => `You are now signed in as ${name}.`,
    rolesOk: (name: string) => `Roles updated for ${name}.`,
    addedOk: (name: string) => `${name} was added.`,
    bulkOk: (n: string) => `${n} users updated.`,
    failed: "That did not work. Try again.",
    dismiss: "Dismiss",
    // confirm dialogs
    cancel: "Cancel",
    disableTitle: (name: string) => `Disable ${name}?`,
    disableBody: "They are signed out at once and cannot sign in until you enable the account again. Their data is kept.",
    disableConfirm: "Disable account",
    resetTitle: (name: string) => `Reset password for ${name}?`,
    resetBody: "We email them a link to choose a new password. Their current password stops working once they use it.",
    resetConfirm: "Send reset link",
    impersonateTitle: (name: string) => `Impersonate ${name}?`,
    impersonateBody: "You will see the app exactly as they do. Everything you do is recorded in the audit log under both names.",
    impersonateConfirm: "Start impersonating",
    // add dialog
    addTitle: "Add a user",
    addBody: "They get an email to set a password, unless you mark the address as verified and skip the invite.",
    name: "Full name",
    emailField: "Email address",
    rolesField: "Roles",
    sendInvite: "Send an invitation email",
    sendInviteHint: "They set their own password.",
    markVerified: "Mark the email as verified",
    markVerifiedHint: "Skips the confirmation step.",
    create: "Add user",
    nameRequired: "Enter a name.",
    emailRequired: "Enter an email address.",
    emailInvalid: "Enter a valid email address.",
    rolesRequired: "Choose at least one role.",
    password: "Password (optional)",
    passwordHint: "Leave it empty to let them set their own.",
    passwordShort: (min: string) => `Use at least ${min} characters.`,
    rolesFreePlaceholder: "Type a role and press Enter",
    rolesFreeHint: "For example admin, editor or billing.",
    // roles dialog
    rolesTitle: (name: string) => `Roles for ${name}`,
    rolesBody: "Choose what this person can do. Changes apply on their next request.",
    saveRoles: "Save roles",
  },
  ar: {
    table: "المستخدمون",
    search: "ابحث بالاسم أو البريد…",
    addUser: "إضافة مستخدم",
    total: "إجمالي المستخدمين",
    active: "نشط",
    unverified: "غير موثّق",
    disabled: "معطّل",
    user: "المستخدم",
    roles: "الأدوار",
    status: "الحالة",
    email: "البريد",
    workspace: "مساحة العمل",
    lastActive: "آخر نشاط",
    joined: "تاريخ الانضمام",
    never: "أبدًا",
    verified: "موثّق",
    notVerified: "غير موثّق",
    statusActive: "نشط",
    statusDisabled: "معطّل",
    statusInvited: "مدعو",
    noRoles: "بلا أدوار",
    you: "أنت",
    verify: "توثيق البريد",
    editRoles: "تعديل الأدوار…",
    resetPassword: "إعادة تعيين كلمة المرور…",
    impersonate: "انتحال الصفة…",
    disable: "تعطيل الحساب…",
    enable: "تفعيل الحساب",
    selectedVerify: "توثيق",
    selectedDisable: "تعطيل",
    empty: "لا يوجد مستخدمون بعد",
    emptyHint: "أضف أول مستخدم للبدء.",
    verifiedOk: (name: string) => `تم توثيق ${name}.`,
    enabledOk: (name: string) => `تم تفعيل ${name}.`,
    disabledOk: (name: string) => `تم تعطيل ${name}.`,
    resetOk: (name: string) => `أُرسل رابط إعادة التعيين إلى ${name}.`,
    impersonateOk: (name: string) => `سجّلت الدخول الآن بصفة ${name}.`,
    rolesOk: (name: string) => `تم تحديث أدوار ${name}.`,
    addedOk: (name: string) => `تمت إضافة ${name}.`,
    bulkOk: (n: string) => `تم تحديث ${n} مستخدمين.`,
    failed: "لم تنجح العملية. حاول مرة أخرى.",
    dismiss: "تجاهل",
    cancel: "إلغاء",
    disableTitle: (name: string) => `تعطيل ${name}؟`,
    disableBody: "سيُسجَّل خروجه فورًا ولن يستطيع الدخول حتى تعيد تفعيل الحساب. تبقى بياناته محفوظة.",
    disableConfirm: "تعطيل الحساب",
    resetTitle: (name: string) => `إعادة تعيين كلمة مرور ${name}؟`,
    resetBody: "نرسل له رابطًا لاختيار كلمة مرور جديدة. تتوقف كلمة المرور الحالية عن العمل بمجرد استخدامه للرابط.",
    resetConfirm: "إرسال رابط إعادة التعيين",
    impersonateTitle: (name: string) => `انتحال صفة ${name}؟`,
    impersonateBody: "سترى التطبيق كما يراه تمامًا. كل ما تفعله يُسجَّل في سجل التدقيق باسمكما معًا.",
    impersonateConfirm: "بدء انتحال الصفة",
    addTitle: "إضافة مستخدم",
    addBody: "يصله بريد لتعيين كلمة المرور، إلا إذا وثّقت العنوان وتخطيت الدعوة.",
    name: "الاسم الكامل",
    emailField: "البريد الإلكتروني",
    rolesField: "الأدوار",
    sendInvite: "إرسال بريد دعوة",
    sendInviteHint: "يعيّن كلمة مروره بنفسه.",
    markVerified: "اعتبار البريد موثّقًا",
    markVerifiedHint: "يتخطى خطوة التأكيد.",
    create: "إضافة المستخدم",
    nameRequired: "أدخل الاسم.",
    emailRequired: "أدخل البريد الإلكتروني.",
    emailInvalid: "أدخل بريدًا إلكترونيًا صالحًا.",
    rolesRequired: "اختر دورًا واحدًا على الأقل.",
    password: "كلمة المرور (اختياري)",
    passwordHint: "اتركها فارغة ليختاروا كلمة مرورهم بأنفسهم.",
    passwordShort: (min: string) => `استخدم ${min} أحرف على الأقل.`,
    rolesFreePlaceholder: "اكتب دورًا واضغط Enter",
    rolesFreeHint: "مثل admin أو editor أو billing.",
    rolesTitle: (name: string) => `أدوار ${name}`,
    rolesBody: "اختر ما يستطيع هذا الشخص فعله. تسري التغييرات عند طلبه التالي.",
    saveRoles: "حفظ الأدوار",
  },
};

export const adminUsersStrings = (locale: string) => ADMIN_USERS_STRINGS[locale.startsWith("ar") ? "ar" : "en"];

export type AdminUsersLabels = Partial<typeof ADMIN_USERS_STRINGS.en>;
