export const CHROME_EXTENSION_STRINGS = {
  en: {
    title: "Install the browser extension",
    description: "Three steps: add it, pin it, sign in.",
    steps: "Installation steps",
    detected: (version?: string) => (version ? `Extension detected, version ${version}` : "Extension detected"),
    notDetected: "Extension not detected yet",
    check: "Check again",
    checking: "Checking…",
    unsupported: "Chrome extensions work in Chrome and other Chromium browsers such as Edge, Brave and Arc. Open this page in one of them.",
    done: "Done",
    stepAdd: "Add it from the Chrome Web Store",
    stepAddBody: "Open the store page and choose Add to Chrome, then confirm in the pop-up.",
    addButton: "Open the Chrome Web Store",
    stepPin: "Pin it to the toolbar",
    stepPinBody: "Click the puzzle-piece Extensions button next to the address bar, then the pin beside the extension. It stays one click away.",
    pinnedButton: "I pinned it",
    unpin: "Undo",
    stepSignIn: "Sign in from the extension",
    stepSignInBody: "Click the extension, then Sign in. It uses your account, so nothing is typed twice.",
    signInButton: "Sign in",
    signedIn: "Signed in",
    signInFailed: "Could not sign in. Try again.",
    blocked: "Do the step above first.",
    ready: "You are all set",
    readyBody: "The extension is installed, pinned and signed in.",
    stepLabel: (n: number, total: number, state: string) => `Step ${n} of ${total}, ${state}`,
    stateDone: "done",
    stateCurrent: "current",
    stateTodo: "to do",
  },
  ar: {
    title: "ثبّت إضافة المتصفح",
    description: "ثلاث خطوات: أضفها، ثبّتها، سجّل الدخول.",
    steps: "خطوات التثبيت",
    detected: (version?: string) => (version ? `تم اكتشاف الإضافة، الإصدار ${version}` : "تم اكتشاف الإضافة"),
    notDetected: "لم تُكتشف الإضافة بعد",
    check: "تحقق مرة أخرى",
    checking: "جارٍ التحقق…",
    unsupported: "إضافات Chrome تعمل في Chrome والمتصفحات المبنية على Chromium مثل Edge وBrave وArc. افتح هذه الصفحة في أحدها.",
    done: "تمت",
    stepAdd: "أضفها من متجر Chrome الإلكتروني",
    stepAddBody: "افتح صفحة المتجر واختر «إضافة إلى Chrome»، ثم أكّد في النافذة المنبثقة.",
    addButton: "افتح متجر Chrome الإلكتروني",
    stepPin: "ثبّتها في شريط الأدوات",
    stepPinBody: "اضغط زر الإضافات على شكل قطعة أحجية بجوار شريط العنوان، ثم الدبوس بجوار الإضافة. تبقى على بعد نقرة واحدة.",
    pinnedButton: "ثبّتُّها",
    unpin: "تراجع",
    stepSignIn: "سجّل الدخول من الإضافة",
    stepSignInBody: "اضغط على الإضافة ثم «تسجيل الدخول». تستخدم حسابك فلا تكتب شيئًا مرتين.",
    signInButton: "تسجيل الدخول",
    signedIn: "تم تسجيل الدخول",
    signInFailed: "تعذر تسجيل الدخول. حاول مرة أخرى.",
    blocked: "أنجز الخطوة السابقة أولًا.",
    ready: "كل شيء جاهز",
    readyBody: "الإضافة مثبّتة وموضوعة في شريط الأدوات ومسجَّل الدخول فيها.",
    stepLabel: (n: number, total: number, state: string) => `الخطوة ${n} من ${total}، ${state}`,
    stateDone: "مكتملة",
    stateCurrent: "الحالية",
    stateTodo: "لم تبدأ",
  },
};

export type ChromeExtensionInstallLabels = (typeof CHROME_EXTENSION_STRINGS)["en"];
