// The panels' own words, en and ar, copied from the React apm-panels.

export const STRINGS = {
  en: {
    latency: "Latency",
    latencyDescription: "Response time percentiles",
    p50: "p50",
    p95: "p95",
    p99: "p99",
    median: "Median",
    slowest5: "Slowest 5%",
    slowest1: "Slowest 1%",
    target: "Target",
    vsPrevious: "vs previous period",
    errorRate: "Error rate",
    errorDescription: "Failed requests as a share of all requests",
    errors: "Errors",
    requests: "Requests",
    slo: "Error budget",
    withinSlo: "Within target",
    overSlo: "Over target",
    topErrors: "Top errors",
    occurrences: (n: number) => (n === 1 ? "1 time" : `${n} times`),
    lastSeen: "Last seen",
    noErrors: "No errors in this period",
    empty: "No data for this period",
    loadError: "This panel could not be loaded.",
    retry: "Try again",
    endpoints: "Slowest endpoints",
    endpointsDescription: "Sorted by the 95th percentile by default",
    endpoint: "Endpoint",
    throughput: "Throughput",
    perMinute: "req/min",
    filterEndpoints: "Filter endpoints…",
    slow: "Slow",
    traces: "Traces",
    tracesDescription: "Recent requests, slowest first",
    trace: "Trace",
    duration: "Duration",
    status: "Status",
    started: "Started",
    spans: (n: number) => (n === 1 ? "1 span" : `${n} spans`),
    services: "Service",
    waterfall: "Span waterfall",
    waterfallOf: (name: string) => `Spans of ${name}`,
    span: "Span",
    close: "Close",
    noTraces: "No traces match",
    failed: "Failed",
    chartLatency: "Latency percentiles over time",
    chartErrors: "Error rate over time",
    selectTrace: (name: string) => `Show spans for ${name}`,
  },
  ar: {
    latency: "زمن الاستجابة",
    latencyDescription: "نسب زمن الاستجابة المئوية",
    p50: "p50",
    p95: "p95",
    p99: "p99",
    median: "الوسيط",
    slowest5: "أبطأ 5%",
    slowest1: "أبطأ 1%",
    target: "الهدف",
    vsPrevious: "مقارنة بالفترة السابقة",
    errorRate: "معدل الأخطاء",
    errorDescription: "الطلبات الفاشلة كنسبة من كل الطلبات",
    errors: "الأخطاء",
    requests: "الطلبات",
    slo: "ميزانية الأخطاء",
    withinSlo: "ضمن الهدف",
    overSlo: "فوق الهدف",
    topErrors: "أكثر الأخطاء",
    occurrences: (n: number) => (n === 1 ? "مرة واحدة" : `${n} مرات`),
    lastSeen: "آخر ظهور",
    noErrors: "لا أخطاء في هذه الفترة",
    empty: "لا بيانات لهذه الفترة",
    loadError: "تعذّر تحميل هذه اللوحة.",
    retry: "حاول مرة أخرى",
    endpoints: "أبطأ نقاط النهاية",
    endpointsDescription: "مرتبة افتراضيًا حسب المئين 95",
    endpoint: "نقطة النهاية",
    throughput: "معدل الطلبات",
    perMinute: "طلب/دقيقة",
    filterEndpoints: "تصفية نقاط النهاية…",
    slow: "بطيء",
    traces: "التتبعات",
    tracesDescription: "أحدث الطلبات، الأبطأ أولًا",
    trace: "التتبع",
    duration: "المدة",
    status: "الحالة",
    started: "البدء",
    spans: (n: number) => (n === 1 ? "مقطع واحد" : `${n} مقاطع`),
    services: "الخدمة",
    waterfall: "شلال المقاطع",
    waterfallOf: (name: string) => `مقاطع ${name}`,
    span: "المقطع",
    close: "إغلاق",
    noTraces: "لا تتبعات مطابقة",
    failed: "فشل",
    chartLatency: "نسب زمن الاستجابة عبر الوقت",
    chartErrors: "معدل الأخطاء عبر الوقت",
    selectTrace: (name: string) => `عرض مقاطع ${name}`,
  },
};

export type ApmPanelsLabels = typeof STRINGS.en;
