"use client";
import { useOptionalNasaq } from "../../provider/nasaq-provider";

const en = {
  // list
  orders: "Orders",
  views: "Saved views",
  viewAll: "All orders",
  viewToFulfil: "To fulfil",
  viewUnpaid: "Unpaid",
  viewDelivered: "Delivered",
  viewRefunds: "Refunds",
  deleteView: "Delete view",
  saveView: "Save view",
  saveViewText: "Keep the current filters as a view you can open again.",
  viewName: "View name",
  searchOrders: "Search by order, customer or product",
  exportCsv: "Export CSV",
  exportSelected: "Export selected",
  printSlips: "Print packing slips",
  printInvoices: "Print invoices",
  printSlip: "Print packing slip",
  printInvoice: "Print invoice",
  openOrder: "Open order",
  loadError: "Orders could not be loaded.",
  noOrders: "No orders yet",
  noOrdersText: "Orders show up here as soon as customers check out.",
  noMatch: "No orders match",
  noMatchHint: "Try a different search or clear the filters.",
  clearFilters: "Clear filters",
  cancel: "Cancel",
  save: "Save",
  retry: "Try again",
  back: "Back",
  document: "Document",
  print: "Print",
  order: "Order",
  date: "Date",
  customer: "Customer",
  payment: "Payment",
  fulfilment: "Fulfilment",
  status: "Status",
  items: "items",
  total: "Total",
  someSkipped: (n: number) => `${n} selected orders cannot be fulfilled and will be skipped`,
  markFulfilled: (n: number) => (n === 1 ? "Mark fulfilled" : `Mark ${n} fulfilled`),
  // detail
  backToOrders: "Back to orders",
  placedOn: "Placed on",
  packingSlip: "Packing slip",
  invoice: "Invoice",
  cancelOrder: "Cancel order",
  cannotCancel: "This order can no longer be cancelled.",
  refund: "Refund",
  fulfil: "Fulfil",
  unpaidTitle: "Payment not received",
  unpaidText: "Nothing has been paid on this order yet, so it cannot be refunded.",
  subtotal: "Subtotal",
  discount: "Discount",
  shipping: "Shipping",
  free: "Free",
  tax: "Tax",
  refunded: "Refunded",
  netPaid: "Net paid",
  due: "Due",
  restocked: "Returned to stock",
  timeline: "Timeline",
  noteAdded: "Note added",
  shippingAddress: "Shipping address",
  billingAddress: "Billing address",
  noAddress: "No address on this order",
  sameAsShipping: "Same as shipping address",
  shipment: "Shipment",
  trackShipment: "Track shipment",
  noTracking: "Nothing has shipped yet.",
  carrier: "Carrier",
  trackingNumber: "Tracking number",
  shippedOf: (a: number, b: number) => `${a} of ${b} shipped`,
  shippedCount: (n: number) => `${n} shipped`,
  toShipCount: (n: number) => `${n} to ship`,
  refundedCount: (n: number) => `${n} refunded`,
  // fulfil dialog
  shippedAll: "All items shipped",
  shippedSome: "Shipment recorded",
  fulfilTitle: "Fulfil items",
  fulfilText: "Choose what goes in this shipment. You can ship the rest later.",
  quantity: "Quantity",
  trackingOptional: "Optional. The customer sees it in their account.",
  willCompleteOrder: "This shipment completes the order.",
  willPartlyShip: "Some items will stay unshipped.",
  pickUnits: "Pick at least one unit to ship.",
  markShipped: "Mark as shipped",
  // refund dialog
  refundIssued: "Refund recorded",
  refundTitle: "Refund order",
  refundLeft: "Still refundable",
  refundBy: "Refund by",
  byLines: "Items",
  byAmount: "Amount",
  byAmountText: "Refund a set amount, for example a goodwill credit.",
  refundShipping: "Refund shipping",
  restock: "Return items to stock",
  restockText: "Adds unshipped and returned units back to inventory.",
  refundAmount: "Amount to refund",
  reason: "Reason",
  reasonPlaceholder: "Why is this being refunded? Only your team sees this.",
  refundTotal: "Refund total",
  issueRefund: "Issue refund",
  refundInvalid: "Check the refund details.",
  shippingDone: "Shipping has already been refunded.",
  refundUnpaid: "This order has no payment to refund.",
  refundOver: (max: number) => `The most you can refund is ${max}.`,
  refundLineOver: (max: number) => `Only ${max} left to refund on this line.`,
  // cancel dialog
  cancelTitle: (n: string) => `Cancel order ${n}?`,
  cancelRefunds: "The customer will be refunded in full and unshipped items go back to stock.",
  cancelNoRefund: "Nothing was paid, so nothing will be refunded.",
  keepOrder: "Keep order",
  cancelled: "Order cancelled",
  // documents
  taxId: "Tax number",
  shipTo: "Ship to",
  billTo: "Bill to",
  item: "Item",
  unitPrice: "Unit price",
  toPack: "To pack",
  packed: "Packed",
  slipNote: "Check each item as you pack it. Prices are not shown on this slip.",
  documentsCount: (n: number) => (n === 1 ? "1 document" : `${n} documents`),
  // abandoned carts
  abandoned: "Abandoned carts",
  statAbandoned: "Abandoned carts",
  statAtRisk: "Value at risk",
  statRecovered: "Recovered",
  statRate: "Recovery rate",
  noCarts: "No abandoned carts",
  noCartsText: "Carts left behind by shoppers will appear here.",
  loadErrorCarts: "Abandoned carts could not be loaded.",
  guest: "Guest",
  sendRecovery: "Send recovery email",
  recoveryTitle: "Send a recovery email",
  recoveryText: "A reminder with a link back to the cart goes to",
  discountPercent: "Discount offered (%)",
  discountHint: (max: number) => `Up to ${max}%. Leave at 0 to offer none.`,
  recoveryMessage: "Personal message",
  recoveryPlaceholder: "Optional. Added above the cart in the email.",
  blockRecovered: "Already recovered",
  blockLost: "Too old to recover",
  blockNoEmail: "No email address",
  blockLimit: "Email limit reached",
  blockTooSoon: (min: number) => `Wait ${min} more min`,
  blockCooldown: (h: number) => `Next email in ${h} h`,
  idleMinutes: (n: number) => `${n} min idle`,
  idleHours: (n: number) => `${n} h idle`,
  idleDays: (n: number) => `${n} days idle`,
  emailsSent: (n: number) => (n === 1 ? "1 email sent" : `${n} emails sent`),
  stage: { cart: "Left the cart", checkout: "Left checkout", payment: "Left at payment" },
  recovery: { new: "Not emailed", emailed: "Emailed", recovered: "Recovered", lost: "Lost", "no-email": "No email" },
};

export type StoreAdminStrings = typeof en;

const ar: StoreAdminStrings = {
  orders: "الطلبات",
  views: "العروض المحفوظة",
  viewAll: "كل الطلبات",
  viewToFulfil: "بانتظار التنفيذ",
  viewUnpaid: "غير مدفوعة",
  viewDelivered: "تم تسليمها",
  viewRefunds: "المستردة",
  deleteView: "حذف العرض",
  saveView: "حفظ العرض",
  saveViewText: "احفظ عوامل التصفية الحالية كعرض تفتحه لاحقًا.",
  viewName: "اسم العرض",
  searchOrders: "ابحث برقم الطلب أو العميل أو المنتج",
  exportCsv: "تصدير CSV",
  exportSelected: "تصدير المحدد",
  printSlips: "طباعة قوائم التعبئة",
  printInvoices: "طباعة الفواتير",
  printSlip: "طباعة قائمة التعبئة",
  printInvoice: "طباعة الفاتورة",
  openOrder: "فتح الطلب",
  loadError: "تعذّر تحميل الطلبات.",
  noOrders: "لا توجد طلبات بعد",
  noOrdersText: "تظهر الطلبات هنا فور إتمام العملاء للشراء.",
  noMatch: "لا توجد طلبات مطابقة",
  noMatchHint: "جرّب بحثًا آخر أو امسح عوامل التصفية.",
  clearFilters: "مسح عوامل التصفية",
  cancel: "إلغاء",
  save: "حفظ",
  retry: "حاول مجددًا",
  back: "رجوع",
  document: "المستند",
  print: "طباعة",
  order: "الطلب",
  date: "التاريخ",
  customer: "العميل",
  payment: "الدفع",
  fulfilment: "التنفيذ",
  status: "الحالة",
  items: "منتجات",
  total: "الإجمالي",
  someSkipped: (n) => `${n} من الطلبات المحددة لا يمكن تنفيذها وسيتم تخطيها`,
  markFulfilled: (n) => (n === 1 ? "تحديد كمنفَّذ" : `تحديد ${n} كمنفَّذة`),
  backToOrders: "العودة إلى الطلبات",
  placedOn: "تاريخ الطلب",
  packingSlip: "قائمة التعبئة",
  invoice: "الفاتورة",
  cancelOrder: "إلغاء الطلب",
  cannotCancel: "لم يعد بالإمكان إلغاء هذا الطلب.",
  refund: "استرداد",
  fulfil: "تنفيذ",
  unpaidTitle: "لم يصل الدفع",
  unpaidText: "لم يُدفع أي مبلغ لهذا الطلب بعد، لذلك لا يمكن استرداده.",
  subtotal: "المجموع الفرعي",
  discount: "الخصم",
  shipping: "الشحن",
  free: "مجاني",
  tax: "الضريبة",
  refunded: "المسترد",
  netPaid: "صافي المدفوع",
  due: "المستحق",
  restocked: "أُعيد إلى المخزون",
  timeline: "السجل الزمني",
  noteAdded: "تمت إضافة ملاحظة",
  shippingAddress: "عنوان الشحن",
  billingAddress: "عنوان الفواتير",
  noAddress: "لا يوجد عنوان لهذا الطلب",
  sameAsShipping: "نفس عنوان الشحن",
  shipment: "الشحنة",
  trackShipment: "تتبّع الشحنة",
  noTracking: "لم يُشحن شيء بعد.",
  carrier: "شركة الشحن",
  trackingNumber: "رقم التتبع",
  shippedOf: (a, b) => `تم شحن ${a} من ${b}`,
  shippedCount: (n) => `${n} تم شحنها`,
  toShipCount: (n) => `${n} بانتظار الشحن`,
  refundedCount: (n) => `${n} مستردة`,
  shippedAll: "تم شحن كل المنتجات",
  shippedSome: "تم تسجيل الشحنة",
  fulfilTitle: "تنفيذ المنتجات",
  fulfilText: "اختر ما سيُشحن في هذه الشحنة. يمكنك شحن الباقي لاحقًا.",
  quantity: "الكمية",
  trackingOptional: "اختياري. يراه العميل في حسابه.",
  willCompleteOrder: "هذه الشحنة تُكمل الطلب.",
  willPartlyShip: "ستبقى بعض المنتجات بدون شحن.",
  pickUnits: "اختر وحدة واحدة على الأقل للشحن.",
  markShipped: "تحديد كمشحون",
  refundIssued: "تم تسجيل الاسترداد",
  refundTitle: "استرداد الطلب",
  refundLeft: "المتاح للاسترداد",
  refundBy: "الاسترداد حسب",
  byLines: "المنتجات",
  byAmount: "المبلغ",
  byAmountText: "استرد مبلغًا محددًا، مثل تعويض تقديري.",
  refundShipping: "استرداد الشحن",
  restock: "إعادة المنتجات إلى المخزون",
  restockText: "يعيد الوحدات غير المشحونة والمرتجعة إلى المخزون.",
  refundAmount: "مبلغ الاسترداد",
  reason: "السبب",
  reasonPlaceholder: "لماذا يُسترد هذا المبلغ؟ يراه فريقك فقط.",
  refundTotal: "إجمالي الاسترداد",
  issueRefund: "تنفيذ الاسترداد",
  refundInvalid: "راجع تفاصيل الاسترداد.",
  shippingDone: "تم استرداد الشحن من قبل.",
  refundUnpaid: "لا توجد دفعة في هذا الطلب لاستردادها.",
  refundOver: (max) => `أقصى مبلغ يمكن استرداده هو ${max}.`,
  refundLineOver: (max) => `المتبقي للاسترداد في هذا البند ${max} فقط.`,
  cancelTitle: (n) => `إلغاء الطلب ${n}؟`,
  cancelRefunds: "سيُسترد للعميل المبلغ كاملًا وتعود المنتجات غير المشحونة إلى المخزون.",
  cancelNoRefund: "لم يُدفع أي مبلغ، لذلك لن يتم استرداد شيء.",
  keepOrder: "إبقاء الطلب",
  cancelled: "تم إلغاء الطلب",
  taxId: "الرقم الضريبي",
  shipTo: "الشحن إلى",
  billTo: "الفاتورة إلى",
  item: "المنتج",
  unitPrice: "سعر الوحدة",
  toPack: "للتعبئة",
  packed: "تمت التعبئة",
  slipNote: "ضع علامة على كل منتج أثناء تعبئته. الأسعار غير ظاهرة في هذه القائمة.",
  documentsCount: (n) => (n === 1 ? "مستند واحد" : `${n} مستندات`),
  abandoned: "السلات المتروكة",
  statAbandoned: "السلات المتروكة",
  statAtRisk: "القيمة المعرّضة للخسارة",
  statRecovered: "المستردة",
  statRate: "نسبة الاسترداد",
  noCarts: "لا توجد سلات متروكة",
  noCartsText: "السلات التي يتركها المتسوقون ستظهر هنا.",
  loadErrorCarts: "تعذّر تحميل السلات المتروكة.",
  guest: "زائر",
  sendRecovery: "إرسال بريد استرجاع",
  recoveryTitle: "إرسال بريد استرجاع",
  recoveryText: "سيصل تذكير برابط العودة إلى السلة إلى",
  discountPercent: "الخصم المعروض (%)",
  discountHint: (max) => `حتى ${max}%. اتركه 0 لعدم تقديم خصم.`,
  recoveryMessage: "رسالة شخصية",
  recoveryPlaceholder: "اختياري. تُضاف أعلى السلة في البريد.",
  blockRecovered: "تم استرجاعها",
  blockLost: "قديمة جدًا للاسترجاع",
  blockNoEmail: "لا يوجد بريد إلكتروني",
  blockLimit: "بلغت حد الرسائل",
  blockTooSoon: (min) => `انتظر ${min} دقيقة أخرى`,
  blockCooldown: (h) => `الرسالة التالية بعد ${h} ساعة`,
  idleMinutes: (n) => `خاملة منذ ${n} دقيقة`,
  idleHours: (n) => `خاملة منذ ${n} ساعة`,
  idleDays: (n) => `خاملة منذ ${n} يومًا`,
  emailsSent: (n) => (n === 1 ? "أُرسل بريد واحد" : `أُرسل ${n} رسائل`),
  stage: { cart: "غادر السلة", checkout: "غادر الدفع", payment: "غادر عند السداد" },
  recovery: { new: "لم يُراسل", emailed: "تمت مراسلته", recovered: "مستردة", lost: "مفقودة", "no-email": "بلا بريد" },
};

export const STORE_ADMIN_STRINGS = { en, ar };

export type StoreAdminLabels = Partial<StoreAdminStrings>;

export function useStoreAdminStrings(labels?: StoreAdminLabels) {
  const locale = useOptionalNasaq()?.locale ?? "en";
  const isAr = locale.startsWith("ar");
  return { t: { ...STORE_ADMIN_STRINGS[isAr ? "ar" : "en"], ...labels } as StoreAdminStrings, ar: isAr, locale };
}
