// Strings of the AI state components, English and Arabic (copied from the React STRINGS table).
export const aiStatesStrings = {
  en: {
    ask: "Ask AI",
    generating: "Generating",
    moreActions: "More AI actions",
    actionsTitle: "AI actions",
    actionsPlaceholder: "What should AI do?",
    recommended: "Recommended",
    allActions: "All actions",
    noActions: "No matching actions",
    navigate: "Navigate",
    run: "Run",
    close: "Close",
    suggestions: "AI suggestions",
    dismiss: (label: string) => `Dismiss ${label}`,
    thinking: "Thinking",
    stepDone: "Done",
    stepActive: "In progress",
    stepPending: "Waiting",
    ready: "Response ready",
    stop: "Stop",
    stopped: "Stopped",
    regenerate: "Regenerate",
    streaming: "Writing",
    failed: "Something went wrong",
    aiGenerated: "AI generated",
    summary: "Summary",
    tldr: "TL;DR",
    keyPoints: "Key points",
    sources: "Sources",
    confidence: "Confidence",
    high: "High",
    medium: "Medium",
    low: "Low",
    showFull: "Show full summary",
    hideFull: "Hide full summary",
    copy: "Copy summary",
    good: "Good summary",
    bad: "Not helpful",
    thanks: "Thanks for the feedback",
    disclaimer: "AI can make mistakes. Check important details.",
    loading: "Summarizing",
  },
  ar: {
    ask: "اسأل الذكاء الاصطناعي",
    generating: "جارٍ التوليد",
    moreActions: "المزيد من إجراءات الذكاء الاصطناعي",
    actionsTitle: "إجراءات الذكاء الاصطناعي",
    actionsPlaceholder: "ماذا تريد أن ينفّذ الذكاء الاصطناعي؟",
    recommended: "موصى بها",
    allActions: "كل الإجراءات",
    noActions: "لا توجد إجراءات مطابقة",
    navigate: "تنقّل",
    run: "تنفيذ",
    close: "إغلاق",
    suggestions: "اقتراحات الذكاء الاصطناعي",
    dismiss: (label: string) => `تجاهل ${label}`,
    thinking: "جارٍ التفكير",
    stepDone: "تمّت",
    stepActive: "قيد التنفيذ",
    stepPending: "بالانتظار",
    ready: "الرد جاهز",
    stop: "إيقاف",
    stopped: "تم الإيقاف",
    regenerate: "إعادة التوليد",
    streaming: "جارٍ الكتابة",
    failed: "حدث خطأ ما",
    aiGenerated: "مُولَّد بالذكاء الاصطناعي",
    summary: "الملخص",
    tldr: "باختصار",
    keyPoints: "النقاط الرئيسية",
    sources: "المصادر",
    confidence: "درجة الثقة",
    high: "عالية",
    medium: "متوسطة",
    low: "منخفضة",
    showFull: "عرض الملخص الكامل",
    hideFull: "إخفاء الملخص الكامل",
    copy: "نسخ الملخص",
    good: "ملخص جيد",
    bad: "غير مفيد",
    thanks: "شكرًا على ملاحظتك",
    disclaimer: "قد يخطئ الذكاء الاصطناعي. تحقق من التفاصيل المهمة.",
    loading: "جارٍ التلخيص",
  },
};

export type AiStatesLabels = Omit<(typeof aiStatesStrings)["en"], "dismiss"> & { dismiss: (label: string) => string };

/** The words for a locale, with the caller's overrides on top. */
export function aiStatesWords(locale: string, labels?: Partial<AiStatesLabels>): AiStatesLabels {
  return { ...aiStatesStrings[locale.startsWith("ar") ? "ar" : "en"], ...labels };
}
