import type { LineItemPeriod } from "./finops-format";

export const FINOPS_STRINGS = {
  en: {
    title: "Costs",
    description: "What the servers and extra items cost each month.",
    total: "Monthly total",
    servers: "Servers",
    items: "Extra items",
    savings: "Possible savings",
    vsPrevious: "vs last month",
    budget: "Budget",
    budgetOf: (used: string, budget: string) => `${used} of ${budget}`,
    budgetNear: "Close to the budget.",
    budgetOver: "Over the budget.",
    serversTitle: "Servers",
    serversDescription: "Price and average use per server. Hints come from CPU and memory use.",
    serversTable: "Servers and their cost",
    server: "Server",
    region: "Region",
    price: "Price",
    cpu: "CPU",
    memory: "Memory",
    disk: "Disk",
    hint: "Hint",
    hintOk: "Right size",
    hintDown: "Could be smaller",
    hintUp: "Needs more room",
    hintDownDetail: (plan: string, save: string) => `Move to ${plan} and save ${save} a month.`,
    hintDownGeneric: "Use is low. A smaller plan would cost less.",
    hintUpDetail: (plan: string, extra: string) => `Move to ${plan} for ${extra} more a month.`,
    hintUpGeneric: "Use is high. Consider a bigger plan.",
    changePlan: (plan: string) => `Switch to ${plan}`,
    serversEmpty: "No servers yet",
    perMonth: "/ month",
    categoryTitle: "Cost by category",
    categoryDescription: "Monthly cost grouped by kind.",
    category: "Category",
    monthlyCost: "Monthly cost",
    serversCategory: "Servers",
    historyTitle: "Cost over time",
    historyDescription: "Daily cost.",
    cost: "Cost",
    itemsTitle: "Extra items",
    itemsDescription: "Costs that are not servers: domains, licences, backups, support.",
    itemsTable: "Extra cost items",
    itemName: "Item",
    itemCategory: "Category",
    itemAmount: "Amount",
    itemPeriod: "Billed",
    periods: { monthly: "Monthly", yearly: "Yearly", once: "One time" } as Record<LineItemPeriod, string>,
    perMonthEquivalent: "Per month",
    itemsEmpty: "No extra items",
    itemsEmptyBody: "Add costs that are not part of a server.",
    addItem: "Add item",
    addItemTitle: "Add a cost item",
    addItemBody: "It counts towards the monthly total. A yearly item is divided by twelve; a one time item is listed but not counted.",
    nameLabel: "Name",
    namePlaceholder: "Domain renewal",
    nameRequired: "Enter a name.",
    categoryLabel: "Category",
    categoryPlaceholder: "Domains",
    amountLabel: "Amount",
    amountInvalid: "Enter an amount greater than zero.",
    periodLabel: "Billed",
    add: "Add",
    cancel: "Cancel",
    remove: "Remove",
    removeTitle: (name: string) => `Remove ${name}?`,
    removeBody: "It stops counting towards the monthly total.",
    dismiss: "Dismiss",
    genericError: "That did not work. Try again.",
    uncategorised: "Other",
    retry: "Try again",
  },
  ar: {
    title: "التكاليف",
    description: "ما تكلفه الخوادم والبنود الإضافية كل شهر.",
    total: "الإجمالي الشهري",
    servers: "الخوادم",
    items: "بنود إضافية",
    savings: "توفير ممكن",
    vsPrevious: "مقارنة بالشهر الماضي",
    budget: "الميزانية",
    budgetOf: (used: string, budget: string) => `${used} من ${budget}`,
    budgetNear: "اقتربت من الميزانية.",
    budgetOver: "تجاوزت الميزانية.",
    serversTitle: "الخوادم",
    serversDescription: "السعر ومتوسط الاستخدام لكل خادم. الاقتراحات مبنية على استخدام المعالج والذاكرة.",
    serversTable: "الخوادم وتكلفتها",
    server: "الخادم",
    region: "المنطقة",
    price: "السعر",
    cpu: "المعالج",
    memory: "الذاكرة",
    disk: "القرص",
    hint: "اقتراح",
    hintOk: "حجم مناسب",
    hintDown: "يمكن أن يكون أصغر",
    hintUp: "يحتاج مساحة أكبر",
    hintDownDetail: (plan: string, save: string) => `انتقل إلى ${plan} ووفّر ${save} شهريًا.`,
    hintDownGeneric: "الاستخدام منخفض. خطة أصغر ستكلف أقل.",
    hintUpDetail: (plan: string, extra: string) => `انتقل إلى ${plan} مقابل ${extra} إضافية شهريًا.`,
    hintUpGeneric: "الاستخدام مرتفع. فكّر في خطة أكبر.",
    changePlan: (plan: string) => `التحويل إلى ${plan}`,
    serversEmpty: "لا توجد خوادم بعد",
    perMonth: "/ شهر",
    categoryTitle: "التكلفة حسب الفئة",
    categoryDescription: "التكلفة الشهرية مجمعة حسب النوع.",
    category: "الفئة",
    monthlyCost: "التكلفة الشهرية",
    serversCategory: "الخوادم",
    historyTitle: "التكلفة عبر الزمن",
    historyDescription: "التكلفة اليومية.",
    cost: "التكلفة",
    itemsTitle: "بنود إضافية",
    itemsDescription: "تكاليف ليست خوادم: نطاقات وتراخيص ونسخ احتياطي ودعم.",
    itemsTable: "بنود التكلفة الإضافية",
    itemName: "البند",
    itemCategory: "الفئة",
    itemAmount: "المبلغ",
    itemPeriod: "الفوترة",
    periods: { monthly: "شهريًا", yearly: "سنويًا", once: "مرة واحدة" } as Record<LineItemPeriod, string>,
    perMonthEquivalent: "في الشهر",
    itemsEmpty: "لا توجد بنود إضافية",
    itemsEmptyBody: "أضف تكاليف ليست جزءًا من خادم.",
    addItem: "إضافة بند",
    addItemTitle: "إضافة بند تكلفة",
    addItemBody: "يُحتسب ضمن الإجمالي الشهري. البند السنوي يُقسم على اثني عشر، والبند لمرة واحدة يُعرض دون احتسابه.",
    nameLabel: "الاسم",
    namePlaceholder: "تجديد النطاق",
    nameRequired: "أدخل اسمًا.",
    categoryLabel: "الفئة",
    categoryPlaceholder: "النطاقات",
    amountLabel: "المبلغ",
    amountInvalid: "أدخل مبلغًا أكبر من صفر.",
    periodLabel: "الفوترة",
    add: "إضافة",
    cancel: "إلغاء",
    remove: "إزالة",
    removeTitle: (name: string) => `إزالة ${name}؟`,
    removeBody: "سيتوقف احتسابه ضمن الإجمالي الشهري.",
    dismiss: "إغلاق",
    genericError: "لم تنجح العملية. حاول مرة أخرى.",
    uncategorised: "أخرى",
    retry: "حاول مرة أخرى",
  },
};

export type FinopsCostLabels = typeof FINOPS_STRINGS.en;
