// Strings of the copilot chat, English and Arabic (copied from the React STRINGS table).
export const copilotChatStrings = {
  en: {
    title: "Copilot",
    assistant: "Copilot",
    you: "You",
    conversation: "Copilot conversation",
    placeholder: "Ask anything. Type @ to mention.",
    send: "Send",
    stop: "Stop",
    close: "Close",
    newChat: "New chat",
    copyChat: "Copy conversation",
    copied: "Copied",
    copy: "Copy answer",
    regenerate: "Try again",
    good: "Good answer",
    bad: "Not helpful",
    sources: "Sources",
    usedSteps: (n: number) => (n === 1 ? "Used 1 tool" : `Used ${n} tools`),
    working: "Working",
    stepFailed: "A step failed",
    context: "Context",
    addContext: "Add context",
    removeContext: (l: string) => `Remove ${l}`,
    model: "Model",
    emptyTitle: "How can I help?",
    emptyBody: "Ask about your data, or start from one of these.",
    followUps: "Suggested follow-ups",
    starters: "Suggestions",
    message: "Message",
    mentions: "Mentions",
    attach: "Attach files",
    dropFiles: "Drop files to attach",
    removeAttachment: (n: string) => `Remove ${n}`,
    attachments: "Attachments",
    commands: "Tools and skills",
    commandHint: "Type / for tools and skills",
    noCommands: "No matching tools",
    removeCommand: (n: string) => `Stop using ${n}`,
    options: "Options",
    history: "History",
    noHistory: "No saved conversations yet.",
    deleteSession: (n: string) => `Delete ${n}`,
    share: "Share answer",
    streamError: "The answer stopped before it finished.",
    retry: "Retry",
  },
  ar: {
    title: "المساعد",
    assistant: "المساعد",
    you: "أنت",
    conversation: "محادثة المساعد",
    placeholder: "اسأل أي شيء. اكتب @ للإشارة.",
    send: "إرسال",
    stop: "إيقاف",
    close: "إغلاق",
    newChat: "محادثة جديدة",
    copyChat: "نسخ المحادثة",
    copied: "تم النسخ",
    copy: "نسخ الإجابة",
    regenerate: "حاول مرة أخرى",
    good: "إجابة جيدة",
    bad: "غير مفيدة",
    sources: "المصادر",
    usedSteps: (n: number) => (n === 1 ? "استخدم أداة واحدة" : n === 2 ? "استخدم أداتين" : `استخدم ${n} أدوات`),
    working: "جارٍ العمل",
    stepFailed: "فشلت إحدى الخطوات",
    context: "السياق",
    addContext: "إضافة سياق",
    removeContext: (l: string) => `إزالة ${l}`,
    model: "النموذج",
    emptyTitle: "كيف أساعدك؟",
    emptyBody: "اسأل عن بياناتك، أو ابدأ من أحد هذه الاقتراحات.",
    followUps: "أسئلة مقترحة للمتابعة",
    starters: "اقتراحات",
    message: "الرسالة",
    mentions: "الإشارات",
    attach: "إرفاق ملفات",
    dropFiles: "أفلت الملفات لإرفاقها",
    removeAttachment: (n: string) => `إزالة ${n}`,
    attachments: "المرفقات",
    commands: "الأدوات والمهارات",
    commandHint: "اكتب / للأدوات والمهارات",
    noCommands: "لا توجد أدوات مطابقة",
    removeCommand: (n: string) => `إيقاف استخدام ${n}`,
    options: "الخيارات",
    history: "السجل",
    noHistory: "لا توجد محادثات محفوظة بعد.",
    deleteSession: (n: string) => `حذف ${n}`,
    share: "مشاركة الإجابة",
    streamError: "توقفت الإجابة قبل أن تكتمل.",
    retry: "إعادة المحاولة",
  },
};

export type CopilotChatLabels = Omit<(typeof copilotChatStrings)["en"], "usedSteps" | "removeContext" | "removeAttachment" | "removeCommand" | "deleteSession"> & {
  usedSteps: (n: number) => string;
  removeContext: (label: string) => string;
  removeAttachment: (name: string) => string;
  removeCommand: (label: string) => string;
  deleteSession: (title: string) => string;
};

/** The words for a locale with the host's overrides on top. */
export function copilotWords(locale: string, labels?: Partial<CopilotChatLabels>): CopilotChatLabels {
  return { ...copilotChatStrings[locale.startsWith("ar") ? "ar" : "en"], ...labels } as CopilotChatLabels;
}
