export const FILE_EXPLORER_STRINGS = {
  en: {
    title: "Files",
    root: "All files",
    folders: "Folders",
    breadcrumb: "Path",
    search: "Search in this folder",
    view: "View",
    listView: "List",
    gridView: "Grid",
    upload: "Upload",
    newFolder: "New folder",
    name: "Name",
    modified: "Modified",
    size: "Size",
    items: (n: number) => (n === 1 ? "1 item" : `${n} items`),
    listLabel: "Files in this folder",
    gridLabel: "Files in this folder",
    emptyTitle: "This folder is empty",
    emptyBody: "Drop files here or use Upload.",
    noMatch: "Nothing here matches your search.",
    loading: "Loading files",
    dropHere: "Drop to upload",
    folderWord: "Folder",
    // preview
    preview: "Preview",
    previewNone: "Select a file to preview it",
    closePreview: "Close preview",
    type: "Type",
    location: "Location",
    download: "Download",
    remove: "Delete",
    noPreview: "No preview for this file type",
    // new folder
    folderTitle: "New folder",
    folderBody: "Created inside the current folder.",
    folderName: "Folder name",
    folderEmpty: "Enter a name.",
    folderInvalid: "A name cannot contain / \\ : * ? \" < > |",
    folderDuplicate: "Something with this name is already here.",
    folderReserved: "That name is not allowed.",
    create: "Create",
    cancel: "Cancel",
    genericError: "Something went wrong. Try again.",
    // delete
    deleteTitle: (name: string) => `Delete ${name}?`,
    deleteBodyFile: "The file is removed for everyone who can see this folder.",
    deleteBodyFolder: (n: number) => (n === 0 ? "The empty folder is removed." : n === 1 ? "The folder and the 1 item inside it are removed." : `The folder and the ${n} items inside it are removed.`),
    deleteConfirm: "Delete",
    kinds: {
      folder: "Folder",
      image: "Image",
      video: "Video",
      audio: "Audio",
      pdf: "PDF document",
      archive: "Archive",
      code: "Source file",
      sheet: "Spreadsheet",
      doc: "Document",
      text: "Text file",
      other: "File",
    },
  },
  ar: {
    title: "الملفات",
    root: "كل الملفات",
    folders: "المجلدات",
    breadcrumb: "المسار",
    search: "ابحث في هذا المجلد",
    view: "العرض",
    listView: "قائمة",
    gridView: "شبكة",
    upload: "رفع",
    newFolder: "مجلد جديد",
    name: "الاسم",
    modified: "آخر تعديل",
    size: "الحجم",
    items: (n: number) => (n === 1 ? "عنصر واحد" : n === 2 ? "عنصران" : n >= 3 && n <= 10 ? `${n} عناصر` : `${n} عنصرًا`),
    listLabel: "ملفات هذا المجلد",
    gridLabel: "ملفات هذا المجلد",
    emptyTitle: "هذا المجلد فارغ",
    emptyBody: "أفلت الملفات هنا أو استخدم زر الرفع.",
    noMatch: "لا يوجد ما يطابق بحثك هنا.",
    loading: "جارٍ تحميل الملفات",
    dropHere: "أفلت للرفع",
    folderWord: "مجلد",
    preview: "المعاينة",
    previewNone: "اختر ملفًا لمعاينته",
    closePreview: "إغلاق المعاينة",
    type: "النوع",
    location: "الموقع",
    download: "تنزيل",
    remove: "حذف",
    noPreview: "لا توجد معاينة لهذا النوع من الملفات",
    folderTitle: "مجلد جديد",
    folderBody: "يُنشأ داخل المجلد الحالي.",
    folderName: "اسم المجلد",
    folderEmpty: "أدخل اسمًا.",
    folderInvalid: "لا يجوز أن يحتوي الاسم على / \\ : * ? \" < > |",
    folderDuplicate: "يوجد هنا عنصر بهذا الاسم.",
    folderReserved: "هذا الاسم غير مسموح.",
    create: "إنشاء",
    cancel: "إلغاء",
    genericError: "حدث خطأ ما. حاول مرة أخرى.",
    deleteTitle: (name: string) => `حذف ${name}؟`,
    deleteBodyFile: "يُزال الملف لكل من يرى هذا المجلد.",
    deleteBodyFolder: (n: number) => (n === 0 ? "يُزال المجلد الفارغ." : n === 1 ? "يُزال المجلد والعنصر الواحد بداخله." : `يُزال المجلد و${n} عناصر بداخله.`),
    deleteConfirm: "حذف",
    kinds: {
      folder: "مجلد",
      image: "صورة",
      video: "فيديو",
      audio: "صوت",
      pdf: "مستند PDF",
      archive: "أرشيف",
      code: "ملف برمجي",
      sheet: "جدول بيانات",
      doc: "مستند",
      text: "ملف نصي",
      other: "ملف",
    },
  },
};

export type FileExplorerLabels = { [K in keyof typeof FILE_EXPLORER_STRINGS.en]: (typeof FILE_EXPLORER_STRINGS.en)[K] };
