// Same strings as the React component (packages/web/src/components/trends-feed).
import type { SourceHealth, SourceTier, TrendAction, TrendState } from "./trends-feed-math";

export const TRENDS_STRINGS = {
  en: {
    states: { new: "New", saved: "Saved", reviewed: "Reviewed", dismissed: "Dismissed" } as Record<TrendState, string>,
    tabs: "Topic state",
    actions: { save: "Save", review: "Mark reviewed", dismiss: "Dismiss", restore: "Restore" } as Record<TrendAction, string>,
    moreFor: (title: string) => `Actions for ${title}`,
    score: "Score",
    hot: "Hot",
    why: "Why it is trending",
    outlets: (n: number) => (n === 1 ? "1 outlet" : `${n} outlets`),
    items: (n: number) => (n === 1 ? "1 article" : `${n} articles`),
    showItems: (n: number) => `Show ${n === 1 ? "1 article" : `${n} articles`}`,
    hideItems: "Hide articles",
    open: "Open",
    failed: (action: string) => `Could not ${action.toLowerCase()}. Try again.`,
    emptyTitle: (state: string) => `No ${state.toLowerCase()} topics`,
    emptyBody: "Topics appear here as they are found.",
    today: "Today",
    yesterday: "Yesterday",
    tier: (n: number) => `Tier ${n}`,
    tierHint: { 1: "Primary sources. Preferred whenever one is working.", 2: "Backup sources. Used when tier 1 has nothing working.", 3: "Last resort. Used when tiers 1 and 2 have nothing working." } as Record<SourceTier, string>,
    active: "Active",
    activeNote: (n: number) => `Feeding the trends: tier ${n}`,
    fellBack: (from: string, to: number) => `${from} has no working source, so tier ${to} is being used.`,
    noneWorking: "No source is working, so no new topics will arrive.",
    health: { ok: "Working", degraded: "Slow", down: "Down" } as Record<SourceHealth, string>,
    enabled: (name: string) => `${name} enabled`,
    lastFetched: "Last fetched",
    never: "Never",
    perDay: (n: string) => `${n} a day`,
    enable: "Enable",
    disable: "Disable",
    retry: "Retry now",
    visit: "Open the site",
    sourcesEmpty: "No sources yet.",
    toggleFailed: "Could not change the source. Try again.",
    sources: "Sources",
  },
  ar: {
    states: { new: "جديدة", saved: "محفوظة", reviewed: "تمت مراجعتها", dismissed: "مستبعدة" } as Record<TrendState, string>,
    tabs: "حالة الموضوع",
    actions: { save: "حفظ", review: "تمت المراجعة", dismiss: "استبعاد", restore: "استعادة" } as Record<TrendAction, string>,
    moreFor: (title: string) => `إجراءات ${title}`,
    score: "الدرجة",
    hot: "رائج جدًا",
    why: "لماذا هو رائج",
    outlets: (n: number) => (n === 1 ? "منفذ واحد" : n === 2 ? "منفذان" : `${n} منافذ`),
    items: (n: number) => (n === 1 ? "مقال واحد" : n === 2 ? "مقالان" : `${n} مقالات`),
    showItems: (n: number) => `عرض ${n === 1 ? "مقال واحد" : n === 2 ? "مقالين" : `${n} مقالات`}`,
    hideItems: "إخفاء المقالات",
    open: "فتح",
    failed: (action: string) => `تعذّر تنفيذ «${action}». حاول مرة أخرى.`,
    emptyTitle: (state: string) => `لا مواضيع ${state}`,
    emptyBody: "تظهر المواضيع هنا عند رصدها.",
    today: "اليوم",
    yesterday: "أمس",
    tier: (n: number) => `المستوى ${n}`,
    tierHint: { 1: "المصادر الأساسية. تُفضَّل متى عمل أحدها.", 2: "مصادر احتياطية. تُستخدم عندما لا يعمل شيء في المستوى 1.", 3: "الملاذ الأخير. يُستخدم عندما لا يعمل شيء في المستويين 1 و2." } as Record<SourceTier, string>,
    active: "نشط",
    activeNote: (n: number) => `يغذّي الاتجاهات: المستوى ${n}`,
    fellBack: (from: string, to: number) => `لا يعمل أي مصدر في ${from}، لذا يُستخدم المستوى ${to}.`,
    noneWorking: "لا يعمل أي مصدر، فلن تصل مواضيع جديدة.",
    health: { ok: "يعمل", degraded: "بطيء", down: "متوقف" } as Record<SourceHealth, string>,
    enabled: (name: string) => `تفعيل ${name}`,
    lastFetched: "آخر جلب",
    never: "لم يُجلب بعد",
    perDay: (n: string) => `${n} يوميًا`,
    enable: "تفعيل",
    disable: "تعطيل",
    retry: "أعد المحاولة الآن",
    visit: "فتح الموقع",
    sourcesEmpty: "لا مصادر بعد.",
    toggleFailed: "تعذّر تغيير المصدر. حاول مرة أخرى.",
    sources: "المصادر",
  },
};

export type TrendsFeedLabels = typeof TRENDS_STRINGS.en;
