// Strings of the chat widget, English and Arabic (copied from the React STRINGS table).
export const chatWidgetStrings = {
  en: {
    title: "Chat with us",
    launcher: "Open chat",
    close: "Close chat",
    online: "Online",
    offline: "Offline",
    subtitleOnline: "We usually reply in a few minutes",
    subtitleOffline: "We are away, leave a message",
    greeting: "Hi! How can we help you today?",
    offlineGreeting: "We are not around right now. Leave your details and we will write back by email.",
    placeholder: "Write a message",
    attach: "Attach a file",
    removeFile: (name: string) => `Remove ${name}`,
    fileTooBig: (name: string, mb: string) => `${name} is larger than ${mb} MB`,
    sendFailed: "Could not send. Try again.",
    unread: (n: string) => `${n} unread`,
    startersLabel: "Quick questions",
    you: "You",
    typing: "The team is typing",
    formName: "Your name",
    formEmail: "Email",
    formMessage: "How can we help?",
    formSend: "Send message",
    formSent: "Thanks, we got it",
    formSentHint: "We will reply to your email as soon as we are back.",
    formAgain: "Send another",
    formInvalidEmail: "Enter a valid email address",
    formRequired: "Required",
  },
  ar: {
    title: "تحدث معنا",
    launcher: "فتح المحادثة",
    close: "إغلاق المحادثة",
    online: "متصل",
    offline: "غير متصل",
    subtitleOnline: "نرد عادةً خلال دقائق",
    subtitleOffline: "نحن بعيدون الآن، اترك رسالة",
    greeting: "مرحباً! كيف يمكننا مساعدتك اليوم؟",
    offlineGreeting: "لسنا متاحين الآن. اترك بياناتك وسنرد عليك عبر البريد الإلكتروني.",
    placeholder: "اكتب رسالة",
    attach: "إرفاق ملف",
    removeFile: (name: string) => `إزالة ${name}`,
    fileTooBig: (name: string, mb: string) => `حجم ${name} أكبر من ${mb} ميغابايت`,
    sendFailed: "تعذر الإرسال. حاول مرة أخرى.",
    unread: (n: string) => `${n} غير مقروءة`,
    startersLabel: "أسئلة سريعة",
    you: "أنت",
    typing: "الفريق يكتب",
    formName: "اسمك",
    formEmail: "البريد الإلكتروني",
    formMessage: "كيف نساعدك؟",
    formSend: "إرسال الرسالة",
    formSent: "شكراً، وصلتنا رسالتك",
    formSentHint: "سنرد على بريدك الإلكتروني فور عودتنا.",
    formAgain: "إرسال رسالة أخرى",
    formInvalidEmail: "أدخل بريداً إلكترونياً صحيحاً",
    formRequired: "مطلوب",
  },
};

export type ChatWidgetLabels = (typeof chatWidgetStrings)["en"];
