import { computed, type ComputedRef } from "vue";
import { useNasaq } from "../../provider";

export const AVAILABILITY_EDITOR_STRINGS = {
  en: {
    weekly: "Weekly hours",
    weeklyHint: "The hours patients can book. Breaks are taken out of them.",
    total: (m: number) => `${Math.floor(m / 60)} h ${m % 60 ? `${m % 60} min ` : ""}a week`,
    dayOn: (d: string) => `Open on ${d}`,
    closed: "Closed",
    hours: (m: number) => `${Math.floor(m / 60)} h${m % 60 ? ` ${m % 60} min` : ""}`,
    from: "From",
    to: "To",
    addHours: "Add hours",
    addBreak: "Add break",
    breaks: "Breaks",
    remove: "Remove",
    copyAll: "Copy to other open days",
    copied: "Copied",
    vacations: "Vacations and days off",
    vacationsHint: "No one can book these days.",
    pickDates: "Pick the days away",
    reason: "Reason (optional)",
    addVacation: "Add",
    noVacations: "No vacations planned.",
    daysCount: (n: number) => (n === 1 ? "1 day" : `${n} days`),
    save: "Save availability",
    saving: "Saving",
    reset: "Discard changes",
    saved: "Availability saved.",
    failed: "It could not be saved. Try again.",
    fix: "Fix these before saving",
    issue: {
      "end-before-start": "ends before it starts",
      "invalid-time": "has a time that is not valid",
      overlap: "overlaps another one",
      "break-outside-hours": "is outside the open hours",
      "vacation-order": "ends before it starts",
      "vacation-overlap": "overlaps another vacation",
      "no-hours": "is open but has no hours",
    } as Record<string, string>,
    hoursWord: "hours",
    breakWord: "break",
    vacationWord: "Vacation",
    startLabel: (n: number) => `Start ${n}`,
    endLabel: (n: number) => `End ${n}`,
  },
  ar: {
    weekly: "ساعات العمل الأسبوعية",
    weeklyHint: "الساعات التي يمكن للمرضى الحجز فيها. تُخصم الاستراحات منها.",
    total: (m: number) => `${Math.floor(m / 60)} س ${m % 60 ? `${m % 60} د ` : ""}في الأسبوع`,
    dayOn: (d: string) => `مفتوح يوم ${d}`,
    closed: "مغلق",
    hours: (m: number) => `${Math.floor(m / 60)} س${m % 60 ? ` ${m % 60} د` : ""}`,
    from: "من",
    to: "إلى",
    addHours: "إضافة ساعات",
    addBreak: "إضافة استراحة",
    breaks: "الاستراحات",
    remove: "حذف",
    copyAll: "نسخ إلى الأيام المفتوحة الأخرى",
    copied: "تم النسخ",
    vacations: "الإجازات وأيام الغياب",
    vacationsHint: "لا يمكن الحجز في هذه الأيام.",
    pickDates: "اختر أيام الغياب",
    reason: "السبب (اختياري)",
    addVacation: "إضافة",
    noVacations: "لا إجازات مخططة.",
    daysCount: (n: number) => (n === 1 ? "يوم واحد" : n === 2 ? "يومان" : n <= 10 ? `${n} أيام` : `${n} يومًا`),
    save: "حفظ أوقات العمل",
    saving: "جارٍ الحفظ",
    reset: "تجاهل التغييرات",
    saved: "تم حفظ أوقات العمل.",
    failed: "تعذّر الحفظ. حاول مجددًا.",
    fix: "صحّح هذه الأخطاء قبل الحفظ",
    issue: {
      "end-before-start": "ينتهي قبل أن يبدأ",
      "invalid-time": "به وقت غير صالح",
      overlap: "يتداخل مع آخر",
      "break-outside-hours": "خارج ساعات العمل",
      "vacation-order": "ينتهي قبل أن يبدأ",
      "vacation-overlap": "يتداخل مع إجازة أخرى",
      "no-hours": "مفتوح بلا ساعات",
    } as Record<string, string>,
    hoursWord: "ساعات العمل",
    breakWord: "استراحة",
    vacationWord: "إجازة",
    startLabel: (n: number) => `البداية ${n}`,
    endLabel: (n: number) => `النهاية ${n}`,
  },
};

export type AvailabilityEditorLabels = (typeof AVAILABILITY_EDITOR_STRINGS)["en"];

export function useAvailabilityEditorLabels(override?: () => Partial<AvailabilityEditorLabels> | undefined): ComputedRef<AvailabilityEditorLabels> {
  const nq = useNasaq();
  return computed(() => ({ ...AVAILABILITY_EDITOR_STRINGS[nq.locale.value.startsWith("ar") ? "ar" : "en"], ...override?.() }) as AvailabilityEditorLabels);
}
