"use client";
import { useOptionalNasaq } from "../../provider/nasaq-provider";
import type { WorkflowIssueCode, WorkflowStatus } from "./workflow-model";

/** Every string the canvas and its panels show. Pass `labels` to override any of them. */
export const CANVAS_STRINGS = {
  en: {
    canvas: "Workflow canvas",
    addStep: "Add step",
    validate: "Validation",
    noProblems: "No problems found",
    problems: (n: string) => `${n} to fix`,
    runs: "Executions",
    versions: "Versions",
    run: "Run",
    save: "Save",
    saving: "Saving",
    saved: "Saved",
    unsaved: "Unsaved changes",
    tidy: "Tidy up",
    readOnly: "Read only",
    runBlocked: "Fix the errors before running",
    previewing: (v: string) => `Previewing version ${v}. Editing is off.`,
    exitPreview: "Back to current",
    pickerTitle: "What happens next?",
    pickerStart: "Choose how this workflow starts.",
    pickerAfter: (name: string) => `Choose a step to add after ${name}.`,
    pickerSearch: "Search steps",
    pickerNone: (q: string) => `No step matches "${q}".`,
    close: "Close",
    settings: "Settings",
    output: "Output",
    name: "Name",
    nameHelp: "Shown on the node. Leave empty to use the step's own name.",
    noFields: "This step has no settings.",
    unknownType: "Unknown step",
    remove: "Remove step",
    addNext: "Add next step",
    required: "Required",
    noOutput: "Nothing to show. This step did not run in the selected execution.",
    runStatus: "Status",
    duration: "Duration",
    items: "Items",
    errorLabel: "Error",
    insertHere: "Insert a step here",
    addAfter: (name: string) => `Add a step after ${name}`,
    runsTitle: "Executions",
    runsHint: "Pick one to see how it ran on the canvas.",
    runsNone: "No executions yet. Run the workflow to see one here.",
    replay: "Replay",
    stopReplay: "Stop",
    clearOverlay: "Hide overlay",
    seconds: (n: string) => `${n} s`,
    minutes: (n: string) => `${n} min`,
    milliseconds: (n: string) => `${n} ms`,
    versionsTitle: "Version history",
    versionsHint: "Every save, newest first. Preview one on the canvas, then restore it.",
    versionLabel: (v: string) => `Version ${v}`,
    current: "Current",
    preview: "Preview",
    restore: "Restore",
    restoring: "Restoring",
    restoreTitle: (v: string) => `Restore version ${v}?`,
    restoreBody: "The current workflow is saved as a new version first, so you can come back to it.",
    cancel: "Cancel",
    by: (name: string) => `by ${name}`,
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    fit: "Fit to view",
    lock: "Lock the canvas",
    unlock: "Unlock the canvas",
    minimap: "Overview map",
    status: {
      idle: "Not run",
      running: "Running",
      success: "Succeeded",
      error: "Failed",
      skipped: "Skipped",
      waiting: "Waiting",
    } satisfies Record<WorkflowStatus, string>,
    issue: {
      empty: () => "The workflow is empty. Add a trigger to start it.",
      "no-trigger": () => "There is no trigger. Add a step that starts the workflow.",
      "multiple-triggers": (node: string) => `${node} is a second trigger. A workflow has one.`,
      "unknown-type": (node: string) => `${node} uses a step that is not installed.`,
      "missing-field": (node: string, field: string) => `${node} needs "${field}".`,
      unreachable: (node: string) => `${node} is not connected to the trigger, so it never runs.`,
      cycle: (node: string) => `${node} is part of a loop. Steps cannot lead back to themselves.`,
      "trigger-input": (node: string) => `${node} is a trigger, so nothing can lead into it.`,
    } satisfies Record<WorkflowIssueCode, (node: string, field: string) => string>,
  },
  ar: {
    canvas: "لوحة سير العمل",
    addStep: "إضافة خطوة",
    validate: "التحقق",
    noProblems: "لا توجد مشكلات",
    problems: (n: string) => `${n} للإصلاح`,
    runs: "التنفيذات",
    versions: "الإصدارات",
    run: "تشغيل",
    save: "حفظ",
    saving: "جارٍ الحفظ",
    saved: "تم الحفظ",
    unsaved: "تغييرات غير محفوظة",
    tidy: "ترتيب تلقائي",
    readOnly: "للقراءة فقط",
    runBlocked: "أصلح الأخطاء قبل التشغيل",
    previewing: (v: string) => `معاينة الإصدار ${v}. التعديل متوقف.`,
    exitPreview: "العودة إلى الحالي",
    pickerTitle: "ماذا يحدث بعد ذلك؟",
    pickerStart: "اختر كيف يبدأ سير العمل هذا.",
    pickerAfter: (name: string) => `اختر خطوة لإضافتها بعد ${name}.`,
    pickerSearch: "ابحث في الخطوات",
    pickerNone: (q: string) => `لا توجد خطوة تطابق "${q}".`,
    close: "إغلاق",
    settings: "الإعدادات",
    output: "المخرجات",
    name: "الاسم",
    nameHelp: "يظهر على العقدة. اتركه فارغًا لاستخدام اسم الخطوة نفسها.",
    noFields: "هذه الخطوة بلا إعدادات.",
    unknownType: "خطوة غير معروفة",
    remove: "حذف الخطوة",
    addNext: "إضافة الخطوة التالية",
    required: "مطلوب",
    noOutput: "لا شيء لعرضه. لم تعمل هذه الخطوة في التنفيذ المحدد.",
    runStatus: "الحالة",
    duration: "المدة",
    items: "العناصر",
    errorLabel: "الخطأ",
    insertHere: "أدرج خطوة هنا",
    addAfter: (name: string) => `أضف خطوة بعد ${name}`,
    runsTitle: "التنفيذات",
    runsHint: "اختر تنفيذًا لترى كيف جرى على اللوحة.",
    runsNone: "لا تنفيذات بعد. شغّل سير العمل لتظهر هنا.",
    replay: "إعادة التشغيل",
    stopReplay: "إيقاف",
    clearOverlay: "إخفاء الطبقة",
    seconds: (n: string) => `${n} ث`,
    minutes: (n: string) => `${n} د`,
    milliseconds: (n: string) => `${n} م.ث`,
    versionsTitle: "سجل الإصدارات",
    versionsHint: "كل عملية حفظ، الأحدث أولًا. عاين إصدارًا على اللوحة ثم استرجعه.",
    versionLabel: (v: string) => `الإصدار ${v}`,
    current: "الحالي",
    preview: "معاينة",
    restore: "استرجاع",
    restoring: "جارٍ الاسترجاع",
    restoreTitle: (v: string) => `استرجاع الإصدار ${v}؟`,
    restoreBody: "يُحفظ سير العمل الحالي كإصدار جديد أولًا، فيمكنك العودة إليه.",
    cancel: "إلغاء",
    by: (name: string) => `بواسطة ${name}`,
    zoomIn: "تكبير",
    zoomOut: "تصغير",
    fit: "ملاءمة العرض",
    lock: "قفل اللوحة",
    unlock: "فتح اللوحة",
    minimap: "خريطة عامة",
    status: {
      idle: "لم يعمل",
      running: "قيد التشغيل",
      success: "نجح",
      error: "فشل",
      skipped: "تم تخطيه",
      waiting: "بالانتظار",
    } satisfies Record<WorkflowStatus, string>,
    issue: {
      empty: () => "سير العمل فارغ. أضف مُشغِّلًا ليبدأ.",
      "no-trigger": () => "لا يوجد مُشغِّل. أضف خطوة تبدأ سير العمل.",
      "multiple-triggers": (node: string) => `${node} مُشغِّل ثانٍ. لسير العمل مُشغِّل واحد فقط.`,
      "unknown-type": (node: string) => `${node} تستخدم خطوة غير مثبّتة.`,
      "missing-field": (node: string, field: string) => `${node} تحتاج إلى "${field}".`,
      unreachable: (node: string) => `${node} غير متصلة بالمُشغِّل، فلن تعمل.`,
      cycle: (node: string) => `${node} جزء من حلقة. لا يمكن لخطوة أن تعود إلى نفسها.`,
      "trigger-input": (node: string) => `${node} مُشغِّل، فلا يمكن توصيل شيء بها.`,
    } satisfies Record<WorkflowIssueCode, (node: string, field: string) => string>,
  },
};

export type WorkflowCanvasLabels = typeof CANVAS_STRINGS.en;

export function useCanvasLabels(labels?: Partial<WorkflowCanvasLabels>): { t: WorkflowCanvasLabels; ar: boolean } {
  const ar = useOptionalNasaq()?.locale.startsWith("ar") ?? false;
  return { t: { ...CANVAS_STRINGS[ar ? "ar" : "en"], ...labels }, ar };
}
