// Built-in English and Arabic strings of FeatureFlagDetail.
export const STRINGS = {
  en: {
    tabEnvironments: "Environments",
    tabTargeting: "Targeting",
    tabVariants: "Variants",
    tabHistory: "History",
    stateKilled: "Killed",
    stateOn: "On",
    statePartial: "Rolling out",
    stateOff: "Off",
    kill: "Kill switch",
    killTitle: "Kill this flag everywhere?",
    killBody: "It turns off in every environment at once, whatever the switches and rules say. Turn it back on with Restore.",
    reasonLabel: "Reason (kept in the history)",
    reasonPlaceholder: "Errors after the last deploy",
    killConfirm: "Kill flag",
    cancel: "Cancel",
    killedTitle: "This flag is killed",
    killedBody: "It is off for everyone in every environment.",
    restore: "Restore",
    envTitle: "Environments",
    envDescription: "Switch the flag per environment and choose how many users get it.",
    enabled: "Enabled",
    rollout: "Rollout",
    rolloutOf: (env: string) => `Rollout in ${env}`,
    rolloutHint: "Users are picked by a stable hash of their id, so raising the percentage keeps the ones who already have it.",
    targetingTitle: "Targeting rules",
    targetingDescription: "Serve a variant to specific users. The first rule that matches wins and skips the rollout.",
    noRules: "No targeting rules. Everyone follows the rollout.",
    rule: (n: number) => `Rule ${n}`,
    addRule: "Add rule",
    removeRule: (n: number) => `Remove rule ${n}`,
    moveRuleUp: (n: number) => `Move rule ${n} up`,
    moveRuleDown: (n: number) => `Move rule ${n} down`,
    saveRules: "Save targeting",
    fixRules: "Finish or remove the rules that are incomplete.",
    evaluated: "the flag is evaluated",
    serve: "Serve variant",
    serveOn: "Serve the flag",
    variantField: "Variant",
    variantsTitle: "Variants",
    variantsDescription: "Split the users who get the flag between values. Only the ratio of the weights matters.",
    noVariants: "No variants: the flag is a plain on/off.",
    variantKey: "Key",
    variantWeight: "Weight",
    variantShare: "Share",
    addVariant: "Add variant",
    removeVariant: (k: string) => `Remove variant ${k}`,
    saveVariants: "Save variants",
    keyInvalid: "Keys are lowercase letters, digits, dots, dashes and underscores.",
    keyDuplicate: "Each key can be used once.",
    saved: "Saved.",
    failed: "Could not save this. Try again.",
    historyTitle: "Audit history",
    updated: "Updated",
  },
  ar: {
    tabEnvironments: "البيئات",
    tabTargeting: "الاستهداف",
    tabVariants: "المتغيّرات",
    tabHistory: "السجل",
    stateKilled: "موقوف طارئًا",
    stateOn: "يعمل",
    statePartial: "إطلاق تدريجي",
    stateOff: "متوقف",
    kill: "الإيقاف الطارئ",
    killTitle: "إيقاف هذا المفتاح في كل مكان؟",
    killBody: "سيتوقف في كل البيئات دفعة واحدة مهما كانت المفاتيح والقواعد. أعده بزر الاستعادة.",
    reasonLabel: "السبب (يُحفظ في السجل)",
    reasonPlaceholder: "أخطاء بعد آخر نشر",
    killConfirm: "إيقاف المفتاح",
    cancel: "إلغاء",
    killedTitle: "هذا المفتاح موقوف طارئًا",
    killedBody: "هو متوقف للجميع في كل البيئات.",
    restore: "استعادة",
    envTitle: "البيئات",
    envDescription: "شغّل المفتاح لكل بيئة واختر نسبة المستخدمين الذين يحصلون عليه.",
    enabled: "مفعّل",
    rollout: "الإطلاق",
    rolloutOf: (env: string) => `الإطلاق في ${env}`,
    rolloutHint: "يُختار المستخدمون بتجزئة ثابتة لمعرّفهم، فرفع النسبة يُبقي من حصلوا عليه سابقًا.",
    targetingTitle: "قواعد الاستهداف",
    targetingDescription: "قدّم متغيّرًا لمستخدمين محددين. أول قاعدة تنطبق تفوز وتتجاوز الإطلاق.",
    noRules: "لا قواعد استهداف. الجميع يتبع الإطلاق.",
    rule: (n: number) => `القاعدة ${n}`,
    addRule: "إضافة قاعدة",
    removeRule: (n: number) => `حذف القاعدة ${n}`,
    moveRuleUp: (n: number) => `نقل القاعدة ${n} للأعلى`,
    moveRuleDown: (n: number) => `نقل القاعدة ${n} للأسفل`,
    saveRules: "حفظ الاستهداف",
    fixRules: "أكمل القواعد الناقصة أو احذفها.",
    evaluated: "يُقيَّم المفتاح",
    serve: "تقديم متغيّر",
    serveOn: "تقديم المفتاح",
    variantField: "المتغيّر",
    variantsTitle: "المتغيّرات",
    variantsDescription: "وزّع المستخدمين الذين يحصلون على المفتاح بين قيم. المهم هو نسبة الأوزان فقط.",
    noVariants: "لا متغيّرات: المفتاح تشغيل وإيقاف فقط.",
    variantKey: "المفتاح",
    variantWeight: "الوزن",
    variantShare: "الحصة",
    addVariant: "إضافة متغيّر",
    removeVariant: (k: string) => `حذف المتغيّر ${k}`,
    saveVariants: "حفظ المتغيّرات",
    keyInvalid: "المفاتيح حروف صغيرة وأرقام ونقاط وشرطات.",
    keyDuplicate: "يُستخدم كل مفتاح مرة واحدة.",
    saved: "تم الحفظ.",
    failed: "تعذّر الحفظ. حاول مرة أخرى.",
    historyTitle: "سجل التدقيق",
    updated: "آخر تحديث",
  },
};

export type FeatureFlagDetailLabels = typeof STRINGS.en;
