// Builds Nasaq tokens from DTCG sources (src/dtcg) with Style Dictionary 5.
//   dist/tokens.css      CSS custom properties (--nq-*, shadcn bridge, --grid-* aliases)
//   dist/theme.css       Tailwind v4 @theme inline mapping + dark variant
//   src/generated/*.ts   typed values for JS and React Native
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import StyleDictionary from "style-dictionary";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = (f) => join(root, "src/dtcg", f);
const shared = ["primitives.json", "brands.json", "expressions.json", "densities.json", "typography.json"].map(src);

/** Resolve all references for one theme and return a plain nested value tree. */
async function resolve(theme) {
  const sd = new StyleDictionary({
    source: [...shared, src(`theme.${theme}.json`)],
    log: { verbosity: "silent", warnings: "disabled" },
    platforms: { js: { transforms: [] } },
  });
  const tokens = await sd.exportPlatform("js");
  const strip = (node) => {
    if (node && typeof node === "object" && "$value" in node) return node.$value;
    if (node && typeof node === "object") {
      const out = {};
      for (const [k, v] of Object.entries(node)) if (!k.startsWith("$")) out[k] = strip(v);
      return out;
    }
    return node;
  };
  return strip(tokens);
}

const light = await resolve("light");
const dark = await resolve("dark");

const dim = (v) => (typeof v === "object" && v && "unit" in v ? `${v.value}${v.unit}` : String(v));
const px = (v) => (typeof v === "object" && v && "unit" in v ? v.value : v);
const fam = (list) => list.map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(", ");
const decl = (entries, indent = "  ") => entries.map(([k, v]) => `${indent}--nq-${k}: ${v};`).join("\n");
const block = (sel, entries) => `${sel} {\n${decl(entries)}\n}\n`;

const brandKeys = Object.keys(light.brand);
const semantic = (t) => Object.entries(t.semantic);

// ---------- CSS ----------
const css = [];
css.push(`/* Nasaq tokens — generated by packages/tokens/scripts/build.mjs. Do not edit. */\n`);

// Primitives (theme-independent).
const prim = [];
for (const [name, scale] of Object.entries(light.color)) {
  if (name === "tag") continue;
  if (typeof scale === "string") prim.push([`color-${name}`, scale]);
  else for (const [step, v] of Object.entries(scale)) prim.push([`color-${name}-${step}`, v]);
}
for (const [k, v] of Object.entries(light.space)) prim.push([`space-${k}`, dim(v)]);
for (const [k, v] of Object.entries(light.layout)) prim.push([`layout-${k}`, dim(v)]);
for (const part of ["titlebar", "inset"])
  for (const [os, v] of Object.entries(light.window[part])) prim.push([`window-${part}-${os}`, dim(v)]);
for (const [k, v] of Object.entries(light.duration)) prim.push([`duration-${k}`, dim(v)]);
for (const [k, v] of Object.entries(light.font)) prim.push([`font-${k}`, fam(v)]);
prim.push(["ease", "cubic-bezier(0.2, 0, 0, 1)"]);
css.push(block(":root", prim));
// Window chrome follows <html data-platform>; web and mobile get no title bar.
css.push(block(":root", [["window-titlebar", "0px"], ["window-inset", "0px"]]));
for (const os of Object.keys(light.window.titlebar))
  css.push(block(`[data-platform="${os}"]`, [["window-titlebar", `var(--nq-window-titlebar-${os})`], ["window-inset", `var(--nq-window-inset-${os})`]]));

// Semantic themes.
const tagDecls = (mode) =>
  Object.entries(light.color.tag).flatMap(([hue, v]) => [
    [`tag-${hue}`, v[mode]],
    [`tag-${hue}-soft`, `color-mix(in oklab, ${v[mode]} ${mode === "light" ? 14 : 22}%, transparent)`],
  ]);
// Derived per theme. Hover/selected are fg overlays so they read on every surface level;
// status soft fills are tints of the status hue. elevated/ok/warn stay as aliases for older code.
const STATUSES = ["success", "warning", "danger", "info"];
const derived = (mode) => [
  ["hover", `color-mix(in oklab, var(--nq-fg) ${mode === "light" ? 5 : 6}%, transparent)`],
  ["selected", `color-mix(in oklab, var(--nq-fg) ${mode === "light" ? 8 : 10}%, transparent)`],
  ...STATUSES.map((st) => [`${st}-soft`, `color-mix(in oklab, var(--nq-${st}) ${mode === "light" ? 12 : 18}%, transparent)`]),
  ["elevated", "var(--nq-surface-overlay)"],
  ["ok", "var(--nq-success)"], ["ok-text", "var(--nq-success-text)"],
  ["warn", "var(--nq-warning)"], ["warn-text", "var(--nq-warning-text)"],
];
const DERIVED_NAMES = derived("light").map(([k]) => k);
const themeDecls = (t, mode) => [...semantic(t), ...derived(mode), ...tagDecls(mode), ["color-scheme", mode]];
css.push(block(`:root,\n[data-theme="light"]`, themeDecls(light, "light")));
css.push(block(`.dark,\n[data-theme="dark"]`, themeDecls(dark, "dark")));
css.push(`@media (prefers-color-scheme: dark) {\n${block(`  [data-theme="system"]`, themeDecls(dark, "dark"))}}\n`);
// color-scheme is a real property, not a custom property:
const cssText0 = css.join("\n").replaceAll("--nq-color-scheme:", "color-scheme:");
css.length = 0;
css.push(cssText0);

// Brand raw values. :root carries the default brand (nasaq).
const brandRaw = (b) => [
  ["brand-l", b.brand.light], ["brand-d", b.brand.dark],
  ["action-l", b.action.light], ["action-d", b.action.dark],
  ["on-action-l", b["on-action"].light], ["on-action-d", b["on-action"].dark],
  ["accent-brand", b.accent],
];
css.push(block(":root", brandRaw(light.brand.nasaq)));
for (const key of brandKeys) css.push(block(`[data-brand="${key}"]`, brandRaw(light.brand[key])));

// Derived values are re-declared on every scoping element so nested brand/theme scopes resolve locally.
const scopeLight = `:root,\n[data-brand],\n[data-theme="light"]`;
const scopeDark = `.dark,\n[data-theme="dark"],\n.dark [data-brand],\n[data-theme="dark"] [data-brand]`;
const pick = (m) => [
  ["brand", `var(--nq-brand-${m})`],
  ["action", `var(--nq-action-${m})`],
  ["on-action", `var(--nq-on-action-${m})`],
  // The one primary action. Named apart from brand (identity) and success (status) on purpose.
  ["primary-action", `var(--nq-action-${m})`],
];
css.push(block(scopeLight, pick("l")));
css.push(block(scopeDark, pick("d")));
css.push(`@media (prefers-color-scheme: dark) {\n${block(`  [data-theme="system"],\n  [data-theme="system"] [data-brand]`, pick("d"))}}\n`);

// Expressions (default grid).
const expr = (e) => [
  ...Object.entries(e.radius).map(([k, v]) => [`radius-${k}`, dim(v)]),
  ["hatch", String(e.hatch)],
];
css.push(block(`:root,\n[data-expression="grid"]`, expr(light.expression.grid)));
css.push(block(`[data-expression="native"]`, expr(light.expression.native)));

// Densities (default compact). Touch devices get a 44px floor via --nq-touch-min.
const dens = (d) => Object.entries(d).map(([k, v]) => [k, dim(v)]);
css.push(block(`:root,\n[data-density="compact"]`, dens(light.density.compact)));
css.push(block(`[data-density="comfortable"]`, dens(light.density.comfortable)));
css.push(block(`[data-density="dense"]`, dens(light.density.dense)));
css.push(`@media (pointer: coarse) {\n  :root {\n    --nq-touch-min: 44px;\n  }\n}\n`);

// Typography roles; Arabic metrics wherever lang="ar".
const typeDecls = (set, arabic) =>
  Object.entries(set).flatMap(([role, t]) => [
    [`type-${role}-size`, `${t.size / 16}rem`],
    [`type-${role}-line`, String(t.line)],
    [`type-${role}-weight`, String(t.weight)],
    [`type-${role}-tracking`, `${t.tracking}em`],
  ]).concat(arabic ? [["font-ui", "var(--nq-font-arabic)"], ["font-eyebrow", "var(--nq-font-arabic)"], ["eyebrow-transform", "none"]] : [["font-ui", "var(--nq-font-sans)"], ["font-eyebrow", "var(--nq-font-mono)"], ["eyebrow-transform", "uppercase"]]);
css.push(block(":root", typeDecls(light.type.latin, false)));
css.push(block(`[lang|="ar"]`, typeDecls(light.type.arabic, true)));
// The native expression drops the mono uppercase eyebrow.
css.push(
  block(`[data-expression="native"]`, [
    ["font-eyebrow", "var(--nq-font-ui)"],
    ["eyebrow-transform", "none"],
    ["type-eyebrow-size", "var(--nq-type-caption-size)"],
    ["type-eyebrow-tracking", "0em"],
  ]),
);

// Bridges: shadcn variables and grid compatibility aliases.
const bridge = {
  background: "bg", foreground: "fg",
  card: "surface", "card-foreground": "fg",
  popover: "surface-overlay", "popover-foreground": "fg",
  primary: "action", "primary-foreground": "on-action",
  secondary: "surface-soft", "secondary-foreground": "fg",
  muted: "surface-soft", "muted-foreground": "fg-muted",
  accent: "hover", "accent-foreground": "fg",
  destructive: "danger-solid", "destructive-foreground": "on-danger",
  border: "line", input: "line", ring: "focus",
  "chart-1": "action", "chart-2": "accent", "chart-3": "tag-teal", "chart-4": "tag-violet", "chart-5": "tag-gray",
  sidebar: "surface", "sidebar-foreground": "fg-body",
  "sidebar-primary": "action", "sidebar-primary-foreground": "on-action",
  "sidebar-accent": "selected", "sidebar-accent-foreground": "fg",
  "sidebar-border": "line", "sidebar-ring": "focus",
};
const grid = {
  bg: "bg", card: "surface", soft: "surface-soft", line: "line", fg: "fg", body: "fg-body", muted: "fg-muted",
  elevated: "surface-overlay", brand: "brand", action: "action", "on-action": "on-action", "brand-accent": "accent",
  ok: "success", warn: "warning", danger: "danger", info: "info",
};
const bridgeScope = `:root,\n[data-brand],\n[data-theme],\n.dark`;
css.push(
  `${bridgeScope} {\n` +
    Object.entries(bridge).map(([k, v]) => `  --${k}: var(--nq-${v});`).join("\n") +
    `\n  --radius: var(--nq-radius-control);\n` +
    Object.entries(grid).map(([k, v]) => `  --grid-${k}: var(--nq-${v});`).join("\n") +
    `\n}\n`,
);

// ---------- Tailwind v4 theme ----------
const colorNames = [
  ...Object.keys(light.semantic), ...DERIVED_NAMES, "brand", "action", "on-action", "primary-action",
  ...Object.keys(light.color.tag).flatMap((h) => [`tag-${h}`, `tag-${h}-soft`]),
];
const theme = `/* Nasaq Tailwind v4 theme — generated. Import after "tailwindcss" and "@fadymondy/nasaq/tokens.css". */
@custom-variant dark (&:where(.dark, .dark *, [data-theme="dark"], [data-theme="dark"] *));

@theme inline {
${Object.keys(bridge).map((k) => `  --color-${k}: var(--${k});`).join("\n")}
${colorNames.map((c) => `  --color-nq-${c}: var(--nq-${c});`).join("\n")}

  --font-sans: var(--nq-font-ui);
  --font-mono: var(--nq-font-mono);
  --font-arabic: var(--nq-font-arabic);

  --radius-surface: var(--nq-radius-surface);
  --radius-card: var(--nq-radius-card);
  --radius-control: var(--nq-radius-control);
  --radius-floating: var(--nq-radius-floating);
  --radius-sm: calc(var(--nq-radius-control) - 2px);
  --radius-md: var(--nq-radius-control);
  --radius-lg: var(--nq-radius-floating);

${Object.keys(light.type.latin).map((r) => `  --text-${r}: var(--nq-type-${r}-size);\n  --text-${r}--line-height: var(--nq-type-${r}-line);\n  --text-${r}--font-weight: var(--nq-type-${r}-weight);\n  --text-${r}--letter-spacing: var(--nq-type-${r}-tracking);`).join("\n")}

  --spacing-control: var(--nq-control);
  --spacing-control-sm: var(--nq-control-sm);
  --spacing-row: var(--nq-row);
  --spacing-nav-row: var(--nq-nav-row);
  --spacing-page: var(--nq-page-pad);
  --spacing-header: var(--nq-header);
  --spacing-shell: var(--nq-shell-pad);
  --spacing-rail: var(--nq-layout-rail);
  --container-column: var(--nq-layout-column);

  --ease-nq: var(--nq-ease);
  --default-transition-duration: var(--nq-duration-fast);
}
`;

// ---------- TypeScript ----------
const toTs = (name, value) => `export const ${name} = ${JSON.stringify(value, null, 2)} as const;\n`;
const brandsTs = Object.fromEntries(
  brandKeys.map((k) => {
    const b = light.brand[k];
    return [k, { brand: b.brand, action: b.action, onAction: b["on-action"], accent: b.accent }];
  }),
);
const dimsToPx = (o) => Object.fromEntries(Object.entries(o).map(([k, v]) => [k, px(v)]));
const ts = [
  "// Generated by packages/tokens/scripts/build.mjs. Do not edit.\n",
  toTs("color", Object.fromEntries(Object.entries(light.color).filter(([k]) => k !== "tag"))),
  toTs("tag", light.color.tag),
  toTs("space", dimsToPx(light.space)),
  toTs("layout", dimsToPx(light.layout)),
  toTs("chrome", { titlebar: dimsToPx(light.window.titlebar), inset: dimsToPx(light.window.inset) }),
  toTs("duration", dimsToPx(light.duration)),
  toTs("font", light.font),
  toTs("themes", { light: light.semantic, dark: dark.semantic }),
  toTs("brands", brandsTs),
  toTs("expressions", Object.fromEntries(Object.entries(light.expression).map(([k, e]) => [k, { radius: dimsToPx(e.radius), hatch: e.hatch === 1 }]))),
  toTs("densities", Object.fromEntries(Object.entries(light.density).map(([k, d]) => [k, dimsToPx(d)]))),
  toTs("typography", light.type),
].join("\n");

await mkdir(join(root, "dist"), { recursive: true });
await mkdir(join(root, "src/generated"), { recursive: true });
await writeFile(join(root, "dist/tokens.css"), css.join("\n"));
await writeFile(join(root, "dist/theme.css"), theme);
await writeFile(join(root, "src/generated/tokens.ts"), ts);
console.log(`nasaq tokens: ${brandKeys.length} brands, ${Object.keys(light.semantic).length} semantic colours, 2 themes`);
