import { computed } from "vue";
import { useNasaq } from "../../provider";

/** Every built-in word of ProjectView: the header and tabs, then the project-level tabs (memory, vault, GitHub, activity) and settings pages. */
const BASE = {
  en: {
    key: "Key",
    client: "Client",
    members: "Members",
    start: "Starts",
    due: "Due",
    noDates: "No dates",
    progress: "Progress",
    newIssue: "New issue",
    newIssueHint: "Give it a title. You can fill in the rest on the issue.",
    title: "Title",
    type: "Type",
    priority: "Priority",
    create: "Create",
    cancel: "Cancel",
    save: "Save",
    tabs: { overview: "Overview", board: "Board", list: "List", timeline: "Timeline", time: "Time", ai: "AI cost", files: "Files", settings: "Settings" },
    statuses: { planning: "Planning", active: "Active", "on-hold": "On hold", completed: "Completed", archived: "Archived" },
    // Overview
    open: "Open issues",
    done: "Done",
    overdue: "Overdue",
    byStatus: "Open issues by status",
    byStatusHint: "Where the work sits now",
    burndown: "Burndown",
    burndownHint: "Open issues per day against the ideal line",
    remaining: "Remaining",
    ideal: "Ideal",
    recent: "Recent activity",
    noActivity: "Nothing has happened yet",
    budget: "Budget",
    budgetHint: "Spent against the budget",
    spent: "Spent",
    left: "Left",
    over: "Over budget",
    noBudget: "No budget set for this project.",
    issues: "Issues",
    // List
    listLabel: "Issues",
    search: "Search issues…",
    colKey: "Key",
    colTitle: "Title",
    colStatus: "Status",
    colPriority: "Priority",
    colAssignee: "Assignee",
    colDue: "Due",
    colEstimate: "Estimate (h)",
    unassigned: "Unassigned",
    emptyIssues: "No issues yet",
    emptyIssuesHint: "Create the first issue to start the board.",
    openIssue: "Open",
    copyKey: "Copy key",
    deleteIssue: "Delete",
    actions: "Actions",
    boardLabel: "Issue board",
    boardEmpty: "No issues",
    // Timeline
    scheduleLabel: "Issue schedule",
    scheduleEmpty: "Nothing scheduled",
    scheduleEmptyHint: "Give issues a due date to see them here.",
    unscheduled: "Without dates",
    today: "Today",
    notes: "Notes and calls",
    // Files
    filesLabel: "Project files",
    fileName: "Name",
    fileSize: "Size",
    fileBy: "Added by",
    fileAt: "Added",
    upload: "Upload",
    download: "Download",
    deleteFile: "Delete",
    noFiles: "No files yet",
    noFilesHint: "Upload contracts, briefs and assets.",
    // Settings
    details: "Project details",
    name: "Name",
    status: "Status",
    startDate: "Start date",
    dueDate: "Due date",
    budgetTotal: "Budget",
    workflow: "Workflow",
    saved: "Saved",
  },
  ar: {
    key: "الرمز",
    client: "العميل",
    members: "الأعضاء",
    start: "يبدأ",
    due: "الاستحقاق",
    noDates: "بلا تواريخ",
    progress: "التقدم",
    newIssue: "مهمة جديدة",
    newIssueHint: "اكتب عنوانًا. يمكنك إكمال الباقي داخل المهمة.",
    title: "العنوان",
    type: "النوع",
    priority: "الأولوية",
    create: "إنشاء",
    cancel: "إلغاء",
    save: "حفظ",
    tabs: { overview: "نظرة عامة", board: "اللوحة", list: "القائمة", timeline: "الجدول الزمني", time: "الوقت", ai: "تكلفة الذكاء الاصطناعي", files: "الملفات", settings: "الإعدادات" },
    statuses: { planning: "قيد التخطيط", active: "نشط", "on-hold": "معلّق", completed: "مكتمل", archived: "مؤرشف" },
    open: "مهام مفتوحة",
    done: "منجزة",
    overdue: "متأخرة",
    byStatus: "المهام المفتوحة حسب الحالة",
    byStatusHint: "أين يقف العمل الآن",
    burndown: "منحنى الإنجاز",
    burndownHint: "المهام المفتوحة كل يوم مقابل الخط المثالي",
    remaining: "المتبقي",
    ideal: "المثالي",
    recent: "آخر النشاط",
    noActivity: "لم يحدث شيء بعد",
    budget: "الميزانية",
    budgetHint: "المصروف مقابل الميزانية",
    spent: "المصروف",
    left: "المتبقي",
    over: "تجاوز الميزانية",
    noBudget: "لا توجد ميزانية لهذا المشروع.",
    issues: "المهام",
    listLabel: "المهام",
    search: "ابحث في المهام…",
    colKey: "الرمز",
    colTitle: "العنوان",
    colStatus: "الحالة",
    colPriority: "الأولوية",
    colAssignee: "المسؤول",
    colDue: "الاستحقاق",
    colEstimate: "التقدير (س)",
    unassigned: "غير مسند",
    emptyIssues: "لا توجد مهام بعد",
    emptyIssuesHint: "أنشئ أول مهمة لتبدأ اللوحة.",
    openIssue: "فتح",
    copyKey: "نسخ الرمز",
    deleteIssue: "حذف",
    actions: "إجراءات",
    boardLabel: "لوحة المهام",
    boardEmpty: "لا مهام",
    scheduleLabel: "جدول المهام",
    scheduleEmpty: "لا شيء مجدول",
    scheduleEmptyHint: "أضف موعد استحقاق للمهام لتظهر هنا.",
    unscheduled: "بلا تواريخ",
    today: "اليوم",
    notes: "الملاحظات والمكالمات",
    filesLabel: "ملفات المشروع",
    fileName: "الاسم",
    fileSize: "الحجم",
    fileBy: "أضافه",
    fileAt: "أُضيف",
    upload: "رفع",
    download: "تنزيل",
    deleteFile: "حذف",
    noFiles: "لا توجد ملفات بعد",
    noFilesHint: "ارفع العقود والملخصات والأصول.",
    details: "تفاصيل المشروع",
    name: "الاسم",
    status: "الحالة",
    startDate: "تاريخ البدء",
    dueDate: "تاريخ الاستحقاق",
    budgetTotal: "الميزانية",
    workflow: "مسار العمل",
    saved: "تم الحفظ",
  },
};

const EXTRA = {
  en: {
    tabs: { activity: "Activity", memory: "Memory", vault: "Vault", github: "GitHub" },
    // Memory
    memoryTitle: "Project memory",
    memoryHint: "Facts and decisions worth remembering about this project.",
    memorySearch: "Search memory",
    memoryAllKinds: "All",
    memoryKinds: { fact: "Fact", decision: "Decision" },
    memoryKindsPlural: { fact: "Facts", decision: "Decisions" },
    memoryAdd: "Remember something",
    memoryEditTitle: "Edit memory",
    memoryAddTitle: "Remember something",
    memoryText: "What to remember",
    memoryTags: "Tags",
    memoryTagsHint: "Separate with commas.",
    memoryKind: "Kind",
    memorySource: "Source",
    memorySourceHint: "A call, a document, a person.",
    memoryEdit: "Edit",
    memoryForget: "Forget",
    memoryForgetTitle: "Forget this memory?",
    memoryForgetBody: "It will no longer be recalled for this project. This cannot be undone.",
    memoryEmpty: "Nothing remembered yet",
    memoryEmptyHint: "Write down decisions and facts so the next person does not have to ask.",
    memoryNoMatch: "No memories match",
    memoryNoMatchHint: "Try another word or clear the tag filter.",
    memoryClear: "Clear filters",
    memoryCount: (n: string) => `${n} remembered`,
    memoryFrom: "From",
    memoryTagFilter: "Filter by tag",
    memoryKindFilter: "Filter by kind",
    // Vault
    vaultTitle: "Project secrets",
    vaultDescription: "Keys and passwords for this project. Values stay hidden until someone reveals them, and every reveal is logged.",
    envTitle: "Environment variables",
    envDescription: "Configuration for this project's environments.",
    // GitHub
    ghRepo: "Repository",
    ghConnectTitle: "Connect a repository",
    ghConnectHint: "Pick the repository this project ships from to see its commits, pull requests and runs here.",
    ghNotConnected: "No repository connected",
    ghNotConnectedHint: "Connect a repository to follow its commits, pull requests and workflow runs.",
    ghChange: "Change repository",
    ghDisconnect: "Disconnect",
    // Activity
    feedTitle: "Project activity",
    feedKind: "Type",
    feedPerson: "Person",
    feedAll: "All",
    feedAllPeople: "Everyone",
    feedKinds: { issue: "Issues", comment: "Comments", status: "Status changes", member: "Members", file: "Files", code: "Code", time: "Time", other: "Other" },
    feedEmpty: "No activity yet",
    feedEmptyHint: "Changes to issues, files and members show up here.",
    feedNoMatch: "Nothing matches these filters",
    feedNoMatchHint: "Change the type or the person.",
    feedClear: "Clear filters",
    feedToday: "Today",
    feedYesterday: "Yesterday",
    feedCount: (n: string) => `${n} events`,
    // Settings
    settingsTitle: "Project settings",
    groupProject: "Project",
    groupTeam: "Team",
    groupConnections: "Connections",
    pageGeneral: "General",
    pageGeneralHint: "Name, key, client, dates and status.",
    pageMembers: "Members and roles",
    pageMembersHint: "Who can work on this project.",
    pageWorkflow: "Labels and statuses",
    pageWorkflowHint: "The stages issues move through and the labels they carry.",
    pageIntegrations: "Integrations",
    pageIntegrationsHint: "Connect the tools this project uses.",
    pageBudget: "Budget",
    pageBudgetHint: "The total, and what has been spent so far.",
    pageDanger: "Danger zone",
    pageDangerHint: "Archive or delete this project.",
    key: "Key",
    keyHint: "Prefix of issue keys. It cannot change once issues exist.",
    connected: "Connected",
    notConnected: "Not connected",
    connect: "Connect",
    disconnect: "Disconnect",
    budgetSpent: "Spent so far",
    budgetSaved: "Budget saved",
    currency: "Currency",
    archiveTitle: "Archive this project",
    archiveBody: "Hides it from active lists and makes it read-only. You can restore it later.",
    archiveAction: "Archive project",
    archiveConfirmTitle: "Archive this project?",
    archiveConfirmBody: "Nobody will be able to change issues until it is restored.",
    deleteTitle: "Delete this project",
    deleteBody: "Permanently removes the project with its issues, files and history.",
    deleteAction: "Delete project",
    deleteConfirmTitle: "Delete this project?",
    deleteConfirmBody: "This cannot be undone. Type the project key to confirm.",
    deleteConfirmField: "Project key",
    confirm: "Confirm",
  },
  ar: {
    tabs: { activity: "النشاط", memory: "الذاكرة", vault: "الخزنة", github: "GitHub" },
    memoryTitle: "ذاكرة المشروع",
    memoryHint: "حقائق وقرارات تستحق أن تُحفظ عن هذا المشروع.",
    memorySearch: "ابحث في الذاكرة",
    memoryAllKinds: "الكل",
    memoryKinds: { fact: "حقيقة", decision: "قرار" },
    memoryKindsPlural: { fact: "حقائق", decision: "قرارات" },
    memoryAdd: "تذكّر شيئًا",
    memoryEditTitle: "تعديل الذاكرة",
    memoryAddTitle: "تذكّر شيئًا",
    memoryText: "ما الذي تريد تذكره",
    memoryTags: "الوسوم",
    memoryTagsHint: "افصل بينها بفواصل.",
    memoryKind: "النوع",
    memorySource: "المصدر",
    memorySourceHint: "مكالمة أو مستند أو شخص.",
    memoryEdit: "تعديل",
    memoryForget: "انسَ",
    memoryForgetTitle: "هل تنسى هذه الذاكرة؟",
    memoryForgetBody: "لن تُستدعى بعد الآن لهذا المشروع. لا يمكن التراجع.",
    memoryEmpty: "لم يُحفظ شيء بعد",
    memoryEmptyHint: "دوّن القرارات والحقائق كي لا يضطر التالي إلى السؤال.",
    memoryNoMatch: "لا ذكريات مطابقة",
    memoryNoMatchHint: "جرّب كلمة أخرى أو امسح تصفية الوسوم.",
    memoryClear: "مسح التصفية",
    memoryCount: (n: string) => `${n} محفوظة`,
    memoryFrom: "من",
    memoryTagFilter: "تصفية بالوسم",
    memoryKindFilter: "تصفية بالنوع",
    vaultTitle: "أسرار المشروع",
    vaultDescription: "مفاتيح وكلمات مرور هذا المشروع. تبقى القيم مخفية حتى يكشفها أحد، وكل كشف يُسجَّل.",
    envTitle: "متغيرات البيئة",
    envDescription: "إعدادات بيئات هذا المشروع.",
    ghRepo: "المستودع",
    ghConnectTitle: "اربط مستودعًا",
    ghConnectHint: "اختر المستودع الذي يُنشر منه هذا المشروع لترى الإيداعات وطلبات الدمج والتشغيلات هنا.",
    ghNotConnected: "لا مستودع مربوطًا",
    ghNotConnectedHint: "اربط مستودعًا لمتابعة إيداعاته وطلبات الدمج وتشغيلات المسارات.",
    ghChange: "تغيير المستودع",
    ghDisconnect: "فصل",
    feedTitle: "نشاط المشروع",
    feedKind: "النوع",
    feedPerson: "الشخص",
    feedAll: "الكل",
    feedAllPeople: "الجميع",
    feedKinds: { issue: "المهام", comment: "التعليقات", status: "تغيّر الحالة", member: "الأعضاء", file: "الملفات", code: "الكود", time: "الوقت", other: "أخرى" },
    feedEmpty: "لا نشاط بعد",
    feedEmptyHint: "تظهر هنا تغييرات المهام والملفات والأعضاء.",
    feedNoMatch: "لا شيء يطابق هذه التصفية",
    feedNoMatchHint: "غيّر النوع أو الشخص.",
    feedClear: "مسح التصفية",
    feedToday: "اليوم",
    feedYesterday: "أمس",
    feedCount: (n: string) => `${n} حدث`,
    settingsTitle: "إعدادات المشروع",
    groupProject: "المشروع",
    groupTeam: "الفريق",
    groupConnections: "الاتصالات",
    pageGeneral: "عام",
    pageGeneralHint: "الاسم والرمز والعميل والتواريخ والحالة.",
    pageMembers: "الأعضاء والأدوار",
    pageMembersHint: "من يمكنه العمل على هذا المشروع.",
    pageWorkflow: "الوسوم والحالات",
    pageWorkflowHint: "المراحل التي تمر بها المهام والوسوم التي تحملها.",
    pageIntegrations: "التكاملات",
    pageIntegrationsHint: "اربط الأدوات التي يستخدمها هذا المشروع.",
    pageBudget: "الميزانية",
    pageBudgetHint: "الإجمالي وما صُرف حتى الآن.",
    pageDanger: "منطقة الخطر",
    pageDangerHint: "أرشفة المشروع أو حذفه.",
    key: "الرمز",
    keyHint: "بادئة مفاتيح المهام. لا يتغير بعد وجود مهام.",
    connected: "مربوط",
    notConnected: "غير مربوط",
    connect: "ربط",
    disconnect: "فصل",
    budgetSpent: "المصروف حتى الآن",
    budgetSaved: "حُفظت الميزانية",
    currency: "العملة",
    archiveTitle: "أرشفة هذا المشروع",
    archiveBody: "يخفيه من القوائم النشطة ويجعله للقراءة فقط. يمكنك استعادته لاحقًا.",
    archiveAction: "أرشفة المشروع",
    archiveConfirmTitle: "هل تؤرشف هذا المشروع؟",
    archiveConfirmBody: "لن يستطيع أحد تغيير المهام حتى تتم استعادته.",
    deleteTitle: "حذف هذا المشروع",
    deleteBody: "يحذف المشروع نهائيًا مع مهامه وملفاته وسجله.",
    deleteAction: "حذف المشروع",
    deleteConfirmTitle: "هل تحذف هذا المشروع؟",
    deleteConfirmBody: "لا يمكن التراجع. اكتب رمز المشروع للتأكيد.",
    deleteConfirmField: "رمز المشروع",
    confirm: "تأكيد",
  },
};


const merge = (l: "en" | "ar") => ({ ...BASE[l], ...EXTRA[l], tabs: { ...BASE[l].tabs, ...EXTRA[l].tabs } });
export const PROJECT_VIEW_STRINGS = { en: merge("en"), ar: merge("ar") };
export type ProjectViewStrings = typeof PROJECT_VIEW_STRINGS.en;
export type ProjectViewLabels = Partial<Omit<ProjectViewStrings, "tabs" | "statuses">> & { tabs?: Partial<ProjectViewStrings["tabs"]>; statuses?: Partial<ProjectViewStrings["statuses"]> };

/** The merged strings (locale + overrides) and whether the locale is Arabic. */
export function useProjectStrings(labels: () => ProjectViewLabels | undefined) {
  const nq = useNasaq();
  const ar = computed(() => nq.locale.value.startsWith("ar"));
  const t = computed(() => {
    const base = PROJECT_VIEW_STRINGS[ar.value ? "ar" : "en"];
    const l = labels();
    return { ...base, ...l, tabs: { ...base.tabs, ...l?.tabs }, statuses: { ...base.statuses, ...l?.statuses } } as ProjectViewStrings;
  });
  return { ar, t, locale: computed(() => nq.locale.value) };
}
