import { computed, toValue, type MaybeRefOrGetter } from "vue";
import { useNasaq } from "../../provider";

const STRINGS = {
  en: {
    inbox: "Inbox",
    conversations: "Conversations",
    search: "Search conversations",
    searchPlaceholder: "Search name, email or message",
    views: "Views",
    viewActive: "Open",
    viewUnread: "Unread",
    viewSnoozed: "Snoozed",
    viewClosed: "Closed",
    viewArchived: "Archived",
    scopeAll: "Everyone",
    scopeMine: "Mine",
    scopeUnassigned: "Unassigned",
    scope: "Assignment",
    channels: "Channel",
    channelAll: "All channels",
    channelChat: "Chat",
    channelEmail: "Email",
    channelWhatsapp: "WhatsApp",
    empty: "No conversations here",
    emptyHint: "New messages show up as they arrive.",
    noSelection: "Select a conversation",
    noSelectionHint: "Pick one from the list to read it and reply.",
    loading: "Loading conversations",
    unreadCount: (n: string) => `${n} unread`,
    typing: "is typing",
    you: "You",
    unassigned: "Unassigned",
    assignTo: "Assign to",
    assignToMe: "Assign to me",
    assignedTo: (name: string) => `Assigned to ${name}`,
    back: "Back to conversations",
    close: "Close conversation",
    reopen: "Reopen",
    closed: "Closed",
    snoozedUntil: (when: string) => `Snoozed until ${when}`,
    openContact: "Contact details",
    hideContact: "Hide contact details",
    popOut: "Open in the dock",
    more: "More actions",
    // row menu
    pin: "Pin",
    unpin: "Unpin",
    archive: "Archive",
    unarchive: "Unarchive",
    mute: "Mute",
    unmute: "Unmute",
    markUnread: "Mark as unread",
    markRead: "Mark as read",
    color: "Colour",
    noColor: "No colour",
    colors: { gray: "Gray", red: "Red", orange: "Orange", amber: "Amber", green: "Green", teal: "Teal", blue: "Blue", violet: "Violet", pink: "Pink" },
    rowActions: (name: string) => `Actions for ${name}`,
    pinned: "Pinned",
    muted: "Muted",
    // snooze
    snooze: "Snooze",
    unsnooze: "Unsnooze",
    snoozeLater: "Later today",
    snoozeTomorrow: "Tomorrow morning",
    snoozeWeekend: "This weekend",
    snoozeNextWeek: "Next week",
    snoozeCustom: "Pick a date and time",
    snoozeConfirm: "Snooze until",
    snoozeCustomLabel: "Wake up at",
    // thread
    thread: "Messages",
    reply: "Reply",
    note: "Internal note",
    noteHint: "Only your team sees notes.",
    noteBadge: "Note",
    replyTo: "Replying to",
    cancelReply: "Cancel reply",
    replyAction: "Reply",
    react: "React",
    reactions: "Reactions",
    reactedWith: (emoji: string, n: string) => `${emoji} ${n}`,
    quoteJump: "Go to the original message",
    sending: "Sending",
    failed: "Failed to send",
    retry: "Retry",
    voiceMessage: "Voice message",
    locationMessage: "Location",
    attachmentMessage: "Attachment",
    linkOpen: "Open link",
    // find
    find: "Find in conversation",
    findPlaceholder: "Find in conversation",
    findCount: (i: string, n: string) => `${i} of ${n}`,
    findNone: "No matches",
    findNext: "Next match",
    findPrev: "Previous match",
    findClose: "Close search",
    // composer
    message: "Message",
    messagePlaceholder: "Write a reply. Type / for saved replies",
    notePlaceholder: "Write a note. Type @ to mention a teammate",
    emailPlaceholder: "Write your reply",
    send: "Send",
    sendNote: "Add note",
    subject: "Subject",
    to: "To",
    cc: "Cc",
    addCc: "Add Cc",
    ccPlaceholder: "name@example.com, another@example.com",
    attach: "Attach files",
    removeAttachment: (name: string) => `Remove ${name}`,
    emoji: "Emoji",
    voice: "Record a voice message",
    location: "Share a location",
    snippets: "Saved replies",
    sendFailed: "Could not send. Try again.",
    channelHintWhatsapp: "Sent through WhatsApp",
    // voice
    recording: "Recording",
    recorderCancel: "Discard recording",
    recorderSend: "Send voice message",
    recorderStop: "Stop recording",
    recorderMic: "Microphone access was blocked. Allow it in the browser and try again.",
    recorderUnsupported: "This browser cannot record audio.",
    recorderStarting: "Starting the microphone",
    play: "Play",
    pause: "Pause",
    speed: "Playback speed",
    voiceProgress: "Voice message position",
    // location
    pickLocation: "Share a location",
    pickLocationHint: "Click the map or drag the pin. You can also type coordinates.",
    mapPad: "Map area. Arrow keys move the pin.",
    latitude: "Latitude",
    longitude: "Longitude",
    place: "Place name",
    placeOptional: "Optional label",
    useMyLocation: "Use my location",
    locating: "Finding you",
    locationDenied: "Location access was blocked.",
    locationInvalid: "Enter a latitude from -90 to 90 and a longitude from -180 to 180.",
    sendLocation: "Send location",
    cancel: "Cancel",
    openInMaps: "Open in maps",
    nearby: "Suggested places",
    // canned
    snippetSearch: "Search saved replies",
    snippetsEmpty: "No saved replies match",
    snippetInsert: "Insert",
    // contact
    contact: "Contact",
    contactEmail: "Email",
    contactPhone: "Phone",
    contactCompany: "Company",
    contactLocation: "Location",
    contactTimezone: "Time zone",
    contactSince: "First seen",
    contactTags: "Tags",
    contactNotes: "Notes",
    copy: "Copy",
    copied: "Copied",
    media: "Media",
    files: "Files",
    links: "Links",
    mediaEmpty: "Nothing shared yet",
    mediaOpen: "Open image",
    mediaTabs: "Shared in this conversation",
    download: "Download",
    // toast / dock
    newMessage: "New message",
    openConversation: "Open",
    dismiss: "Dismiss",
    dock: "Chats",
    dockOpen: "Open chats",
    dockClose: "Close chats",
    dockMinimize: "Minimize",
    dockCloseWindow: "Close chat",
    dockEmpty: "No open chats",
    dockNew: "Recent conversations",
    system: "Event",
    email: "Email",
    from: "From",
    showQuoted: "Show earlier messages",
  },
  ar: {
    inbox: "صندوق الوارد",
    conversations: "المحادثات",
    search: "بحث في المحادثات",
    searchPlaceholder: "ابحث بالاسم أو البريد أو الرسالة",
    views: "العروض",
    viewActive: "مفتوحة",
    viewUnread: "غير مقروءة",
    viewSnoozed: "مؤجلة",
    viewClosed: "مغلقة",
    viewArchived: "مؤرشفة",
    scopeAll: "الجميع",
    scopeMine: "محادثاتي",
    scopeUnassigned: "غير مسندة",
    scope: "الإسناد",
    channels: "القناة",
    channelAll: "كل القنوات",
    channelChat: "دردشة",
    channelEmail: "بريد إلكتروني",
    channelWhatsapp: "WhatsApp",
    empty: "لا توجد محادثات هنا",
    emptyHint: "تظهر الرسائل الجديدة فور وصولها.",
    noSelection: "اختر محادثة",
    noSelectionHint: "اختر محادثة من القائمة لقراءتها والرد عليها.",
    loading: "جارٍ تحميل المحادثات",
    unreadCount: (n: string) => `${n} غير مقروءة`,
    typing: "يكتب الآن",
    you: "أنت",
    unassigned: "غير مسندة",
    assignTo: "إسناد إلى",
    assignToMe: "إسناد إليّ",
    assignedTo: (name: string) => `مسندة إلى ${name}`,
    back: "العودة إلى المحادثات",
    close: "إغلاق المحادثة",
    reopen: "إعادة فتح",
    closed: "مغلقة",
    snoozedUntil: (when: string) => `مؤجلة حتى ${when}`,
    openContact: "بيانات جهة الاتصال",
    hideContact: "إخفاء بيانات جهة الاتصال",
    popOut: "فتح في الشريط السفلي",
    more: "المزيد من الإجراءات",
    pin: "تثبيت",
    unpin: "إلغاء التثبيت",
    archive: "أرشفة",
    unarchive: "إلغاء الأرشفة",
    mute: "كتم",
    unmute: "إلغاء الكتم",
    markUnread: "تعليم كغير مقروءة",
    markRead: "تعليم كمقروءة",
    color: "اللون",
    noColor: "بلا لون",
    colors: { gray: "رمادي", red: "أحمر", orange: "برتقالي", amber: "كهرماني", green: "أخضر", teal: "تركوازي", blue: "أزرق", violet: "بنفسجي", pink: "وردي" },
    rowActions: (name: string) => `إجراءات ${name}`,
    pinned: "مثبتة",
    muted: "مكتومة",
    snooze: "تأجيل",
    unsnooze: "إلغاء التأجيل",
    snoozeLater: "لاحقًا اليوم",
    snoozeTomorrow: "صباح الغد",
    snoozeWeekend: "نهاية الأسبوع",
    snoozeNextWeek: "الأسبوع القادم",
    snoozeCustom: "اختيار تاريخ ووقت",
    snoozeConfirm: "تأجيل حتى",
    snoozeCustomLabel: "أعد التنبيه في",
    thread: "الرسائل",
    reply: "رد",
    note: "ملاحظة داخلية",
    noteHint: "الملاحظات يراها فريقك فقط.",
    noteBadge: "ملاحظة",
    replyTo: "ردًا على",
    cancelReply: "إلغاء الرد",
    replyAction: "رد",
    react: "تفاعل",
    reactions: "التفاعلات",
    reactedWith: (emoji: string, n: string) => `${emoji} ${n}`,
    quoteJump: "الانتقال إلى الرسالة الأصلية",
    sending: "جارٍ الإرسال",
    failed: "تعذر الإرسال",
    retry: "إعادة المحاولة",
    voiceMessage: "رسالة صوتية",
    locationMessage: "موقع",
    attachmentMessage: "مرفق",
    linkOpen: "فتح الرابط",
    find: "بحث في المحادثة",
    findPlaceholder: "ابحث في المحادثة",
    findCount: (i: string, n: string) => `${i} من ${n}`,
    findNone: "لا نتائج",
    findNext: "النتيجة التالية",
    findPrev: "النتيجة السابقة",
    findClose: "إغلاق البحث",
    message: "الرسالة",
    messagePlaceholder: "اكتب ردًا. اكتب / للردود المحفوظة",
    notePlaceholder: "اكتب ملاحظة. اكتب @ للإشارة إلى زميل",
    emailPlaceholder: "اكتب ردك",
    send: "إرسال",
    sendNote: "إضافة الملاحظة",
    subject: "الموضوع",
    to: "إلى",
    cc: "نسخة",
    addCc: "إضافة نسخة",
    ccPlaceholder: "name@example.com, another@example.com",
    attach: "إرفاق ملفات",
    removeAttachment: (name: string) => `إزالة ${name}`,
    emoji: "إيموجي",
    voice: "تسجيل رسالة صوتية",
    location: "مشاركة موقع",
    snippets: "الردود المحفوظة",
    sendFailed: "تعذر الإرسال. حاول مرة أخرى.",
    channelHintWhatsapp: "تُرسل عبر WhatsApp",
    recording: "جارٍ التسجيل",
    recorderCancel: "تجاهل التسجيل",
    recorderSend: "إرسال الرسالة الصوتية",
    recorderStop: "إيقاف التسجيل",
    recorderMic: "تم حظر الوصول إلى الميكروفون. اسمح به من المتصفح ثم حاول مرة أخرى.",
    recorderUnsupported: "هذا المتصفح لا يدعم تسجيل الصوت.",
    recorderStarting: "جارٍ تشغيل الميكروفون",
    play: "تشغيل",
    pause: "إيقاف مؤقت",
    speed: "سرعة التشغيل",
    voiceProgress: "موضع الرسالة الصوتية",
    pickLocation: "مشاركة موقع",
    pickLocationHint: "اضغط على الخريطة أو اسحب الدبوس. يمكنك أيضًا كتابة الإحداثيات.",
    mapPad: "منطقة الخريطة. مفاتيح الأسهم تحرّك الدبوس.",
    latitude: "خط العرض",
    longitude: "خط الطول",
    place: "اسم المكان",
    placeOptional: "تسمية اختيارية",
    useMyLocation: "استخدم موقعي",
    locating: "جارٍ تحديد موقعك",
    locationDenied: "تم حظر الوصول إلى الموقع.",
    locationInvalid: "أدخل خط عرض من -90 إلى 90 وخط طول من -180 إلى 180.",
    sendLocation: "إرسال الموقع",
    cancel: "إلغاء",
    openInMaps: "فتح في الخرائط",
    nearby: "أماكن مقترحة",
    snippetSearch: "ابحث في الردود المحفوظة",
    snippetsEmpty: "لا ردود محفوظة مطابقة",
    snippetInsert: "إدراج",
    contact: "جهة الاتصال",
    contactEmail: "البريد الإلكتروني",
    contactPhone: "الهاتف",
    contactCompany: "الشركة",
    contactLocation: "الموقع",
    contactTimezone: "المنطقة الزمنية",
    contactSince: "أول ظهور",
    contactTags: "الوسوم",
    contactNotes: "ملاحظات",
    copy: "نسخ",
    copied: "تم النسخ",
    media: "الوسائط",
    files: "الملفات",
    links: "الروابط",
    mediaEmpty: "لم تتم مشاركة أي شيء بعد",
    mediaOpen: "فتح الصورة",
    mediaTabs: "المشارَك في هذه المحادثة",
    download: "تنزيل",
    newMessage: "رسالة جديدة",
    openConversation: "فتح",
    dismiss: "إخفاء",
    dock: "المحادثات",
    dockOpen: "فتح المحادثات",
    dockClose: "إغلاق المحادثات",
    dockMinimize: "تصغير",
    dockCloseWindow: "إغلاق المحادثة",
    dockEmpty: "لا توجد محادثات مفتوحة",
    dockNew: "أحدث المحادثات",
    system: "حدث",
    email: "بريد إلكتروني",
    from: "من",
    showQuoted: "إظهار الرسائل السابقة",
  },
};

export type InboxLabels = (typeof STRINGS)["en"];

/** English or Arabic by the Nasaq locale, with per-key overrides. */
export function useInboxLabels(labels?: MaybeRefOrGetter<Partial<InboxLabels> | undefined>) {
  const nq = useNasaq();
  return computed<InboxLabels>(() => ({ ...STRINGS[nq.locale.value.startsWith("ar") ? "ar" : "en"], ...toValue(labels) }));
}

export { STRINGS as INBOX_STRINGS };
