// Strings for the storefront listing, card, quick view and compare components (English and Arabic), same keys as the React kit.
import { computed } from "vue";
import { useNasaq } from "../../provider";

const STRINGS = {
  en: {
    // card
    addToCart: "Add to cart",
    quickAdd: "Quick add",
    quickView: "Quick view",
    quickViewFor: "Quick view {name}",
    wishlistAdd: "Add {name} to wishlist",
    wishlistRemove: "Remove {name} from wishlist",
    compare: "Compare",
    compareFor: "Compare {name}",
    soldOut: "Sold out",
    from: "From",
    chooseOption: "Choose {option}",
    added: "Added to cart",
    addedLive: "{name} added to cart",
    percentOff: "{n}% off",
    optionSoldOut: "sold out",
    optionUnavailable: "unavailable",
    moreValues: "+{n} more",
    reviews: "reviews",
    viewProduct: "View {name}",
    // quick view
    quickViewTitle: "Quick view",
    quantity: "Quantity",
    increase: "Increase quantity",
    decrease: "Decrease quantity",
    viewDetails: "View full details",
    inStock: "In stock",
    outOfStock: "Out of stock",
    lowStock: "Only {n} left",
    selectOption: "Select {option}",
    unavailableCombo: "This combination is unavailable",
    gallery: "Product images",
    showImage: "Show image {n}",
    // listing
    results: "{n} results",
    resultsOne: "1 result",
    showing: "Showing {from}–{to} of {total}",
    sortBy: "Sort by",
    sort: {
      relevance: "Featured",
      popular: "Most popular",
      rating: "Top rated",
      "price-asc": "Price: low to high",
      "price-desc": "Price: high to low",
      discount: "Biggest discount",
      name: "Name A–Z",
    },
    view: "View",
    grid: "Grid view",
    list: "List view",
    density: "Density",
    comfortable: "Comfortable",
    compact: "Compact",
    filters: "Filters",
    filtersCount: "Filters ({n})",
    clearAll: "Clear all",
    apply: "Show {n} results",
    applyNone: "No results",
    close: "Close",
    activeFilters: "Active filters",
    removeFilter: "Remove filter: {label}",
    categories: "Categories",
    allCategories: "All categories",
    price: "Price",
    priceMin: "Minimum price",
    priceMax: "Maximum price",
    brand: "Brand",
    rating: "Rating",
    andUp: "{n} & up",
    availability: "Availability",
    onSale: "On sale",
    showMore: "Show more",
    showLess: "Show less",
    loadMore: "Load more",
    loadedOf: "You have seen {n} of {total}",
    pagination: "Product pages",
    noResults: "No products match",
    noResultsFor: "No results for “{query}”",
    noResultsHint: "Check the spelling, or loosen a filter.",
    tryRemoving: "Try removing",
    resetFilters: "Reset filters",
    errorTitle: "We could not load the products",
    errorHint: "Check your connection and try again.",
    retry: "Try again",
    loading: "Loading products",
    facets: "Product filters",
    // compare
    compareTray: "Compare products",
    compareCount: "{n} of {max} selected",
    compareNow: "Compare ({n})",
    compareNeedTwo: "Select at least two products to compare",
    compareFull: "You can compare up to {max} products",
    compareRemove: "Remove {name} from comparison",
    compareEmptySlot: "Add a product",
    compareTitle: "Compare products",
    compareDescription: "Side by side, with the differences highlighted.",
    onlyDifferences: "Show only differences",
    noDifferences: "These products are identical on every attribute shown.",
    attribute: "Attribute",
    brandRow: "Brand",
    categoryRow: "Category",
    ratingRow: "Rating",
    availabilityRow: "Availability",
    descriptionRow: "Description",
    priceRow: "Price",
    none: "None",
    // search results
    resultsFor: "Results for “{query}”",
    didYouMean: "Popular searches",
  },
  ar: {
    addToCart: "أضف إلى السلة",
    quickAdd: "إضافة سريعة",
    quickView: "نظرة سريعة",
    quickViewFor: "نظرة سريعة على {name}",
    wishlistAdd: "أضف {name} إلى المفضلة",
    wishlistRemove: "أزل {name} من المفضلة",
    compare: "قارن",
    compareFor: "قارن {name}",
    soldOut: "نفدت الكمية",
    from: "ابتداءً من",
    chooseOption: "اختر {option}",
    added: "تمت الإضافة إلى السلة",
    addedLive: "تمت إضافة {name} إلى السلة",
    percentOff: "خصم {n}%",
    optionSoldOut: "نفدت الكمية",
    optionUnavailable: "غير متوفر",
    moreValues: "+{n} أخرى",
    reviews: "تقييم",
    viewProduct: "عرض {name}",
    quickViewTitle: "نظرة سريعة",
    quantity: "الكمية",
    increase: "زيادة الكمية",
    decrease: "تقليل الكمية",
    viewDetails: "عرض التفاصيل الكاملة",
    inStock: "متوفر",
    outOfStock: "غير متوفر",
    lowStock: "بقيت {n} فقط",
    selectOption: "اختر {option}",
    unavailableCombo: "هذا الاختيار غير متوفر",
    gallery: "صور المنتج",
    showImage: "عرض الصورة {n}",
    results: "{n} نتيجة",
    resultsOne: "نتيجة واحدة",
    showing: "عرض {from}–{to} من {total}",
    sortBy: "ترتيب حسب",
    sort: {
      relevance: "الأنسب",
      popular: "الأكثر رواجًا",
      rating: "الأعلى تقييمًا",
      "price-asc": "السعر: من الأقل إلى الأعلى",
      "price-desc": "السعر: من الأعلى إلى الأقل",
      discount: "أكبر خصم",
      name: "الاسم أ–ي",
    },
    view: "طريقة العرض",
    grid: "عرض شبكي",
    list: "عرض قائمة",
    density: "الكثافة",
    comfortable: "مريح",
    compact: "مضغوط",
    filters: "التصفية",
    filtersCount: "التصفية ({n})",
    clearAll: "مسح الكل",
    apply: "عرض {n} نتيجة",
    applyNone: "لا توجد نتائج",
    close: "إغلاق",
    activeFilters: "عوامل التصفية المطبّقة",
    removeFilter: "إزالة عامل التصفية: {label}",
    categories: "الأقسام",
    allCategories: "كل الأقسام",
    price: "السعر",
    priceMin: "أقل سعر",
    priceMax: "أعلى سعر",
    brand: "العلامة التجارية",
    rating: "التقييم",
    andUp: "{n} فأكثر",
    availability: "التوفر",
    onSale: "عليها خصم",
    showMore: "عرض المزيد",
    showLess: "عرض أقل",
    loadMore: "تحميل المزيد",
    loadedOf: "شاهدت {n} من {total}",
    pagination: "صفحات المنتجات",
    noResults: "لا توجد منتجات مطابقة",
    noResultsFor: "لا نتائج عن «{query}»",
    noResultsHint: "تأكد من الإملاء، أو خفّف أحد عوامل التصفية.",
    tryRemoving: "جرّب إزالة",
    resetFilters: "إعادة ضبط التصفية",
    errorTitle: "تعذّر تحميل المنتجات",
    errorHint: "تحقق من اتصالك بالإنترنت وحاول مجددًا.",
    retry: "حاول مجددًا",
    loading: "جارٍ تحميل المنتجات",
    facets: "تصفية المنتجات",
    compareTray: "مقارنة المنتجات",
    compareCount: "تم اختيار {n} من {max}",
    compareNow: "قارن ({n})",
    compareNeedTwo: "اختر منتجين على الأقل للمقارنة",
    compareFull: "يمكنك مقارنة {max} منتجات كحد أقصى",
    compareRemove: "أزل {name} من المقارنة",
    compareEmptySlot: "أضف منتجًا",
    compareTitle: "مقارنة المنتجات",
    compareDescription: "جنبًا إلى جنب، مع إبراز الفروقات.",
    onlyDifferences: "إظهار الفروقات فقط",
    noDifferences: "المنتجات متطابقة في كل الخصائص المعروضة.",
    attribute: "الخاصية",
    brandRow: "العلامة التجارية",
    categoryRow: "القسم",
    ratingRow: "التقييم",
    availabilityRow: "التوفر",
    descriptionRow: "الوصف",
    priceRow: "السعر",
    none: "لا شيء",
    resultsFor: "نتائج البحث عن «{query}»",
    didYouMean: "عمليات بحث شائعة",
  },
};

export type ListingLabels = Partial<Omit<(typeof STRINGS)["en"], "sort">> & { sort?: Partial<(typeof STRINGS)["en"]["sort"]> };
export type ListingStrings = (typeof STRINGS)["en"];

export const fillTemplate = (template: string, values: Record<string, string | number>) => template.replace(/\{(\w+)\}/g, (_, k: string) => String(values[k] ?? ""));

/** Strings and locale for the storefront components. `labels` overrides any key. */
export function useListingStrings(labels: () => ListingLabels | undefined = () => undefined) {
  const nq = useNasaq();
  const t = computed<ListingStrings>(() => {
    const base = STRINGS[nq.locale.value.startsWith("ar") ? "ar" : "en"];
    const l = labels();
    return { ...base, ...l, sort: { ...base.sort, ...l?.sort } } as ListingStrings;
  });
  return { t, locale: nq.locale };
}

/** Minor-unit exponent of a currency (USD 2, JPY 0, KWD 3). */
export function currencyDigits(currency: string): number {
  try {
    return new Intl.NumberFormat("en", { style: "currency", currency }).resolvedOptions().maximumFractionDigits ?? 2;
  } catch {
    return 2;
  }
}
