export const STRINGS = {
  en: {
    launcher: "Feedback",
    hubTitle: "Reports on this page",
    hubDescription: "What other people already told us about this page. Add your vote instead of sending a duplicate.",
    page: "Page",
    reportNew: "Report a problem",
    all: "All",
    open: "Open",
    inProgress: "In progress",
    resolved: "Resolved",
    emptyTitle: "Nothing reported here",
    emptyBody: "No one has reported a problem on this page yet.",
    emptyFiltered: "No reports with this status.",
    meToo: "Me too",
    voted: "You said this too",
    votes: "{count} people have this",
    by: "by {name}",
    filterLabel: "Filter by status",
    listLabel: "Reports on this page",
    configTitle: "Launcher",
    configDescription: "Choose how the feedback button looks and where it sits, then copy the install code.",
    shape: "Shape",
    position: "Position",
    text: "Button text",
    preview: "Preview",
    shapePill: "Pill",
    shapeCircle: "Circle",
    shapeTab: "Edge tab",
    posBottomEnd: "Bottom end",
    posBottomStart: "Bottom start",
    posTopEnd: "Top end",
    posTopStart: "Top start",
    posEdgeEnd: "Edge end",
    posEdgeStart: "Edge start",
    install: "Install",
    react: "React",
    json: "Config",
    copyCode: "Copy code",
    codeLabel: "Install code",
    shakeTitle: "Something wrong?",
    shakeDescription: "You shook your phone. Do you want to report a problem on this screen?",
    shakeReport: "Report a problem",
    shakeDismiss: "Not now",
    shakeSetting: "Shake to report",
    shakeSettingHint: "Shaking your phone opens this sheet.",
    moveHint: "Drag to move it out of the way. Alt + arrow keys move it too.",
    mine: "Mine",
    yours: "Yours",
    emptyMineTitle: "You have not reported anything",
    emptyMine: "Reports you send from this page show up here, with their status.",
    loadMore: "Load more",
    showing: "Showing {shown} of {total}",
  },
  ar: {
    launcher: "ملاحظات",
    hubTitle: "البلاغات على هذه الصفحة",
    hubDescription: "ما أخبرنا به الآخرون عن هذه الصفحة. أضف صوتك بدل إرسال بلاغ مكرر.",
    page: "الصفحة",
    reportNew: "الإبلاغ عن مشكلة",
    all: "الكل",
    open: "مفتوحة",
    inProgress: "قيد المعالجة",
    resolved: "تم حلها",
    emptyTitle: "لا بلاغات هنا",
    emptyBody: "لم يبلّغ أحد عن مشكلة في هذه الصفحة بعد.",
    emptyFiltered: "لا توجد بلاغات بهذه الحالة.",
    meToo: "وأنا أيضاً",
    voted: "قلت ذلك أيضاً",
    votes: "{count} أشخاص لديهم المشكلة",
    by: "بواسطة {name}",
    filterLabel: "تصفية حسب الحالة",
    listLabel: "البلاغات على هذه الصفحة",
    configTitle: "زر الملاحظات",
    configDescription: "اختر شكل الزر ومكانه ثم انسخ كود التركيب.",
    shape: "الشكل",
    position: "المكان",
    text: "نص الزر",
    preview: "معاينة",
    shapePill: "كبسولة",
    shapeCircle: "دائرة",
    shapeTab: "لسان جانبي",
    posBottomEnd: "أسفل النهاية",
    posBottomStart: "أسفل البداية",
    posTopEnd: "أعلى النهاية",
    posTopStart: "أعلى البداية",
    posEdgeEnd: "حافة النهاية",
    posEdgeStart: "حافة البداية",
    install: "التركيب",
    react: "React",
    json: "الإعداد",
    copyCode: "نسخ الكود",
    codeLabel: "كود التركيب",
    shakeTitle: "هل من مشكلة؟",
    shakeDescription: "هززت هاتفك. هل تريد الإبلاغ عن مشكلة في هذه الشاشة؟",
    shakeReport: "الإبلاغ عن مشكلة",
    shakeDismiss: "ليس الآن",
    shakeSetting: "الهز للإبلاغ",
    shakeSettingHint: "هز هاتفك يفتح هذه الورقة.",
    moveHint: "اسحبه لإبعاده عن طريقك. Alt مع الأسهم يحركه أيضًا.",
    mine: "بلاغاتي",
    yours: "بلاغك",
    emptyMineTitle: "لم تبلغ عن شيء بعد",
    emptyMine: "البلاغات التي ترسلها من هذه الصفحة تظهر هنا مع حالتها.",
    loadMore: "عرض المزيد",
    showing: "يعرض {shown} من {total}",
  },
};

export type FeedbackReporterLabels = Partial<(typeof STRINGS)["en"]>;
export type FeedbackReporterStrings = (typeof STRINGS)["en"];
export const feedbackStrings = (locale: string, labels?: FeedbackReporterLabels): FeedbackReporterStrings => ({ ...STRINGS[locale.startsWith("ar") ? "ar" : "en"], ...labels });
export const fill = (text: string, values: Record<string, string | number>) => text.replace(/\{(\w+)\}/g, (_, k: string) => String(values[k] ?? ""));
