import type { IssueCode } from "./import-wizard-csv";

export const STRINGS = {
  en: {
    steps: ["Upload", "Match columns", "Review", "Import"],
    uploadTitle: "Choose a file",
    uploadHint: "CSV or TSV. Working in Excel? Use Save as, then CSV.",
    dropPrompt: "Drop a CSV file here, or click to choose one",
    orPaste: "Or paste the rows",
    pastePlaceholder: "name,email,phone",
    usePasted: "Use pasted rows",
    template: "Download a template",
    fileTooBig: "That file is too large.",
    wrongType: "Use a CSV or TSV file.",
    empty: "The file has no rows.",
    tooMany: (n: number) => `Import up to ${n} rows at a time. Split the file and try again.`,
    readFailed: "Could not read that file.",
    loaded: (name: string, rows: number, cols: number) => `${name}: ${rows} rows, ${cols} columns`,
    mapTitle: "Match your columns",
    mapBody: "Say which column holds each field. We matched the ones we could.",
    fieldCol: "Field",
    sourceCol: "Column in your file",
    example: "Example",
    skip: "Do not import",
    required: "Required",
    unmappedRequired: (names: string) => `Match the required fields first: ${names}.`,
    reviewTitle: "Review before you import",
    ready: "Ready",
    problems: "Need fixing",
    duplicates: "Duplicates",
    total: "Total",
    skipInvalid: "Skip rows with problems",
    skipInvalidHint: "Rows with problems are left out. Fix them in the file to bring them in.",
    line: "Line",
    unresolved: "Rows with problems",
    showing: (n: number, total: number) => `Showing the first ${n} of ${total} rows`,
    issue: { required: "Missing", email: "Not an email", phone: "Not a phone number", number: "Not a number", date: "Not a date", url: "Not a link", duplicate: "Repeated" } satisfies Record<IssueCode, string>,
    importN: (n: number) => (n === 1 ? "Import 1 row" : `Import ${n} rows`),
    nothing: "Nothing to import",
    nothingBody: "Every row has a problem. Fix the file and upload it again.",
    back: "Back",
    next: "Next",
    importing: "Importing",
    done: "Import finished",
    imported: (n: number) => (n === 1 ? "1 row imported" : `${n} rows imported`),
    skipped: (n: number) => (n === 1 ? "1 row skipped" : `${n} rows skipped`),
    failedRows: "Rows the server refused",
    finish: "Done",
    another: "Import another file",
    retry: "Try again",
    failed: "The import did not finish. Nothing was lost; try again.",
    filePreview: "Preview of your rows",
  },
  ar: {
    steps: ["الرفع", "مطابقة الأعمدة", "المراجعة", "الاستيراد"],
    uploadTitle: "اختر ملفًا",
    uploadHint: "ملف CSV أو TSV. تعمل في إكسل؟ احفظ باسم ثم اختر CSV.",
    dropPrompt: "أفلت ملف CSV هنا، أو اضغط لاختياره",
    orPaste: "أو الصق الصفوف",
    pastePlaceholder: "الاسم,البريد,الهاتف",
    usePasted: "استخدم الصفوف الملصقة",
    template: "تنزيل قالب",
    fileTooBig: "هذا الملف كبير جدًا.",
    wrongType: "استخدم ملف CSV أو TSV.",
    empty: "الملف لا يحتوي على صفوف.",
    tooMany: (n: number) => `استورد حتى ${n} صف في المرة. قسّم الملف وحاول مجددًا.`,
    readFailed: "تعذّرت قراءة هذا الملف.",
    loaded: (name: string, rows: number, cols: number) => `${name}: ${rows} صف، ${cols} عمود`,
    mapTitle: "طابق أعمدتك",
    mapBody: "حدّد العمود الذي يحمل كل حقل. طابقنا ما استطعنا.",
    fieldCol: "الحقل",
    sourceCol: "العمود في ملفك",
    example: "مثال",
    skip: "لا تستورد",
    required: "مطلوب",
    unmappedRequired: (names: string) => `طابق الحقول المطلوبة أولًا: ${names}.`,
    reviewTitle: "راجع قبل الاستيراد",
    ready: "جاهز",
    problems: "يحتاج إصلاحًا",
    duplicates: "مكرر",
    total: "الإجمالي",
    skipInvalid: "تخطَّ الصفوف التي بها مشكلات",
    skipInvalidHint: "تُستبعد الصفوف التي بها مشكلات. أصلحها في الملف لإدخالها.",
    line: "السطر",
    unresolved: "الصفوف التي بها مشكلات",
    showing: (n: number, total: number) => `عرض أول ${n} من ${total} صف`,
    issue: { required: "ناقص", email: "ليس بريدًا", phone: "ليس رقم هاتف", number: "ليس رقمًا", date: "ليس تاريخًا", url: "ليس رابطًا", duplicate: "مكرر" } satisfies Record<IssueCode, string>,
    importN: (n: number) => (n === 1 ? "استيراد صف واحد" : n === 2 ? "استيراد صفين" : n <= 10 ? `استيراد ${n} صفوف` : `استيراد ${n} صفًا`),
    nothing: "لا شيء للاستيراد",
    nothingBody: "كل الصفوف بها مشكلات. أصلح الملف وارفعه من جديد.",
    back: "رجوع",
    next: "التالي",
    importing: "جارٍ الاستيراد",
    done: "اكتمل الاستيراد",
    imported: (n: number) => (n === 1 ? "استُورد صف واحد" : n === 2 ? "استُورد صفان" : n <= 10 ? `استُوردت ${n} صفوف` : `استُورد ${n} صفًا`),
    skipped: (n: number) => (n === 1 ? "تُخطي صف واحد" : n === 2 ? "تُخطي صفان" : n <= 10 ? `تُخطيت ${n} صفوف` : `تُخطي ${n} صفًا`),
    failedRows: "صفوف رفضها الخادم",
    finish: "تم",
    another: "استيراد ملف آخر",
    retry: "حاول مرة أخرى",
    failed: "لم يكتمل الاستيراد. لم يضِع شيء؛ حاول مرة أخرى.",
    filePreview: "معاينة صفوفك",
  },
};
export const strings = (locale: string) => STRINGS[locale.startsWith("ar") ? "ar" : "en"];

export type Strings = typeof STRINGS.en;
export type Labels = Partial<Strings>;
