export type EmailTemplateCategory = "welcome" | "transactional" | "marketing" | "notification";
export type EmailTemplateStatus = "draft" | "active";

export const STRINGS = {
  en: {
    gallery: "Email templates",
    search: "Search templates…",
    newTemplate: "New template",
    untitled: "Untitled template",
    all: "All",
    categories: { welcome: "Welcome", transactional: "Transactional", marketing: "Marketing", notification: "Notification" },
    statuses: { draft: "Draft", active: "Active" },
    updated: "Updated",
    noneTitle: "No templates yet",
    noneHint: "Create a template to reuse the same message everywhere.",
    noMatchTitle: "No templates match",
    noMatchHint: "Try another search or category.",
    open: "Edit",
    duplicate: "Duplicate",
    delete: "Delete",
    back: "All templates",
    save: "Save template",
    saved: "Template saved.",
    unsaved: "Unsaved changes",
    name: "Template name",
    category: "Category",
    subject: "Subject",
    preheader: "Preview text",
    preheaderHint: "The grey line shown after the subject in most inboxes.",
    body: "Body",
    direction: "Direction",
    ltr: "Left to right",
    rtl: "Right to left",
    footer: "Footer",
    variables: "Variables",
    variablesHint: "Copy a variable and paste it into the subject or the body. It is replaced when the email is sent.",
    copyVariable: (k: string) => `Copy ${k}`,
    unknown: (keys: string) => `Unknown variables: ${keys}`,
    edit: "Edit",
    preview: "Preview",
    desktop: "Desktop",
    mobile: "Mobile",
    from: "From",
    to: "To",
    subjectLabel: "Subject",
    sendTest: "Send test",
    sendTestTitle: "Send a test email",
    sendTestBody: "Sends this template with the sample values to one address.",
    email: "Email address",
    send: "Send",
    cancel: "Cancel",
    sent: "Test email sent.",
    invalidEmail: "Enter a valid email address.",
    previewFrame: "Email preview",
    thumbnail: (n: string) => `Preview of ${n}`,
    deleteConfirm: (n: string) => `Delete ${n}?`,
    deleteBody: "This cannot be undone.",
    failed: "Something went wrong. Try again.",
  },
  ar: {
    gallery: "قوالب البريد",
    search: "ابحث في القوالب…",
    newTemplate: "قالب جديد",
    untitled: "قالب بلا عنوان",
    all: "الكل",
    categories: { welcome: "ترحيب", transactional: "معاملات", marketing: "تسويق", notification: "إشعارات" },
    statuses: { draft: "مسودة", active: "نشط" },
    updated: "آخر تحديث",
    noneTitle: "لا توجد قوالب بعد",
    noneHint: "أنشئ قالبًا لإعادة استخدام الرسالة نفسها في كل مكان.",
    noMatchTitle: "لا توجد قوالب مطابقة",
    noMatchHint: "جرّب بحثًا أو تصنيفًا آخر.",
    open: "تحرير",
    duplicate: "تكرار",
    delete: "حذف",
    back: "كل القوالب",
    save: "حفظ القالب",
    saved: "تم حفظ القالب.",
    unsaved: "تغييرات غير محفوظة",
    name: "اسم القالب",
    category: "التصنيف",
    subject: "الموضوع",
    preheader: "نص المعاينة",
    preheaderHint: "السطر الرمادي الذي يظهر بعد الموضوع في معظم صناديق البريد.",
    body: "المحتوى",
    direction: "الاتجاه",
    ltr: "من اليسار إلى اليمين",
    rtl: "من اليمين إلى اليسار",
    footer: "التذييل",
    variables: "المتغيرات",
    variablesHint: "انسخ المتغير والصقه في الموضوع أو المحتوى. يُستبدل بقيمته عند إرسال البريد.",
    copyVariable: (k: string) => `نسخ ${k}`,
    unknown: (keys: string) => `متغيرات غير معروفة: ${keys}`,
    edit: "تحرير",
    preview: "معاينة",
    desktop: "حاسوب",
    mobile: "جوال",
    from: "من",
    to: "إلى",
    subjectLabel: "الموضوع",
    sendTest: "إرسال تجريبي",
    sendTestTitle: "إرسال بريد تجريبي",
    sendTestBody: "يرسل هذا القالب بالقيم التجريبية إلى عنوان واحد.",
    email: "البريد الإلكتروني",
    send: "إرسال",
    cancel: "إلغاء",
    sent: "أُرسل البريد التجريبي.",
    invalidEmail: "أدخل بريدًا إلكترونيًا صالحًا.",
    previewFrame: "معاينة البريد",
    thumbnail: (n: string) => `معاينة ${n}`,
    deleteConfirm: (n: string) => `حذف ${n}؟`,
    deleteBody: "لا يمكن التراجع عن هذا.",
    failed: "حدث خطأ. حاول مرة أخرى.",
  },
};

export type EmailTemplatesLabels = Omit<typeof STRINGS.en, "categories" | "statuses"> & {
  categories: Record<EmailTemplateCategory, string>;
  statuses: Record<EmailTemplateStatus, string>;
};
export type EmailTemplatesLabelOverrides = Partial<Omit<EmailTemplatesLabels, "categories" | "statuses">> & {
  categories?: Partial<EmailTemplatesLabels["categories"]>;
  statuses?: Partial<EmailTemplatesLabels["statuses"]>;
};

/** English or Arabic strings by locale, with any overrides merged in. */
export function emailStrings(locale: string, labels?: EmailTemplatesLabelOverrides): EmailTemplatesLabels {
  const base = STRINGS[locale.startsWith("ar") ? "ar" : "en"];
  return { ...base, ...labels, categories: { ...base.categories, ...labels?.categories }, statuses: { ...base.statuses, ...labels?.statuses } } as EmailTemplatesLabels;
}
