export const STRINGS = {
  en: {
    title: "Checklist",
    progress: (done: number, total: number) => `${done} of ${total} done`,
    empty: "No items yet",
    emptyBody: "Add the first thing that needs doing.",
    add: "Add",
    addPlaceholder: "Add an item",
    addLabel: "New item",
    subtaskPlaceholder: "Add a subtask",
    addSubtask: "Add subtask",
    addSubtaskFor: (n: string) => `Add a subtask to ${n}`,
    expand: (n: string) => `Show subtasks of ${n}`,
    collapse: (n: string) => `Hide subtasks of ${n}`,
    subtasksDone: (done: number, total: number) => `${done}/${total} subtasks`,
    attach: "Attach a file",
    attachFor: (n: string) => `Attach a file to ${n}`,
    removeAttachment: (n: string) => `Remove ${n}`,
    remove: "Delete",
    removeFor: (n: string) => `Delete ${n}`,
    complete: "All done",
    failed: "That did not save. Try again.",
    list: "Items",
    cancel: "Cancel",
  },
  ar: {
    title: "قائمة المهام",
    progress: (done: number, total: number) => `أُنجز ${done} من ${total}`,
    empty: "لا توجد عناصر بعد",
    emptyBody: "أضف أول شيء يحتاج إلى إنجاز.",
    add: "إضافة",
    addPlaceholder: "أضف عنصرًا",
    addLabel: "عنصر جديد",
    subtaskPlaceholder: "أضف مهمة فرعية",
    addSubtask: "إضافة مهمة فرعية",
    addSubtaskFor: (n: string) => `إضافة مهمة فرعية إلى ${n}`,
    expand: (n: string) => `إظهار المهام الفرعية لـ ${n}`,
    collapse: (n: string) => `إخفاء المهام الفرعية لـ ${n}`,
    subtasksDone: (done: number, total: number) => `${done}/${total} مهام فرعية`,
    attach: "إرفاق ملف",
    attachFor: (n: string) => `إرفاق ملف إلى ${n}`,
    removeAttachment: (n: string) => `إزالة ${n}`,
    remove: "حذف",
    removeFor: (n: string) => `حذف ${n}`,
    complete: "اكتمل كل شيء",
    failed: "لم يُحفظ ذلك. حاول مرة أخرى.",
    list: "العناصر",
    cancel: "إلغاء",
  },
};
export const strings = (locale: string) => STRINGS[locale.startsWith("ar") ? "ar" : "en"];

export type Strings = typeof STRINGS.en;
export type Labels = Partial<Strings>;
