// Built-in words of TrashBin, English and Arabic. Copied from the React component.

export const STRINGS = {
  en: {
    title: "Trash",
    listLabel: "Deleted items",
    notice: (days: number) => `Items are deleted for good ${days} days after you delete them.`,
    noticeKept: "Items stay here until you empty the trash.",
    name: "Name",
    type: "Type",
    deleted: "Deleted",
    deletedBy: "Deleted by",
    timeLeft: "Time left",
    types: "Type",
    restore: "Restore",
    restoreSelected: "Restore selected",
    delete: "Delete forever",
    deleteSelected: "Delete selected forever",
    empty: "Empty trash",
    search: "Search deleted items",
    daysLeft: (n: number) => (n === 1 ? "1 day left" : `${n} days left`),
    hoursLeft: (n: number) => (n === 1 ? "1 hour left" : `${n} hours left`),
    due: "Due for deletion",
    kept: "Kept",
    purgeOn: (date: string) => `Deleted for good on ${date}`,
    emptyTitle: "The trash is empty",
    emptyBody: "Things you delete show up here, and you can bring them back until they expire.",
    deleteTitle: (name: string) => `Delete “${name}” forever?`,
    deleteTitleMany: (n: number) => `Delete ${n} items forever?`,
    deleteBody: "This cannot be undone. The item and everything inside it is gone for good.",
    emptyDialogTitle: "Empty the trash?",
    emptyDialogBody: (n: number) => `${n === 1 ? "1 item" : `${n} items`} will be deleted for good. This cannot be undone.`,
    cancel: "Cancel",
    confirmDelete: "Delete forever",
    confirmEmpty: "Empty trash",
    error: "Something went wrong. Nothing was changed.",
    restored: (n: number) => (n === 1 ? "1 item restored" : `${n} items restored`),
    deletedDone: (n: number) => (n === 1 ? "1 item deleted" : `${n} items deleted`),
    trashEmptied: "Trash emptied",
    unknownType: "Item",
  },
  ar: {
    title: "سلة المحذوفات",
    listLabel: "العناصر المحذوفة",
    notice: (days: number) => `تُحذف العناصر نهائيًا بعد ${days} يومًا من حذفها.`,
    noticeKept: "تبقى العناصر هنا حتى تفرّغ السلة.",
    name: "الاسم",
    type: "النوع",
    deleted: "تاريخ الحذف",
    deletedBy: "حذفه",
    timeLeft: "الوقت المتبقي",
    types: "النوع",
    restore: "استعادة",
    restoreSelected: "استعادة المحدد",
    delete: "حذف نهائي",
    deleteSelected: "حذف المحدد نهائيًا",
    empty: "إفراغ السلة",
    search: "ابحث في المحذوفات",
    daysLeft: (n: number) => (n === 1 ? "متبقٍ يوم واحد" : n === 2 ? "متبقٍ يومان" : n <= 10 ? `متبقٍ ${n} أيام` : `متبقٍ ${n} يومًا`),
    hoursLeft: (n: number) => (n === 1 ? "متبقية ساعة" : n === 2 ? "متبقٍ ساعتان" : n <= 10 ? `متبقٍ ${n} ساعات` : `متبقٍ ${n} ساعة`),
    due: "جاهز للحذف",
    kept: "محفوظ",
    purgeOn: (date: string) => `يُحذف نهائيًا في ${date}`,
    emptyTitle: "السلة فارغة",
    emptyBody: "ما تحذفه يظهر هنا، ويمكنك استعادته قبل أن تنتهي مهلته.",
    deleteTitle: (name: string) => `حذف «${name}» نهائيًا؟`,
    deleteTitleMany: (n: number) => `حذف ${n} عنصرًا نهائيًا؟`,
    deleteBody: "لا يمكن التراجع عن هذا. يُحذف العنصر وكل ما بداخله نهائيًا.",
    emptyDialogTitle: "إفراغ السلة؟",
    emptyDialogBody: (n: number) => `سيُحذف ${n === 1 ? "عنصر واحد" : `${n} عنصرًا`} نهائيًا. لا يمكن التراجع عن هذا.`,
    cancel: "إلغاء",
    confirmDelete: "حذف نهائي",
    confirmEmpty: "إفراغ السلة",
    error: "حدث خطأ ما. لم يتغير شيء.",
    restored: (n: number) => (n === 1 ? "تمت استعادة عنصر واحد" : `تمت استعادة ${n} عنصرًا`),
    deletedDone: (n: number) => (n === 1 ? "تم حذف عنصر واحد" : `تم حذف ${n} عنصرًا`),
    trashEmptied: "تم إفراغ السلة",
    unknownType: "عنصر",
  },
};

export type TrashBinLabels = Partial<(typeof STRINGS)["en"]>;
