// Built-in English and Arabic strings, copied from packages/web/src/components/backup-manager/backup-manager.tsx.
import type { BackupFrequency, BackupStatus, RetentionError } from "./backup-format";

export const STRINGS = {
  en: {
    title: "Backups",
    description: "Automatic and manual copies of your data. Restore one to roll back.",
    runNow: "Back up now",
    running: "Backing up",
    lastBackup: "Last backup",
    nextRun: "Next backup",
    scheduleOff: "Schedule is off",
    storage: "Storage used",
    backupsCount: (n: number) => (n === 1 ? "1 backup" : `${n} backups`),
    never: "No backup yet",
    listTitle: "Backup history",
    list: "Backups",
    emptyTitle: "No backups yet",
    emptyBody: "Run your first backup now, or turn on the schedule.",
    kind: { scheduled: "Scheduled", manual: "Manual", "pre-restore": "Before restore" },
    status: { completed: "Completed", running: "In progress", failed: "Failed", restoring: "Restoring" } satisfies Record<BackupStatus, string>,
    progressFor: (name: string) => `Progress of ${name}`,
    locked: "Kept until you delete it",
    restore: "Restore",
    restoreFor: (name: string) => `Restore ${name}`,
    download: "Download",
    downloadFor: (name: string) => `Download ${name}`,
    remove: "Delete",
    removeFor: (name: string) => `Delete ${name}`,
    deleteTitle: (name: string) => `Delete ${name}?`,
    deleteBody: "This backup is removed for good. You will not be able to restore from it.",
    deleteConfirm: "Delete backup",
    restoreTitle: (name: string) => `Restore ${name}?`,
    restoreBody: "Your current data is replaced with the data in this backup. Changes made after it was taken are lost.",
    restoreSafety: "A safety backup of the current data is taken first, so you can undo this.",
    restoreCheck: "I understand my current data will be replaced.",
    restoreConfirm: "Restore backup",
    cancel: "Cancel",
    scheduleTitle: "Schedule",
    scheduleBody: "Back up on a schedule, in the server's time.",
    enabled: "Automatic backups",
    frequency: "Frequency",
    frequencies: { hourly: "Every hour", daily: "Every day", weekly: "Every week", monthly: "Every month" } satisfies Record<BackupFrequency, string>,
    time: "Time",
    minute: "Minute past the hour",
    weekday: "Day of the week",
    monthlyHint: "Runs on the 1st of each month.",
    retentionTitle: "Retention",
    retentionBody: "Old backups are deleted automatically so storage stays under control.",
    keepLast: "Keep the last",
    keepLastSuffix: "backups",
    maxAge: "Delete after (days)",
    maxAgeHint: "0 keeps backups until the count limit removes them.",
    prune: (n: number) => (n === 0 ? "Nothing would be deleted right now." : n === 1 ? "1 backup would be deleted at the next run." : `${n} backups would be deleted at the next run.`),
    errors: {
      keepLast: "Keep a whole number of backups, from 1 to 1000.",
      maxAgeDays: "Days is a whole number from 0 to 3650.",
    } satisfies Record<RetentionError, string>,
    timeInvalid: "Enter a time like 02:30.",
    save: "Save schedule",
    saved: "Schedule saved.",
    genericError: "Something went wrong. Try again.",
    actionsFor: (name: string) => `Actions for ${name}`,
    loading: "Loading backups",
  },
  ar: {
    title: "النسخ الاحتياطية",
    description: "نسخ تلقائية ويدوية من بياناتك. استعد إحداها للرجوع إلى حالة سابقة.",
    runNow: "نسخ احتياطي الآن",
    running: "جارٍ النسخ",
    lastBackup: "آخر نسخة",
    nextRun: "النسخة القادمة",
    scheduleOff: "الجدولة متوقفة",
    storage: "المساحة المستخدمة",
    backupsCount: (n: number) => (n === 1 ? "نسخة واحدة" : n === 2 ? "نسختان" : n <= 10 ? `${n} نسخ` : `${n} نسخة`),
    never: "لا توجد نسخة بعد",
    listTitle: "سجل النسخ",
    list: "النسخ الاحتياطية",
    emptyTitle: "لا توجد نسخ احتياطية بعد",
    emptyBody: "شغّل أول نسخة الآن، أو فعّل الجدولة.",
    kind: { scheduled: "مجدولة", manual: "يدوية", "pre-restore": "قبل الاستعادة" },
    status: { completed: "مكتملة", running: "قيد التنفيذ", failed: "فشلت", restoring: "قيد الاستعادة" } satisfies Record<BackupStatus, string>,
    progressFor: (name: string) => `تقدم ${name}`,
    locked: "محفوظة حتى تحذفها",
    restore: "استعادة",
    restoreFor: (name: string) => `استعادة ${name}`,
    download: "تنزيل",
    downloadFor: (name: string) => `تنزيل ${name}`,
    remove: "حذف",
    removeFor: (name: string) => `حذف ${name}`,
    deleteTitle: (name: string) => `حذف ${name}؟`,
    deleteBody: "تُحذف هذه النسخة نهائيًا ولن تتمكن من الاستعادة منها.",
    deleteConfirm: "حذف النسخة",
    restoreTitle: (name: string) => `استعادة ${name}؟`,
    restoreBody: "تُستبدل بياناتك الحالية ببيانات هذه النسخة. تضيع التغييرات التي جرت بعد أخذها.",
    restoreSafety: "تؤخذ أولًا نسخة أمان من البيانات الحالية، ليمكنك التراجع.",
    restoreCheck: "أفهم أن بياناتي الحالية ستُستبدل.",
    restoreConfirm: "استعادة النسخة",
    cancel: "إلغاء",
    scheduleTitle: "الجدولة",
    scheduleBody: "خذ نسخة احتياطية حسب جدول، بتوقيت الخادم.",
    enabled: "النسخ التلقائي",
    frequency: "التكرار",
    frequencies: { hourly: "كل ساعة", daily: "كل يوم", weekly: "كل أسبوع", monthly: "كل شهر" } satisfies Record<BackupFrequency, string>,
    time: "الوقت",
    minute: "الدقيقة من الساعة",
    weekday: "يوم الأسبوع",
    monthlyHint: "تعمل في اليوم الأول من كل شهر.",
    retentionTitle: "الاحتفاظ",
    retentionBody: "تُحذف النسخ القديمة تلقائيًا ليبقى التخزين تحت السيطرة.",
    keepLast: "احتفظ بآخر",
    keepLastSuffix: "نسخة",
    maxAge: "الحذف بعد (أيام)",
    maxAgeHint: "الصفر يبقي النسخ إلى أن يزيلها حد العدد.",
    prune: (n: number) =>
      n === 0 ? "لن يُحذف شيء الآن." : n === 1 ? "ستُحذف نسخة واحدة عند التشغيل القادم." : n === 2 ? "ستُحذف نسختان عند التشغيل القادم." : `ستُحذف ${n} نسخ عند التشغيل القادم.`,
    errors: {
      keepLast: "أدخل عددًا صحيحًا من النسخ، من 1 إلى 1000.",
      maxAgeDays: "الأيام عدد صحيح من 0 إلى 3650.",
    } satisfies Record<RetentionError, string>,
    timeInvalid: "أدخل وقتًا مثل 02:30.",
    save: "حفظ الجدولة",
    saved: "تم حفظ الجدولة.",
    genericError: "حدث خطأ ما. حاول مرة أخرى.",
    actionsFor: (name: string) => `إجراءات ${name}`,
    loading: "جارٍ تحميل النسخ",
  },
};

export type BackupManagerLabels = (typeof STRINGS)["en"];
