export { default as NqLinkify } from "./NqLinkify.vue";
export { default as NqUserText } from "./NqUserText.vue";
export { default as NqTranslatableText, type TranslateResult } from "./NqTranslatableText.vue";
export { default as NqScrollFade } from "./NqScrollFade.vue";
export { default as NqBookmarkButton } from "./NqBookmarkButton.vue";
export { default as NqProgressiveReveal } from "./NqProgressiveReveal.vue";
export { default as NqProgressiveList } from "./NqProgressiveList.vue";
export type { TextUtilitiesLabels } from "./strings";
export { linkifyText, linkifyTrim, progressiveNextCount, progressiveRemaining, scrollFadeMask, scrollFadeState } from "./text-utilities-logic";
export type { LinkifyOptions, LinkifySegment, ScrollFadeMetrics } from "./text-utilities-logic";
