export const STRINGS = {
  en: {
    title: "Vault",
    description: "Secrets stay hidden until someone with access reveals them. Every reveal and copy is logged.",
    secrets: "Secrets",
    accessLog: "Access log",
    add: "Add secret",
    filter: "Filter secrets",
    count: (n: number) => (n === 1 ? "1 secret" : `${n} secrets`),
    ungrouped: "Ungrouped",
    noMatch: "No secrets match your filter.",
    emptyTitle: "The vault is empty",
    emptyBody: "Store API keys, passwords and certificates here instead of in chat or files.",
    loading: "Loading secrets",
    reveal: (name: string) => `Reveal ${name}`,
    hide: (name: string) => `Hide ${name}`,
    copy: (name: string) => `Copy ${name}`,
    copied: "Copied to clipboard",
    copyFailed: "Could not copy",
    edit: (name: string) => `Edit ${name}`,
    remove: (name: string) => `Delete ${name}`,
    hidden: "Value hidden",
    autoHide: (s: number) => `Hides again in ${s} seconds`,
    updated: "Updated",
    lastUsed: "Last used",
    never: "never",
    expires: "Expires",
    expired: "Expired",
    expiresIn: (d: number) => (d === 1 ? "Expires in 1 day" : `Expires in ${d} days`),
    revealFailed: "Could not fetch the value.",
    kind: {
      "api-key": "API key",
      password: "Password",
      token: "Token",
      certificate: "Certificate",
      "ssh-key": "SSH key",
      other: "Secret",
    },
    // dialog
    addTitle: "Add secret",
    editTitle: (name: string) => `Edit ${name}`,
    nameLabel: "Name",
    nameEmpty: "Enter a name.",
    nameDuplicate: "A secret with this name already exists in this group.",
    groupLabel: "Group",
    groupHint: "Secrets with the same group are listed together, like a project or a service.",
    kindLabel: "Type",
    valueLabel: "Value",
    valueKeep: "Leave blank to keep the current value.",
    valueEmpty: "Enter the value.",
    showValue: "Show value",
    noteLabel: "Note (optional)",
    expiryLabel: "Expires on (optional)",
    save: "Save",
    cancel: "Cancel",
    genericError: "Something went wrong. Try again.",
    deleteTitle: (name: string) => `Delete ${name}?`,
    deleteBody: "The value is removed from the vault for everyone. Anything still using it will stop working.",
    deleteConfirm: "Delete",
    // log
    logTable: "Access log",
    logSearch: "Search the log",
    logEmpty: "Nothing has been accessed yet",
    time: "When",
    actor: "Who",
    action: "Action",
    secret: "Secret",
    address: "Address",
    actions: {
      reveal: "Revealed",
      copy: "Copied",
      create: "Created",
      update: "Updated",
      delete: "Deleted",
    },
  },
  ar: {
    title: "الخزنة",
    description: "تبقى الأسرار مخفية إلى أن يكشفها من يملك الصلاحية. يُسجَّل كل كشف ونسخ.",
    secrets: "الأسرار",
    accessLog: "سجل الوصول",
    add: "إضافة سر",
    filter: "تصفية الأسرار",
    count: (n: number) => (n === 1 ? "سر واحد" : n === 2 ? "سران" : n >= 3 && n <= 10 ? `${n} أسرار` : `${n} سرًّا`),
    ungrouped: "بلا مجموعة",
    noMatch: "لا توجد أسرار تطابق التصفية.",
    emptyTitle: "الخزنة فارغة",
    emptyBody: "احفظ مفاتيح الواجهات وكلمات المرور والشهادات هنا بدلًا من المحادثات والملفات.",
    loading: "جارٍ تحميل الأسرار",
    reveal: (name: string) => `كشف ${name}`,
    hide: (name: string) => `إخفاء ${name}`,
    copy: (name: string) => `نسخ ${name}`,
    copied: "تم النسخ",
    copyFailed: "تعذر النسخ",
    edit: (name: string) => `تعديل ${name}`,
    remove: (name: string) => `حذف ${name}`,
    hidden: "القيمة مخفية",
    autoHide: (s: number) => `تُخفى مجددًا بعد ${s} ثانية`,
    updated: "آخر تحديث",
    lastUsed: "آخر استخدام",
    never: "أبدًا",
    expires: "ينتهي",
    expired: "منتهي الصلاحية",
    expiresIn: (d: number) => (d === 1 ? "ينتهي خلال يوم" : d === 2 ? "ينتهي خلال يومين" : d >= 3 && d <= 10 ? `ينتهي خلال ${d} أيام` : `ينتهي خلال ${d} يومًا`),
    revealFailed: "تعذر جلب القيمة.",
    kind: {
      "api-key": "مفتاح API",
      password: "كلمة مرور",
      token: "رمز وصول",
      certificate: "شهادة",
      "ssh-key": "مفتاح SSH",
      other: "سر",
    },
    addTitle: "إضافة سر",
    editTitle: (name: string) => `تعديل ${name}`,
    nameLabel: "الاسم",
    nameEmpty: "أدخل اسمًا.",
    nameDuplicate: "يوجد سر بهذا الاسم في المجموعة نفسها.",
    groupLabel: "المجموعة",
    groupHint: "تُعرض الأسرار ذات المجموعة نفسها معًا، مثل مشروع أو خدمة.",
    kindLabel: "النوع",
    valueLabel: "القيمة",
    valueKeep: "اتركها فارغة للإبقاء على القيمة الحالية.",
    valueEmpty: "أدخل القيمة.",
    showValue: "إظهار القيمة",
    noteLabel: "ملاحظة (اختياري)",
    expiryLabel: "تاريخ الانتهاء (اختياري)",
    save: "حفظ",
    cancel: "إلغاء",
    genericError: "حدث خطأ ما. حاول مرة أخرى.",
    deleteTitle: (name: string) => `حذف ${name}؟`,
    deleteBody: "تُزال القيمة من الخزنة للجميع، وسيتوقف أي شيء لا يزال يستخدمها عن العمل.",
    deleteConfirm: "حذف",
    logTable: "سجل الوصول",
    logSearch: "ابحث في السجل",
    logEmpty: "لم يُصل إلى أي سر بعد",
    time: "الوقت",
    actor: "من",
    action: "الإجراء",
    secret: "السر",
    address: "العنوان",
    actions: {
      reveal: "كشف",
      copy: "نسخ",
      create: "إنشاء",
      update: "تحديث",
      delete: "حذف",
    },
  },
};

export type VaultLabels = { [K in keyof typeof STRINGS.en]: (typeof STRINGS.en)[K] };
