// The card own words, en and ar, copied from the React EngineCard. Time arguments are strings (already formatted).

export const STRINGS = {
  en: {
    details: "Details",
    logUnit: "Log one unit",
    logWake: "I woke up",
    logDose: "Log dose",
    recordDose: "Record a dose",
    wait: (time: string) => `Wait ${time}`,
    working: "Working…",
    unitsToday: "Units today",
    ofCap: "of",
    blockProgress: "Block",
    blockLeft: (time: string) => `${time} left`,
    blockOver: "The block has ended.",
    blockWaiting: "Log when you woke up to start the block.",
    cupsToday: "Caffeine drinks today",
    cupsOf: (n: string, of: string) => `${n} of ${of}`,
    violations: "Logged inside the block",
    windowLabel: "Window",
    windowRange: (from: string, to: string) => `${from} to ${to}`,
    windowLeft: (time: string) => `${time} left in the window`,
    windowNone: "Set your bedtime to open a window.",
    allowedInside: "Allowed inside the window",
    gerdViolations: "Outside the list, today",
    needsReview: "Needs review",
    nextDose: "Next dose",
    noDoses: "No doses are scheduled today.",
    logged: "Logged",
    triggerBearing: "Trigger-bearing",
    safe: "Judged safe",
    unclassified: "Not judged",
    unclassifiedNote: "An item nobody has classified is not judged. It is never shown as safe.",
    byFamily: "By family",
    calibration: "Cycles counted",
    calibrationValue: (n: string, of: string) => `${n} of ${of}`,
    average: "Average cycle",
    nextStart: "Next expected start",
    ovulation: "Estimated ovulation",
    fertile: "Fertile window",
    fertileRange: (from: string, to: string) => `${from} to ${to}`,
    reasons: {
      insufficient_cycles: "Not enough cycles are recorded yet.",
      irregular: "Recent cycles vary too much for a prediction.",
      recalibrating: "Building up history again after a suspension.",
    } as Record<string, string>,
    predictionNote: "A prediction is not a guarantee.",
    method: "Method",
    nextDue: "Next due",
    lastRecorded: "Last recorded",
    daysOverdue: "Past the plan",
    unconfiguredNote: "Add your schedule to start tracking.",
    graceNote: (time: string) => `Each dose can be logged on time for ${time} after its scheduled time.`,
    noSnapshot: "Something went wrong. Try again.",
    stateLabel: "State",
  },
  ar: {
    details: "التفاصيل",
    logUnit: "سجّل وحدة",
    logWake: "استيقظت",
    logDose: "سجّل الجرعة",
    recordDose: "سجّل جرعة",
    wait: (time: string) => `انتظر ${time}`,
    working: "جارٍ التنفيذ…",
    unitsToday: "وحدات اليوم",
    ofCap: "من",
    blockProgress: "الحظر",
    blockLeft: (time: string) => `متبقٍّ ${time}`,
    blockOver: "انتهى الحظر.",
    blockWaiting: "سجّل وقت استيقاظك لبدء الحظر.",
    cupsToday: "مشروبات الكافيين اليوم",
    cupsOf: (n: string, of: string) => `${n} من ${of}`,
    violations: "سُجّل داخل الحظر",
    windowLabel: "النافذة",
    windowRange: (from: string, to: string) => `من ${from} إلى ${to}`,
    windowLeft: (time: string) => `متبقٍّ ${time} من النافذة`,
    windowNone: "حدّد موعد نومك لفتح نافذة.",
    allowedInside: "المسموح داخل النافذة",
    gerdViolations: "خارج القائمة اليوم",
    needsReview: "بحاجة إلى مراجعة",
    nextDose: "الجرعة التالية",
    noDoses: "لا توجد جرعات مجدولة اليوم.",
    logged: "سُجّلت",
    triggerBearing: "يحمل محفّزًا",
    safe: "مُقيَّم آمنًا",
    unclassified: "لم يُقيَّم",
    unclassifiedNote: "ما لم يصنّفه أحد يبقى غير مُقيَّم، ولا يُعرض أبدًا على أنه آمن.",
    byFamily: "بحسب العائلة",
    calibration: "الدورات المحسوبة",
    calibrationValue: (n: string, of: string) => `${n} من ${of}`,
    average: "متوسط الدورة",
    nextStart: "البداية المتوقعة التالية",
    ovulation: "الإباضة المقدّرة",
    fertile: "فترة الخصوبة",
    fertileRange: (from: string, to: string) => `من ${from} إلى ${to}`,
    reasons: {
      insufficient_cycles: "لم تُسجَّل دورات كافية بعد.",
      irregular: "الدورات الأخيرة متفاوتة جدًا لإعطاء توقع.",
      recalibrating: "يُعاد بناء السجل بعد تعليق التوقع.",
    } as Record<string, string>,
    predictionNote: "التوقع ليس ضمانًا.",
    method: "الوسيلة",
    nextDue: "الموعد التالي",
    lastRecorded: "آخر تسجيل",
    daysOverdue: "بعد الخطة",
    unconfiguredNote: "أضف جدولك لبدء التتبّع.",
    graceNote: (time: string) => `يمكن تسجيل كل جرعة في وقتها خلال ${time} من موعدها.`,
    noSnapshot: "حدث خطأ ما. حاول مرة أخرى.",
    stateLabel: "الحالة",
  },
};

export type EngineCardLabels = typeof STRINGS.en;
