import type { EngineId } from "./health-engines";

export const VOCAB = {
  en: {
    engines: {
      hydration: { title: "Hydration", subtitle: "One fixed unit at a time, up to a daily cap." },
      caffeine: { title: "Caffeine Block", subtitle: "No caffeine for a set time after waking." },
      gerd: { title: "GERD Window", subtitle: "Only water, chamomile or anise before sleep." },
      medication: { title: "Medication Grace", subtitle: "Was each scheduled dose logged, and on time?" },
      triggers: { title: "Trigger Families", subtitle: "What was logged, by trigger family." },
      cycle: { title: "Cycle", subtitle: "Predictions only when the history supports them." },
      contraceptive: { title: "Contraceptive Schedule", subtitle: "What has been recorded against your own plan." },
    } as Record<EngineId, { title: string; subtitle: string }>,
    states: {
      "hydration.idle": "Ready to log",
      "hydration.cooldown": "Cooling down",
      "hydration.capped": "Daily cap reached",
      "caffeine.awaiting_wake": "Waiting for wake time",
      "caffeine.blocked": "Blocked",
      "caffeine.clear": "Clear",
      "gerd.unanchored": "No sleep time set",
      "gerd.open": "Window closed",
      "gerd.window_active": "Window active",
      "gerd.sleeping": "Sleeping",
      "medication.none": "No doses today",
      "medication.grace_open": "Dose window open",
      "medication.missed": "Dose not logged",
      "medication.scheduled": "Scheduled",
      "medication.late_logged": "Logged late",
      "medication.logged": "All logged",
      "triggers.none": "Nothing logged",
      "triggers.unjudged": "Not judged",
      "triggers.clear": "No trigger logged",
      "triggers.exposed": "Trigger logged",
      "cycle.insufficient": "Building history",
      "cycle.calibrated": "Prediction offered",
      "cycle.suspended": "Prediction withdrawn",
      "contraceptive.unconfigured": "Not set up",
      "contraceptive.on_schedule": "On schedule",
      "contraceptive.due": "Due",
      "contraceptive.overdue": "Overdue",
      "contraceptive.expiring": "Expiring soon",
      "contraceptive.expired": "Expired",
    } as Record<string, string>,
    doseStatus: {
      scheduled: "Scheduled",
      grace_open: "Window open",
      logged: "Logged",
      late_logged: "Logged late",
      missed: "Not logged",
    } as Record<string, string>,
    verdicts: { on_protocol: "On protocol", off_protocol: "Off protocol", unevaluated: "Not judged" } as Record<string, string>,
    families: { gout: "Gout", ibs_gerd: "IBS and reflux", fatty_liver: "Fatty liver" } as Record<string, string>,
    whitelist: { water: "Water", chamomile: "Chamomile", anise: "Anise" } as Record<string, string>,
    methods: { daily_pill: "Daily pill", monthly_injection: "Monthly injection", implant: "Implant" } as Record<string, string>,
    units: { kcal: "kcal", bpm: "bpm", steps: "steps", bmi: "kg/m²", level: "", cups: "cups", cycles: "cycles" } as Record<string, string>,
    consult: "Consult your doctor.",
    unavailable: "Unavailable",
    daysUnit: "days",
  },
  ar: {
    engines: {
      hydration: { title: "شرب الماء", subtitle: "وحدة ثابتة واحدة في كل مرة، حتى سقف يومي." },
      caffeine: { title: "حظر الكافيين", subtitle: "لا كافيين لفترة محددة بعد الاستيقاظ." },
      gerd: { title: "نافذة الارتجاع", subtitle: "الماء أو البابونج أو اليانسون فقط قبل النوم." },
      medication: { title: "مهلة الدواء", subtitle: "هل سُجّلت كل جرعة مجدولة، وفي وقتها؟" },
      triggers: { title: "عائلات المحفّزات", subtitle: "ما سُجّل، بحسب عائلة المحفّز." },
      cycle: { title: "الدورة الشهرية", subtitle: "لا توقعات إلا حين يدعمها السجل." },
      contraceptive: { title: "جدول وسائل منع الحمل", subtitle: "ما سُجّل مقابل خطتك أنت." },
    } as Record<EngineId, { title: string; subtitle: string }>,
    states: {
      "hydration.idle": "جاهز للتسجيل",
      "hydration.cooldown": "فترة انتظار",
      "hydration.capped": "بلغت السقف اليومي",
      "caffeine.awaiting_wake": "بانتظار وقت الاستيقاظ",
      "caffeine.blocked": "محظور",
      "caffeine.clear": "مسموح",
      "gerd.unanchored": "لم يُحدَّد وقت النوم",
      "gerd.open": "النافذة مغلقة",
      "gerd.window_active": "النافذة نشطة",
      "gerd.sleeping": "نائم",
      "medication.none": "لا جرعات اليوم",
      "medication.grace_open": "نافذة الجرعة مفتوحة",
      "medication.missed": "جرعة غير مسجّلة",
      "medication.scheduled": "مجدولة",
      "medication.late_logged": "سُجّلت متأخرة",
      "medication.logged": "سُجّلت كلها",
      "triggers.none": "لا شيء مسجّل",
      "triggers.unjudged": "لم يُقيَّم",
      "triggers.clear": "لا محفّز مسجّل",
      "triggers.exposed": "سُجّل محفّز",
      "cycle.insufficient": "بناء السجل",
      "cycle.calibrated": "التوقع متاح",
      "cycle.suspended": "سُحب التوقع",
      "contraceptive.unconfigured": "لم يُعدّ بعد",
      "contraceptive.on_schedule": "في الموعد",
      "contraceptive.due": "مستحقة",
      "contraceptive.overdue": "متأخرة",
      "contraceptive.expiring": "تنتهي قريبًا",
      "contraceptive.expired": "منتهية",
    } as Record<string, string>,
    doseStatus: {
      scheduled: "مجدولة",
      grace_open: "النافذة مفتوحة",
      logged: "مسجّلة",
      late_logged: "سُجّلت متأخرة",
      missed: "غير مسجّلة",
    } as Record<string, string>,
    verdicts: { on_protocol: "ضمن البروتوكول", off_protocol: "خارج البروتوكول", unevaluated: "لم يُقيَّم" } as Record<string, string>,
    families: { gout: "النقرس", ibs_gerd: "القولون والارتجاع", fatty_liver: "الكبد الدهني" } as Record<string, string>,
    whitelist: { water: "الماء", chamomile: "البابونج", anise: "اليانسون" } as Record<string, string>,
    methods: { daily_pill: "حبوب يومية", monthly_injection: "حقنة شهرية", implant: "غرسة" } as Record<string, string>,
    units: { kcal: "kcal", bpm: "bpm", steps: "خطوة", bmi: "kg/m²", level: "", cups: "أكواب", cycles: "دورات" } as Record<string, string>,
    consult: "استشر طبيبك.",
    unavailable: "غير متاح",
    daysUnit: "أيام",
  },
};

export type HealthVocab = (typeof VOCAB)["en"];
