"use client";

import { useCallback, useRef, useState } from "react";
import { useOptionalNasaq } from "../../provider/nasaq-provider";
import { minorToMajor } from "../currency-input/currency-input-logic";
import { formatNumber, Num } from "../numeric";
import type { DiscountClass, DiscountKind, DiscountRejection, DiscountStanding } from "./discount-logic";
import type { GiftCardEntryKind, GiftCardError, GiftCardStatus, LedgerIssue } from "./gift-card-logic";
import type { RateUnavailable, ShippingRateType, TierIssue } from "./shipping-logic";

/* ------------------------------------------------------------------ strings */

const en = {
  // common
  saveFailed: "Could not save. Try again.",
  loadFailed: "This did not load.",
  edit: "Edit",
  delete: "Delete",
  cancel: "Cancel",
  yes: "Yes",
  no: "No",
  on: "On",
  off: "Off",
  active: "Active",
  free: "Free",
  never: "Never",
  enable: "Turn on",
  disable: "Turn off",
  statusCol: "Status",
  price: "Price",
  type: "Type",
  value: "Value",
  code: "Code",
  amount: "Amount",
  note: "Note",
  country: "Country",
  countryHint: "Two-letter code, like EG or SA.",
  city: "City",
  cities: "Cities",
  address: "Address",
  // shipping
  shipping: "Shipping",
  zones: "Shipping zones",
  addZone: "Add zone",
  editZone: "Edit zone",
  zonesEmpty: "No shipping zones yet",
  zonesEmptyHint: "Add a zone so customers can pick a delivery option.",
  overlapTitle: "Some countries are in more than one zone",
  overlapBody: (list: string) => `${list}. The first zone in the list wins, so the others never apply there.`,
  restOfWorld: "Rest of the world",
  noRates: "No rates",
  express: "Express",
  freeOver: "Free over",
  tiersCount: (n: string) => `${n} tiers`,
  etaDays: (from: number, to: number) => (from === to ? `${from} days` : `${from} to ${to} days`),
  readyIn: (n: string) => `Ready in ${n} h`,
  pickup: "Local pickup",
  pickupBadge: "Pickup",
  addPickup: "Add pickup point",
  editPickup: "Edit pickup point",
  pickupEmpty: "No pickup points",
  pickupEmptyHint: "Let customers collect orders from your shop or warehouse.",
  pickupHint: "Customers who pick up pay no shipping, only the fee if you set one.",
  pickupName: "Name",
  pickupFee: "Fee",
  readyInHoursLabel: "Ready in (hours)",
  savePickup: "Save pickup point",
  deleteZoneTitle: "Delete this zone?",
  deletePickupTitle: "Delete this pickup point?",
  deleteBody: (name: string) => `${name} will be removed. This cannot be undone.`,
  zoneHint: "A zone is the places you deliver to and what you charge there.",
  zoneName: "Zone name",
  zoneNameRequired: "Give the zone a name.",
  countries: "Countries",
  countriesPlaceholder: "Add a country code",
  countriesHint: "Use * for every country not listed in another zone.",
  citiesPlaceholder: "Add a city",
  citiesHint: "Optional. Leave empty to cover the whole country.",
  countriesRequired: "Add at least one country.",
  fixRates: "Fix the rates marked in red first.",
  rates: "Rates",
  addRate: "Add rate",
  rateName: "Rate name",
  rateNamePlaceholder: "Standard delivery",
  rateType: "Rate type",
  rateTypes: { flat: "Flat rate", weight: "By weight", price: "By order price", "free-over": "Free over an amount" } as Record<ShippingRateType, string>,
  removeRate: (n: string) => `Remove rate ${n}`,
  freeOverAmount: "Free when the order is at least",
  belowPrice: "Charge below that",
  belowPriceHint: "What customers pay under the threshold. Leave empty to hide the rate until they reach it.",
  etaFrom: "Delivery from (days)",
  etaTo: "Delivery to (days)",
  saveZone: "Save zone",
  weightTiers: "Weight tiers",
  priceTiers: "Price tiers",
  tierFrom: "From",
  tierTo: "Up to",
  tierPrice: "Charge",
  andAbove: "and above",
  addTier: "Add tier",
  removeTier: (n: string) => `Remove tier ${n}`,
  grams: "g",
  weightUnitHint: "Weight is in grams.",
  tierIssues: { overlap: "Two tiers overlap.", gap: "There is a gap between two tiers.", "min-after-max": "A tier starts after it ends.", negative: "A tier has a negative value.", "no-tiers": "Add at least one tier.", "not-open-ended": "The last tier must have no upper limit." } as Record<TierIssue, string>,
  unavailable: { inactive: "is turned off", "no-tier": "has no tier for this cart", "below-threshold": "needs a bigger order" } as Record<RateUnavailable, string>,
  tryDestination: "Try a destination",
  cartTotal: "Cart total",
  cartWeight: "Cart weight (g)",
  servedBy: (zone: string) => `Served by ${zone}`,
  noZone: "No zone covers this destination.",
  noOptions: "Customers would see no delivery option here.",
  spendMore: "Spend",
  // tax
  taxes: "Taxes",
  taxRates: "Tax rates",
  addTax: "Add tax rate",
  editTax: "Edit tax rate",
  taxOverlapTitle: "Two rates cover the same place",
  taxOverlapBody: (list: string) => `${list}. Only one is used, so remove or narrow the other.`,
  searchTax: "Search tax rates",
  taxName: "Name",
  taxNamePlaceholder: "VAT",
  region: "Region",
  regionOptional: "Region (optional)",
  regionHint: "A state or governorate code. Leave empty to cover the country.",
  rate: "Rate",
  ratePercent: "Rate (%)",
  rateInvalid: "Enter a percentage from 0 to 100, like 14 or 7.5.",
  bpsIs: (bps: string) => `${bps} basis points`,
  mode: "Prices",
  inclusive: "Tax included",
  exclusive: "Tax added at checkout",
  inclusiveHint: "Shelf prices already contain tax. The customer pays the same price.",
  exclusiveHint: "Tax is added on top of the price at checkout.",
  onShipping: "Charge tax on shipping",
  enableTax: "Turn on",
  taxEmpty: "No tax rates yet",
  taxEmptyHint: "Add the rate you collect so checkout can show tax.",
  deleteTaxTitle: "Delete this tax rate?",
  taxHint: "Rates are stored in basis points, so 14% is 1400. Tax is rounded once per order.",
  saveTax: "Save tax rate",
  tryTax: "Try it on an order",
  goods: "Goods",
  shippingCharge: "Shipping",
  taxAmount: "Tax",
  netAmount: "Net",
  addedToTotal: "added to the total",
  customerPays: "Customer pays",
  noTaxRate: "No tax rate covers this country.",
  // discounts
  discounts: "Discounts",
  addDiscount: "Add discount",
  editDiscount: "Edit discount",
  discountHint: "Automatic discounts apply by themselves. Codes apply when the customer types them.",
  discountTitle: "Title",
  method: "Method",
  automatic: "Automatic",
  byCode: "Discount code",
  used: "Used",
  perItemShort: "per item",
  bxgyShort: (buy: string, get: string) => `Buy ${buy}, get ${get}`,
  freeShipping: "Free shipping",
  freeShippingHint: "Takes the whole shipping charge off.",
  duplicate: "Duplicate",
  copyOf: (title: string) => `Copy of ${title}`,
  duplicateCodes: (list: string) => `The same code is used twice: ${list}.`,
  searchDiscounts: "Search discounts",
  discountsEmpty: "No discounts yet",
  discountsEmptyHint: "Create a discount to run a sale or reward customers.",
  deleteDiscountTitle: "Delete this discount?",
  saveDiscount: "Save discount",
  whatItDoes: "What it does",
  kinds: { percentage: "Percentage off", fixed: "Amount off", bxgy: "Buy X get Y", "free-shipping": "Free shipping" } as Record<DiscountKind, string>,
  classes: { product: "Product discount", order: "Order discount", shipping: "Shipping discount" } as Record<DiscountClass, string>,
  standings: { live: "Live", scheduled: "Scheduled", ended: "Ended", off: "Off", "used-up": "Used up" } as Record<DiscountStanding, string>,
  percentOff: "Percent off",
  amountOff: "Amount off",
  perItem: "Take the amount off each item",
  cap: "Most it can take off",
  capShipping: "Most it can take off shipping",
  capHint: "Leave empty for no cap.",
  appliesTo: "Applies to",
  excludeOnSale: "Skip items already on sale",
  requirements: "Requirements",
  minSpend: "Minimum spend",
  minQuantity: "Minimum items",
  eligibility: "Who can use it",
  customers: "Customers",
  customersAll: "Everyone",
  customersSegments: "Segments",
  customersSpecific: "Specific customers",
  segmentsLabel: "Segments",
  segmentsPlaceholder: "Add a segment",
  customerIdsLabel: "Customer ids",
  customerIdsPlaceholder: "Add a customer id",
  firstOrderOnly: "First order only",
  schedule: "Schedule",
  startsOn: "Starts",
  endsOn: "Ends",
  limits: "Limits",
  limitTotal: "Total uses",
  limitCustomer: "Uses per customer",
  combinesWith: "Can combine with",
  combinesHint: "Discounts of the same kind never stack, whatever you pick.",
  problemTitle: "Fix these first",
  problemCode: "Add a code.",
  problemDuplicateCode: "Another discount already uses this code.",
  problemPercent: "Enter a percentage from 0 to 100.",
  problemAmount: "Enter an amount above zero.",
  problemBxgy: "Set how many to buy and how many to get.",
  problemDates: "The end date must be after the start date.",
  buyQty: "Buy quantity",
  getQty: "Get quantity",
  getPercent: "Discount on the free items (%)",
  getPercentHint: "100 makes them free.",
  maxSets: "Most sets per order",
  noLimit: "No limit",
  buyItems: "Items to buy",
  getItems: "Items to get",
  sameAsBuy: "Same as the items to buy",
  everything: "Everything",
  scopeCount: (n: string) => `${n} selected`,
  collection: "Collection",
  rejections: {
    inactive: "is turned off",
    "not-started": "has not started",
    ended: "has ended",
    "limit-total": "has been used up",
    "limit-customer": "this customer used it already",
    "code-required": "needs its code",
    customer: "not open to this customer",
    "first-order": "first orders only",
    "min-subtotal": "spend is below the minimum",
    "min-quantity": "not enough items",
    "no-match": "no matching items",
    "no-shipping": "no shipping charge",
    "no-benefit": "would take nothing off",
    "not-combinable": "cannot combine with another discount",
  } as Record<DiscountRejection, string>,
  simulator: "Try a basket",
  simulatorHint: "Pick items and type codes to see what a customer would get. Money is in whole minor units.",
  basket: "Basket",
  decrease: "Fewer",
  increase: "More",
  codesTyped: "Codes typed",
  pastOrders: "Past orders",
  basketEmpty: "Add an item to the basket.",
  subtotal: "Subtotal",
  capped: "Capped",
  freeUnits: (n: string) => `${n} free`,
  nothingApplies: "No discount applies.",
  notApplied: "Not applied",
  // gift cards
  giftCards: "Gift cards",
  giftCard: "Gift card",
  issueCard: "Issue gift card",
  issueHint: "Creates a card with a code you can send. The balance is kept as a ledger.",
  searchCards: "Search gift cards",
  cardsEmpty: "No gift cards yet",
  cardsEmptyHint: "Issue a card and share its code with the buyer.",
  openCard: "Open",
  balance: "Balance",
  issuedValue: "Issued for",
  expires: "Expires",
  expiresHint: "Optional. The card works through the end of that day.",
  generate: "New code",
  codeHint: "Sixteen characters. The last one checks for typing errors.",
  codeInvalid: "This code is not valid. Check for typing errors.",
  codeTaken: "A card already has this code.",
  recipientName: "Recipient name",
  recipientEmail: "Recipient email",
  noRecipient: "No recipient",
  redeem: "Redeem",
  redeemed: "Redeemed.",
  orderRef: "Order",
  adjust: "Adjust balance",
  adjusted: "Balance adjusted.",
  direction: "Direction",
  addBalance: "Add balance",
  removeBalance: "Remove balance",
  cardEnabled: "Card can be used",
  history: "History",
  ledgerProblem: "This ledger looks wrong",
  giftStatuses: { active: "Active", depleted: "Used up", expired: "Expired", disabled: "Disabled" } as Record<GiftCardStatus, string>,
  entryKinds: { issue: "Issued", redeem: "Redeemed", refund: "Refunded", adjust: "Adjusted", expire: "Expired", void: "Voided" } as Record<GiftCardEntryKind, string>,
  giftErrors: {
    "not-found": "We could not find this gift card.",
    disabled: "This gift card is turned off.",
    expired: "This gift card has expired.",
    empty: "This gift card has no balance left.",
    currency: "This gift card is in another currency.",
    "invalid-amount": "Enter an amount above zero.",
    "over-balance": "That is more than the balance.",
  } as Record<GiftCardError, string>,
  ledgerIssues: { "no-issue": "The ledger has no issue entry.", sign: "An entry has the wrong sign.", "negative-balance": "The balance dips below zero.", "duplicate-id": "Two entries share an id.", "out-of-order": "Entries are out of date order." } as Record<LedgerIssue, string>,
  applyCard: "Apply",
  removeCard: "Remove gift card",
  alreadyAdded: "This card is already added.",
  lookupFailed: "We could not check this card. Try again.",
  youPay: "Left to pay",
};

export type SettingsStrings = typeof en;

const ar: SettingsStrings = {
  saveFailed: "لم يتم الحفظ. حاول مرة أخرى.",
  loadFailed: "تعذّر التحميل.",
  edit: "تعديل",
  delete: "حذف",
  cancel: "إلغاء",
  yes: "نعم",
  no: "لا",
  on: "مفعّل",
  off: "متوقف",
  active: "نشط",
  free: "مجاني",
  never: "بلا انتهاء",
  enable: "تشغيل",
  disable: "إيقاف",
  statusCol: "الحالة",
  price: "السعر",
  type: "النوع",
  value: "القيمة",
  code: "الرمز",
  amount: "المبلغ",
  note: "ملاحظة",
  country: "الدولة",
  countryHint: "رمز من حرفين مثل EG أو SA.",
  city: "المدينة",
  cities: "المدن",
  address: "العنوان",
  shipping: "الشحن",
  zones: "مناطق الشحن",
  addZone: "إضافة منطقة",
  editZone: "تعديل المنطقة",
  zonesEmpty: "لا توجد مناطق شحن بعد",
  zonesEmptyHint: "أضف منطقة ليختار العملاء طريقة التوصيل.",
  overlapTitle: "بعض الدول في أكثر من منطقة",
  overlapBody: (list) => `${list}. تُطبَّق أول منطقة في القائمة، فلا تعمل الأخرى هناك.`,
  restOfWorld: "باقي دول العالم",
  noRates: "بلا أسعار",
  express: "سريع",
  freeOver: "مجاني فوق",
  tiersCount: (n) => `${n} شرائح`,
  etaDays: (from, to) => (from === to ? (from === 1 ? "يوم" : `${from} أيام`) : `من ${from} إلى ${to} أيام`),
  readyIn: (n) => `جاهز خلال ${n} ساعة`,
  pickup: "الاستلام من المتجر",
  pickupBadge: "استلام",
  addPickup: "إضافة نقطة استلام",
  editPickup: "تعديل نقطة الاستلام",
  pickupEmpty: "لا توجد نقاط استلام",
  pickupEmptyHint: "دع العملاء يستلمون طلباتهم من متجرك أو مخزنك.",
  pickupHint: "من يستلم بنفسه لا يدفع شحنًا، فقط الرسوم إن حددتها.",
  pickupName: "الاسم",
  pickupFee: "الرسوم",
  readyInHoursLabel: "جاهز خلال (ساعات)",
  savePickup: "حفظ نقطة الاستلام",
  deleteZoneTitle: "حذف هذه المنطقة؟",
  deletePickupTitle: "حذف نقطة الاستلام هذه؟",
  deleteBody: (name) => `سيُحذف ${name}. لا يمكن التراجع.`,
  zoneHint: "المنطقة هي الأماكن التي توصّل إليها وما تحصّله فيها.",
  zoneName: "اسم المنطقة",
  zoneNameRequired: "أعطِ المنطقة اسمًا.",
  countries: "الدول",
  countriesPlaceholder: "أضف رمز دولة",
  countriesHint: "استخدم * لكل دولة غير مذكورة في منطقة أخرى.",
  citiesPlaceholder: "أضف مدينة",
  citiesHint: "اختياري. اتركه فارغًا لتغطية الدولة كلها.",
  countriesRequired: "أضف دولة واحدة على الأقل.",
  fixRates: "أصلح الأسعار المعلّمة بالأحمر أولًا.",
  rates: "الأسعار",
  addRate: "إضافة سعر",
  rateName: "اسم السعر",
  rateNamePlaceholder: "توصيل عادي",
  rateType: "نوع السعر",
  rateTypes: { flat: "سعر ثابت", weight: "حسب الوزن", price: "حسب سعر الطلب", "free-over": "مجاني فوق مبلغ" },
  removeRate: (n) => `حذف السعر ${n}`,
  freeOverAmount: "مجاني عندما يبلغ الطلب",
  belowPrice: "الرسوم دون ذلك",
  belowPriceHint: "ما يدفعه العميل تحت الحد. اتركه فارغًا لإخفاء السعر حتى يبلغه.",
  etaFrom: "التوصيل من (أيام)",
  etaTo: "التوصيل إلى (أيام)",
  saveZone: "حفظ المنطقة",
  weightTiers: "شرائح الوزن",
  priceTiers: "شرائح السعر",
  tierFrom: "من",
  tierTo: "حتى",
  tierPrice: "الرسوم",
  andAbove: "فما فوق",
  addTier: "إضافة شريحة",
  removeTier: (n) => `حذف الشريحة ${n}`,
  grams: "جم",
  weightUnitHint: "الوزن بالجرام.",
  tierIssues: { overlap: "شريحتان متداخلتان.", gap: "هناك فجوة بين شريحتين.", "min-after-max": "شريحة تبدأ بعد نهايتها.", negative: "شريحة قيمتها سالبة.", "no-tiers": "أضف شريحة واحدة على الأقل.", "not-open-ended": "آخر شريحة يجب ألا يكون لها حد أعلى." },
  unavailable: { inactive: "متوقف", "no-tier": "لا شريحة لهذه السلة", "below-threshold": "يحتاج طلبًا أكبر" },
  tryDestination: "جرّب وجهة",
  cartTotal: "إجمالي السلة",
  cartWeight: "وزن السلة (جم)",
  servedBy: (zone) => `تخدمها ${zone}`,
  noZone: "لا توجد منطقة تغطي هذه الوجهة.",
  noOptions: "لن يرى العملاء أي خيار توصيل هنا.",
  spendMore: "أنفق",
  taxes: "الضرائب",
  taxRates: "نسب الضريبة",
  addTax: "إضافة نسبة ضريبة",
  editTax: "تعديل نسبة الضريبة",
  taxOverlapTitle: "نسبتان تغطيان المكان نفسه",
  taxOverlapBody: (list) => `${list}. تُستخدم واحدة فقط، فاحذف الأخرى أو ضيّقها.`,
  searchTax: "ابحث في الضرائب",
  taxName: "الاسم",
  taxNamePlaceholder: "ضريبة القيمة المضافة",
  region: "المنطقة",
  regionOptional: "المنطقة (اختياري)",
  regionHint: "رمز محافظة أو ولاية. اتركه فارغًا لتغطية الدولة.",
  rate: "النسبة",
  ratePercent: "النسبة (%)",
  rateInvalid: "أدخل نسبة من 0 إلى 100 مثل 14 أو 7.5.",
  bpsIs: (bps) => `${bps} نقطة أساس`,
  mode: "الأسعار",
  inclusive: "شاملة الضريبة",
  exclusive: "تُضاف الضريبة عند الدفع",
  inclusiveHint: "أسعار العرض تحوي الضريبة أصلًا. يدفع العميل السعر نفسه.",
  exclusiveHint: "تُضاف الضريبة فوق السعر عند الدفع.",
  onShipping: "احتساب الضريبة على الشحن",
  enableTax: "تشغيل",
  taxEmpty: "لا توجد نسب ضريبة بعد",
  taxEmptyHint: "أضف النسبة التي تحصّلها ليعرض الدفع الضريبة.",
  deleteTaxTitle: "حذف نسبة الضريبة هذه؟",
  taxHint: "تُخزَّن النسب بنقاط الأساس، فـ14% تساوي 1400. تُقرَّب الضريبة مرة واحدة لكل طلب.",
  saveTax: "حفظ النسبة",
  tryTax: "جرّبها على طلب",
  goods: "البضاعة",
  shippingCharge: "الشحن",
  taxAmount: "الضريبة",
  netAmount: "الصافي",
  addedToTotal: "تُضاف إلى الإجمالي",
  customerPays: "يدفع العميل",
  noTaxRate: "لا توجد نسبة ضريبة لهذه الدولة.",
  discounts: "الخصومات",
  addDiscount: "إضافة خصم",
  editDiscount: "تعديل الخصم",
  discountHint: "الخصومات التلقائية تُطبَّق وحدها. الرموز تُطبَّق عندما يكتبها العميل.",
  discountTitle: "العنوان",
  method: "الطريقة",
  automatic: "تلقائي",
  byCode: "رمز خصم",
  used: "المستخدم",
  perItemShort: "لكل قطعة",
  bxgyShort: (buy, get) => `اشترِ ${buy} واحصل على ${get}`,
  freeShipping: "شحن مجاني",
  freeShippingHint: "يخصم رسوم الشحن كاملة.",
  duplicate: "تكرار",
  copyOf: (title) => `نسخة من ${title}`,
  duplicateCodes: (list) => `الرمز نفسه مستخدم مرتين: ${list}.`,
  searchDiscounts: "ابحث في الخصومات",
  discountsEmpty: "لا توجد خصومات بعد",
  discountsEmptyHint: "أنشئ خصمًا لتقيم تخفيضًا أو تكافئ العملاء.",
  deleteDiscountTitle: "حذف هذا الخصم؟",
  saveDiscount: "حفظ الخصم",
  whatItDoes: "ماذا يفعل",
  kinds: { percentage: "نسبة خصم", fixed: "مبلغ خصم", bxgy: "اشترِ X واحصل على Y", "free-shipping": "شحن مجاني" },
  classes: { product: "خصم على المنتجات", order: "خصم على الطلب", shipping: "خصم على الشحن" },
  standings: { live: "ساري", scheduled: "مجدول", ended: "انتهى", off: "متوقف", "used-up": "استُنفد" },
  percentOff: "نسبة الخصم",
  amountOff: "مبلغ الخصم",
  perItem: "اخصم المبلغ من كل قطعة",
  cap: "أقصى ما يخصمه",
  capShipping: "أقصى ما يخصمه من الشحن",
  capHint: "اتركه فارغًا بلا حد.",
  appliesTo: "ينطبق على",
  excludeOnSale: "تجاهل القطع المخفّضة أصلًا",
  requirements: "الشروط",
  minSpend: "أقل إنفاق",
  minQuantity: "أقل عدد قطع",
  eligibility: "من يستطيع استخدامه",
  customers: "العملاء",
  customersAll: "الجميع",
  customersSegments: "شرائح",
  customersSpecific: "عملاء محددون",
  segmentsLabel: "الشرائح",
  segmentsPlaceholder: "أضف شريحة",
  customerIdsLabel: "معرّفات العملاء",
  customerIdsPlaceholder: "أضف معرّف عميل",
  firstOrderOnly: "للطلب الأول فقط",
  schedule: "الجدولة",
  startsOn: "يبدأ",
  endsOn: "ينتهي",
  limits: "الحدود",
  limitTotal: "إجمالي الاستخدامات",
  limitCustomer: "الاستخدامات لكل عميل",
  combinesWith: "يمكن جمعه مع",
  combinesHint: "الخصومات من النوع نفسه لا تُجمع أبدًا مهما اخترت.",
  problemTitle: "أصلح هذه أولًا",
  problemCode: "أضف رمزًا.",
  problemDuplicateCode: "خصم آخر يستخدم هذا الرمز.",
  problemPercent: "أدخل نسبة من 0 إلى 100.",
  problemAmount: "أدخل مبلغًا أكبر من صفر.",
  problemBxgy: "حدد كم يشتري العميل وكم يحصل.",
  problemDates: "يجب أن يكون تاريخ الانتهاء بعد البداية.",
  buyQty: "كمية الشراء",
  getQty: "كمية الحصول",
  getPercent: "الخصم على القطع المجانية (%)",
  getPercentHint: "100 تجعلها مجانية.",
  maxSets: "أقصى عدد مجموعات لكل طلب",
  noLimit: "بلا حد",
  buyItems: "قطع الشراء",
  getItems: "قطع الحصول",
  sameAsBuy: "نفس قطع الشراء",
  everything: "كل شيء",
  scopeCount: (n) => `${n} محدد`,
  collection: "مجموعة",
  rejections: {
    inactive: "متوقف",
    "not-started": "لم يبدأ",
    ended: "انتهى",
    "limit-total": "استُنفد",
    "limit-customer": "استخدمه هذا العميل من قبل",
    "code-required": "يحتاج رمزه",
    customer: "غير متاح لهذا العميل",
    "first-order": "للطلب الأول فقط",
    "min-subtotal": "الإنفاق أقل من الحد الأدنى",
    "min-quantity": "عدد القطع غير كافٍ",
    "no-match": "لا توجد قطع مطابقة",
    "no-shipping": "لا توجد رسوم شحن",
    "no-benefit": "لن يخصم شيئًا",
    "not-combinable": "لا يُجمع مع خصم آخر",
  },
  simulator: "جرّب سلة",
  simulatorHint: "اختر قطعًا واكتب رموزًا لترى ما سيحصل عليه العميل. المبالغ بوحدات صغرى صحيحة.",
  basket: "السلة",
  decrease: "أقل",
  increase: "أكثر",
  codesTyped: "الرموز المكتوبة",
  pastOrders: "الطلبات السابقة",
  basketEmpty: "أضف قطعة إلى السلة.",
  subtotal: "المجموع الفرعي",
  capped: "بلغ الحد",
  freeUnits: (n) => `${n} مجانًا`,
  nothingApplies: "لا ينطبق أي خصم.",
  notApplied: "لم يُطبَّق",
  giftCards: "بطاقات الهدايا",
  giftCard: "بطاقة هدية",
  issueCard: "إصدار بطاقة هدية",
  issueHint: "تنشئ بطاقة برمز يمكنك إرساله. يُحفظ الرصيد كسجل حركات.",
  searchCards: "ابحث في البطاقات",
  cardsEmpty: "لا توجد بطاقات هدايا بعد",
  cardsEmptyHint: "أصدر بطاقة وشارك رمزها مع المشتري.",
  openCard: "فتح",
  balance: "الرصيد",
  issuedValue: "صدرت بقيمة",
  expires: "تنتهي",
  expiresHint: "اختياري. تعمل البطاقة حتى نهاية ذلك اليوم.",
  generate: "رمز جديد",
  codeHint: "ستة عشر حرفًا. الأخير يكشف أخطاء الكتابة.",
  codeInvalid: "هذا الرمز غير صالح. تحقق من أخطاء الكتابة.",
  codeTaken: "توجد بطاقة بهذا الرمز.",
  recipientName: "اسم المستلم",
  recipientEmail: "بريد المستلم",
  noRecipient: "بلا مستلم",
  redeem: "استخدام",
  redeemed: "تم الاستخدام.",
  orderRef: "الطلب",
  adjust: "تعديل الرصيد",
  adjusted: "تم تعديل الرصيد.",
  direction: "الاتجاه",
  addBalance: "إضافة رصيد",
  removeBalance: "خصم رصيد",
  cardEnabled: "يمكن استخدام البطاقة",
  history: "السجل",
  ledgerProblem: "يبدو أن السجل به خطأ",
  giftStatuses: { active: "نشطة", depleted: "مستهلكة", expired: "منتهية", disabled: "موقوفة" },
  entryKinds: { issue: "إصدار", redeem: "استخدام", refund: "استرداد", adjust: "تعديل", expire: "انتهاء", void: "إلغاء" },
  giftErrors: {
    "not-found": "لم نجد بطاقة الهدية هذه.",
    disabled: "بطاقة الهدية هذه موقوفة.",
    expired: "انتهت صلاحية بطاقة الهدية هذه.",
    empty: "لا يوجد رصيد في بطاقة الهدية هذه.",
    currency: "بطاقة الهدية هذه بعملة أخرى.",
    "invalid-amount": "أدخل مبلغًا أكبر من صفر.",
    "over-balance": "المبلغ أكبر من الرصيد.",
  },
  ledgerIssues: { "no-issue": "السجل بلا حركة إصدار.", sign: "حركة إشارتها خاطئة.", "negative-balance": "الرصيد ينزل تحت الصفر.", "duplicate-id": "حركتان بالمعرّف نفسه.", "out-of-order": "الحركات غير مرتبة بالتاريخ." },
  applyCard: "تطبيق",
  removeCard: "إزالة بطاقة الهدية",
  alreadyAdded: "هذه البطاقة مضافة بالفعل.",
  lookupFailed: "تعذّر التحقق من البطاقة. حاول مرة أخرى.",
  youPay: "المتبقي للدفع",
};

export const STORE_SETTINGS_STRINGS = { en, ar };

const NESTED = ["rateTypes", "tierIssues", "unavailable", "kinds", "classes", "standings", "rejections", "giftStatuses", "entryKinds", "giftErrors", "ledgerIssues"] as const;
type Nested = (typeof NESTED)[number];
/** Every text can be replaced. Nested groups (rate types, rejections and so on) merge key by key. */
export type StoreSettingsLabels = Partial<Omit<SettingsStrings, Nested>> & { [K in Nested]?: Partial<SettingsStrings[K]> };

export function useSettingsStrings(labels?: StoreSettingsLabels) {
  const locale = useOptionalNasaq()?.locale ?? "en";
  const base = STORE_SETTINGS_STRINGS[locale.startsWith("ar") ? "ar" : "en"];
  const t = { ...base, ...labels } as SettingsStrings;
  for (const k of NESTED) (t as Record<string, unknown>)[k] = { ...base[k], ...labels?.[k] };
  return { t, locale, n: (v: number) => formatNumber(v, locale) };
}

/* ------------------------------------------------------------------ shared bits */

/** What a save callback resolves. Resolve `{ error }` to keep the form open and show the message. */
export type SettingsResult = void | { error?: string };

export function Money({ minor, currency, className }: { minor: number; currency: string; className?: string }) {
  return <Num className={className} value={minorToMajor(minor, currency)} format={{ style: "currency", currency }} />;
}

/** "EG" to "Egypt" or "مصر", in the page language. Falls back to the code. */
export function regionName(locale: string, code: string): string {
  try {
    return new Intl.DisplayNames([locale], { type: "region" }).of(code.trim().toUpperCase()) ?? code;
  } catch {
    return code;
  }
}

let counter = 0;
/** A short unique id for a new record. Replace it on your server. */
export const uid = (prefix: string) => `${prefix}-${Date.now().toString(36)}${(counter++).toString(36)}`;

/** Runs a save or delete, tracks busy and the error, and reports whether it worked. */
export function useAction(fallback: string) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const alive = useRef(true);
  const run = useCallback(
    async (job: () => Promise<SettingsResult>): Promise<boolean> => {
      setBusy(true);
      setError(null);
      try {
        const r = await job();
        if (r && typeof r === "object" && r.error) {
          setError(r.error);
          return false;
        }
        return true;
      } catch (e) {
        setError(e instanceof Error && e.message ? e.message : fallback);
        return false;
      } finally {
        if (alive.current) setBusy(false);
      }
    },
    [fallback],
  );
  return { busy, error, setError, run };
}

/** "14" or "14.5" or "7.25" to basis points, with integer maths. Undefined when it is not a percentage of 0 to 100. */
export function percentToBps(text: string): number | undefined {
  const m = /^(\d{1,3})(?:[.,](\d{1,2}))?$/.exec(text.trim());
  if (!m) return undefined;
  const bps = Number(m[1]) * 100 + Number((m[2] ?? "").padEnd(2, "0") || 0);
  return bps <= 10000 ? bps : undefined;
}

/** Basis points as a percentage string without float error: 1450 gives "14.5". */
export const bpsToPercent = (bps: number): string => {
  const whole = Math.trunc(bps / 100);
  const frac = String(Math.abs(bps % 100)).padStart(2, "0").replace(/0+$/, "");
  return frac ? `${whole}.${frac}` : String(whole);
};
