import type { ApiKeyStatus } from "./format";

export const STRINGS = {
  en: {
    title: "API keys",
    description: "Keys let your own code call the API. Give each key only the access it needs.",
    create: "Create key",
    list: "API keys",
    emptyTitle: "No API keys yet",
    emptyBody: "Create a key to call the API from a script or a server.",
    createTitle: "Create an API key",
    createBody: "Name it after where it will be used. You will see the key once.",
    name: "Name",
    namePlaceholder: "Production server",
    nameRequired: "Give the key a name.",
    scopes: "Scopes",
    scopesHint: "The key can do only what these allow.",
    scopesRequired: "Pick at least one scope.",
    expiry: "Expires",
    expiryLabel: (days: number | null) => (days == null ? "Never" : days === 1 ? "In 1 day" : days === 365 ? "In 1 year" : `In ${days} days`),
    cancel: "Cancel",
    submit: "Create key",
    revealTitle: "Copy your new key now",
    revealRotated: (name: string) => `New key for ${name}`,
    revealBody: "This is the only time the full key is shown. Store it in a secret manager. If you lose it, rotate the key.",
    revealAlert: "You will not see this key again.",
    secretLabel: "Secret key",
    done: "Done",
    createdAt: "Created",
    lastUsed: "Last used",
    neverUsed: "Never used",
    expires: "Expires",
    neverExpires: "Never expires",
    expiredOn: "Expired",
    status: { active: "Active", expiring: "Expiring soon", expired: "Expired", revoked: "Revoked" } satisfies Record<ApiKeyStatus, string>,
    expiresIn: (n: number) => (n === 1 ? "in 1 day" : `in ${n} days`),
    rotate: "Rotate",
    rotateTitle: (name: string) => `Rotate ${name}?`,
    rotateBody: "A new secret replaces the old one, and the old one stops working at once. Update the places that use it.",
    rotateConfirm: "Rotate key",
    revoke: "Revoke",
    revokeTitle: (name: string) => `Revoke ${name}?`,
    revokeBody: "Anything using this key loses access immediately. This cannot be undone.",
    revokeConfirm: "Revoke key",
    genericError: "Something went wrong. Try again.",
    actionsFor: (name: string) => `Actions for ${name}`,
  },
  ar: {
    title: "مفاتيح API",
    description: "تتيح المفاتيح لشيفرتك استدعاء الـ API. امنح كل مفتاح الصلاحيات التي يحتاجها فقط.",
    create: "إنشاء مفتاح",
    list: "مفاتيح API",
    emptyTitle: "لا توجد مفاتيح بعد",
    emptyBody: "أنشئ مفتاحًا لاستدعاء الـ API من سكربت أو خادم.",
    createTitle: "إنشاء مفتاح API",
    createBody: "سمِّه باسم المكان الذي سيُستخدم فيه. ستراه مرة واحدة فقط.",
    name: "الاسم",
    namePlaceholder: "خادم الإنتاج",
    nameRequired: "أعطِ المفتاح اسمًا.",
    scopes: "الصلاحيات",
    scopesHint: "لا يستطيع المفتاح فعل أكثر مما تسمح به هذه الصلاحيات.",
    scopesRequired: "اختر صلاحية واحدة على الأقل.",
    expiry: "الانتهاء",
    expiryLabel: (days: number | null) => (days == null ? "بلا انتهاء" : days === 1 ? "بعد يوم" : days === 365 ? "بعد سنة" : `بعد ${days} يومًا`),
    cancel: "إلغاء",
    submit: "إنشاء المفتاح",
    revealTitle: "انسخ مفتاحك الجديد الآن",
    revealRotated: (name: string) => `مفتاح جديد لـ ${name}`,
    revealBody: "هذه هي المرة الوحيدة التي يظهر فيها المفتاح كاملًا. احفظه في مدير أسرار. إذا فقدته فبدّل المفتاح.",
    revealAlert: "لن تتمكن من رؤية هذا المفتاح مرة أخرى.",
    secretLabel: "المفتاح السري",
    done: "تم",
    createdAt: "أُنشئ",
    lastUsed: "آخر استخدام",
    neverUsed: "لم يُستخدم بعد",
    expires: "ينتهي",
    neverExpires: "لا ينتهي",
    expiredOn: "انتهى",
    status: { active: "نشط", expiring: "ينتهي قريبًا", expired: "منتهي", revoked: "ملغى" } satisfies Record<ApiKeyStatus, string>,
    expiresIn: (n: number) => (n === 1 ? "بعد يوم" : `بعد ${n} أيام`),
    rotate: "تبديل",
    rotateTitle: (name: string) => `تبديل ${name}؟`,
    rotateBody: "يحل سر جديد محل القديم، ويتوقف القديم عن العمل فورًا. حدّث الأماكن التي تستخدمه.",
    rotateConfirm: "تبديل المفتاح",
    revoke: "إلغاء",
    revokeTitle: (name: string) => `إلغاء ${name}؟`,
    revokeBody: "أي شيء يستخدم هذا المفتاح يفقد الوصول فورًا. لا يمكن التراجع.",
    revokeConfirm: "إلغاء المفتاح",
    genericError: "حدث خطأ ما. حاول مرة أخرى.",
    actionsFor: (name: string) => `إجراءات ${name}`,
  },
};

export type ApiKeysLabels = (typeof STRINGS)["en"];
