// The built-in words of BookingFlow (English and Arabic), same as the React component's STRINGS.
export type BookingStepId = "location" | "service" | "provider" | "time" | "details" | "notes" | "payment" | "review";

export const STRINGS = {
  en: {
    steps: { location: "Branch", service: "Service", provider: "Doctor", time: "Time", details: "Details", notes: "Notes", payment: "Payment", review: "Review" } as Record<BookingStepId, string>,
    heading: {
      location: "Where would you like to be seen?",
      service: "What do you need?",
      provider: "Who would you like to see?",
      time: "Pick a day and time",
      details: "Who is this booking for?",
      notes: "Anything the clinic should know?",
      payment: "How would you like to pay?",
      review: "Check and confirm",
    } as Record<BookingStepId, string>,
    stepOf: (n: number, total: number, name: string) => `Step ${n} of ${total}: ${name}`,
    progress: "Booking steps",
    back: "Back",
    next: "Continue",
    confirm: "Confirm booking",
    confirming: "Confirming",
    minutes: (n: number) => `${n} min`,
    anyProvider: "First available doctor",
    anyProviderText: "We match you with whoever has the earliest time.",
    noRating: "New",
    reviews: "reviews",
    noProviders: "No doctor offers this service here. Go back and change the service or branch.",
    slotsFailed: "We could not load the times.",
    retry: "Try again",
    name: "Full name",
    phone: "Mobile number",
    phoneHint: "We send the confirmation and reminders here.",
    email: "Email (optional)",
    forOther: "I am booking for someone else",
    otherName: "Patient's full name",
    bookingAs: (n: string) => `Booking as ${n}`,
    guestNote: "No account needed. You get a code and a QR ticket.",
    required: "This field is required.",
    invalid: "This does not look right.",
    notesLabel: "Notes for the clinic (optional)",
    notesHint: "Symptoms, questions, or anything that helps prepare.",
    attachments: "Attachments (optional)",
    attachmentsHint: "Earlier results or referrals. Images or PDF, up to 5 MB each.",
    payOnline: "Pay online now",
    payOnlineText: "Secure card payment. Nothing more to pay at the clinic.",
    payVisit: "Pay at the visit",
    payVisitText: "Cash or card at reception. Your time is held.",
    subtotal: "Service",
    tax: "Tax",
    total: "Total",
    summary: "Your booking",
    empty: "Nothing chosen yet.",
    edit: "Edit",
    location: "Branch",
    provider: "Doctor",
    when: "When",
    patient: "Patient",
    payment: "Payment",
    attachedCount: (n: number) => `${n} ${n === 1 ? "file" : "files"} attached`,
    submitFailed: "We could not confirm the booking. Try again.",
    confirmedTitle: "Your booking is confirmed",
    confirmedText: "Keep this ticket. Scan the code at the kiosk, or give reception the code.",
    another: "Book another visit",
    cancelPolicy: "Free cancellation up to 24 hours before.",
    payLater: "Pay at the visit",
    payNow: "Pay online",
  },
  ar: {
    steps: { location: "الفرع", service: "الخدمة", provider: "الطبيب", time: "الموعد", details: "البيانات", notes: "ملاحظات", payment: "الدفع", review: "المراجعة" } as Record<BookingStepId, string>,
    heading: {
      location: "أين تودّ أن تُعالَج؟",
      service: "ما الذي تحتاجه؟",
      provider: "مع من تريد الحجز؟",
      time: "اختر اليوم والوقت",
      details: "لمن هذا الحجز؟",
      notes: "هل من شيء تودّ أن تعرفه العيادة؟",
      payment: "كيف تودّ الدفع؟",
      review: "راجع وأكّد",
    } as Record<BookingStepId, string>,
    stepOf: (n: number, total: number, name: string) => `الخطوة ${n} من ${total}: ${name}`,
    progress: "خطوات الحجز",
    back: "رجوع",
    next: "متابعة",
    confirm: "تأكيد الحجز",
    confirming: "جارٍ التأكيد",
    minutes: (n: number) => `${n} دقيقة`,
    anyProvider: "أول طبيب متاح",
    anyProviderText: "نحجز لك مع من لديه أقرب موعد.",
    noRating: "جديد",
    reviews: "تقييم",
    noProviders: "لا يقدّم أي طبيب هذه الخدمة هنا. ارجع وغيّر الخدمة أو الفرع.",
    slotsFailed: "تعذّر تحميل المواعيد.",
    retry: "حاول مجددًا",
    name: "الاسم الكامل",
    phone: "رقم الجوال",
    phoneHint: "نرسل التأكيد والتذكيرات على هذا الرقم.",
    email: "البريد الإلكتروني (اختياري)",
    forOther: "أحجز لشخص آخر",
    otherName: "الاسم الكامل للمريض",
    bookingAs: (n: string) => `الحجز باسم ${n}`,
    guestNote: "لا حاجة لحساب. ستحصل على رمز وتذكرة QR.",
    required: "هذا الحقل مطلوب.",
    invalid: "القيمة غير صحيحة.",
    notesLabel: "ملاحظات للعيادة (اختياري)",
    notesHint: "الأعراض أو الأسئلة أو أي شيء يساعد على التحضير.",
    attachments: "مرفقات (اختياري)",
    attachmentsHint: "نتائج سابقة أو تحويلات. صور أو PDF، حتى 5 ميجابايت لكل ملف.",
    payOnline: "الدفع إلكترونيًا الآن",
    payOnlineText: "دفع آمن بالبطاقة. لا شيء آخر عند العيادة.",
    payVisit: "الدفع عند الزيارة",
    payVisitText: "نقدًا أو بالبطاقة عند الاستقبال. موعدك محجوز.",
    subtotal: "الخدمة",
    tax: "الضريبة",
    total: "الإجمالي",
    summary: "حجزك",
    empty: "لم تختر شيئًا بعد.",
    edit: "تعديل",
    location: "الفرع",
    provider: "الطبيب",
    when: "الموعد",
    patient: "المريض",
    payment: "الدفع",
    attachedCount: (n: number) => (n === 1 ? "ملف واحد مرفق" : n === 2 ? "ملفان مرفقان" : `${n} ملفات مرفقة`),
    submitFailed: "تعذّر تأكيد الحجز. حاول مجددًا.",
    confirmedTitle: "تم تأكيد حجزك",
    confirmedText: "احتفظ بهذه التذكرة. امسح الرمز في الكشك أو أعطِ الاستقبال الرمز.",
    another: "احجز زيارة أخرى",
    cancelPolicy: "إلغاء مجاني حتى 24 ساعة قبل الموعد.",
    payLater: "الدفع عند الزيارة",
    payNow: "الدفع إلكترونيًا",
  },
};

export type BookingFlowLabels = (typeof STRINGS)["en"];
