// Generated by scripts/gen-index.mjs. Do not edit.
import type { Register } from "./types";
import { accordion } from "./accordion";
import { accountSettings } from "./account-settings";
import { activeSessions } from "./active-sessions";
import { aiModelPicker } from "./ai-model-picker";
import { alert } from "./alert";
import { alertDialog } from "./alert-dialog";
import { alerts } from "./alerts";
import { apiKeys } from "./api-keys";
import { appShell } from "./app-shell";
import { appUpdate } from "./app-update";
import { appearancePickers } from "./appearance-pickers";
import { approvalQueue } from "./approval-queue";
import { attention } from "./attention";
import { authLayout } from "./auth-layout";
import { avatar } from "./avatar";
import { avatarUpload } from "./avatar-upload";
import { backupManager } from "./backup-manager";
import { barcode } from "./barcode";
import { blogIndex } from "./blog-index";
import { bookingPipeline } from "./booking-pipeline";
import { bookingSlots } from "./booking-slots";
import { calendar } from "./calendar";
import { carousel } from "./carousel";
import { cashCollect } from "./cash-collect";
import { catalogStore } from "./catalog-store";
import { changePasswordForm } from "./change-password-form";
import { checkbox } from "./checkbox";
import { checklist } from "./checklist";
import { checkoutSteps } from "./checkout-steps";
import { chipGroup } from "./chip-group";
import { chromeExtensionInstall } from "./chrome-extension-install";
import { codeBlock } from "./code-block";
import { collapsible } from "./collapsible";
import { colorPicker } from "./color-picker";
import { combobox } from "./combobox";
import { commandPalette } from "./command-palette";
import { confirmProvider } from "./confirm-provider";
import { connectedAccounts } from "./connected-accounts";
import { contactIdentities } from "./contact-identities";
import { contextMenu } from "./context-menu";
import { copyButton } from "./copy-button";
import { countdown } from "./countdown";
import { countryFlag } from "./country-flag";
import { cronBuilder } from "./cron-builder";
import { currencyInput } from "./currency-input";
import { dailySummary } from "./daily-summary";
import { dataTable } from "./data-table";
import { datePicker } from "./date-picker";
import { desktopIcons } from "./desktop-icons";
import { desktopLocations } from "./desktop-locations";
import { desktopNotification } from "./desktop-notification";
import { desktopOsShell } from "./desktop-os-shell";
import { dialog } from "./dialog";
import { drawer } from "./drawer";
import { dropdownMenu } from "./dropdown-menu";
import { editorChrome } from "./editor-chrome";
import { emailTemplates } from "./email-templates";
import { emojiPicker } from "./emoji-picker";
import { engineCard } from "./engine-card";
import { engineDetails } from "./engine-details";
import { envList } from "./env-list";
import { errorPages } from "./error-pages";
import { exportAction } from "./export-action";
import { extensionPopup } from "./extension-popup";
import { field } from "./field";
import { fileUpload } from "./file-upload";
import { form } from "./form";
import { gamification } from "./gamification";
import { graphView } from "./graph-view";
import { healthReports } from "./health-reports";
import { heatmap } from "./heatmap";
import { hotkeyRecorder } from "./hotkey-recorder";
import { hoverCard } from "./hover-card";
import { iconPicker } from "./icon-picker";
import { iconRailSidebar } from "./icon-rail-sidebar";
import { impersonationBanner } from "./impersonation-banner";
import { importWizard } from "./import-wizard";
import { inlineEdit } from "./inline-edit";
import { installPrompt } from "./install-prompt";
import { integrationConnector } from "./integration-connector";
import { invoiceView } from "./invoice-view";
import { kanbanBoard } from "./kanban-board";
import { keyboardShortcuts } from "./keyboard-shortcuts";
import { killSwitch } from "./kill-switch";
import { knowledgeGaps } from "./knowledge-gaps";
import { landingPageEditor } from "./landing-page-editor";
import { limitsEditor } from "./limits-editor";
import { lineItemEditor } from "./line-item-editor";
import { mapView } from "./map-view";
import { mentionTextarea } from "./mention-textarea";
import { menubar } from "./menubar";
import { metricTiles } from "./metric-tiles";
import { mobileNavKit } from "./mobile-nav-kit";
import { modelRoutingEditor } from "./model-routing-editor";
import { navigationMenu } from "./navigation-menu";
import { notificationCenter } from "./notification-center";
import { oauthButtons } from "./oauth-buttons";
import { otpInput } from "./otp-input";
import { pagination } from "./pagination";
import { passkeyList } from "./passkey-list";
import { passwordInput } from "./password-input";
import { personalWidgets } from "./personal-widgets";
import { phoneInput } from "./phone-input";
import { popover } from "./popover";
import { presentationEditor } from "./presentation-editor";
import { pricingTable } from "./pricing-table";
import { productDetail } from "./product-detail";
import { productReviews } from "./product-reviews";
import { productSwitcher } from "./product-switcher";
import { profileCard } from "./profile-card";
import { providerSwitcher } from "./provider-switcher";
import { qrCode } from "./qr-code";
import { quickCapture } from "./quick-capture";
import { radioGroup } from "./radio-group";
import { relationPicker } from "./relation-picker";
import { repeater } from "./repeater";
import { reportEditor } from "./report-editor";
import { repositoryPicker } from "./repository-picker";
import { resizable } from "./resizable";
import { richTextEditor } from "./rich-text-editor";
import { routeProgress } from "./route-progress";
import { scheduler } from "./scheduler";
import { scrollArea } from "./scroll-area";
import { select } from "./select";
import { semanticSearch } from "./semantic-search";
import { serverCard } from "./server-card";
import { settingsSections } from "./settings-sections";
import { shareAction } from "./share-action";
import { sidebarLayout } from "./sidebar-layout";
import { slider } from "./slider";
import { storeListing } from "./store-listing";
import { storeOrderTimeline } from "./store-order-timeline";
import { subscriptionLanding } from "./subscription-landing";
import { switchControl } from "./switch-control";
import { switchers } from "./switchers";
import { tabs } from "./tabs";
import { tagInput } from "./tag-input";
import { terminal } from "./terminal";
import { textUtilities } from "./text-utilities";
import { toast } from "./toast";
import { toggleGroup } from "./toggle-group";
import { tooltip } from "./tooltip";
import { treeView } from "./tree-view";
import { twoFactorSetup } from "./two-factor-setup";
import { upgradePrompt } from "./upgrade-prompt";
import { userActionsMenu } from "./user-actions-menu";
import { viewToggle } from "./view-toggle";
import { waitingScreen } from "./waiting-screen";
import { wallet } from "./wallet";
import { weightedCriteriaCard } from "./weighted-criteria-card";
import { whatsappQrConnect } from "./whatsapp-qr-connect";
import { widgetGallery } from "./widget-gallery";
import { workflowNetwork } from "./workflow-network";
import { wsStatus } from "./ws-status";

/** Every component's Alpine.data registration, keyed by component folder name. */
export const components: Record<string, Register> = {
  "accordion": accordion,
  "account-settings": accountSettings,
  "active-sessions": activeSessions,
  "ai-model-picker": aiModelPicker,
  "alert": alert,
  "alert-dialog": alertDialog,
  "alerts": alerts,
  "api-keys": apiKeys,
  "app-shell": appShell,
  "app-update": appUpdate,
  "appearance-pickers": appearancePickers,
  "approval-queue": approvalQueue,
  "attention": attention,
  "auth-layout": authLayout,
  "avatar": avatar,
  "avatar-upload": avatarUpload,
  "backup-manager": backupManager,
  "barcode": barcode,
  "blog-index": blogIndex,
  "booking-pipeline": bookingPipeline,
  "booking-slots": bookingSlots,
  "calendar": calendar,
  "carousel": carousel,
  "cash-collect": cashCollect,
  "catalog-store": catalogStore,
  "change-password-form": changePasswordForm,
  "checkbox": checkbox,
  "checklist": checklist,
  "checkout-steps": checkoutSteps,
  "chip-group": chipGroup,
  "chrome-extension-install": chromeExtensionInstall,
  "code-block": codeBlock,
  "collapsible": collapsible,
  "color-picker": colorPicker,
  "combobox": combobox,
  "command-palette": commandPalette,
  "confirm-provider": confirmProvider,
  "connected-accounts": connectedAccounts,
  "contact-identities": contactIdentities,
  "context-menu": contextMenu,
  "copy-button": copyButton,
  "countdown": countdown,
  "country-flag": countryFlag,
  "cron-builder": cronBuilder,
  "currency-input": currencyInput,
  "daily-summary": dailySummary,
  "data-table": dataTable,
  "date-picker": datePicker,
  "desktop-icons": desktopIcons,
  "desktop-locations": desktopLocations,
  "desktop-notification": desktopNotification,
  "desktop-os-shell": desktopOsShell,
  "dialog": dialog,
  "drawer": drawer,
  "dropdown-menu": dropdownMenu,
  "editor-chrome": editorChrome,
  "email-templates": emailTemplates,
  "emoji-picker": emojiPicker,
  "engine-card": engineCard,
  "engine-details": engineDetails,
  "env-list": envList,
  "error-pages": errorPages,
  "export-action": exportAction,
  "extension-popup": extensionPopup,
  "field": field,
  "file-upload": fileUpload,
  "form": form,
  "gamification": gamification,
  "graph-view": graphView,
  "health-reports": healthReports,
  "heatmap": heatmap,
  "hotkey-recorder": hotkeyRecorder,
  "hover-card": hoverCard,
  "icon-picker": iconPicker,
  "icon-rail-sidebar": iconRailSidebar,
  "impersonation-banner": impersonationBanner,
  "import-wizard": importWizard,
  "inline-edit": inlineEdit,
  "install-prompt": installPrompt,
  "integration-connector": integrationConnector,
  "invoice-view": invoiceView,
  "kanban-board": kanbanBoard,
  "keyboard-shortcuts": keyboardShortcuts,
  "kill-switch": killSwitch,
  "knowledge-gaps": knowledgeGaps,
  "landing-page-editor": landingPageEditor,
  "limits-editor": limitsEditor,
  "line-item-editor": lineItemEditor,
  "map-view": mapView,
  "mention-textarea": mentionTextarea,
  "menubar": menubar,
  "metric-tiles": metricTiles,
  "mobile-nav-kit": mobileNavKit,
  "model-routing-editor": modelRoutingEditor,
  "navigation-menu": navigationMenu,
  "notification-center": notificationCenter,
  "oauth-buttons": oauthButtons,
  "otp-input": otpInput,
  "pagination": pagination,
  "passkey-list": passkeyList,
  "password-input": passwordInput,
  "personal-widgets": personalWidgets,
  "phone-input": phoneInput,
  "popover": popover,
  "presentation-editor": presentationEditor,
  "pricing-table": pricingTable,
  "product-detail": productDetail,
  "product-reviews": productReviews,
  "product-switcher": productSwitcher,
  "profile-card": profileCard,
  "provider-switcher": providerSwitcher,
  "qr-code": qrCode,
  "quick-capture": quickCapture,
  "radio-group": radioGroup,
  "relation-picker": relationPicker,
  "repeater": repeater,
  "report-editor": reportEditor,
  "repository-picker": repositoryPicker,
  "resizable": resizable,
  "rich-text-editor": richTextEditor,
  "route-progress": routeProgress,
  "scheduler": scheduler,
  "scroll-area": scrollArea,
  "select": select,
  "semantic-search": semanticSearch,
  "server-card": serverCard,
  "settings-sections": settingsSections,
  "share-action": shareAction,
  "sidebar-layout": sidebarLayout,
  "slider": slider,
  "store-listing": storeListing,
  "store-order-timeline": storeOrderTimeline,
  "subscription-landing": subscriptionLanding,
  "switch-control": switchControl,
  "switchers": switchers,
  "tabs": tabs,
  "tag-input": tagInput,
  "terminal": terminal,
  "text-utilities": textUtilities,
  "toast": toast,
  "toggle-group": toggleGroup,
  "tooltip": tooltip,
  "tree-view": treeView,
  "two-factor-setup": twoFactorSetup,
  "upgrade-prompt": upgradePrompt,
  "user-actions-menu": userActionsMenu,
  "view-toggle": viewToggle,
  "waiting-screen": waitingScreen,
  "wallet": wallet,
  "weighted-criteria-card": weightedCriteriaCard,
  "whatsapp-qr-connect": whatsappQrConnect,
  "widget-gallery": widgetGallery,
  "workflow-network": workflowNetwork,
  "ws-status": wsStatus,
};
