// Generated by scripts/gen-index.mjs. Do not edit.
import type { Register } from "./types";
import { avatar } from "./avatar";
import { checkbox } from "./checkbox";
import { collapsible } from "./collapsible";
import { countryFlag } from "./country-flag";
import { dialog } from "./dialog";
import { field } from "./field";
import { hoverCard } from "./hover-card";
import { navigationMenu } from "./navigation-menu";
import { otpInput } from "./otp-input";
import { popover } from "./popover";
import { radioGroup } from "./radio-group";
import { routeProgress } from "./route-progress";
import { scrollArea } from "./scroll-area";
import { select } from "./select";
import { switchControl } from "./switch-control";
import { tabs } from "./tabs";
import { toast } from "./toast";
import { toggleGroup } from "./toggle-group";
import { tooltip } from "./tooltip";

/** Every component's Alpine.data registration, keyed by component folder name. */
export const components: Record<string, Register> = {
  "avatar": avatar,
  "checkbox": checkbox,
  "collapsible": collapsible,
  "country-flag": countryFlag,
  "dialog": dialog,
  "field": field,
  "hover-card": hoverCard,
  "navigation-menu": navigationMenu,
  "otp-input": otpInput,
  "popover": popover,
  "radio-group": radioGroup,
  "route-progress": routeProgress,
  "scroll-area": scrollArea,
  "select": select,
  "switch-control": switchControl,
  "tabs": tabs,
  "toast": toast,
  "toggle-group": toggleGroup,
  "tooltip": tooltip,
};
