// Generated by scripts/gen-index.mjs. Do not edit.
import type { Register } from "./types";
import { accordion } from "./accordion";
import { avatar } from "./avatar";
import { checkbox } from "./checkbox";
import { collapsible } from "./collapsible";
import { combobox } from "./combobox";
import { countryFlag } from "./country-flag";
import { currencyInput } from "./currency-input";
import { dialog } from "./dialog";
import { drawer } from "./drawer";
import { dropdownMenu } from "./dropdown-menu";
import { field } from "./field";
import { hoverCard } from "./hover-card";
import { navigationMenu } from "./navigation-menu";
import { otpInput } from "./otp-input";
import { popover } from "./popover";
import { providerSwitcher } from "./provider-switcher";
import { radioGroup } from "./radio-group";
import { resizable } from "./resizable";
import { routeProgress } from "./route-progress";
import { scrollArea } from "./scroll-area";
import { select } from "./select";
import { slider } from "./slider";
import { switchControl } from "./switch-control";
import { tabs } from "./tabs";
import { tagInput } from "./tag-input";
import { toast } from "./toast";
import { toggleGroup } from "./toggle-group";
import { tooltip } from "./tooltip";
import { treeView } from "./tree-view";
import { viewToggle } from "./view-toggle";
import { workflowNetwork } from "./workflow-network";

/** Every component's Alpine.data registration, keyed by component folder name. */
export const components: Record<string, Register> = {
  "accordion": accordion,
  "avatar": avatar,
  "checkbox": checkbox,
  "collapsible": collapsible,
  "combobox": combobox,
  "country-flag": countryFlag,
  "currency-input": currencyInput,
  "dialog": dialog,
  "drawer": drawer,
  "dropdown-menu": dropdownMenu,
  "field": field,
  "hover-card": hoverCard,
  "navigation-menu": navigationMenu,
  "otp-input": otpInput,
  "popover": popover,
  "provider-switcher": providerSwitcher,
  "radio-group": radioGroup,
  "resizable": resizable,
  "route-progress": routeProgress,
  "scroll-area": scrollArea,
  "select": select,
  "slider": slider,
  "switch-control": switchControl,
  "tabs": tabs,
  "tag-input": tagInput,
  "toast": toast,
  "toggle-group": toggleGroup,
  "tooltip": tooltip,
  "tree-view": treeView,
  "view-toggle": viewToggle,
  "workflow-network": workflowNetwork,
};
