// The card's own words, en and ar, copied from packages/web/src/components/server-card/server-card.tsx.
import type { PowerAction, ServerLimitField, ServerStatus } from "./server-format";

export const STRINGS = {
  en: {
    status: { running: "Running", stopped: "Stopped", starting: "Starting", stopping: "Stopping", restarting: "Restarting", provisioning: "Setting up", suspended: "Suspended", error: "Error" } satisfies Record<ServerStatus, string>,
    copyAddress: "Copy address",
    hardware: "Hardware",
    cores: (n: number) => (n === 1 ? "1 vCPU" : `${n} vCPU`),
    cpu: "CPU",
    memory: "Memory",
    disk: "Disk",
    usage: "Live usage",
    cpuTrend: (name: string) => `CPU load of ${name}, recent`,
    noMetrics: "Live usage is not available while the server is off.",
    lastDeploy: "Last deploy",
    noDeploy: "No deploys yet",
    deployStatus: { success: "Succeeded", failed: "Failed", running: "In progress" },
    by: (name: string) => `by ${name}`,
    power: "Power",
    powerActions: { start: "Start", stop: "Stop", restart: "Restart", "force-stop": "Force stop" } satisfies Record<PowerAction, string>,
    powerConfirmTitle: (action: string, name: string) => `${action} ${name}?`,
    powerConfirmBody: {
      start: "The server boots and services start.",
      restart: "The server reboots. Connections drop for a minute or so.",
      stop: "The server shuts down cleanly. Sites and services on it go offline until you start it again.",
      "force-stop": "The power is cut without a clean shutdown. Unsaved data can be lost. Use it only when a normal stop does not work.",
    } satisfies Record<PowerAction, string>,
    snapshots: "Snapshots",
    snapshotsBody: "Point-in-time copies of the disk. Roll back to return to one.",
    takeSnapshot: "Take snapshot",
    snapshotName: "Name",
    snapshotNameHint: "Optional. Leave empty to name it by date.",
    snapshotCreate: "Create snapshot",
    snapshotsEmpty: "No snapshots yet.",
    snapshotCreating: "Creating",
    rollback: "Roll back",
    rollbackTitle: (name: string) => `Roll back to ${name}?`,
    rollbackBody: "The disk returns to how it was in this snapshot. Everything written after it is lost, and the server restarts.",
    remove: "Delete",
    removeTitle: (name: string) => `Delete ${name}?`,
    removeBody: "The snapshot is removed for good. You will not be able to roll back to it.",
    actionsFor: (name: string) => `Actions for ${name}`,
    limits: "Resource limits",
    limitsBody: "The most this server may use. Changes apply after a restart.",
    limitFields: { cpuCores: "CPU cores", memoryMb: "Memory (MB)", diskGb: "Disk (GB)" } satisfies Record<ServerLimitField, string>,
    limitErrors: { integer: "Enter a whole number.", range: (min: number, max: number) => `Enter a number from ${min} to ${max}.` },
    limitsSave: "Save limits",
    cancel: "Cancel",
    genericError: "Something went wrong. Try again.",
    loading: "Loading server",
  },
  ar: {
    status: { running: "يعمل", stopped: "متوقف", starting: "قيد التشغيل", stopping: "قيد الإيقاف", restarting: "يعاد تشغيله", provisioning: "قيد الإعداد", suspended: "معلّق", error: "خطأ" } satisfies Record<ServerStatus, string>,
    copyAddress: "نسخ العنوان",
    hardware: "العتاد",
    cores: (n: number) => (n === 1 ? "معالج افتراضي واحد" : `${n} معالجات افتراضية`),
    cpu: "المعالج",
    memory: "الذاكرة",
    disk: "القرص",
    usage: "الاستخدام المباشر",
    cpuTrend: (name: string) => `حمل معالج ${name} مؤخرًا`,
    noMetrics: "الاستخدام المباشر غير متاح والخادم متوقف.",
    lastDeploy: "آخر نشر",
    noDeploy: "لا توجد عمليات نشر بعد",
    deployStatus: { success: "نجح", failed: "فشل", running: "قيد التنفيذ" },
    by: (name: string) => `بواسطة ${name}`,
    power: "الطاقة",
    powerActions: { start: "تشغيل", stop: "إيقاف", restart: "إعادة تشغيل", "force-stop": "إيقاف قسري" } satisfies Record<PowerAction, string>,
    powerConfirmTitle: (action: string, name: string) => `${action} ${name}؟`,
    powerConfirmBody: {
      start: "يُقلع الخادم وتبدأ الخدمات.",
      restart: "يُعاد إقلاع الخادم وتنقطع الاتصالات نحو دقيقة.",
      stop: "يُغلق الخادم بشكل سليم، وتتوقف المواقع والخدمات عليه حتى تشغّله مجددًا.",
      "force-stop": "تُقطع الطاقة دون إغلاق سليم وقد تضيع بيانات غير محفوظة. استخدمه فقط إذا لم ينفع الإيقاف العادي.",
    } satisfies Record<PowerAction, string>,
    snapshots: "اللقطات",
    snapshotsBody: "نسخ من القرص في لحظة معينة. ارجع إلى إحداها عند الحاجة.",
    takeSnapshot: "التقاط لقطة",
    snapshotName: "الاسم",
    snapshotNameHint: "اختياري. اتركه فارغًا ليُسمّى بالتاريخ.",
    snapshotCreate: "إنشاء اللقطة",
    snapshotsEmpty: "لا توجد لقطات بعد.",
    snapshotCreating: "قيد الإنشاء",
    rollback: "استرجاع",
    rollbackTitle: (name: string) => `الرجوع إلى ${name}؟`,
    rollbackBody: "يعود القرص إلى حالته في هذه اللقطة. يضيع كل ما كُتب بعدها ويُعاد تشغيل الخادم.",
    remove: "حذف",
    removeTitle: (name: string) => `حذف ${name}؟`,
    removeBody: "تُحذف اللقطة نهائيًا ولن تتمكن من الرجوع إليها.",
    actionsFor: (name: string) => `إجراءات ${name}`,
    limits: "حدود الموارد",
    limitsBody: "أقصى ما يستهلكه هذا الخادم. تسري التغييرات بعد إعادة التشغيل.",
    limitFields: { cpuCores: "أنوية المعالج", memoryMb: "الذاكرة (ميغابايت)", diskGb: "القرص (غيغابايت)" } satisfies Record<ServerLimitField, string>,
    limitErrors: { integer: "أدخل عددًا صحيحًا.", range: (min: number, max: number) => `أدخل رقمًا من ${min} إلى ${max}.` },
    limitsSave: "حفظ الحدود",
    cancel: "إلغاء",
    genericError: "حدث خطأ ما. حاول مرة أخرى.",
    loading: "جارٍ تحميل الخادم",
  },
};

export type ServerCardStrings = typeof STRINGS.en;
export type ServerCardLabels = Partial<ServerCardStrings>;

export function serverCardStrings(locale: string, labels?: ServerCardLabels): ServerCardStrings {
  const ar = locale.startsWith("ar");
  return { ...STRINGS[ar ? "ar" : "en"], ...labels } as ServerCardStrings;
}
