"use client";

import { useOptionalNasaq } from "../../provider/nasaq-provider";

const STRINGS = {
  en: {
    editor: "Presentation editor",
    deckTitle: "Presentation title",
    deckTitlePlaceholder: "Untitled presentation",
    slides: "Slides",
    slide: (n: string) => `Slide ${n}`,
    slideOf: (n: string, total: string) => `Slide ${n} of ${total}`,
    untitled: "Untitled slide",
    addSlide: "Add slide",
    duplicate: "Duplicate slide",
    delete: "Delete slide",
    moveEarlier: "Move earlier",
    moveLater: "Move later",
    moved: (n: string) => `Slide moved to position ${n}`,
    added: "Slide added",
    deleted: "Slide deleted",
    layout: "Layout",
    theme: "Theme",
    themeLight: "Light",
    themeDark: "Dark",
    themeBrand: "Brand",
    layoutTitle: "Title",
    layoutSection: "Section",
    layoutContent: "Content",
    layoutTwoColumn: "Two columns",
    layoutQuote: "Quote",
    layoutImage: "Image",
    layoutBlank: "Blank",
    titlePlaceholder: "Slide title",
    subtitlePlaceholder: "Subtitle",
    authorPlaceholder: "Who said it",
    bodyPlaceholder: "One bullet per line",
    quotePlaceholder: "The quote",
    leftPlaceholder: "Left column, one bullet per line",
    rightPlaceholder: "Right column, one bullet per line",
    imageUrl: "Image address",
    imageAlt: "Image description",
    imageHint: "Use an https link or an uploaded file address.",
    noImage: "No image yet",
    notes: "Presenter notes",
    notesPlaceholder: "What to say on this slide. Only you see this.",
    present: "Present",
    save: "Save",
    saving: "Saving",
    saved: "Saved",
    unsaved: "Unsaved changes",
    saveFailed: "Could not save",
    empty: "No slides yet",
    emptyHint: "Add a slide to start your presentation.",
    slideCount: (n: string) => `${n} slides`,
    notesCount: (n: string) => `${n} with notes`,
    reorderHint: "Drag a slide to reorder, or use Move earlier and Move later.",
    // player
    player: "Presentation",
    close: "Exit presentation",
    next: "Next slide",
    previous: "Previous slide",
    showNotes: "Show notes",
    hideNotes: "Hide notes",
    enterFullscreen: "Enter full screen",
    exitFullscreen: "Exit full screen",
    progress: "Progress",
    upNext: "Up next",
    endOfDeck: "End of presentation",
    noNotes: "No notes for this slide.",
    elapsed: "Elapsed time",
    keys: "Arrow keys or swipe to move, N for notes, F for full screen, Esc to exit.",
    emptyDeck: "This presentation has no slides.",
  },
  ar: {
    editor: "محرر العروض التقديمية",
    deckTitle: "عنوان العرض",
    deckTitlePlaceholder: "عرض بلا عنوان",
    slides: "الشرائح",
    slide: (n: string) => `الشريحة ${n}`,
    slideOf: (n: string, total: string) => `الشريحة ${n} من ${total}`,
    untitled: "شريحة بلا عنوان",
    addSlide: "إضافة شريحة",
    duplicate: "تكرار الشريحة",
    delete: "حذف الشريحة",
    moveEarlier: "نقل للأمام",
    moveLater: "نقل للخلف",
    moved: (n: string) => `نُقلت الشريحة إلى الموضع ${n}`,
    added: "أُضيفت شريحة",
    deleted: "حُذفت الشريحة",
    layout: "التخطيط",
    theme: "السمة",
    themeLight: "فاتحة",
    themeDark: "داكنة",
    themeBrand: "العلامة",
    layoutTitle: "عنوان",
    layoutSection: "قسم",
    layoutContent: "محتوى",
    layoutTwoColumn: "عمودان",
    layoutQuote: "اقتباس",
    layoutImage: "صورة",
    layoutBlank: "فارغة",
    titlePlaceholder: "عنوان الشريحة",
    subtitlePlaceholder: "عنوان فرعي",
    authorPlaceholder: "قائل الاقتباس",
    bodyPlaceholder: "نقطة في كل سطر",
    quotePlaceholder: "الاقتباس",
    leftPlaceholder: "العمود الأول، نقطة في كل سطر",
    rightPlaceholder: "العمود الثاني، نقطة في كل سطر",
    imageUrl: "عنوان الصورة",
    imageAlt: "وصف الصورة",
    imageHint: "استخدم رابط https أو عنوان ملف مرفوع.",
    noImage: "لا توجد صورة بعد",
    notes: "ملاحظات المقدّم",
    notesPlaceholder: "ما ستقوله في هذه الشريحة. أنت وحدك تراها.",
    present: "عرض",
    save: "حفظ",
    saving: "جارٍ الحفظ",
    saved: "تم الحفظ",
    unsaved: "تغييرات غير محفوظة",
    saveFailed: "تعذر الحفظ",
    empty: "لا توجد شرائح بعد",
    emptyHint: "أضف شريحة لبدء عرضك التقديمي.",
    slideCount: (n: string) => `${n} شرائح`,
    notesCount: (n: string) => `${n} بملاحظات`,
    reorderHint: "اسحب شريحة لإعادة ترتيبها، أو استخدم النقل للأمام والنقل للخلف.",
    player: "العرض التقديمي",
    close: "إنهاء العرض",
    next: "الشريحة التالية",
    previous: "الشريحة السابقة",
    showNotes: "إظهار الملاحظات",
    hideNotes: "إخفاء الملاحظات",
    enterFullscreen: "ملء الشاشة",
    exitFullscreen: "إنهاء ملء الشاشة",
    progress: "التقدم",
    upNext: "التالية",
    endOfDeck: "نهاية العرض",
    noNotes: "لا توجد ملاحظات لهذه الشريحة.",
    elapsed: "الوقت المنقضي",
    keys: "مفاتيح الأسهم أو السحب للتنقل، N للملاحظات، F لملء الشاشة، Esc للخروج.",
    emptyDeck: "لا يحتوي هذا العرض على شرائح.",
  },
};

export type PresentationText = typeof STRINGS.en;
export type PresentationLabels = Partial<PresentationText>;

export function usePresentationStrings(labels?: PresentationLabels) {
  const nq = useOptionalNasaq();
  const locale = nq?.locale ?? "en";
  return { locale, isRtl: nq?.isRtl ?? locale.startsWith("ar"), t: { ...STRINGS[locale.startsWith("ar") ? "ar" : "en"], ...labels } as PresentationText };
}
