// The built-in English and Arabic strings, copied from the React components. Override any of them with the `labels` prop.
import type { CronFrequency } from "./cron";

export const BUILDER_STRINGS = {
  en: {
    label: "Schedule",
    presets: "Common schedules",
    simple: "Simple",
    cron: "Cron expression",
    frequency: "Repeat",
    frequencies: { minutes: "Every few minutes", hours: "Every few hours", daily: "Every day", weekly: "Every week", monthly: "Every month" } satisfies Record<CronFrequency, string>,
    every: "Every",
    minutesUnit: "minutes",
    hoursUnit: "hours",
    atMinute: "At minute",
    atTime: "At",
    onDays: "On",
    dayOfMonth: "Day of the month",
    days: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    daysLong: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    expression: "Cron expression",
    expressionHelp: "Five fields: minute, hour, day of month, month, day of week. Ranges 1-5, lists 1,3 and steps */15 work.",
    notSimple: "This schedule cannot be shown as simple settings. Edit the cron expression, or start over from a simple one.",
    startOver: "Start over",
    summary: "Runs",
    custom: "Custom schedule",
    invalid: "Not a valid schedule",
    timeZone: "Time zone",
    timeZoneHelp: "The schedule is read in this time zone.",
    nextRuns: "Next runs",
    nextNone: "This schedule never runs.",
    fieldNames: ["minute", "hour", "day of month", "month", "day of week"],
    errors: {
      empty: () => "Enter a cron expression.",
      fields: () => "A cron expression has five fields separated by spaces.",
      syntax: (field: string, token: string) => `The ${field} field has a value that cannot be read: ${token}.`,
      range: (field: string, token: string) => `The ${field} field is out of range: ${token}.`,
      step: (field: string, token: string) => `The ${field} field has a step that does not fit: ${token}.`,
    },
    presetLabels: { "every-5-min": "Every 5 minutes", hourly: "Hourly", "daily-9": "Daily at 09:00", "weekdays-9": "Weekdays at 09:00", "weekly-mon": "Mondays at 09:00", "monthly-1st": "Monthly on the 1st" } as Record<string, string>,
  },
  ar: {
    label: "الجدولة",
    presets: "جداول شائعة",
    simple: "مبسّط",
    cron: "تعبير كرون",
    frequency: "التكرار",
    frequencies: { minutes: "كل بضع دقائق", hours: "كل بضع ساعات", daily: "كل يوم", weekly: "كل أسبوع", monthly: "كل شهر" } satisfies Record<CronFrequency, string>,
    every: "كل",
    minutesUnit: "دقيقة",
    hoursUnit: "ساعة",
    atMinute: "عند الدقيقة",
    atTime: "عند",
    onDays: "في",
    dayOfMonth: "يوم الشهر",
    days: ["أحد", "اثنين", "ثلاثاء", "أربعاء", "خميس", "جمعة", "سبت"],
    daysLong: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
    expression: "تعبير كرون",
    expressionHelp: "خمسة حقول: الدقيقة، الساعة، يوم الشهر، الشهر، يوم الأسبوع. تعمل النطاقات 1-5 والقوائم 1,3 والخطوات */15.",
    notSimple: "لا يمكن عرض هذا الجدول كإعدادات مبسّطة. عدّل تعبير كرون، أو ابدأ من جدول مبسّط.",
    startOver: "ابدأ من جديد",
    summary: "يعمل",
    custom: "جدول مخصص",
    invalid: "جدول غير صالح",
    timeZone: "المنطقة الزمنية",
    timeZoneHelp: "يُقرأ الجدول بهذه المنطقة الزمنية.",
    nextRuns: "التشغيلات القادمة",
    nextNone: "هذا الجدول لن يعمل أبدًا.",
    fieldNames: ["الدقيقة", "الساعة", "يوم الشهر", "الشهر", "يوم الأسبوع"],
    errors: {
      empty: () => "أدخل تعبير كرون.",
      fields: () => "يتكون تعبير كرون من خمسة حقول مفصولة بمسافات.",
      syntax: (field: string, token: string) => `في حقل ${field} قيمة لا يمكن قراءتها: ${token}.`,
      range: (field: string, token: string) => `حقل ${field} خارج النطاق: ${token}.`,
      step: (field: string, token: string) => `في حقل ${field} خطوة غير مناسبة: ${token}.`,
    },
    presetLabels: { "every-5-min": "كل 5 دقائق", hourly: "كل ساعة", "daily-9": "يوميًا عند 09:00", "weekdays-9": "أيام العمل عند 09:00", "weekly-mon": "الاثنين عند 09:00", "monthly-1st": "شهريًا في اليوم الأول" } as Record<string, string>,
  },
};

export type CronBuilderLabels = (typeof BUILDER_STRINGS)["en"];

export const SCHEDULE_STRINGS = {
  en: {
    label: "Schedules",
    empty: "No schedules yet",
    emptyBody: "Create a schedule to run something on a timer.",
    status: { ok: "Ran fine", failed: "Failed", missed: "Missed" },
    never: "Has not run yet",
    lastRun: "Last run",
    nextRun: "Next run",
    off: "Paused",
    custom: "Custom schedule",
    invalid: "Invalid schedule",
    enable: (name: string) => `Turn on ${name}`,
    runNow: "Run now",
    edit: "Edit",
    remove: "Delete",
    removeTitle: (name: string) => `Delete ${name}?`,
    removeBody: "It stops running and its schedule is lost. Past runs are kept.",
  },
  ar: {
    label: "الجداول",
    empty: "لا جداول بعد",
    emptyBody: "أنشئ جدولًا لتشغيل شيء في مواعيد محددة.",
    status: { ok: "عمل بنجاح", failed: "فشل", missed: "فاته الموعد" },
    never: "لم يعمل بعد",
    lastRun: "آخر تشغيل",
    nextRun: "التشغيل القادم",
    off: "متوقف مؤقتًا",
    custom: "جدول مخصص",
    invalid: "جدول غير صالح",
    enable: (name: string) => `تشغيل ${name}`,
    runNow: "شغّل الآن",
    edit: "تعديل",
    remove: "حذف",
    removeTitle: (name: string) => `حذف ${name}؟`,
    removeBody: "يتوقف عن العمل ويُفقد جدوله. تبقى التشغيلات السابقة.",
  },
};

export type CronScheduleListLabels = (typeof SCHEDULE_STRINGS)["en"];
