import type { StatusHue, StatusStage } from "./status-label-logic";

export const STRINGS = {
  en: {
    statuses: "Statuses",
    labels: "Labels",
    statusesBody: "The steps work moves through. Each status belongs to a stage, so reports know what is open and what is done.",
    labelsBody: "Free-form tags you can put on any item.",
    stage: { backlog: "Backlog", todo: "To do", active: "In progress", review: "In review", done: "Done", canceled: "Canceled" } satisfies Record<StatusStage, string>,
    stageEmpty: "No statuses in this stage",
    addStatus: "New status",
    addLabel: "New label",
    editStatus: "Edit status",
    editLabel: "Edit label",
    edit: (n: string) => `Edit ${n}`,
    remove: (n: string) => `Delete ${n}`,
    moveUp: (n: string) => `Move ${n} up`,
    moveDown: (n: string) => `Move ${n} down`,
    name: "Name",
    nameHint: (n: number) => `Up to ${n} characters.`,
    colour: "Colour",
    stageField: "Stage",
    preview: "Preview",
    errors: { empty: "Give it a name.", tooLong: (n: number) => `Use ${n} characters or fewer.`, duplicate: "That name is already used." },
    save: "Save",
    create: "Create",
    cancel: "Cancel",
    usedBy: (n: number) => (n === 0 ? "Not used" : n === 1 ? "Used by 1 item" : `Used by ${n} items`),
    deleteStatusTitle: (n: string) => `Delete status ${n}?`,
    deleteLabelTitle: (n: string) => `Delete label ${n}?`,
    deleteBody: (n: number) => (n === 0 ? "Nothing uses it, so nothing else changes." : n === 1 ? "1 item uses it. It loses this value." : `${n} items use it. They lose this value.`),
    deleteConfirm: "Delete",
    emptyLabels: "No labels yet",
    emptyLabelsBody: "Labels help you find and group items.",
    noDone: "Add a status in the Done stage so finished work can be counted.",
    failed: "Could not save. Try again.",
    colours: { gray: "Gray", red: "Red", orange: "Orange", amber: "Amber", green: "Green", teal: "Teal", blue: "Blue", violet: "Violet", pink: "Pink" } satisfies Record<StatusHue, string>,
  },
  ar: {
    statuses: "الحالات",
    labels: "التصنيفات",
    statusesBody: "الخطوات التي يمر بها العمل. تنتمي كل حالة إلى مرحلة، لتعرف التقارير ما هو مفتوح وما هو منجز.",
    labelsBody: "وسوم حرة يمكنك وضعها على أي عنصر.",
    stage: { backlog: "قائمة الانتظار", todo: "للتنفيذ", active: "قيد التنفيذ", review: "قيد المراجعة", done: "منجز", canceled: "ملغى" } satisfies Record<StatusStage, string>,
    stageEmpty: "لا توجد حالات في هذه المرحلة",
    addStatus: "حالة جديدة",
    addLabel: "تصنيف جديد",
    editStatus: "تعديل الحالة",
    editLabel: "تعديل التصنيف",
    edit: (n: string) => `تعديل ${n}`,
    remove: (n: string) => `حذف ${n}`,
    moveUp: (n: string) => `نقل ${n} لأعلى`,
    moveDown: (n: string) => `نقل ${n} لأسفل`,
    name: "الاسم",
    nameHint: (n: number) => `حتى ${n} حرفًا.`,
    colour: "اللون",
    stageField: "المرحلة",
    preview: "معاينة",
    errors: { empty: "اكتب اسمًا.", tooLong: (n: number) => `استخدم ${n} حرفًا أو أقل.`, duplicate: "هذا الاسم مستخدم بالفعل." },
    save: "حفظ",
    create: "إنشاء",
    cancel: "إلغاء",
    usedBy: (n: number) => (n === 0 ? "غير مستخدم" : n === 1 ? "يستخدمه عنصر واحد" : n === 2 ? "يستخدمه عنصران" : n <= 10 ? `يستخدمه ${n} عناصر` : `يستخدمه ${n} عنصرًا`),
    deleteStatusTitle: (n: string) => `حذف الحالة ${n}؟`,
    deleteLabelTitle: (n: string) => `حذف التصنيف ${n}؟`,
    deleteBody: (n: number) => (n === 0 ? "لا شيء يستخدمه، فلن يتغير أي شيء آخر." : n === 1 ? "يستخدمه عنصر واحد وسيفقد هذه القيمة." : `يستخدمه ${n} عنصرًا وسيفقدون هذه القيمة.`),
    deleteConfirm: "حذف",
    emptyLabels: "لا توجد تصنيفات بعد",
    emptyLabelsBody: "تساعدك التصنيفات على إيجاد العناصر وتجميعها.",
    noDone: "أضف حالة في مرحلة «منجز» ليمكن احتساب العمل المنتهي.",
    failed: "تعذّر الحفظ. حاول مرة أخرى.",
    colours: { gray: "رمادي", red: "أحمر", orange: "برتقالي", amber: "كهرماني", green: "أخضر", teal: "تركوازي", blue: "أزرق", violet: "بنفسجي", pink: "وردي" } satisfies Record<StatusHue, string>,
  },
};

export const statusLabelStrings = (locale: string) => STRINGS[locale.startsWith("ar") ? "ar" : "en"];
export type StatusLabelManagerLabels = Partial<typeof STRINGS.en>;
export type StatusLabelStrings = typeof STRINGS.en;
