// The page's own words, en and ar, copied from the React EngineDetails and EngineHistoryStrip.
export const STRINGS = {
  en: {
    back: "Back to today",
    lede: "What this engine says right now, and what it has recorded.",
    history: "History",
    historyDescription: "Days on protocol, off it, and days the engine declined to judge. Counts, never a rate.",
    window: "Window",
    windowOption: (days: number) => `${days} days`,
    windowLabel: "History window",
    onProtocol: "Days on protocol",
    offProtocol: "Days off protocol",
    unevaluated: "Days not judged",
    currentStreak: "Current streak",
    bestStreak: "Best streak",
    entriesChart: "Entries per day",
    weeklyChart: "Days per week",
    entries: "Entries",
    chartSummary: (days: number) => `Protocol history for the last ${days} days`,
    strip: "Every day",
    record: "Record",
    recordDescription: "What this engine has written down, newest first.",
    noRecord: "Nothing recorded yet.",
    noHistory: "No history yet",
    noHistoryHint: "History appears after the first day of tracking.",
    noLedger: "This engine keeps a ledger, not a day verdict.",
    noLedgerHint: "It never marks a day on or off protocol, because it makes no such judgement.",
    protocol: "The protocol",
    protocolDescription: "The fixed rules this engine follows. They live in the engine, not in this screen.",
    unit: "Loggable unit",
    dailyCap: "Daily cap",
    cooldown: "Cooldown between entries",
    blockAfterWake: "No caffeine after waking",
    windowBeforeSleep: "Window before sleep",
    allowedInside: "Allowed inside the window",
    graceWindow: "On-time window for a dose",
    familiesLabel: "Trigger families",
    minCycles: "Cycles needed for a prediction",
    irregularSpread: "Spread that withdraws a prediction",
    ovulationBefore: "Ovulation estimated before next start",
    fertileWindow: "Fertile window around ovulation",
    fertileWindowValue: (before: string, after: string) => `${before} before, ${after} after`,
    methodsLabel: "Methods tracked",
    ownPlan: "Every interval comes from your own plan. The engine has no default.",
    loadError: "The history could not be loaded.",
    retry: "Try again",
    disclaimer: "Every line on this page is about the protocol and what was logged. None of it is a claim about your body.",
  },
  ar: {
    back: "العودة إلى اليوم",
    lede: "ما يقوله هذا المحرّك الآن، وما سجّله.",
    history: "السجل",
    historyDescription: "أيام ضمن البروتوكول وخارجه، وأيام امتنع المحرّك عن تقييمها. أعداد، وليست نسبًا.",
    window: "النطاق",
    windowOption: (days: number) => `${days} يومًا`,
    windowLabel: "نطاق السجل",
    onProtocol: "أيام ضمن البروتوكول",
    offProtocol: "أيام خارج البروتوكول",
    unevaluated: "أيام لم تُقيَّم",
    currentStreak: "السلسلة الحالية",
    bestStreak: "أفضل سلسلة",
    entriesChart: "الإدخالات في اليوم",
    weeklyChart: "الأيام في الأسبوع",
    entries: "الإدخالات",
    chartSummary: (days: number) => `سجل البروتوكول لآخر ${days} يومًا`,
    strip: "كل الأيام",
    record: "التسجيلات",
    recordDescription: "ما دوّنه هذا المحرّك، من الأحدث.",
    noRecord: "لا شيء مسجّل بعد.",
    noHistory: "لا سجل بعد",
    noHistoryHint: "يظهر السجل بعد أول يوم من التتبّع.",
    noLedger: "يحتفظ هذا المحرّك بدفتر تسجيلات، لا بحكم يومي.",
    noLedgerHint: "لا يصف أي يوم بأنه ضمن البروتوكول أو خارجه، لأنه لا يصدر هذا الحكم.",
    protocol: "البروتوكول",
    protocolDescription: "القواعد الثابتة التي يتبعها هذا المحرّك. مكانها المحرّك نفسه لا هذه الشاشة.",
    unit: "الوحدة القابلة للتسجيل",
    dailyCap: "السقف اليومي",
    cooldown: "الفاصل بين الإدخالات",
    blockAfterWake: "لا كافيين بعد الاستيقاظ",
    windowBeforeSleep: "النافذة قبل النوم",
    allowedInside: "المسموح داخل النافذة",
    graceWindow: "نافذة الجرعة في وقتها",
    familiesLabel: "عائلات المحفّزات",
    minCycles: "الدورات اللازمة للتوقع",
    irregularSpread: "التفاوت الذي يسحب التوقع",
    ovulationBefore: "الإباضة المقدّرة قبل البداية التالية",
    fertileWindow: "فترة الخصوبة حول الإباضة",
    fertileWindowValue: (before: string, after: string) => `${before} قبلها، و${after} بعدها`,
    methodsLabel: "الوسائل المتتبَّعة",
    ownPlan: "كل فاصل يأتي من خطتك أنت. لا قيمة افتراضية لدى المحرّك.",
    loadError: "تعذّر تحميل السجل.",
    retry: "حاول مرة أخرى",
    disclaimer: "كل سطر في هذه الصفحة عن البروتوكول وما سُجّل. ليس فيه أي ادعاء عن جسدك.",
  },
};

export type EngineDetailsLabels = typeof STRINGS.en;

export const STRIP_STRINGS = {
  en: {
    dayLabel: (date: string, verdict: string, entries: string) => `${date}: ${verdict}, ${entries}`,
    entries: (n: number) => (n === 1 ? "1 entry" : `${n} entries`),
    stripLabel: "Day by day, oldest first",
    legend: "Legend",
  },
  ar: {
    dayLabel: (date: string, verdict: string, entries: string) => `${date}: ${verdict}، ${entries}`,
    entries: (n: number) => (n === 0 ? "لا إدخالات" : n === 1 ? "إدخال واحد" : n === 2 ? "إدخالان" : n <= 10 ? `${n} إدخالات` : `${n} إدخالًا`),
    stripLabel: "يومًا بيوم، من الأقدم",
    legend: "دليل الرموز",
  },
};

export type HistoryStripLabels = typeof STRIP_STRINGS.en;
