// The built-in words of CurrentVisit (English and Arabic), same as the React component's STRINGS.
export const STRINGS = {
  en: {
    years: (n: number) => `${n} years`,
    allergies: "Allergies",
    conditions: "Conditions",
    none: "None recorded",
    history: "Earlier visits",
    noHistory: "No earlier visits.",
    visit: "This visit",
    timer: "Time in visit",
    notes: "Visit notes",
    notesHint: "Findings, diagnosis and advice.",
    prescriptions: "Prescriptions",
    addRx: "Add medicine",
    removeRx: (n: number) => `Remove medicine ${n}`,
    drug: "Medicine",
    dose: "Dose",
    frequency: "How often",
    days: "Days",
    frequencyHint: "Twice daily",
    required: "Required",
    invalid: "1 to 365",
    followUp: "Follow-up",
    noFollowUp: "None",
    inDays: (n: number) => (n % 30 === 0 ? `In ${n / 30} ${n === 30 ? "month" : "months"}` : n % 7 === 0 ? `In ${n / 7} ${n === 7 ? "week" : "weeks"}` : `In ${n} days`),
    orPick: "Or pick a date",
    followUpOn: (d: string) => `Follow-up on ${d}`,
    finish: "Finish visit",
    finishing: "Saving",
    needSomething: "Add a note or a prescription to finish.",
    fixRx: "Fix the highlighted medicines to finish.",
    failed: "The visit could not be saved. Try again.",
    saved: "Visit saved.",
    room: (r: string) => `Room ${r}`,
  },
  ar: {
    years: (n: number) => (n === 1 ? "سنة" : n === 2 ? "سنتان" : n <= 10 ? `${n} سنوات` : `${n} سنة`),
    allergies: "الحساسية",
    conditions: "الحالات",
    none: "لا شيء مسجل",
    history: "الزيارات السابقة",
    noHistory: "لا زيارات سابقة.",
    visit: "هذه الزيارة",
    timer: "مدة الزيارة",
    notes: "ملاحظات الزيارة",
    notesHint: "الفحص والتشخيص والنصائح.",
    prescriptions: "الوصفة الطبية",
    addRx: "إضافة دواء",
    removeRx: (n: number) => `حذف الدواء ${n}`,
    drug: "الدواء",
    dose: "الجرعة",
    frequency: "التكرار",
    days: "الأيام",
    frequencyHint: "مرتين يوميًا",
    required: "مطلوب",
    invalid: "من 1 إلى 365",
    followUp: "المتابعة",
    noFollowUp: "بدون",
    inDays: (n: number) => (n % 30 === 0 ? (n === 30 ? "بعد شهر" : "بعد شهرين") : n % 7 === 0 ? (n === 7 ? "بعد أسبوع" : "بعد أسبوعين") : `بعد ${n} أيام`),
    orPick: "أو اختر تاريخًا",
    followUpOn: (d: string) => `المتابعة في ${d}`,
    finish: "إنهاء الزيارة",
    finishing: "جارٍ الحفظ",
    needSomething: "أضف ملاحظة أو دواءً لإنهاء الزيارة.",
    fixRx: "صحّح الأدوية المظللة لإنهاء الزيارة.",
    failed: "تعذّر حفظ الزيارة. حاول مجددًا.",
    saved: "تم حفظ الزيارة.",
    room: (r: string) => `الغرفة ${r}`,
  },
};

export type CurrentVisitLabels = (typeof STRINGS)["en"];
