import { computed, type MaybeRefOrGetter, toValue } from "vue";
import { useNasaq } from "../../provider";
import type { RunFilter } from "./run-model";

export const RUN_STRINGS = {
  en: {
    runs: "Runs",
    search: "Search runs",
    filters: "Filter by status",
    filterNames: { all: "All", failed: "Failed", success: "Succeeded", running: "Running" } satisfies Record<RunFilter, string>,
    none: "No runs match",
    noneBody: "Change the filter or the search.",
    pick: "Choose a run",
    pickBody: "Pick a run on the left to see its steps, timing and output.",
    back: "Back to runs",
    unnamed: "Run",
    started: "Started",
    duration: "Duration",
    trigger: "Trigger",
    retry: "Run again",
    cancel: "Cancel run",
    steps: "Steps",
    trace: "Trace",
    raw: "Raw",
    stepsNone: "This run recorded no steps.",
    failedHere: "Failed here",
    skippedNote: "Skipped",
    failure: (step: string) => `Failed at ${step}`,
    failureRun: "This run failed",
    showStep: "Show the step",
    attempt: (n: string) => `Attempt ${n}`,
    input: "Input",
    output: "Output",
    error: "Error",
    logs: "Logs",
    shots: "Screenshots",
    openShot: (name: string) => `Enlarge: ${name}`,
    expand: (name: string) => `Show details of ${name}`,
    collapse: (name: string) => `Hide details of ${name}`,
    noDetail: "No input, output or logs were recorded for this step.",
    waterfall: "Spans",
    spanDetail: "Span details",
    spanName: "Name",
    spanService: "Service",
    spanStart: "Starts at",
    spanDuration: "Duration",
    spanAttrs: "Attributes",
    spanNoAttrs: "No attributes.",
    spanFailed: "Failed",
    pickSpan: "Choose a span to see its attributes.",
    traceNone: "No trace was recorded for this run.",
    rawLabel: "Raw run data",
    stepCount: (n: string) => `${n} steps`,
  },
  ar: {
    runs: "التشغيلات",
    search: "ابحث في التشغيلات",
    filters: "التصفية بالحالة",
    filterNames: { all: "الكل", failed: "الفاشلة", success: "الناجحة", running: "الجارية" } satisfies Record<RunFilter, string>,
    none: "لا تشغيلات مطابقة",
    noneBody: "غيّر التصفية أو البحث.",
    pick: "اختر تشغيلًا",
    pickBody: "اختر تشغيلًا من القائمة لترى خطواته وتوقيته ومخرجاته.",
    back: "العودة إلى التشغيلات",
    unnamed: "تشغيل",
    started: "بدأ",
    duration: "المدة",
    trigger: "المشغّل",
    retry: "أعد التشغيل",
    cancel: "إلغاء التشغيل",
    steps: "الخطوات",
    trace: "التتبع",
    raw: "الخام",
    stepsNone: "لم يسجّل هذا التشغيل أي خطوات.",
    failedHere: "فشل هنا",
    skippedNote: "تم تخطيها",
    failure: (step: string) => `فشل عند ${step}`,
    failureRun: "فشل هذا التشغيل",
    showStep: "اعرض الخطوة",
    attempt: (n: string) => `المحاولة ${n}`,
    input: "المُدخل",
    output: "المخرج",
    error: "الخطأ",
    logs: "السجل",
    shots: "لقطات الشاشة",
    openShot: (name: string) => `تكبير: ${name}`,
    expand: (name: string) => `عرض تفاصيل ${name}`,
    collapse: (name: string) => `إخفاء تفاصيل ${name}`,
    noDetail: "لم يُسجَّل مُدخل أو مخرج أو سجل لهذه الخطوة.",
    waterfall: "المقاطع الزمنية",
    spanDetail: "تفاصيل المقطع",
    spanName: "الاسم",
    spanService: "الخدمة",
    spanStart: "يبدأ عند",
    spanDuration: "المدة",
    spanAttrs: "الخصائص",
    spanNoAttrs: "لا خصائص.",
    spanFailed: "فشل",
    pickSpan: "اختر مقطعًا لترى خصائصه.",
    traceNone: "لم يُسجَّل تتبع لهذا التشغيل.",
    rawLabel: "بيانات التشغيل الخام",
    stepCount: (n: string) => `${n} خطوات`,
  },
};

export type RunHistoryLabels = (typeof RUN_STRINGS)["en"];

/** Built-in strings by the Nasaq locale, with `labels` on top. */
export function useRunLabels(labels?: MaybeRefOrGetter<Partial<RunHistoryLabels> | undefined>) {
  const nq = useNasaq();
  const ar = computed(() => nq.locale.value.startsWith("ar"));
  const t = computed<RunHistoryLabels>(() => ({ ...RUN_STRINGS[ar.value ? "ar" : "en"], ...toValue(labels) }));
  return { t, ar };
}
