// Built-in English and Arabic strings of the product admin (list, editor, media, options, variants, collections).
import { useNasaq } from "../../provider";
import { formatNumber } from "../numeric";
import { computed } from "vue";

const en = {
  // list
  products: "Products",
  newProduct: "New product",
  searchProducts: "Search products",
  productCol: "Product",
  statusCol: "Status",
  stockCol: "Stock",
  priceCol: "Price",
  variantsCol: "Variants",
  categoryCol: "Category",
  statuses: { active: "Active", draft: "Draft", archived: "Archived" },
  stockLevels: { in: "In stock", low: "Low stock", out: "Out of stock", untracked: "Not tracked" },
  units: (n: string) => `${n} in stock`,
  variantCount: (n: string) => `${n} variants`,
  oneVariant: "1 variant",
  productListLabel: "Products",
  noProducts: "No products yet",
  noProductsHint: "Add your first product to start selling.",
  loadFailed: "Products did not load.",
  retry: "Try again",
  edit: "Edit",
  setActive: "Set active",
  setDraft: "Move to drafts",
  archive: "Archive",
  delete: "Delete",
  deleteTitle: "Delete this product?",
  deleteDescription: (name: string) => `${name} and its variants are removed. Past orders keep their copy.`,
  selectedCount: (n: string) => `${n} selected`,
  bulkEdit: "Bulk edit",
  bulkTitle: (n: string) => `Edit ${n} products`,
  bulkDescription: "Leave a section on Keep to leave it alone. Changes apply to every variant.",
  bulkPrice: "Price",
  bulkStock: "Stock",
  bulkStatus: "Status",
  keep: "Keep",
  priceModes: { set: "Set to", "increase-percent": "Raise by percent", "decrease-percent": "Lower by percent", "increase-amount": "Raise by amount", "decrease-amount": "Lower by amount" },
  stockModes: { set: "Set to", add: "Add", remove: "Remove" },
  alsoCompareAt: "Move compare-at price the same way",
  percent: "Percent",
  amount: "Amount",
  quantity: "Quantity",
  preview: "Preview",
  previewEmpty: "Nothing changes yet. Pick a change above.",
  previewRow: (name: string) => `${name}`,
  applyToProducts: (n: string) => `Apply to ${n} products`,
  cancel: "Cancel",
  actions: "Actions",
  // editor
  editProduct: "Edit product",
  newProductTitle: "New product",
  general: "General",
  title: "Title",
  description: "Description",
  descriptionLabel: "Product description",
  media: "Media",
  pricing: "Pricing",
  price: "Price",
  compareAt: "Compare-at price",
  compareAtHint: "The old price shown struck through. Must be above the price.",
  cost: "Cost per item",
  costHint: "Only you see this.",
  margin: "Margin",
  profit: "Profit",
  markup: "Markup",
  noMargin: "Add a price and a cost to see the margin.",
  inventory: "Inventory",
  sku: "SKU",
  trackStock: "Track stock",
  stockQty: "In stock",
  backorder: "Sell when out of stock",
  weight: "Weight (grams)",
  organization: "Organisation",
  brand: "Brand",
  category: "Category",
  tags: "Tags",
  tagsPlaceholder: "Add a tag",
  seo: "Search listing",
  seoTitle: "Page title",
  seoDescription: "Meta description",
  slug: "URL handle",
  slugHint: "Lower-case letters, digits and dashes.",
  statusSection: "Status and visibility",
  visibility: "Visibility",
  visible: "Visible in the store",
  hidden: "Hidden from the store (link still works)",
  statusHint: { active: "Customers can buy it.", draft: "Only you can see it.", archived: "Kept for records, not sold." },
  save: "Save product",
  saving: "Saving",
  discard: "Discard changes",
  unsaved: "Unsaved changes",
  allSaved: "All changes saved",
  saveFailed: "That did not save. Try again.",
  fixIssues: (n: string) => `${n} to fix before saving`,
  issues: {
    title: "Add a title.",
    price: "Add a price.",
    "compare-at": "Compare-at must be above the price.",
    "sku-duplicate": "Two variants share a SKU.",
    "no-variants": "Generate the variants for these options.",
    "too-many-variants": "Too many variants. Remove an option value.",
    slug: "The URL handle has characters that are not allowed.",
  },
  // media
  mediaLabel: "Product images",
  addImage: "Add image",
  imageUrl: "Image URL",
  imageUrlPlaceholder: "https://…",
  altText: "Alt text",
  altHint: "Describe the picture for people who cannot see it.",
  missingAlt: "Alt text missing",
  primary: "Main image",
  moveEarlier: "Move earlier",
  moveLater: "Move later",
  removeImage: "Remove image",
  dragHandle: (n: string) => `Reorder image ${n}`,
  movedTo: (n: string, total: string) => `Image moved to position ${n} of ${total}`,
  noImages: "No images yet",
  noImagesHint: "Add a picture by its URL. The first one is the main image.",
  imageFailed: "Image did not load",
  // options and variants
  optionsTitle: "Options",
  optionsHint: "Colour, size, material. Up to three options.",
  addOption: "Add option",
  removeOption: "Remove option",
  optionName: "Option name",
  optionNamePlaceholder: "Size",
  optionValues: "Values",
  optionValuesPlaceholder: "Add a value",
  variantsTitle: "Variants",
  variantsSummary: (n: string) => `${n} variants`,
  variantsRemoved: (n: string) => `${n} variants no longer match and were removed.`,
  variantsTruncated: (max: string) => `More than ${max} combinations. Only the first ${max} are created.`,
  variantLabel: "Variant",
  skuCol: "SKU",
  priceCol2: "Price",
  compareCol: "Compare-at",
  stockCol2: "Stock",
  imageCol: "Image",
  noImage: "No image",
  bulkFill: "Fill selected variants",
  selectVariants: "Select variants to fill them at once.",
  selectAll: "Select all variants",
  selectVariant: (v: string) => `Select ${v}`,
  fillPrice: "Price",
  fillCompare: "Compare-at",
  fillStock: "Stock",
  fillAddStock: "Add stock",
  fillSkuPrefix: "SKU prefix",
  fillApply: "Apply to selected",
  fillClear: "Clear selection",
  variantsSelected: (n: string) => `${n} selected`,
  dupSku: "Duplicate SKU",
  variantsEmpty: "Add an option to create variants.",
  // collections
  collections: "Collections",
  newCollection: "New collection",
  collectionsLabel: "Collections",
  collectionTitle: "Collection title",
  manual: "Manual",
  rules: "Rules",
  kindLabel: "How products join",
  manualHint: "Pick the products yourself, in the order you want them.",
  rulesHint: "Products join on their own when they match the rules.",
  matchPreview: (n: string) => `${n} products match`,
  matchNone: "No products match yet.",
  matchPreviewLabel: "Products in this collection",
  addProducts: "Add products",
  addProduct: "Add a product",
  pickProduct: "Choose a product",
  removeFromCollection: "Remove from collection",
  moveUp: "Move up",
  moveDown: "Move down",
  saveCollection: "Save collection",
  deleteCollection: "Delete collection",
  deleteCollectionTitle: "Delete this collection?",
  deleteCollectionDescription: (name: string) => `${name} is removed. The products stay in your catalogue.`,
  collectionsEmpty: "No collections yet",
  collectionsEmptyHint: "Group products so customers can browse them together.",
  productsCount: (n: string) => `${n} products`,
  ruleAnyProduct: "any product",
  ruleAddIt: "add it to this collection",
  ruleEventLabel: "Applies to",
  ruleEventHelp: "Every active product is checked against the conditions below.",
  ruleIfTitle: "Products that match",
  ruleIfHelp: "Add conditions. A product joins when they hold. With none, no product joins.",
  ruleThenTitle: "Result",
  ruleThenHelp: "Matching products are added to this collection.",
  ruleAction: "Add it to this collection",
  ruleWhere: "where",
  ruleSo: "so",
  and: "and",
  or: "or",
  editCollection: "Edit collection",
  fields: { tag: "Tag", brand: "Brand", category: "Category", title: "Title", price: "Price", stock: "Stock", onSale: "On sale", status: "Status" },
  close: "Close",
};

export type ProductAdminStrings = typeof en;

const ar: ProductAdminStrings = {
  products: "المنتجات",
  newProduct: "منتج جديد",
  searchProducts: "ابحث في المنتجات",
  productCol: "المنتج",
  statusCol: "الحالة",
  stockCol: "المخزون",
  priceCol: "السعر",
  variantsCol: "الأنواع",
  categoryCol: "الفئة",
  statuses: { active: "نشط", draft: "مسودة", archived: "مؤرشف" },
  stockLevels: { in: "متوفر", low: "مخزون منخفض", out: "نفد", untracked: "غير متتبَّع" },
  units: (n) => `${n} في المخزون`,
  variantCount: (n) => `${n} أنواع`,
  oneVariant: "نوع واحد",
  productListLabel: "المنتجات",
  noProducts: "لا توجد منتجات بعد",
  noProductsHint: "أضف أول منتج لتبدأ البيع.",
  loadFailed: "تعذّر تحميل المنتجات.",
  retry: "حاول مرة أخرى",
  edit: "تعديل",
  setActive: "تفعيل",
  setDraft: "نقل إلى المسودات",
  archive: "أرشفة",
  delete: "حذف",
  deleteTitle: "حذف هذا المنتج؟",
  deleteDescription: (name) => `سيُحذف ${name} مع أنواعه. الطلبات السابقة تحتفظ بنسختها.`,
  selectedCount: (n) => `${n} محدد`,
  bulkEdit: "تعديل جماعي",
  bulkTitle: (n) => `تعديل ${n} منتجات`,
  bulkDescription: "اترك القسم على «بدون تغيير» ليبقى كما هو. التغييرات تشمل كل الأنواع.",
  bulkPrice: "السعر",
  bulkStock: "المخزون",
  bulkStatus: "الحالة",
  keep: "بدون تغيير",
  priceModes: { set: "تحديد بقيمة", "increase-percent": "رفع بنسبة", "decrease-percent": "خفض بنسبة", "increase-amount": "رفع بمبلغ", "decrease-amount": "خفض بمبلغ" },
  stockModes: { set: "تحديد بقيمة", add: "إضافة", remove: "إزالة" },
  alsoCompareAt: "حرّك سعر المقارنة بالطريقة نفسها",
  percent: "النسبة",
  amount: "المبلغ",
  quantity: "الكمية",
  preview: "معاينة",
  previewEmpty: "لا تغيير بعد. اختر تغييرًا أعلاه.",
  previewRow: (name) => `${name}`,
  applyToProducts: (n) => `تطبيق على ${n} منتجات`,
  cancel: "إلغاء",
  actions: "الإجراءات",
  editProduct: "تعديل المنتج",
  newProductTitle: "منتج جديد",
  general: "عام",
  title: "العنوان",
  description: "الوصف",
  descriptionLabel: "وصف المنتج",
  media: "الوسائط",
  pricing: "التسعير",
  price: "السعر",
  compareAt: "سعر المقارنة",
  compareAtHint: "السعر القديم الذي يظهر مشطوبًا. يجب أن يكون أعلى من السعر.",
  cost: "التكلفة للقطعة",
  costHint: "لا يراها غيرك.",
  margin: "الهامش",
  profit: "الربح",
  markup: "نسبة الزيادة",
  noMargin: "أضف سعرًا وتكلفة لترى الهامش.",
  inventory: "المخزون",
  sku: "رمز المنتج (SKU)",
  trackStock: "تتبّع المخزون",
  stockQty: "المتوفر",
  backorder: "البيع عند نفاد المخزون",
  weight: "الوزن (جرام)",
  organization: "التنظيم",
  brand: "العلامة التجارية",
  category: "الفئة",
  tags: "الوسوم",
  tagsPlaceholder: "أضف وسمًا",
  seo: "الظهور في البحث",
  seoTitle: "عنوان الصفحة",
  seoDescription: "الوصف التعريفي",
  slug: "معرّف الرابط",
  slugHint: "حروف إنجليزية صغيرة وأرقام وشرطات.",
  statusSection: "الحالة والظهور",
  visibility: "الظهور",
  visible: "ظاهر في المتجر",
  hidden: "مخفي عن المتجر (الرابط يعمل)",
  statusHint: { active: "يمكن للعملاء شراؤه.", draft: "لا يراه غيرك.", archived: "محفوظ للسجلات ولا يُباع." },
  save: "حفظ المنتج",
  saving: "جارٍ الحفظ",
  discard: "تجاهل التغييرات",
  unsaved: "تغييرات غير محفوظة",
  allSaved: "كل التغييرات محفوظة",
  saveFailed: "لم يتم الحفظ. حاول مرة أخرى.",
  fixIssues: (n) => `${n} يلزم إصلاحها قبل الحفظ`,
  issues: {
    title: "أضف عنوانًا.",
    price: "أضف سعرًا.",
    "compare-at": "سعر المقارنة يجب أن يكون أعلى من السعر.",
    "sku-duplicate": "نوعان يشتركان في الرمز نفسه.",
    "no-variants": "أنشئ الأنواع لهذه الخيارات.",
    "too-many-variants": "أنواع كثيرة جدًا. احذف قيمة من أحد الخيارات.",
    slug: "معرّف الرابط يحوي حروفًا غير مسموحة.",
  },
  mediaLabel: "صور المنتج",
  addImage: "إضافة صورة",
  imageUrl: "رابط الصورة",
  imageUrlPlaceholder: "https://…",
  altText: "النص البديل",
  altHint: "صف الصورة لمن لا يستطيع رؤيتها.",
  missingAlt: "النص البديل ناقص",
  primary: "الصورة الرئيسية",
  moveEarlier: "قدّم",
  moveLater: "أخّر",
  removeImage: "حذف الصورة",
  dragHandle: (n) => `إعادة ترتيب الصورة ${n}`,
  movedTo: (n, total) => `نُقلت الصورة إلى الموضع ${n} من ${total}`,
  noImages: "لا توجد صور بعد",
  noImagesHint: "أضف صورة برابطها. الأولى هي الصورة الرئيسية.",
  imageFailed: "تعذّر تحميل الصورة",
  optionsTitle: "الخيارات",
  optionsHint: "اللون والمقاس والخامة. حتى ثلاثة خيارات.",
  addOption: "إضافة خيار",
  removeOption: "حذف الخيار",
  optionName: "اسم الخيار",
  optionNamePlaceholder: "المقاس",
  optionValues: "القيم",
  optionValuesPlaceholder: "أضف قيمة",
  variantsTitle: "الأنواع",
  variantsSummary: (n) => `${n} أنواع`,
  variantsRemoved: (n) => `${n} أنواع لم تعد مطابقة وأُزيلت.`,
  variantsTruncated: (max) => `أكثر من ${max} تركيبة. أُنشئت أول ${max} فقط.`,
  variantLabel: "النوع",
  skuCol: "الرمز",
  priceCol2: "السعر",
  compareCol: "سعر المقارنة",
  stockCol2: "المخزون",
  imageCol: "الصورة",
  noImage: "بلا صورة",
  bulkFill: "تعبئة الأنواع المحددة",
  selectVariants: "حدد أنواعًا لتعبئتها دفعة واحدة.",
  selectAll: "تحديد كل الأنواع",
  selectVariant: (v) => `تحديد ${v}`,
  fillPrice: "السعر",
  fillCompare: "سعر المقارنة",
  fillStock: "المخزون",
  fillAddStock: "إضافة مخزون",
  fillSkuPrefix: "بادئة الرمز",
  fillApply: "تطبيق على المحدد",
  fillClear: "إلغاء التحديد",
  variantsSelected: (n) => `${n} محدد`,
  dupSku: "رمز مكرر",
  variantsEmpty: "أضف خيارًا لإنشاء الأنواع.",
  collections: "المجموعات",
  newCollection: "مجموعة جديدة",
  collectionsLabel: "المجموعات",
  collectionTitle: "عنوان المجموعة",
  manual: "يدوية",
  rules: "بقواعد",
  kindLabel: "كيف تنضم المنتجات",
  manualHint: "اختر المنتجات بنفسك بالترتيب الذي تريده.",
  rulesHint: "تنضم المنتجات تلقائيًا عندما تطابق القواعد.",
  matchPreview: (n) => `${n} منتجات مطابقة`,
  matchNone: "لا توجد منتجات مطابقة بعد.",
  matchPreviewLabel: "منتجات هذه المجموعة",
  addProducts: "إضافة منتجات",
  addProduct: "أضف منتجًا",
  pickProduct: "اختر منتجًا",
  removeFromCollection: "إزالة من المجموعة",
  moveUp: "تحريك لأعلى",
  moveDown: "تحريك لأسفل",
  saveCollection: "حفظ المجموعة",
  deleteCollection: "حذف المجموعة",
  deleteCollectionTitle: "حذف هذه المجموعة؟",
  deleteCollectionDescription: (name) => `ستُحذف ${name}. تبقى المنتجات في الكتالوج.`,
  collectionsEmpty: "لا توجد مجموعات بعد",
  collectionsEmptyHint: "اجمع المنتجات ليتصفحها العملاء معًا.",
  productsCount: (n) => `${n} منتجات`,
  ruleAnyProduct: "أي منتج",
  ruleAddIt: "أضفه إلى هذه المجموعة",
  ruleEventLabel: "ينطبق على",
  ruleEventHelp: "يُفحص كل منتج نشط مقابل الشروط أدناه.",
  ruleIfTitle: "المنتجات المطابقة",
  ruleIfHelp: "أضف شروطًا. ينضم المنتج عند تحققها. بدون شروط لا ينضم أي منتج.",
  ruleThenTitle: "النتيجة",
  ruleThenHelp: "تُضاف المنتجات المطابقة إلى هذه المجموعة.",
  ruleAction: "أضفه إلى هذه المجموعة",
  ruleWhere: "حيث",
  ruleSo: "وعندها",
  and: "و",
  or: "أو",
  editCollection: "تعديل المجموعة",
  fields: { tag: "الوسم", brand: "العلامة", category: "الفئة", title: "العنوان", price: "السعر", stock: "المخزون", onSale: "عليه تخفيض", status: "الحالة" },
  close: "إغلاق",
};

export const PRODUCT_ADMIN_STRINGS = { en, ar };

type Nested = "statuses" | "stockLevels" | "priceModes" | "stockModes" | "statusHint" | "issues" | "fields";
/** Every text can be replaced. Nested groups (statuses, issues and so on) merge key by key. */
export type StoreProductsAdminLabels = Partial<Omit<ProductAdminStrings, Nested>> & { [K in Nested]?: Partial<ProductAdminStrings[K]> };

/** The strings for a locale with the host's overrides merged in; nested groups merge key by key. */
export function productAdminStrings(locale: string, labels?: StoreProductsAdminLabels): ProductAdminStrings {
  const base = PRODUCT_ADMIN_STRINGS[locale.startsWith("ar") ? "ar" : "en"];
  const t = { ...base, ...labels } as ProductAdminStrings;
  for (const k of ["statuses", "stockLevels", "priceModes", "stockModes", "statusHint", "issues", "fields"] as const) (t as Record<string, unknown>)[k] = { ...base[k], ...labels?.[k] };
  return t;
}

/** The strings for the current Nasaq locale, reactive. */
export function useProductAdminStrings(labels: () => StoreProductsAdminLabels | undefined) {
  const nq = useNasaq();
  const locale = computed(() => nq.locale.value);
  const t = computed(() => productAdminStrings(locale.value, labels()));
  return { t, locale, n: (v: number) => formatNumber(v, locale.value) };
}

/** What a save callback resolves. Resolve `{ error }` to keep the form open and show the message. */
export type ProductAdminResult = void | { error?: string };
export const productFailMessage = (e: unknown, fallback: string) => (e instanceof Error && e.message ? e.message : fallback);
