import type { Rarity } from "./gamification-logic";

// Words for the kit, English and Arabic. Some are functions so the number sits where the language wants it.
export const STRINGS = {
  en: {
    rarity: { common: "Common", uncommon: "Uncommon", rare: "Rare", epic: "Epic", legendary: "Legendary" },
    earned: "Earned",
    inProgress: "In progress",
    locked: "Locked",
    all: "All",
    secret: "Secret achievement",
    secretHint: "Keep going to discover it.",
    earnedOn: (d: string) => `Earned ${d}`,
    progressOf: (a: string, b: string) => `${a} of ${b}`,
    xpReward: (n: string) => `+${n} XP`,
    badgesFilter: "Filter achievements",
    noMatches: "Nothing here yet",
    noMatchesHint: "Achievements that match this filter show up here.",
    level: (n: string) => `Level ${n}`,
    xpOf: (a: string, b: string) => `${a} / ${b} XP`,
    xpToNext: (n: string, level: string) => `${n} XP to level ${level}`,
    period: "Period",
    you: "You",
    rank: "Rank",
    yourRank: "Your rank",
    ranked: (n: string) => `Rank ${n}`,
    movedUp: (n: string) => `Up ${n}`,
    movedDown: (n: string) => `Down ${n}`,
    same: "No change",
    isNew: "New",
    score: "Score",
    emptyBoard: "No one on the board yet",
    emptyBoardHint: "Scores show up here once people start earning them.",
    leaderboard: "Leaderboard",
    streak: "Day streak",
    days: (n: number) => (n === 1 ? "day" : "days"),
    longest: (n: string) => `Longest ${n}`,
    atRisk: "Do something today to keep it going",
    prevMonth: "Previous month",
    nextMonth: "Next month",
    activeDay: "Active",
    today: "Today",
    reward: "Reward",
    claim: "Claim",
    claiming: "Claiming",
    claimed: "Owned",
    needMore: (n: string) => `${n} more needed`,
    cost: (n: string, unit: string) => `${n} ${unit}`,
    points: "points",
    unlocked: "Achievement unlocked",
    dismiss: "Dismiss",
    view: "View",
    failed: "Could not claim. Try again.",
  },
  ar: {
    rarity: { common: "شائع", uncommon: "غير شائع", rare: "نادر", epic: "ملحمي", legendary: "أسطوري" },
    earned: "مُكتسب",
    inProgress: "قيد التقدّم",
    locked: "مقفل",
    all: "الكل",
    secret: "إنجاز سري",
    secretHint: "واصل التقدّم لتكتشفه.",
    earnedOn: (d: string) => `اكتُسب ${d}`,
    progressOf: (a: string, b: string) => `${a} من ${b}`,
    xpReward: (n: string) => `+${n} نقطة خبرة`,
    badgesFilter: "تصفية الإنجازات",
    noMatches: "لا شيء هنا بعد",
    noMatchesHint: "تظهر هنا الإنجازات المطابقة لهذه التصفية.",
    level: (n: string) => `المستوى ${n}`,
    xpOf: (a: string, b: string) => `${a} / ${b} نقطة خبرة`,
    xpToNext: (n: string, level: string) => `${n} نقطة خبرة للمستوى ${level}`,
    period: "الفترة",
    you: "أنت",
    rank: "الترتيب",
    yourRank: "ترتيبك",
    ranked: (n: string) => `المركز ${n}`,
    movedUp: (n: string) => `صعود ${n}`,
    movedDown: (n: string) => `هبوط ${n}`,
    same: "بلا تغيير",
    isNew: "جديد",
    score: "النقاط",
    emptyBoard: "لا أحد في القائمة بعد",
    emptyBoardHint: "تظهر النقاط هنا عندما يبدأ الناس بكسبها.",
    leaderboard: "لوحة المتصدّرين",
    streak: "أيام متتالية",
    days: (n: number) => (n === 1 ? "يوم" : n === 2 ? "يومان" : n >= 3 && n <= 10 ? "أيام" : "يومًا"),
    longest: (n: string) => `الأطول ${n}`,
    atRisk: "أنجز شيئًا اليوم لتحافظ على السلسلة",
    prevMonth: "الشهر السابق",
    nextMonth: "الشهر التالي",
    activeDay: "نشِط",
    today: "اليوم",
    reward: "مكافأة",
    claim: "استلام",
    claiming: "جارٍ الاستلام",
    claimed: "مملوكة",
    needMore: (n: string) => `يلزم ${n} إضافية`,
    cost: (n: string, unit: string) => `${n} ${unit}`,
    points: "نقطة",
    unlocked: "تم فتح إنجاز",
    dismiss: "إغلاق",
    view: "عرض",
    failed: "تعذّر الاستلام. حاول مرة أخرى.",
  },
};

export type GamificationLabels = (typeof STRINGS)["en"];

/** Rarity is shown as a word too, never as colour alone. Tokens only: epic uses the violet tag hue, legendary the accent. */
export const RARITY_STYLE: Record<Rarity, { ring: string; soft: string; text: string }> = {
  common: { ring: "border-nq-line-strong", soft: "bg-secondary", text: "text-muted-foreground" },
  uncommon: { ring: "border-nq-success", soft: "bg-nq-success-soft", text: "text-nq-success-text" },
  rare: { ring: "border-nq-info", soft: "bg-nq-info-soft", text: "text-nq-info-text" },
  epic: { ring: "border-[var(--nq-tag-violet)]", soft: "bg-[var(--nq-tag-violet-soft)]", text: "text-[var(--nq-tag-violet)]" },
  legendary: { ring: "border-nq-accent", soft: "bg-nq-accent/15", text: "text-nq-accent-text" },
};
