// The English and Arabic text of the report filter bar, saved views, sheet and export menu (the React STRINGS table).
export const REPORT_FILTER_STRINGS = {
  en: {
    filters: "Report filters",
    reset: "Reset filters",
    active: (n: number) => (n === 1 ? "1 filter applied" : `${n} filters applied`),
    all: "All",
    selected: (n: number) => `${n} selected`,
    clear: "Clear",
    removeFilter: (name: string) => `Remove filter ${name}`,
    views: "Saved views",
    noViews: "No saved views yet. Set the filters you use often and save them.",
    saveView: "Save view",
    saveAsNew: "Save as new view",
    saveTitle: "Save this view",
    saveHelp: "Stores the period and filters as they are now.",
    renameTitle: "Rename view",
    nameLabel: "Name",
    namePlaceholder: "Weekly review",
    nameInvalid: "Enter a name of up to 60 characters.",
    save: "Save",
    cancel: "Cancel",
    saving: "Saving",
    failed: "That did not save. Try again.",
    apply: "Open view",
    rename: "Rename",
    update: "Update with current filters",
    modified: "Changed",
    share: "Share",
    unshare: "Stop sharing",
    copyLink: "Copy link",
    linkCopied: "Link copied",
    shared: "Shared",
    shareOn: "Anyone with the link can open this view.",
    remove: "Delete",
    deleteTitle: (name: string) => `Delete "${name}"?`,
    deleteBody: "The view is removed for everyone it is shared with. The report itself is not changed.",
    more: (name: string) => `Actions for ${name}`,
    export: "Export",
    print: "Print or save as PDF",
    markdown: "Download Markdown",
    copyMarkdown: "Copy as Markdown",
    copied: "Copied",
    generated: "Generated",
    reportFilters: "Filters",
  },
  ar: {
    filters: "مرشّحات التقرير",
    reset: "إعادة ضبط المرشّحات",
    active: (n: number) => (n === 1 ? "مرشّح واحد مطبّق" : n === 2 ? "مرشّحان مطبّقان" : `${n} مرشّحات مطبّقة`),
    all: "الكل",
    selected: (n: number) => `${n} محدّد`,
    clear: "مسح",
    removeFilter: (name: string) => `إزالة المرشّح ${name}`,
    views: "العروض المحفوظة",
    noViews: "لا توجد عروض محفوظة بعد. اضبط المرشّحات التي تستخدمها كثيرًا واحفظها.",
    saveView: "حفظ العرض",
    saveAsNew: "حفظ كعرض جديد",
    saveTitle: "حفظ هذا العرض",
    saveHelp: "يحفظ الفترة والمرشّحات كما هي الآن.",
    renameTitle: "إعادة تسمية العرض",
    nameLabel: "الاسم",
    namePlaceholder: "المراجعة الأسبوعية",
    nameInvalid: "أدخل اسمًا لا يزيد عن 60 حرفًا.",
    save: "حفظ",
    cancel: "إلغاء",
    saving: "جارٍ الحفظ",
    failed: "تعذّر الحفظ. حاول مرة أخرى.",
    apply: "فتح العرض",
    rename: "إعادة تسمية",
    update: "تحديث بالمرشّحات الحالية",
    modified: "معدَّل",
    share: "مشاركة",
    unshare: "إيقاف المشاركة",
    copyLink: "نسخ الرابط",
    linkCopied: "تم نسخ الرابط",
    shared: "مشترك",
    shareOn: "يمكن لأي شخص لديه الرابط فتح هذا العرض.",
    remove: "حذف",
    deleteTitle: (name: string) => `حذف «${name}»؟`,
    deleteBody: "يُزال العرض لكل من شاركته معه. لا يتغير التقرير نفسه.",
    more: (name: string) => `إجراءات ${name}`,
    export: "تصدير",
    print: "طباعة أو حفظ PDF",
    markdown: "تنزيل Markdown",
    copyMarkdown: "نسخ بصيغة Markdown",
    copied: "تم النسخ",
    generated: "أُنشئ في",
    reportFilters: "المرشّحات",
  },
};

export type ReportFilterBarLabels = typeof REPORT_FILTER_STRINGS.en;

export type ReportExportFormat = "pdf" | "markdown" | "copy";
