"use client";

import { useOptionalNasaq } from "../../provider/nasaq-provider";

const STRINGS = {
  en: {
    table: "Content table",
    gridHint: "Arrow keys move between cells. Enter edits, Escape cancels, Delete clears.",
    search: "Search rows",
    searchPlaceholder: "Search rows",
    addRow: "Add row",
    addColumn: "Add column",
    editColumn: "Edit column",
    deleteColumn: "Delete column",
    columnName: "Column name",
    columnType: "Type",
    options: "Options",
    optionsHint: "One per line or separated by commas.",
    required: "Required",
    saveColumn: "Save column",
    cancel: "Cancel",
    typeText: "Text",
    typeNumber: "Number",
    typeSelect: "Select",
    typeDate: "Date",
    typeCheckbox: "Checkbox",
    typeUrl: "Link",
    typeTags: "Tags",
    sortAsc: "Sort ascending",
    sortDesc: "Sort descending",
    clearSort: "Clear sort",
    moveLeft: "Move left",
    moveRight: "Move right",
    columnMenu: (name: string) => `${name} column options`,
    rowActions: (n: string) => `Actions for row ${n}`,
    insertAbove: "Insert row above",
    insertBelow: "Insert row below",
    duplicate: "Duplicate row",
    moveUp: "Move up",
    moveDown: "Move down",
    delete: "Delete row",
    deleteSelected: (n: string) => `Delete ${n} selected`,
    selected: (n: string) => `${n} selected`,
    selectAll: "Select all rows",
    selectRow: (n: string) => `Select row ${n}`,
    clearSelection: "Clear selection",
    undo: "Undo",
    redo: "Redo",
    exportCsv: "Export CSV",
    save: "Save",
    saving: "Saving",
    saved: "Saved",
    unsaved: "Unsaved changes",
    saveFailed: "Could not save",
    issues: (n: string) => `${n} to fix`,
    issueRequired: "Required",
    issueUrl: "Enter a full link that starts with https://",
    empty: "No rows yet",
    emptyHint: "Add the first row to start your content table.",
    noMatches: "No rows match your search",
    clearSearch: "Clear search",
    rowCount: (n: string) => `${n} rows`,
    rowCountOf: (n: string, total: string) => `${n} of ${total} rows`,
    choose: "Choose an option",
    noOptions: "No options yet. Edit the column to add some.",
    clear: "Clear",
    open: "Open link",
    sum: "Sum",
    filled: (n: string, total: string) => `${n} of ${total} filled`,
    checked: (n: string) => `${n} checked`,
    announceRowAdded: "Row added",
    announceRowsDeleted: (n: string) => `${n} rows deleted`,
    announceColumnAdded: (name: string) => `Column ${name} added`,
    announceColumnDeleted: (name: string) => `Column ${name} deleted`,
    announceSorted: (name: string, dir: string) => `Sorted by ${name}, ${dir}`,
    ascending: "ascending",
    descending: "descending",
    reorderOff: "Clear the search and sorting to move rows.",
  },
  ar: {
    table: "جدول المحتوى",
    gridHint: "مفاتيح الأسهم للتنقل بين الخلايا. Enter للتحرير وEscape للإلغاء وDelete للمسح.",
    search: "بحث في الصفوف",
    searchPlaceholder: "ابحث في الصفوف",
    addRow: "إضافة صف",
    addColumn: "إضافة عمود",
    editColumn: "تحرير العمود",
    deleteColumn: "حذف العمود",
    columnName: "اسم العمود",
    columnType: "النوع",
    options: "الخيارات",
    optionsHint: "خيار في كل سطر أو مفصولة بفواصل.",
    required: "مطلوب",
    saveColumn: "حفظ العمود",
    cancel: "إلغاء",
    typeText: "نص",
    typeNumber: "رقم",
    typeSelect: "اختيار",
    typeDate: "تاريخ",
    typeCheckbox: "خانة اختيار",
    typeUrl: "رابط",
    typeTags: "وسوم",
    sortAsc: "ترتيب تصاعدي",
    sortDesc: "ترتيب تنازلي",
    clearSort: "إلغاء الترتيب",
    moveLeft: "نقل إلى اليسار",
    moveRight: "نقل إلى اليمين",
    columnMenu: (name: string) => `خيارات عمود ${name}`,
    rowActions: (n: string) => `إجراءات الصف ${n}`,
    insertAbove: "إدراج صف أعلاه",
    insertBelow: "إدراج صف أدناه",
    duplicate: "تكرار الصف",
    moveUp: "نقل لأعلى",
    moveDown: "نقل لأسفل",
    delete: "حذف الصف",
    deleteSelected: (n: string) => `حذف ${n} محدد`,
    selected: (n: string) => `${n} محدد`,
    selectAll: "تحديد كل الصفوف",
    selectRow: (n: string) => `تحديد الصف ${n}`,
    clearSelection: "إلغاء التحديد",
    undo: "تراجع",
    redo: "إعادة",
    exportCsv: "تصدير CSV",
    save: "حفظ",
    saving: "جارٍ الحفظ",
    saved: "تم الحفظ",
    unsaved: "تغييرات غير محفوظة",
    saveFailed: "تعذر الحفظ",
    issues: (n: string) => `${n} للإصلاح`,
    issueRequired: "مطلوب",
    issueUrl: "أدخل رابطًا كاملًا يبدأ بـ https://",
    empty: "لا توجد صفوف بعد",
    emptyHint: "أضف أول صف لبدء جدول المحتوى.",
    noMatches: "لا توجد صفوف تطابق بحثك",
    clearSearch: "مسح البحث",
    rowCount: (n: string) => `${n} صفوف`,
    rowCountOf: (n: string, total: string) => `${n} من ${total} صفوف`,
    choose: "اختر خيارًا",
    noOptions: "لا توجد خيارات بعد. حرّر العمود لإضافتها.",
    clear: "مسح",
    open: "فتح الرابط",
    sum: "المجموع",
    filled: (n: string, total: string) => `${n} من ${total} معبأة`,
    checked: (n: string) => `${n} محددة`,
    announceRowAdded: "أُضيف صف",
    announceRowsDeleted: (n: string) => `حُذفت ${n} صفوف`,
    announceColumnAdded: (name: string) => `أُضيف العمود ${name}`,
    announceColumnDeleted: (name: string) => `حُذف العمود ${name}`,
    announceSorted: (name: string, dir: string) => `مرتب حسب ${name}، ${dir}`,
    ascending: "تصاعديًا",
    descending: "تنازليًا",
    reorderOff: "امسح البحث والترتيب لنقل الصفوف.",
  },
};

export type ContentTableText = typeof STRINGS.en;
export type ContentTableLabels = Partial<ContentTableText>;

export function useContentTableStrings(labels?: ContentTableLabels) {
  const locale = useOptionalNasaq()?.locale ?? "en";
  return { locale, t: { ...STRINGS[locale.startsWith("ar") ? "ar" : "en"], ...labels } as ContentTableText };
}
