export const BRAND_STRINGS = {
  en: {
    guidelines: "Brand guidelines",
    sections: "Sections",
    logo: "Logo",
    logoIntro: "The mark is drawn from the brand's own specification. Use these files as they are.",
    color: "Colour",
    colorIntro: "Copy a value and use it exactly. Do not adjust a brand colour to suit a layout.",
    typography: "Typography",
    typographyIntro: "The typefaces the brand is set in. Font files are not shared here. Get them from their licence holder.",
    usage: "Usage",
    usageIntro: "How the marks and colours are and are not used.",
    social: "Social cards",
    socialIntro: "What a link to the product looks like when it is shared.",
    download: "Download",
    downloadFor: "Download {name}",
    onLight: "Mark on a light ground",
    onDark: "Mark on a dark ground",
    copy: "Copy {value}",
    copied: "Copied {value}",
    sample: "Aa",
    licence: "Licence",
    weights: "Weights",
    do: "Do",
    dont: "Don't",
    role: "Role",
    "brand-light": "Brand, light",
    "brand-dark": "Brand, dark",
    "action-light": "Action, light",
    "action-dark": "Action, dark",
    accent: "Accent",
    noSections: "Nothing to show yet.",
    defaultDos: [
      { id: "d1", title: "Use the mark as supplied", description: "Take the file from this page. It is generated from the brand's specification." },
      { id: "d2", title: "Keep clear space", description: "Leave at least the width of one cube on every side." },
      { id: "d3", title: "Use the colour pairs listed", description: "The dark-ground colours are for dark grounds, the light ones for light." },
    ],
    defaultDonts: [
      { id: "n1", title: "Do not recolour the mark", description: "Its body and its accent cube keep their colours on every ground." },
      { id: "n2", title: "Do not mirror, stretch or redraw it", description: "It does not flip in right-to-left layouts." },
      { id: "n3", title: "Do not swap in a generic icon", description: "If the mark is unavailable, use the brand name as text." },
      { id: "n4", title: "Do not invent colours", description: "Use only the palette on this page." },
    ],
  },
  ar: {
    guidelines: "دليل الهوية",
    sections: "الأقسام",
    logo: "الشعار",
    logoIntro: "الشعار مرسوم من مواصفات العلامة نفسها. استخدم هذه الملفات كما هي.",
    color: "الألوان",
    colorIntro: "انسخ القيمة واستخدمها كما هي. لا تعدّل لون العلامة ليناسب التصميم.",
    typography: "الخطوط",
    typographyIntro: "الخطوط التي تُكتب بها العلامة. ملفات الخطوط غير متاحة هنا. احصل عليها من صاحب الترخيص.",
    usage: "الاستخدام",
    usageIntro: "كيف تُستخدم الشعارات والألوان وكيف لا تُستخدم.",
    social: "بطاقات المشاركة",
    socialIntro: "كيف يبدو رابط المنتج عند مشاركته.",
    download: "تنزيل",
    downloadFor: "تنزيل {name}",
    onLight: "الشعار على خلفية فاتحة",
    onDark: "الشعار على خلفية داكنة",
    copy: "نسخ {value}",
    copied: "تم نسخ {value}",
    sample: "أبج",
    licence: "الترخيص",
    weights: "الأوزان",
    do: "افعل",
    dont: "لا تفعل",
    role: "الدور",
    "brand-light": "لون العلامة، فاتح",
    "brand-dark": "لون العلامة، داكن",
    "action-light": "لون الإجراء، فاتح",
    "action-dark": "لون الإجراء، داكن",
    accent: "اللون المميّز",
    noSections: "لا شيء للعرض بعد.",
    defaultDos: [
      { id: "d1", title: "استخدم الشعار كما هو", description: "خذ الملف من هذه الصفحة. فهو مولَّد من مواصفات العلامة." },
      { id: "d2", title: "اترك مساحة حرة", description: "اترك عرض مكعب واحد على الأقل من كل جانب." },
      { id: "d3", title: "استخدم أزواج الألوان المذكورة", description: "ألوان الخلفية الداكنة للخلفيات الداكنة، والفاتحة للفاتحة." },
    ],
    defaultDonts: [
      { id: "n1", title: "لا تغيّر ألوان الشعار", description: "يحتفظ جسمه ومكعبه المميّز بلونيهما على كل خلفية." },
      { id: "n2", title: "لا تعكسه ولا تمطّه ولا تعِد رسمه", description: "لا ينقلب في التخطيطات من اليمين إلى اليسار." },
      { id: "n3", title: "لا تستبدله بأيقونة عامة", description: "إن لم يتوفر الشعار فاستخدم اسم العلامة نصًا." },
      { id: "n4", title: "لا تخترع ألوانًا", description: "استخدم اللوحة الواردة في هذه الصفحة فقط." },
    ],
  },
};

export type BrandStrings = (typeof BRAND_STRINGS)["en"];

export interface BrandRule {
  id: string;
  title: string;
  description?: string;
}
export type BrandGuidelinesLabels = Partial<Omit<BrandStrings, "defaultDos" | "defaultDonts">> & { defaultDos?: BrandRule[]; defaultDonts?: BrandRule[] };
