import type { VitalRating, WebVitalId } from "../web-vital-gauge";
import type { SeoSeverity } from "./seo-pages-math";

export const SEO_PAGES_STRINGS = {
  en: {
    pagesTitle: "Pages",
    pagesDescription: "Every crawled page with its SEO score, open issues, index status and Core Web Vitals.",
    page: "Page",
    score: "Score",
    issues: "Issues",
    index: "Index status",
    vitals: "Vitals",
    crawled: "Last crawled",
    filter: "Filter pages…",
    empty: "No pages crawled yet",
    noIssues: "No issues",
    indexed: "Indexed",
    "not-indexed": "Not indexed",
    blocked: "Blocked",
    pending: "Pending",
    viewIssues: "View issues",
    recrawl: "Crawl again",
    requestIndexing: "Request indexing",
    openPage: "Open page",
    actionsFailed: "Could not complete this. Try again.",
    errors: (n: number) => (n === 1 ? "1 error" : `${n} errors`),
    warnings: (n: number) => (n === 1 ? "1 warning" : `${n} warnings`),
    notices: (n: number) => (n === 1 ? "1 notice" : `${n} notices`),
    good: "Good",
    fair: "Fair",
    poor: "Poor",
    scoreOf: (n: number) => `SEO score ${n} of 100`,
    checklistTitle: "Issues to fix",
    checklistDescription: (n: number) => (n === 0 ? "Everything on this page is fixed." : n === 1 ? "1 issue is open." : `${n} issues are open.`),
    severity: { error: "Error", warning: "Warning", info: "Notice" } as Record<SeoSeverity, string>,
    fixed: "Fixed",
    markFixed: (title: string) => `Mark "${title}" as fixed`,
    why: "Why it matters",
    howToFix: "How to fix",
    allFixed: "Nothing to fix",
    allFixedBody: "This page has no open issues.",
    vital: { LCP: "LCP", INP: "INP", CLS: "CLS", FCP: "FCP", TTFB: "TTFB" } as Record<WebVitalId, string>,
    rating: { good: "good", "needs-improvement": "needs improvement", poor: "poor" } as Record<VitalRating, string>,
    noVitals: "No field data",
  },
  ar: {
    pagesTitle: "الصفحات",
    pagesDescription: "كل صفحة تم زحفها مع درجة SEO والمشكلات المفتوحة وحالة الفهرسة ومؤشرات الويب الأساسية.",
    page: "الصفحة",
    score: "الدرجة",
    issues: "المشكلات",
    index: "حالة الفهرسة",
    vitals: "المؤشرات",
    crawled: "آخر زحف",
    filter: "تصفية الصفحات…",
    empty: "لم يتم زحف أي صفحة بعد",
    noIssues: "لا مشكلات",
    indexed: "مفهرسة",
    "not-indexed": "غير مفهرسة",
    blocked: "محجوبة",
    pending: "قيد الانتظار",
    viewIssues: "عرض المشكلات",
    recrawl: "زحف مرة أخرى",
    requestIndexing: "طلب الفهرسة",
    openPage: "فتح الصفحة",
    actionsFailed: "تعذّر إكمال هذا. حاول مرة أخرى.",
    errors: (n: number) => (n === 1 ? "خطأ واحد" : `${n} أخطاء`),
    warnings: (n: number) => (n === 1 ? "تحذير واحد" : `${n} تحذيرات`),
    notices: (n: number) => (n === 1 ? "ملاحظة واحدة" : `${n} ملاحظات`),
    good: "جيدة",
    fair: "مقبولة",
    poor: "ضعيفة",
    scoreOf: (n: number) => `درجة SEO ${n} من 100`,
    checklistTitle: "مشكلات للإصلاح",
    checklistDescription: (n: number) => (n === 0 ? "تم إصلاح كل شيء في هذه الصفحة." : n === 1 ? "مشكلة واحدة مفتوحة." : `${n} مشكلات مفتوحة.`),
    severity: { error: "خطأ", warning: "تحذير", info: "ملاحظة" } as Record<SeoSeverity, string>,
    fixed: "تم الإصلاح",
    markFixed: (title: string) => `تعليم «${title}» كمُصلَح`,
    why: "لماذا يهم",
    howToFix: "كيف تصلحها",
    allFixed: "لا شيء للإصلاح",
    allFixedBody: "لا توجد مشكلات مفتوحة في هذه الصفحة.",
    vital: { LCP: "LCP", INP: "INP", CLS: "CLS", FCP: "FCP", TTFB: "TTFB" } as Record<WebVitalId, string>,
    rating: { good: "جيد", "needs-improvement": "يحتاج تحسينًا", poor: "ضعيف" } as Record<VitalRating, string>,
    noVitals: "لا بيانات ميدانية",
  },
};

export type SeoPagesLabels = typeof SEO_PAGES_STRINGS.en;
