/** Strings for the project-level tabs added after the first cut: memory, vault, GitHub, activity and the settings pages. */
export const EXTRA = {
  en: {
    tabs: { activity: "Activity", memory: "Memory", vault: "Vault", github: "GitHub" },
    // Memory
    memoryTitle: "Project memory",
    memoryHint: "Facts and decisions worth remembering about this project.",
    memorySearch: "Search memory",
    memoryAllKinds: "All",
    memoryKinds: { fact: "Fact", decision: "Decision" },
    memoryKindsPlural: { fact: "Facts", decision: "Decisions" },
    memoryAdd: "Remember something",
    memoryEditTitle: "Edit memory",
    memoryAddTitle: "Remember something",
    memoryText: "What to remember",
    memoryTags: "Tags",
    memoryTagsHint: "Separate with commas.",
    memoryKind: "Kind",
    memorySource: "Source",
    memorySourceHint: "A call, a document, a person.",
    memoryEdit: "Edit",
    memoryForget: "Forget",
    memoryForgetTitle: "Forget this memory?",
    memoryForgetBody: "It will no longer be recalled for this project. This cannot be undone.",
    memoryEmpty: "Nothing remembered yet",
    memoryEmptyHint: "Write down decisions and facts so the next person does not have to ask.",
    memoryNoMatch: "No memories match",
    memoryNoMatchHint: "Try another word or clear the tag filter.",
    memoryClear: "Clear filters",
    memoryCount: (n: string) => `${n} remembered`,
    memoryFrom: "From",
    memoryTagFilter: "Filter by tag",
    memoryKindFilter: "Filter by kind",
    // Vault
    vaultTitle: "Project secrets",
    vaultDescription: "Keys and passwords for this project. Values stay hidden until someone reveals them, and every reveal is logged.",
    envTitle: "Environment variables",
    envDescription: "Configuration for this project's environments.",
    // GitHub
    ghRepo: "Repository",
    ghConnectTitle: "Connect a repository",
    ghConnectHint: "Pick the repository this project ships from to see its commits, pull requests and runs here.",
    ghNotConnected: "No repository connected",
    ghNotConnectedHint: "Connect a repository to follow its commits, pull requests and workflow runs.",
    ghChange: "Change repository",
    ghDisconnect: "Disconnect",
    // Activity
    feedTitle: "Project activity",
    feedKind: "Type",
    feedPerson: "Person",
    feedAll: "All",
    feedAllPeople: "Everyone",
    feedKinds: { issue: "Issues", comment: "Comments", status: "Status changes", member: "Members", file: "Files", code: "Code", time: "Time", other: "Other" },
    feedEmpty: "No activity yet",
    feedEmptyHint: "Changes to issues, files and members show up here.",
    feedNoMatch: "Nothing matches these filters",
    feedNoMatchHint: "Change the type or the person.",
    feedClear: "Clear filters",
    feedToday: "Today",
    feedYesterday: "Yesterday",
    feedCount: (n: string) => `${n} events`,
    // Settings
    settingsTitle: "Project settings",
    groupProject: "Project",
    groupTeam: "Team",
    groupConnections: "Connections",
    pageGeneral: "General",
    pageGeneralHint: "Name, key, client, dates and status.",
    pageMembers: "Members and roles",
    pageMembersHint: "Who can work on this project.",
    pageWorkflow: "Labels and statuses",
    pageWorkflowHint: "The stages issues move through and the labels they carry.",
    pageIntegrations: "Integrations",
    pageIntegrationsHint: "Connect the tools this project uses.",
    pageBudget: "Budget",
    pageBudgetHint: "The total, and what has been spent so far.",
    pageDanger: "Danger zone",
    pageDangerHint: "Archive or delete this project.",
    key: "Key",
    keyHint: "Prefix of issue keys. It cannot change once issues exist.",
    connected: "Connected",
    notConnected: "Not connected",
    connect: "Connect",
    disconnect: "Disconnect",
    budgetSpent: "Spent so far",
    budgetSaved: "Budget saved",
    currency: "Currency",
    archiveTitle: "Archive this project",
    archiveBody: "Hides it from active lists and makes it read-only. You can restore it later.",
    archiveAction: "Archive project",
    archiveConfirmTitle: "Archive this project?",
    archiveConfirmBody: "Nobody will be able to change issues until it is restored.",
    deleteTitle: "Delete this project",
    deleteBody: "Permanently removes the project with its issues, files and history.",
    deleteAction: "Delete project",
    deleteConfirmTitle: "Delete this project?",
    deleteConfirmBody: "This cannot be undone. Type the project key to confirm.",
    deleteConfirmField: "Project key",
    confirm: "Confirm",
  },
  ar: {
    tabs: { activity: "النشاط", memory: "الذاكرة", vault: "الخزنة", github: "GitHub" },
    memoryTitle: "ذاكرة المشروع",
    memoryHint: "حقائق وقرارات تستحق أن تُحفظ عن هذا المشروع.",
    memorySearch: "ابحث في الذاكرة",
    memoryAllKinds: "الكل",
    memoryKinds: { fact: "حقيقة", decision: "قرار" },
    memoryKindsPlural: { fact: "حقائق", decision: "قرارات" },
    memoryAdd: "تذكّر شيئًا",
    memoryEditTitle: "تعديل الذاكرة",
    memoryAddTitle: "تذكّر شيئًا",
    memoryText: "ما الذي تريد تذكره",
    memoryTags: "الوسوم",
    memoryTagsHint: "افصل بينها بفواصل.",
    memoryKind: "النوع",
    memorySource: "المصدر",
    memorySourceHint: "مكالمة أو مستند أو شخص.",
    memoryEdit: "تعديل",
    memoryForget: "انسَ",
    memoryForgetTitle: "هل تنسى هذه الذاكرة؟",
    memoryForgetBody: "لن تُستدعى بعد الآن لهذا المشروع. لا يمكن التراجع.",
    memoryEmpty: "لم يُحفظ شيء بعد",
    memoryEmptyHint: "دوّن القرارات والحقائق كي لا يضطر التالي إلى السؤال.",
    memoryNoMatch: "لا ذكريات مطابقة",
    memoryNoMatchHint: "جرّب كلمة أخرى أو امسح تصفية الوسوم.",
    memoryClear: "مسح التصفية",
    memoryCount: (n: string) => `${n} محفوظة`,
    memoryFrom: "من",
    memoryTagFilter: "تصفية بالوسم",
    memoryKindFilter: "تصفية بالنوع",
    vaultTitle: "أسرار المشروع",
    vaultDescription: "مفاتيح وكلمات مرور هذا المشروع. تبقى القيم مخفية حتى يكشفها أحد، وكل كشف يُسجَّل.",
    envTitle: "متغيرات البيئة",
    envDescription: "إعدادات بيئات هذا المشروع.",
    ghRepo: "المستودع",
    ghConnectTitle: "اربط مستودعًا",
    ghConnectHint: "اختر المستودع الذي يُنشر منه هذا المشروع لترى الإيداعات وطلبات الدمج والتشغيلات هنا.",
    ghNotConnected: "لا مستودع مربوطًا",
    ghNotConnectedHint: "اربط مستودعًا لمتابعة إيداعاته وطلبات الدمج وتشغيلات المسارات.",
    ghChange: "تغيير المستودع",
    ghDisconnect: "فصل",
    feedTitle: "نشاط المشروع",
    feedKind: "النوع",
    feedPerson: "الشخص",
    feedAll: "الكل",
    feedAllPeople: "الجميع",
    feedKinds: { issue: "المهام", comment: "التعليقات", status: "تغيّر الحالة", member: "الأعضاء", file: "الملفات", code: "الكود", time: "الوقت", other: "أخرى" },
    feedEmpty: "لا نشاط بعد",
    feedEmptyHint: "تظهر هنا تغييرات المهام والملفات والأعضاء.",
    feedNoMatch: "لا شيء يطابق هذه التصفية",
    feedNoMatchHint: "غيّر النوع أو الشخص.",
    feedClear: "مسح التصفية",
    feedToday: "اليوم",
    feedYesterday: "أمس",
    feedCount: (n: string) => `${n} حدث`,
    settingsTitle: "إعدادات المشروع",
    groupProject: "المشروع",
    groupTeam: "الفريق",
    groupConnections: "الاتصالات",
    pageGeneral: "عام",
    pageGeneralHint: "الاسم والرمز والعميل والتواريخ والحالة.",
    pageMembers: "الأعضاء والأدوار",
    pageMembersHint: "من يمكنه العمل على هذا المشروع.",
    pageWorkflow: "الوسوم والحالات",
    pageWorkflowHint: "المراحل التي تمر بها المهام والوسوم التي تحملها.",
    pageIntegrations: "التكاملات",
    pageIntegrationsHint: "اربط الأدوات التي يستخدمها هذا المشروع.",
    pageBudget: "الميزانية",
    pageBudgetHint: "الإجمالي وما صُرف حتى الآن.",
    pageDanger: "منطقة الخطر",
    pageDangerHint: "أرشفة المشروع أو حذفه.",
    key: "الرمز",
    keyHint: "بادئة مفاتيح المهام. لا يتغير بعد وجود مهام.",
    connected: "مربوط",
    notConnected: "غير مربوط",
    connect: "ربط",
    disconnect: "فصل",
    budgetSpent: "المصروف حتى الآن",
    budgetSaved: "حُفظت الميزانية",
    currency: "العملة",
    archiveTitle: "أرشفة هذا المشروع",
    archiveBody: "يخفيه من القوائم النشطة ويجعله للقراءة فقط. يمكنك استعادته لاحقًا.",
    archiveAction: "أرشفة المشروع",
    archiveConfirmTitle: "هل تؤرشف هذا المشروع؟",
    archiveConfirmBody: "لن يستطيع أحد تغيير المهام حتى تتم استعادته.",
    deleteTitle: "حذف هذا المشروع",
    deleteBody: "يحذف المشروع نهائيًا مع مهامه وملفاته وسجله.",
    deleteAction: "حذف المشروع",
    deleteConfirmTitle: "هل تحذف هذا المشروع؟",
    deleteConfirmBody: "لا يمكن التراجع. اكتب رمز المشروع للتأكيد.",
    deleteConfirmField: "رمز المشروع",
    confirm: "تأكيد",
  },
};

export type ExtraText = (typeof EXTRA)["en"];
