// Built-in English and Arabic strings of the POS register.
export const POS_STRINGS = {
  en: {
    search: "Search or scan",
    searchHint: "Type a name, or scan a barcode and press Enter",
    all: "All",
    noProducts: "No products match",
    noProductsText: "Clear the search or pick another category.",
    left: "left",
    outOfStock: "Out of stock",
    basket: "Basket",
    walkIn: "Walk-in customer",
    emptyBasket: "The basket is empty",
    emptyBasketText: "Tap a product to add it.",
    increase: "Add one",
    decrease: "Remove one",
    remove: "Remove line",
    lineActions: "Line actions",
    clear: "Clear basket",
    subtotal: "Subtotal",
    discount: "Discounts",
    tax: "Tax",
    total: "Total",
    charge: "Charge",
    items: "items",
    sessionOpen: "Register open",
    sessionSince: "since",
    drawer: "Cash drawer",
    closedTitle: "The register is closed",
    closedText: "Count the cash in the drawer and open a session to start selling.",
    openingFloat: "Opening float",
    openRegister: "Open register",
    closeRegister: "Close register",
    closeText: "Count the cash in the drawer. The difference from what the sales say should be there is recorded.",
    floatRow: "Opening float",
    cashSales: "Cash sales",
    cardSales: "Card sales",
    walletSales: "Wallet sales",
    salesCount: "Sales",
    expectedCash: "Expected in drawer",
    countedCash: "Counted cash",
    variance: "Difference",
    exact: "The drawer balances",
    short: "Short",
    over: "Over",
    payTitle: "Take payment",
    payText: "Walk-in sale",
    method: "Payment method",
    cash: "Cash",
    card: "Card",
    wallet: "Wallet",
    tendered: "Cash received",
    exactAmount: "Exact",
    change: "Change due",
    confirm: "Confirm payment",
    cancel: "Cancel",
    saleDone: "Sale complete",
    receiptNo: "Receipt",
    newSale: "New sale",
    paid: "Paid",
    cashier: "Cashier",
    failed: "The payment did not go through. Nothing was charged.",
    qty: "Quantity",
    hold: "Hold sale",
    parked: "Parked sales",
    holdTitle: "Hold this sale",
    holdText: "Park the basket to serve someone else. Resume it any time.",
    note: "Note (optional)",
    notePlaceholder: "A name or a table",
    park: "Park sale",
    noParked: "Nothing on hold",
    noParkedText: "Sales you hold appear here.",
    resume: "Resume",
    discard: "Discard",
    discardTitle: "Discard this parked sale?",
    discardText: "Its items are removed and cannot be brought back.",
    resumeTitle: "Replace the current basket?",
    resumeText: "The basket has items. Resuming replaces them with the parked sale.",
    close: "Close",
    payments: "Payments",
    amount: "Amount",
    addPayment: "Add payment",
    removePayment: "Remove payment",
    remaining: "Remaining",
    overpay: "Card and wallet cannot be more than the remaining amount.",
    paidInFull: "Paid in full",
  },
  ar: {
    search: "بحث أو مسح",
    searchHint: "اكتب اسمًا، أو امسح الباركود واضغط Enter",
    all: "الكل",
    noProducts: "لا توجد منتجات مطابقة",
    noProductsText: "امسح البحث أو اختر فئة أخرى.",
    left: "متبقي",
    outOfStock: "نفد المخزون",
    basket: "السلة",
    walkIn: "عميل عابر",
    emptyBasket: "السلة فارغة",
    emptyBasketText: "المس منتجًا لإضافته.",
    increase: "إضافة واحدة",
    decrease: "إزالة واحدة",
    remove: "حذف البند",
    lineActions: "إجراءات البند",
    clear: "تفريغ السلة",
    subtotal: "المجموع الفرعي",
    discount: "الخصومات",
    tax: "الضريبة",
    total: "الإجمالي",
    charge: "الدفع",
    items: "أصناف",
    sessionOpen: "الصندوق مفتوح",
    sessionSince: "منذ",
    drawer: "درج النقد",
    closedTitle: "الصندوق مغلق",
    closedText: "عُدّ النقد في الدرج وافتح جلسة لبدء البيع.",
    openingFloat: "رصيد الافتتاح",
    openRegister: "فتح الصندوق",
    closeRegister: "إغلاق الصندوق",
    closeText: "عُدّ النقد في الدرج. يُسجَّل الفرق عن المبلغ المتوقع من المبيعات.",
    floatRow: "رصيد الافتتاح",
    cashSales: "مبيعات نقدية",
    cardSales: "مبيعات بالبطاقة",
    walletSales: "مبيعات بالمحفظة",
    salesCount: "عدد المبيعات",
    expectedCash: "المتوقع في الدرج",
    countedCash: "النقد المعدود",
    variance: "الفرق",
    exact: "الدرج متطابق",
    short: "عجز",
    over: "زيادة",
    payTitle: "استلام الدفع",
    payText: "بيع لعميل عابر",
    method: "طريقة الدفع",
    cash: "نقدًا",
    card: "بطاقة",
    wallet: "محفظة",
    tendered: "النقد المستلم",
    exactAmount: "المبلغ بالضبط",
    change: "الباقي للعميل",
    confirm: "تأكيد الدفع",
    cancel: "إلغاء",
    saleDone: "تمت العملية",
    receiptNo: "الإيصال",
    newSale: "عملية جديدة",
    paid: "المدفوع",
    cashier: "الكاشير",
    failed: "لم تتم عملية الدفع. لم يُخصم أي مبلغ.",
    qty: "الكمية",
    hold: "تعليق العملية",
    parked: "المبيعات المعلّقة",
    holdTitle: "تعليق هذه العملية",
    holdText: "علّق السلة لخدمة عميل آخر، واستأنفها في أي وقت.",
    note: "ملاحظة (اختياري)",
    notePlaceholder: "اسم أو رقم طاولة",
    park: "تعليق",
    noParked: "لا توجد عمليات معلّقة",
    noParkedText: "تظهر هنا العمليات التي تعلّقها.",
    resume: "استئناف",
    discard: "حذف",
    discardTitle: "حذف هذه العملية المعلّقة؟",
    discardText: "تُحذف أصنافها ولا يمكن استرجاعها.",
    resumeTitle: "استبدال السلة الحالية؟",
    resumeText: "السلة تحتوي أصنافًا. الاستئناف يستبدلها بالعملية المعلّقة.",
    close: "إغلاق",
    payments: "الدفعات",
    amount: "المبلغ",
    addPayment: "إضافة دفعة",
    removePayment: "حذف الدفعة",
    remaining: "المتبقي",
    overpay: "لا يمكن أن تزيد البطاقة أو المحفظة عن المبلغ المتبقي.",
    paidInFull: "تم السداد بالكامل",
  },
} as const;

export type PosRegisterStrings = { [K in keyof (typeof POS_STRINGS)["en"]]: string };
export type PosRegisterLabels = Partial<PosRegisterStrings>;

import { computed, type ComputedRef } from "vue";
import { useNasaq } from "../../provider";

/** Merged strings for the active locale plus `labels`. */
export function usePosRegisterStrings(labels?: () => PosRegisterLabels | undefined): { t: ComputedRef<PosRegisterStrings>; ar: ComputedRef<boolean>; locale: ComputedRef<string> } {
  const nasaq = useNasaq();
  const ar = computed(() => nasaq.locale.value.startsWith("ar"));
  return {
    t: computed(() => ({ ...POS_STRINGS[ar.value ? "ar" : "en"], ...labels?.() }) as PosRegisterStrings),
    ar,
    locale: computed(() => nasaq.locale.value),
  };
}
