export const ADMIN_STRINGS = {
  en: {
    overview: "Overview",
    dashboard: "Dashboard",
    activity: "Activity",
    people: "People",
    users: "Users",
    roles: "Roles",
    invitations: "Invitations",
    tenants: "Tenants",
    workspaces: "Workspaces",
    plans: "Plans",
    billing: "Billing",
    invoices: "Invoices",
    coupons: "Coupons",
    security: "Security",
    audit: "Audit log",
    sessions: "Sessions",
    apiKeys: "API keys",
    settings: "Settings",
    impersonating: (name: string) => `You are viewing the app as ${name}.`,
    impersonatingHint: "Actions you take count as this user.",
    stop: "Exit impersonation",
    account: "Your account",
    admin: "Admin",
    breadcrumb: "Breadcrumb",
  },
  ar: {
    overview: "نظرة عامة",
    dashboard: "لوحة التحكم",
    activity: "النشاط",
    people: "الأشخاص",
    users: "المستخدمون",
    roles: "الأدوار",
    invitations: "الدعوات",
    tenants: "المستأجرون",
    workspaces: "مساحات العمل",
    plans: "الباقات",
    billing: "الفوترة",
    invoices: "الفواتير",
    coupons: "القسائم",
    security: "الأمان",
    audit: "سجل التدقيق",
    sessions: "الجلسات",
    apiKeys: "مفاتيح API",
    settings: "الإعدادات",
    impersonating: (name: string) => `أنت تتصفح التطبيق بصفة ${name}.`,
    impersonatingHint: "الإجراءات التي تنفذها تُنسب إلى هذا المستخدم.",
    stop: "إنهاء انتحال الصفة",
    account: "حسابك",
    admin: "الإدارة",
    breadcrumb: "مسار التنقل",
  },
};

export const adminStrings = (locale: string) => ADMIN_STRINGS[locale.startsWith("ar") ? "ar" : "en"];

export type AdminAreaLabels = Partial<typeof ADMIN_STRINGS.en>;
