export const STRINGS = {
  en: {
    share: "Share",
    title: "Share",
    description: "Invite people or send a link.",
    invite: "Invite people",
    invitePlaceholder: "Add email addresses",
    inviteHint: "Press Enter or comma after each address.",
    invalidEmail: (v: string) => `${v} is not a valid email address.`,
    sendInvite: "Send invite",
    inviteSent: (n: string) => `Invitation sent to ${n}.`,
    role: "Role",
    people: "People with access",
    owner: "Owner",
    remove: "Remove access",
    removeFor: (name: string) => `Remove ${name}`,
    roleFor: (name: string) => `Role for ${name}`,
    linkAccess: "Link access",
    restricted: "Restricted",
    restrictedHint: "Only people you invite can open the link.",
    anyone: "Anyone with the link",
    anyoneHint: "Anyone who has the link can open it.",
    linkRole: "Link permission",
    expiry: "Link expires",
    never: "Never",
    "1d": "In 1 day",
    "7d": "In 7 days",
    "30d": "In 30 days",
    link: "Link",
    copyLink: "Copy link",
    copied: "Copied",
    nativeShare: "Share via…",
    email: "Email",
    done: "Done",
    close: "Close",
    failed: "Something went wrong. Try again.",
    expiresOn: "Expires",
  },
  ar: {
    share: "مشاركة",
    title: "مشاركة",
    description: "ادعُ أشخاصًا أو أرسل رابطًا.",
    invite: "دعوة أشخاص",
    invitePlaceholder: "أضف عناوين البريد",
    inviteHint: "اضغط Enter أو الفاصلة بعد كل عنوان.",
    invalidEmail: (v: string) => `${v} ليس بريدًا إلكترونيًا صالحًا.`,
    sendInvite: "إرسال الدعوة",
    inviteSent: (n: string) => `أُرسلت الدعوة إلى ${n}.`,
    role: "الدور",
    people: "أشخاص لديهم صلاحية",
    owner: "المالك",
    remove: "إزالة الصلاحية",
    removeFor: (name: string) => `إزالة ${name}`,
    roleFor: (name: string) => `دور ${name}`,
    linkAccess: "الوصول عبر الرابط",
    restricted: "مقيّد",
    restrictedHint: "يفتح الرابط من دعوتهم فقط.",
    anyone: "أي شخص لديه الرابط",
    anyoneHint: "يستطيع فتحه كل من لديه الرابط.",
    linkRole: "صلاحية الرابط",
    expiry: "ينتهي الرابط",
    never: "أبدًا",
    "1d": "بعد يوم",
    "7d": "بعد 7 أيام",
    "30d": "بعد 30 يومًا",
    link: "الرابط",
    copyLink: "نسخ الرابط",
    copied: "تم النسخ",
    nativeShare: "مشاركة عبر…",
    email: "البريد",
    done: "تم",
    close: "إغلاق",
    failed: "حدث خطأ. حاول مرة أخرى.",
    expiresOn: "ينتهي",
  },
};
export const DEFAULT_ROLES: Record<"en" | "ar", { value: string; label: string }[]> = {
  en: [
    { value: "viewer", label: "Can view" },
    { value: "commenter", label: "Can comment" },
    { value: "editor", label: "Can edit" },
  ],
  ar: [
    { value: "viewer", label: "يمكنه العرض" },
    { value: "commenter", label: "يمكنه التعليق" },
    { value: "editor", label: "يمكنه التعديل" },
  ],
};
export const EXPIRIES: ("never" | "1d" | "7d" | "30d")[] = ["never", "1d", "7d", "30d"];
export const strings = (locale: string) => STRINGS[locale.startsWith("ar") ? "ar" : "en"];
export const defaultRoles = (locale: string) => DEFAULT_ROLES[locale.startsWith("ar") ? "ar" : "en"];

export type Strings = typeof STRINGS.en;
export type Labels = Partial<Strings>;
