// Same strings as the React component (packages/web/src/components/contact-merge).

export const CONTACT_MERGE_STRINGS = {
  en: {
    title: "Merge duplicate contacts",
    description: "Choose the record that stays, then pick which value survives wherever the records disagree.",
    survivor: "Keep this record",
    survivorHint: "Its history stays. The others are folded into it and deleted.",
    created: "Created",
    differ: (n: number) => (n === 1 ? "1 field differs" : `${n} fields differ`),
    noneDiffer: "Nothing to decide: the records do not disagree.",
    combineAll: "Combine all",
    combined: "Everything from every record",
    from: "from",
    empty: "Empty",
    same: "Same in every record",
    result: "After the merge",
    resultHint: "This is the contact that will exist.",
    moves: "Moves over",
    identities: "Linked accounts",
    consent: "Consent",
    consentNote: "If any record opted out, the merged contact stays opted out.",
    consentGranted: "Opted in",
    consentDenied: "Opted out",
    consentUnknown: "Not asked",
    merge: (n: number) => `Merge ${n} contacts`,
    cancel: "Cancel",
    confirmTitle: (name: string) => `Merge into ${name}?`,
    confirmBody: (n: number) => `${n === 1 ? "The other record is" : `The other ${n} records are`} deleted. This cannot be undone.`,
    confirm: "Merge",
    failed: "The merge did not go through. Nothing was changed.",
    needTwo: "Pick at least two contacts to merge.",
    fields: { name: "Name", email: "Email", phone: "Phone", company: "Company", jobTitle: "Job title", owner: "Owner", tags: "Tags" } as Record<string, string>,
    channels: { email: "Email", whatsapp: "WhatsApp", phone: "Phone" } as Record<string, string>,
  },
  ar: {
    title: "دمج جهات الاتصال المكرّرة",
    description: "اختر السجل الذي يبقى، ثم اختر القيمة التي تبقى في كل حقل تختلف فيه السجلات.",
    survivor: "أبقِ هذا السجل",
    survivorHint: "يبقى سجله كما هو. تُدمج السجلات الأخرى فيه وتُحذف.",
    created: "أُنشئ",
    differ: (n: number) => (n === 1 ? "حقل واحد مختلف" : `${n} حقول مختلفة`),
    noneDiffer: "لا شيء لتحسمه: السجلات متطابقة.",
    combineAll: "دمج الكل",
    combined: "كل ما في كل السجلات",
    from: "من",
    empty: "فارغ",
    same: "متطابق في كل السجلات",
    result: "بعد الدمج",
    resultHint: "هذه جهة الاتصال التي ستبقى.",
    moves: "ينتقل إليها",
    identities: "الحسابات المرتبطة",
    consent: "الموافقة",
    consentNote: "إذا رفض أي سجل، تبقى جهة الاتصال المدموجة رافضة.",
    consentGranted: "موافق",
    consentDenied: "رافض",
    consentUnknown: "لم يُسأل",
    merge: (n: number) => `دمج ${n} جهات اتصال`,
    cancel: "إلغاء",
    confirmTitle: (name: string) => `الدمج في ${name}؟`,
    confirmBody: (n: number) => `${n === 1 ? "يُحذف السجل الآخر" : `تُحذف السجلات الأخرى وعددها ${n}`}. لا يمكن التراجع.`,
    confirm: "دمج",
    failed: "لم يتم الدمج. لم يتغير شيء.",
    needTwo: "اختر جهتي اتصال على الأقل للدمج.",
    fields: { name: "الاسم", email: "البريد", phone: "الهاتف", company: "الشركة", jobTitle: "المسمى الوظيفي", owner: "المسؤول", tags: "الوسوم" } as Record<string, string>,
    channels: { email: "البريد", whatsapp: "WhatsApp", phone: "الهاتف" } as Record<string, string>,
  },
};

export type ContactMergeLabels = Omit<typeof CONTACT_MERGE_STRINGS.en, "fields" | "channels"> & { fields: Record<string, string>; channels: Record<string, string> };
export type ContactMergeLabelOverrides = Partial<Omit<ContactMergeLabels, "fields" | "channels">> & { fields?: Record<string, string>; channels?: Record<string, string> };
