import type { DomainCheck } from "./format";

export const DOMAINS_STRINGS = {
  en: {
    title: "Custom domains",
    description: "Serve this site from your own domain names.",
    checks: { verified: "Verified", pending: "Waiting for DNS", checking: "Checking", failed: "Check failed" } satisfies Record<DomainCheck, string>,
    summary: (v: number, total: number) => `${v} of ${total} verified`,
    primary: "Primary",
    makePrimary: "Make primary",
    recheck: "Check again",
    remove: "Remove",
    removeTitle: (host: string) => `Remove ${host}?`,
    removeBody: "The site stops answering on this domain. The DNS records at your registrar are not touched.",
    cancel: "Cancel",
    add: "Add domain",
    addLabel: "Domain name",
    addHint: "For example shop.example.com",
    invalid: "Enter a full domain name like shop.example.com.",
    duplicate: "This domain is already added.",
    table: "Custom domains",
    cols: { domain: "Domain", status: "Status", added: "Added" },
    empty: "No custom domains yet. Add one to get started.",
    setup: "Point the domain at us",
    setupBody: "At your DNS provider, add a CNAME record for the domain that points to",
    copyTarget: "Copy the CNAME target",
    actionsFor: (host: string) => `Actions for ${host}`,
    more: (n: number) => `+${n} more`,
    moreLabel: (n: number) => `Show ${n} more domains`,
    genericError: "Something went wrong. Try again.",
    domainsLabel: "Domains",
  },
  ar: {
    title: "النطاقات المخصصة",
    description: "اخدم هذا الموقع من أسماء نطاقاتك الخاصة.",
    checks: { verified: "موثّق", pending: "بانتظار DNS", checking: "قيد الفحص", failed: "فشل الفحص" } satisfies Record<DomainCheck, string>,
    summary: (v: number, total: number) => `${v} من ${total} موثّق`,
    primary: "أساسي",
    makePrimary: "تعيين كأساسي",
    recheck: "فحص مجددًا",
    remove: "إزالة",
    removeTitle: (host: string) => `إزالة ${host}؟`,
    removeBody: "يتوقف الموقع عن الاستجابة على هذا النطاق. لا تتأثر سجلات DNS لدى مسجّل النطاق.",
    cancel: "إلغاء",
    add: "إضافة نطاق",
    addLabel: "اسم النطاق",
    addHint: "مثال: shop.example.com",
    invalid: "أدخل اسم نطاق كاملًا مثل shop.example.com.",
    duplicate: "هذا النطاق مضاف بالفعل.",
    table: "النطاقات المخصصة",
    cols: { domain: "النطاق", status: "الحالة", added: "أضيف" },
    empty: "لا توجد نطاقات مخصصة بعد. أضف نطاقًا للبدء.",
    setup: "وجّه النطاق إلينا",
    setupBody: "لدى مزوّد DNS أضف سجل CNAME للنطاق يشير إلى",
    copyTarget: "نسخ هدف CNAME",
    actionsFor: (host: string) => `إجراءات ${host}`,
    more: (n: number) => `+${n} أخرى`,
    moreLabel: (n: number) => `عرض ${n} نطاقات أخرى`,
    genericError: "حدث خطأ ما. حاول مرة أخرى.",
    domainsLabel: "النطاقات",
  },
};

export type DomainsManagerLabels = Partial<(typeof DOMAINS_STRINGS)["en"]>;
