// English and Arabic strings of the dashboard board (copied from the React component).

export const BOARD_STRINGS = {
  en: {
    region: "Dashboard",
    customise: "Customise",
    customiseHint: "Drag cards to reorder, resize them, pin the ones you always want first.",
    editing: "Editing the dashboard",
    save: "Save",
    saving: "Saving",
    cancel: "Cancel",
    reset: "Reset to default",
    add: "Add widget",
    addTitle: "Add a widget",
    addBody: "Pick a widget to add to the end of the dashboard.",
    alreadyOnBoard: "Already on the dashboard",
    close: "Close",
    saveFailed: "Could not save the dashboard. Your changes are still here, try again.",
    dragHandle: (t: string) => `Drag ${t} to reorder`,
    sortable: "draggable card",
    more: (t: string) => `Actions for ${t}`,
    pinned: "Pinned",
    pin: "Pin to the front",
    unpin: "Unpin",
    wider: "Wider",
    narrower: "Narrower",
    taller: "Taller",
    shorter: "Shorter",
    earlier: "Move earlier",
    later: "Move later",
    settings: "Settings",
    remove: "Remove",
    size: (c: number, r: number) => `${c} by ${r}`,
    sizeLabel: "Size in columns by rows",
    emptyTitle: "This dashboard is empty",
    emptyBody: "Add widgets to see your numbers here.",
    settingsTitle: (t: string) => `${t} settings`,
    settingsBody: "These are saved with your dashboard.",
    settingsSave: "Save settings",
    settingsFailed: "Could not save the settings. Try again.",
    retry: "Try again",
    unavailable: "This widget is not available any more.",
    announce: {
      pickedUp: (t: string, n: number, total: number) => `Picked up ${t}. Position ${n} of ${total}. Use the arrow keys to move, Space to drop, Escape to cancel.`,
      over: (t: string, n: number, total: number) => `${t} is now at position ${n} of ${total}.`,
      dropped: (t: string, n: number, total: number) => `Dropped ${t} at position ${n} of ${total}.`,
      cancelled: (t: string) => `Cancelled. ${t} went back.`,
      resized: (t: string, c: number, r: number) => `${t} is now ${c} by ${r}.`,
      pinned: (t: string) => `${t} pinned.`,
      unpinned: (t: string) => `${t} unpinned.`,
      removed: (t: string) => `${t} removed.`,
      added: (t: string) => `${t} added.`,
    },
    instructions: "To reorder, focus the drag handle and press Space, then use the arrow keys. Or open the actions menu and choose Move earlier or Move later.",
  },
  ar: {
    region: "لوحة المعلومات",
    customise: "تخصيص",
    customiseHint: "اسحب البطاقات لإعادة ترتيبها، وغيّر أحجامها، وثبّت ما تريده في المقدمة دائمًا.",
    editing: "تعديل لوحة المعلومات",
    save: "حفظ",
    saving: "جارٍ الحفظ",
    cancel: "إلغاء",
    reset: "استعادة الافتراضي",
    add: "إضافة عنصر",
    addTitle: "إضافة عنصر",
    addBody: "اختر عنصرًا لإضافته في نهاية اللوحة.",
    alreadyOnBoard: "موجود في اللوحة",
    close: "إغلاق",
    saveFailed: "تعذّر حفظ اللوحة. تغييراتك ما زالت هنا، حاول مرة أخرى.",
    dragHandle: (t: string) => `اسحب ${t} لإعادة الترتيب`,
    sortable: "بطاقة قابلة للسحب",
    more: (t: string) => `إجراءات ${t}`,
    pinned: "مثبّتة",
    pin: "تثبيت في المقدمة",
    unpin: "إلغاء التثبيت",
    wider: "أعرض",
    narrower: "أضيق",
    taller: "أطول",
    shorter: "أقصر",
    earlier: "تقديم",
    later: "تأخير",
    settings: "الإعدادات",
    remove: "إزالة",
    size: (c: number, r: number) => `${c} في ${r}`,
    sizeLabel: "الحجم بالأعمدة في الصفوف",
    emptyTitle: "اللوحة فارغة",
    emptyBody: "أضف عناصر لعرض أرقامك هنا.",
    settingsTitle: (t: string) => `إعدادات ${t}`,
    settingsBody: "تُحفظ هذه مع لوحتك.",
    settingsSave: "حفظ الإعدادات",
    settingsFailed: "تعذّر حفظ الإعدادات. حاول مرة أخرى.",
    retry: "إعادة المحاولة",
    unavailable: "هذا العنصر لم يعد متاحًا.",
    announce: {
      pickedUp: (t: string, n: number, total: number) => `تم التقاط ${t}. الموضع ${n} من ${total}. استخدم الأسهم للنقل، ومفتاح المسافة للإفلات، وEscape للإلغاء.`,
      over: (t: string, n: number, total: number) => `${t} الآن في الموضع ${n} من ${total}.`,
      dropped: (t: string, n: number, total: number) => `تم إفلات ${t} في الموضع ${n} من ${total}.`,
      cancelled: (t: string) => `أُلغي. عاد ${t} إلى مكانه.`,
      resized: (t: string, c: number, r: number) => `أصبح حجم ${t} ${c} في ${r}.`,
      pinned: (t: string) => `تم تثبيت ${t}.`,
      unpinned: (t: string) => `أُلغي تثبيت ${t}.`,
      removed: (t: string) => `أُزيل ${t}.`,
      added: (t: string) => `أُضيف ${t}.`,
    },
    instructions: "لإعادة الترتيب، ركّز على مقبض السحب واضغط المسافة ثم استخدم الأسهم. أو افتح قائمة الإجراءات واختر تقديم أو تأخير.",
  },
};

export type DashboardBoardLabels = typeof BOARD_STRINGS.en;
