// Built-in English and Arabic strings of the stock ledger.
export const STOCK_STRINGS = {
  en: {
    onHand: "On hand",
    product: "Product",
    warehouse: "Warehouse",
    allWarehouses: "All warehouses",
    total: "Total",
    status: "Status",
    inStock: "In stock",
    low: "Low",
    out: "Out",
    reorderAt: "Reorder at",
    receive: "Receive",
    issue: "Issue",
    adjust: "Adjust",
    transfer: "Transfer",
    record: "Record movement",
    recordText: "Stock changes only through movements. Pick what happened and how many.",
    movementType: "Movement type",
    from: "From",
    to: "To",
    date: "Date",
    quantity: "Quantity",
    direction: "Direction",
    increase: "Increase",
    decrease: "Decrease",
    reference: "Reference",
    referencePlaceholder: "PO-2041, SO-5520, count sheet",
    note: "Note",
    available: "Available here",
    save: "Save movement",
    cancel: "Cancel",
    errQuantity: "Enter a quantity above zero.",
    errProduct: "Pick a product.",
    errWarehouse: "Pick a warehouse.",
    errSame: "Pick two different warehouses.",
    errStock: "Not enough stock: only {n} available here.",
    errSave: "Could not save the movement.",
    movements: "Movements",
    movement: "Movement",
    change: "Change",
    balance: "Balance",
    reference2: "Reference",
    noMovements: "No movements yet",
    noMovementsText: "Record a receive, issue or adjustment and it shows here.",
    noProducts: "No products to track",
    noProductsText: "Add products and warehouses to see stock.",
    viewMovements: "View movements",
    rowActions: "Product actions",
    filterProduct: "Product",
    filterWarehouse: "Warehouse",
    asOf: "Balance after each movement",
    reorderNote: "Flagged low at or under the reorder point.",
  },
  ar: {
    onHand: "المتوفر",
    product: "المنتج",
    warehouse: "المستودع",
    allWarehouses: "كل المستودعات",
    total: "الإجمالي",
    status: "الحالة",
    inStock: "متوفر",
    low: "منخفض",
    out: "نافد",
    reorderAt: "حد إعادة الطلب",
    receive: "استلام",
    issue: "صرف",
    adjust: "تسوية",
    transfer: "تحويل",
    record: "تسجيل حركة",
    recordText: "لا يتغير المخزون إلا بحركة. اختر ما حدث وكم الكمية.",
    movementType: "نوع الحركة",
    from: "من",
    to: "إلى",
    date: "التاريخ",
    quantity: "الكمية",
    direction: "الاتجاه",
    increase: "زيادة",
    decrease: "نقصان",
    reference: "المرجع",
    referencePlaceholder: "أمر شراء، أمر بيع، ورقة جرد",
    note: "ملاحظة",
    available: "المتاح هنا",
    save: "حفظ الحركة",
    cancel: "إلغاء",
    errQuantity: "أدخل كمية أكبر من صفر.",
    errProduct: "اختر منتجًا.",
    errWarehouse: "اختر مستودعًا.",
    errSame: "اختر مستودعين مختلفين.",
    errStock: "المخزون لا يكفي: المتاح هنا {n} فقط.",
    errSave: "تعذر حفظ الحركة.",
    movements: "الحركات",
    movement: "الحركة",
    change: "التغيير",
    balance: "الرصيد",
    reference2: "المرجع",
    noMovements: "لا توجد حركات بعد",
    noMovementsText: "سجّل استلامًا أو صرفًا أو تسوية وستظهر هنا.",
    noProducts: "لا توجد منتجات للتتبع",
    noProductsText: "أضف منتجات ومستودعات لعرض المخزون.",
    viewMovements: "عرض الحركات",
    rowActions: "إجراءات المنتج",
    filterProduct: "المنتج",
    filterWarehouse: "المستودع",
    asOf: "الرصيد بعد كل حركة",
    reorderNote: "يُعلَّم منخفضًا عند حد إعادة الطلب أو أقل.",
  },
} as const;

export type StockLedgerStrings = { [K in keyof (typeof STOCK_STRINGS)["en"]]: string };
export type StockLedgerLabels = Partial<StockLedgerStrings>;

import { computed, type ComputedRef } from "vue";
import { useNasaq } from "../../provider";

/** Merged strings for the active locale plus `labels`. */
export function useStockLedgerStrings(labels?: () => StockLedgerLabels | undefined): { t: ComputedRef<StockLedgerStrings>; locale: ComputedRef<string> } {
  const nasaq = useNasaq();
  return {
    t: computed(() => ({ ...STOCK_STRINGS[nasaq.locale.value.startsWith("ar") ? "ar" : "en"], ...labels?.() }) as StockLedgerStrings),
    locale: computed(() => nasaq.locale.value),
  };
}

/** A medium date in Latin digits, from the first ten characters of an ISO date. */
export function stockDate(locale: string, iso: string): string {
  return new Intl.DateTimeFormat(new Intl.Locale(locale, { numberingSystem: "latn" }).toString(), { dateStyle: "medium", timeZone: "UTC" }).format(new Date(`${iso.slice(0, 10)}T00:00:00Z`));
}
