// Every string the step editor shows, in English and Arabic. Pass `labels` to override any of them.
export const STEP_STRINGS = {
  en: {
    steps: "Steps",
    params: "Parameters",
    test: "Test run",
    newStep: "New step",
    addStep: "Add step",
    addChild: "Add a step inside",
    stepList: "Steps",
    innerList: (name: string) => `Steps inside ${name}`,
    innerEmpty: "Nothing inside yet.",
    empty: "No steps yet.",
    name: "Name",
    nameHelp: "Shown in the list. Leave empty to use the step's own name.",
    continueOn: "Continue if this step fails",
    continueHelp: "The next step still runs. The failure is recorded.",
    noFields: "This step has no settings.",
    unknownType: "Unknown step",
    chooseType: "Choose a step type",
    cancelPick: "Cancel",
    required: "Required",
    issueMissing: (label: string, field: string) => `${label}: "${field}" is required`,
    issuePlaceholder: (label: string, name: string) => `${label}: {{${name}}} is not defined`,
    issueNoType: (label: string) => `${label}: choose a step type`,
    issueParamName: (name: string) => `Parameter "${name}": use letters, digits, _ - and . and start with a letter`,
    issueParamDup: (name: string) => `Parameter "${name}" is defined twice`,
    problems: (n: string) => `${n} to fix before running`,
    paramsIntro: "Use a parameter in any text field as {{name}}. Secret values are masked and hidden from test output.",
    paramName: "Name",
    paramValue: "Value",
    paramSecret: "Secret",
    paramAdd: "Add parameter",
    paramList: "Parameters",
    paramEmpty: "No parameters yet.",
    paramRow: (n: string) => `Parameter ${n}`,
    show: "Show value",
    hide: "Hide value",
    usedIn: (n: string) => `Used in ${n} places`,
    unused: "Not used yet",
    testIntro: "Run the steps in order with these parameters. Nothing here is saved.",
    testRun: "Run test",
    testing: "Running",
    testBlocked: "Fix the problems first",
    testNone: "No test yet.",
    testFailed: "The test could not run",
    status: { success: "Succeeded", error: "Failed", skipped: "Skipped" },
    output: "Output",
    error: "Error",
    stepCount: (n: string) => `${n} steps`,
    testAria: "Test run results",
  },
  ar: {
    steps: "الخطوات",
    params: "المعاملات",
    test: "تشغيل تجريبي",
    newStep: "خطوة جديدة",
    addStep: "إضافة خطوة",
    addChild: "أضف خطوة بالداخل",
    stepList: "الخطوات",
    innerList: (name: string) => `الخطوات داخل ${name}`,
    innerEmpty: "لا شيء بالداخل بعد.",
    empty: "لا خطوات بعد.",
    name: "الاسم",
    nameHelp: "يظهر في القائمة. اتركه فارغًا لاستخدام اسم الخطوة نفسها.",
    continueOn: "المتابعة إذا فشلت هذه الخطوة",
    continueHelp: "تعمل الخطوة التالية رغم ذلك، ويُسجَّل الفشل.",
    noFields: "ليس لهذه الخطوة إعدادات.",
    unknownType: "خطوة غير معروفة",
    chooseType: "اختر نوع الخطوة",
    cancelPick: "إلغاء",
    required: "مطلوب",
    issueMissing: (label: string, field: string) => `${label}: الحقل "${field}" مطلوب`,
    issuePlaceholder: (label: string, name: string) => `${label}: {{${name}}} غير معرَّف`,
    issueNoType: (label: string) => `${label}: اختر نوع الخطوة`,
    issueParamName: (name: string) => `المعامل "${name}": استخدم حروفًا وأرقامًا و _ - . وابدأ بحرف`,
    issueParamDup: (name: string) => `المعامل "${name}" معرَّف مرتين`,
    problems: (n: string) => `${n} للإصلاح قبل التشغيل`,
    paramsIntro: "استخدم المعامل في أي حقل نصي بالصيغة {{الاسم}}. القيم السرية مخفية وتُحجب من ناتج التجربة.",
    paramName: "الاسم",
    paramValue: "القيمة",
    paramSecret: "سري",
    paramAdd: "إضافة معامل",
    paramList: "المعاملات",
    paramEmpty: "لا معاملات بعد.",
    paramRow: (n: string) => `المعامل ${n}`,
    show: "إظهار القيمة",
    hide: "إخفاء القيمة",
    usedIn: (n: string) => `مستخدم في ${n} مواضع`,
    unused: "غير مستخدم بعد",
    testIntro: "شغّل الخطوات بالترتيب بهذه المعاملات. لا يُحفظ شيء هنا.",
    testRun: "شغّل التجربة",
    testing: "جارٍ التشغيل",
    testBlocked: "أصلح المشكلات أولًا",
    testNone: "لا تجربة بعد.",
    testFailed: "تعذّر تشغيل التجربة",
    status: { success: "نجحت", error: "فشلت", skipped: "تم تخطيها" },
    output: "المخرج",
    error: "الخطأ",
    stepCount: (n: string) => `${n} خطوات`,
    testAria: "نتائج التشغيل التجريبي",
  },
};

export type StepEditorLabels = (typeof STEP_STRINGS)["en"];
