// Built-in English and Arabic strings of the accounting ledger.
export const ACCOUNTING_STRINGS = {
  en: {
    code: "Code",
    account: "Account",
    type: "Type",
    balance: "Balance",
    debit: "Debit",
    credit: "Credit",
    asset: "Asset",
    liability: "Liability",
    equity: "Equity",
    revenue: "Revenue",
    expense: "Expense",
    chart: "Chart of accounts",
    noAccounts: "No accounts yet",
    noAccountsText: "Add the first account to start the chart.",
    expand: "Expand",
    collapse: "Collapse",
    archived: "Archived",
    viewStatement: "View statement",
    addChild: "Add sub-account",
    archive: "Archive account",
    restore: "Restore account",
    rowActions: "Account actions",
    date: "Date",
    memo: "Memo",
    entry: "Journal entry",
    lines: "Lines",
    pickAccount: "Pick an account",
    noAccountMatch: "No account matches",
    linePlaceholder: "Line memo",
    line: "Line",
    addLine: "Add line",
    removeLine: "Remove line",
    duplicateLine: "Duplicate line",
    balanceLine: "Balance with this line",
    lineActions: "Line actions",
    totals: "Totals",
    difference: "Difference",
    balanced: "Balanced",
    outOfBalance: "Out of balance",
    post: "Post entry",
    saveDraft: "Save draft",
    entryNumber: "Entry number",
    problemFewLines: "An entry needs at least two lines with an amount.",
    problemNoAccount: "Every line with an amount needs an account.",
    problemBothSides: "A line is either a debit or a credit, not both.",
    problemNegative: "Amounts cannot be negative.",
    problemUnbalanced: "Debits and credits must be equal.",
    problemZero: "Enter an amount.",
    trial: "Trial balance",
    asOf: "As of",
    total: "Total",
    trialBalanced: "Debits equal credits",
    trialOff: "Debits and credits differ",
    empty: "No posted entries yet",
    emptyText: "Post a journal entry and it shows here.",
    statement: "Account statement",
    number: "Number",
    running: "Running balance",
    noMovements: "No movements on this account",
    inCurrency: "Amounts in",
  },
  ar: {
    code: "الرمز",
    account: "الحساب",
    type: "النوع",
    balance: "الرصيد",
    debit: "مدين",
    credit: "دائن",
    asset: "أصول",
    liability: "التزامات",
    equity: "حقوق ملكية",
    revenue: "إيرادات",
    expense: "مصروفات",
    chart: "دليل الحسابات",
    noAccounts: "لا توجد حسابات بعد",
    noAccountsText: "أضف أول حساب لبدء الدليل.",
    expand: "توسيع",
    collapse: "طي",
    archived: "مؤرشف",
    viewStatement: "عرض كشف الحساب",
    addChild: "إضافة حساب فرعي",
    archive: "أرشفة الحساب",
    restore: "استعادة الحساب",
    rowActions: "إجراءات الحساب",
    date: "التاريخ",
    memo: "البيان",
    entry: "قيد يومية",
    lines: "البنود",
    pickAccount: "اختر حسابًا",
    noAccountMatch: "لا يوجد حساب مطابق",
    linePlaceholder: "بيان البند",
    line: "البند",
    addLine: "إضافة بند",
    removeLine: "حذف البند",
    duplicateLine: "تكرار البند",
    balanceLine: "موازنة القيد بهذا البند",
    lineActions: "إجراءات البند",
    totals: "الإجماليات",
    difference: "الفرق",
    balanced: "متوازن",
    outOfBalance: "غير متوازن",
    post: "ترحيل القيد",
    saveDraft: "حفظ كمسودة",
    entryNumber: "رقم القيد",
    problemFewLines: "يحتاج القيد إلى بندين على الأقل بمبلغ.",
    problemNoAccount: "كل بند بمبلغ يحتاج إلى حساب.",
    problemBothSides: "البند إما مدين أو دائن، وليس كليهما.",
    problemNegative: "لا يمكن أن تكون المبالغ سالبة.",
    problemUnbalanced: "يجب أن يتساوى المدين والدائن.",
    problemZero: "أدخل مبلغًا.",
    trial: "ميزان المراجعة",
    asOf: "حتى تاريخ",
    total: "الإجمالي",
    trialBalanced: "المدين يساوي الدائن",
    trialOff: "المدين والدائن مختلفان",
    empty: "لا توجد قيود مرحّلة بعد",
    emptyText: "رحِّل قيد يومية وسيظهر هنا.",
    statement: "كشف حساب",
    number: "الرقم",
    running: "الرصيد الجاري",
    noMovements: "لا توجد حركات على هذا الحساب",
    inCurrency: "المبالغ بعملة",
  },
} as const;

export type AccountingLedgerStrings = { [K in keyof (typeof ACCOUNTING_STRINGS)["en"]]: string };
export type AccountingLedgerLabels = Partial<AccountingLedgerStrings>;

import { computed, type ComputedRef } from "vue";
import { useNasaq } from "../../provider";

/** Merged strings for the active locale plus `labels`. */
export function useAccountingLedgerStrings(labels?: () => AccountingLedgerLabels | undefined): { t: ComputedRef<AccountingLedgerStrings>; locale: ComputedRef<string>; ar: ComputedRef<boolean> } {
  const nasaq = useNasaq();
  const ar = computed(() => nasaq.locale.value.startsWith("ar"));
  return {
    t: computed(() => ({ ...ACCOUNTING_STRINGS[ar.value ? "ar" : "en"], ...labels?.() }) as AccountingLedgerStrings),
    locale: computed(() => nasaq.locale.value),
    ar,
  };
}

/** A medium date in Latin digits, from the first ten characters of an ISO date. */
export function accountingDate(locale: string, iso: string): string {
  return new Intl.DateTimeFormat(new Intl.Locale(locale, { numberingSystem: "latn" }).toString(), { dateStyle: "medium", timeZone: "UTC" }).format(new Date(`${iso.slice(0, 10)}T00:00:00Z`));
}
