// Built-in English and Arabic strings of the customer account.
import { computed } from "vue";
import { useNasaq } from "../../provider";
import type { OrderGroup } from "./account-logic";
import type { RefundMethod, ReturnReason, RmaStatus } from "./return-math";

const en = {
  // shell
  account: "My account",
  navOrders: "Orders",
  navReturns: "Returns",
  navWishlist: "Wishlist",
  navAddresses: "Addresses",
  navRecent: "Recently viewed",
  retry: "Try again",
  cancel: "Cancel",
  save: "Save",
  back: "Back",
  items: "items",
  // history
  ordersTitle: "My orders",
  searchOrders: "Search by order number or product",
  groups: { all: "All", active: "In progress", delivered: "Delivered", returns: "Returns", cancelled: "Cancelled" } satisfies Record<OrderGroup, string>,
  order: "Order",
  placedOn: "Placed on",
  total: "Total",
  viewOrder: "View order",
  orderAgain: "Order again",
  trackOrder: "Track",
  noOrders: "You have no orders yet",
  noOrdersText: "When you place an order it will show up here.",
  noMatch: "No orders match",
  noMatchHint: "Try another search or another filter.",
  clearFilters: "Show all orders",
  loadError: "Your orders could not be loaded.",
  reorderAdded: (n: number) => (n === 1 ? "1 item added to your cart." : `${n} items added to your cart.`),
  reorderReduced: (n: number) => (n === 1 ? "1 item was added in a smaller quantity because of stock." : `${n} items were added in smaller quantities because of stock.`),
  reorderSkipped: (n: number) => (n === 1 ? "1 item is no longer available." : `${n} items are no longer available.`),
  reorderPriceChanged: "Some prices have changed since you ordered.",
  reorderNothing: "None of these items are available any more.",
  goToCart: "Go to cart",
  // order detail
  backToOrders: "Back to orders",
  progress: "Order progress",
  itemsOrdered: "Items",
  quantity: "Qty",
  subtotal: "Subtotal",
  discount: "Discount",
  shipping: "Shipping",
  free: "Free",
  tax: "Tax",
  paid: "Total",
  shippingAddress: "Shipping address",
  paymentMethod: "Payment",
  returnItems: "Return items",
  returnsTitle: "Returns for this order",
  noReturnsYet: "No returns for this order.",
  returnClosed: "The return window for this order has closed.",
  returnNotYet: "You can request a return once the order is delivered.",
  returnDaysLeft: (n: number) => (n === 1 ? "1 day left to return" : `${n} days left to return`),
  invoice: "Invoice",
  needHelp: "Need help with this order?",
  shippedQty: (n: number) => `${n} shipped`,
  refundedQty: (n: number) => `${n} refunded`,
  // return request
  returnTitle: "Return items",
  returnIntro: "Choose what you are sending back and tell us why.",
  returnPick: "What are you returning?",
  returnableLeft: (n: number) => `${n} can be returned`,
  notReturnable: "Nothing left to return",
  inRequest: (n: number) => `${n} already in a return`,
  returnReason: "Why are you returning it?",
  reasonPlaceholder: "Choose a reason",
  reasons: {
    defective: "It arrived damaged or does not work",
    "wrong-item": "I received the wrong item",
    "not-as-described": "It is not as described",
    "too-small": "It is too small",
    "too-large": "It is too large",
    "changed-mind": "I changed my mind",
    late: "It arrived too late",
    other: "Something else",
  } satisfies Record<ReturnReason, string>,
  returnNote: "Tell us more",
  returnNoteRequired: "Please tell us what went wrong.",
  photos: "Photos",
  photosNeeded: "Add at least one photo so we can review your request.",
  photosOptional: "Optional. Photos help us process your return faster.",
  photoPrompt: "Drop photos here or choose files",
  removePhoto: "Remove photo",
  tooManyPhotos: (n: number) => `Up to ${n} photos.`,
  photoRejected: "That file could not be added. Use an image under 5 MB.",
  refundMethod: "Refund me by",
  methods: { original: "Original payment method", "store-credit": "Store credit", bank: "Bank transfer" } satisfies Record<RefundMethod, string>,
  methodHints: {
    original: "Back to the card or wallet you paid with. Takes 5 to 10 days.",
    "store-credit": "Available right away for your next order.",
    bank: "Sent to your bank account after we receive the items.",
  } satisfies Record<RefundMethod, string>,
  refundEstimate: "Estimated refund",
  estimateNote: "Shipping is not refunded. The final amount is confirmed when we receive your items.",
  windowOpen: (n: number) => (n === 1 ? "Return window closes tomorrow" : `Return window open for ${n} more days`),
  windowShut: "The return window has closed.",
  submitReturn: "Submit return request",
  fixIssues: "Complete the highlighted parts to continue.",
  issueEmpty: "Choose at least one item to return.",
  issueLineOver: (max: number) => `You can return at most ${max} of this item.`,
  issueReason: "Choose a reason.",
  issueMethod: "Choose how you want to be refunded.",
  submitted: "Return request sent",
  // return status
  rma: "Return",
  requestedOn: "Requested on",
  status: "Status",
  rmaStatus: {
    requested: "Requested",
    approved: "Approved",
    "shipped-back": "Sent back",
    received: "Received",
    refunded: "Refunded",
    rejected: "Rejected",
    cancelled: "Cancelled",
  } satisfies Record<RmaStatus, string>,
  rmaHint: {
    requested: "We are reviewing your request. This usually takes a day.",
    approved: "Approved. Pack the items and send them back with the label we emailed you.",
    "shipped-back": "Your parcel is on its way back to us.",
    received: "We received your items and are processing the refund.",
    refunded: "Your refund has been issued.",
    rejected: "We could not accept this return.",
    cancelled: "You cancelled this request.",
  } satisfies Record<RmaStatus, string>,
  rejectionReason: "Reason given",
  cancelRequest: "Cancel request",
  cancelRequestTitle: "Cancel this return request?",
  cancelRequestText: "The items stay with you and no refund is issued.",
  keepRequest: "Keep request",
  refundTotal: "Refund",
  // wishlist
  wishlistTitle: "Wishlist",
  wishlistEmpty: "Your wishlist is empty",
  wishlistEmptyText: "Save things you like and come back to them later.",
  moveToCart: "Move to cart",
  notifyMe: "Notify me when back",
  notifying: "We will email you",
  remove: "Remove",
  inStock: "In stock",
  lowStock: (n: number) => `Only ${n} left`,
  outOfStock: "Out of stock",
  unavailable: "No longer available",
  priceDropped: "Price dropped",
  was: "Was",
  savedOn: "Saved on",
  backInStock: (n: number) => (n === 1 ? "1 saved item is back in stock" : `${n} saved items are back in stock`),
  movedToCart: "Moved to cart",
  // addresses
  addressesTitle: "Address book",
  addAddress: "Add address",
  editAddress: "Edit address",
  newAddress: "New address",
  noAddresses: "No saved addresses",
  noAddressesText: "Save an address to check out faster.",
  makeDefault: "Set as default",
  defaultAddress: "Default",
  edit: "Edit",
  delete: "Delete",
  deleteTitle: "Delete this address?",
  deleteText: "It will be removed from your address book. Past orders are not affected.",
  fullName: "Full name",
  phone: "Phone",
  line1: "Address line 1",
  line2: "Address line 2 (optional)",
  city: "City",
  region: "Region (optional)",
  postalCode: "Postal code",
  country: "Country",
  required: "This field is required.",
  invalid: "This does not look right.",
  setDefaultCheck: "Use as my default address",
  // recently viewed
  recentTitle: "Recently viewed",
  recentEmpty: "Nothing viewed yet",
  recentEmptyText: "Products you look at will appear here.",
  clearAll: "Clear all",
  viewProduct: "View product",
};

export type StoreAccountStrings = typeof en;

const ar: StoreAccountStrings = {
  account: "حسابي",
  navOrders: "الطلبات",
  navReturns: "المرتجعات",
  navWishlist: "المفضلة",
  navAddresses: "العناوين",
  navRecent: "شاهدتها مؤخرًا",
  retry: "حاول مجددًا",
  cancel: "إلغاء",
  save: "حفظ",
  back: "رجوع",
  items: "منتجات",
  ordersTitle: "طلباتي",
  searchOrders: "ابحث برقم الطلب أو المنتج",
  groups: { all: "الكل", active: "قيد التنفيذ", delivered: "تم التسليم", returns: "المرتجعات", cancelled: "الملغاة" },
  order: "الطلب",
  placedOn: "تاريخ الطلب",
  total: "الإجمالي",
  viewOrder: "عرض الطلب",
  orderAgain: "اطلب مرة أخرى",
  trackOrder: "تتبّع",
  noOrders: "لا توجد لديك طلبات بعد",
  noOrdersText: "ستظهر طلباتك هنا عند إتمام أول طلب.",
  noMatch: "لا توجد طلبات مطابقة",
  noMatchHint: "جرّب بحثًا آخر أو تصنيفًا آخر.",
  clearFilters: "عرض كل الطلبات",
  loadError: "تعذّر تحميل طلباتك.",
  reorderAdded: (n) => (n === 1 ? "أُضيف منتج واحد إلى سلتك." : `أُضيفت ${n} منتجات إلى سلتك.`),
  reorderReduced: (n) => (n === 1 ? "أُضيف منتج واحد بكمية أقل بسبب المخزون." : `أُضيفت ${n} منتجات بكميات أقل بسبب المخزون.`),
  reorderSkipped: (n) => (n === 1 ? "منتج واحد لم يعد متوفرًا." : `${n} منتجات لم تعد متوفرة.`),
  reorderPriceChanged: "تغيّرت بعض الأسعار منذ طلبك.",
  reorderNothing: "لم يعد أي من هذه المنتجات متوفرًا.",
  goToCart: "اذهب إلى السلة",
  backToOrders: "العودة إلى الطلبات",
  progress: "تقدّم الطلب",
  itemsOrdered: "المنتجات",
  quantity: "الكمية",
  subtotal: "المجموع الفرعي",
  discount: "الخصم",
  shipping: "الشحن",
  free: "مجاني",
  tax: "الضريبة",
  paid: "الإجمالي",
  shippingAddress: "عنوان الشحن",
  paymentMethod: "الدفع",
  returnItems: "إرجاع منتجات",
  returnsTitle: "مرتجعات هذا الطلب",
  noReturnsYet: "لا توجد مرتجعات لهذا الطلب.",
  returnClosed: "انتهت مهلة الإرجاع لهذا الطلب.",
  returnNotYet: "يمكنك طلب الإرجاع بعد تسليم الطلب.",
  returnDaysLeft: (n) => (n === 1 ? "بقي يوم واحد للإرجاع" : `بقي ${n} أيام للإرجاع`),
  invoice: "الفاتورة",
  needHelp: "هل تحتاج مساعدة بخصوص هذا الطلب؟",
  shippedQty: (n) => `${n} تم شحنها`,
  refundedQty: (n) => `${n} مستردة`,
  returnTitle: "إرجاع منتجات",
  returnIntro: "اختر ما تريد إرجاعه وأخبرنا بالسبب.",
  returnPick: "ما الذي تريد إرجاعه؟",
  returnableLeft: (n) => `يمكن إرجاع ${n}`,
  notReturnable: "لا يوجد ما يمكن إرجاعه",
  inRequest: (n) => `${n} ضمن طلب إرجاع سابق`,
  returnReason: "لماذا تريد الإرجاع؟",
  reasonPlaceholder: "اختر السبب",
  reasons: {
    defective: "وصل تالفًا أو لا يعمل",
    "wrong-item": "استلمت منتجًا خاطئًا",
    "not-as-described": "لا يطابق الوصف",
    "too-small": "صغير جدًا",
    "too-large": "كبير جدًا",
    "changed-mind": "غيّرت رأيي",
    late: "وصل متأخرًا",
    other: "سبب آخر",
  },
  returnNote: "أخبرنا بالمزيد",
  returnNoteRequired: "يرجى إخبارنا بما حدث.",
  photos: "الصور",
  photosNeeded: "أضف صورة واحدة على الأقل لنتمكن من مراجعة طلبك.",
  photosOptional: "اختياري. الصور تساعدنا على معالجة الإرجاع أسرع.",
  photoPrompt: "أفلت الصور هنا أو اختر ملفات",
  removePhoto: "إزالة الصورة",
  tooManyPhotos: (n) => `حتى ${n} صور.`,
  photoRejected: "تعذّرت إضافة هذا الملف. استخدم صورة أقل من 5 ميغابايت.",
  refundMethod: "استرد المبلغ عبر",
  methods: { original: "وسيلة الدفع الأصلية", "store-credit": "رصيد المتجر", bank: "تحويل بنكي" },
  methodHints: {
    original: "يعود إلى البطاقة أو المحفظة التي دفعت بها. يستغرق من 5 إلى 10 أيام.",
    "store-credit": "متاح فورًا لطلبك القادم.",
    bank: "يُرسل إلى حسابك البنكي بعد استلامنا المنتجات.",
  },
  refundEstimate: "الاسترداد المتوقع",
  estimateNote: "الشحن غير قابل للاسترداد. يُؤكَّد المبلغ النهائي عند استلام منتجاتك.",
  windowOpen: (n) => (n === 1 ? "تنتهي مهلة الإرجاع غدًا" : `مهلة الإرجاع مفتوحة لـ ${n} أيام أخرى`),
  windowShut: "انتهت مهلة الإرجاع.",
  submitReturn: "إرسال طلب الإرجاع",
  fixIssues: "أكمل الأجزاء المحددة للمتابعة.",
  issueEmpty: "اختر منتجًا واحدًا على الأقل لإرجاعه.",
  issueLineOver: (max) => `يمكنك إرجاع ${max} فقط من هذا المنتج.`,
  issueReason: "اختر السبب.",
  issueMethod: "اختر طريقة استرداد المبلغ.",
  submitted: "تم إرسال طلب الإرجاع",
  rma: "مرتجع",
  requestedOn: "تاريخ الطلب",
  status: "الحالة",
  rmaStatus: { requested: "تم الطلب", approved: "تمت الموافقة", "shipped-back": "أُعيد شحنه", received: "تم الاستلام", refunded: "تم الاسترداد", rejected: "مرفوض", cancelled: "ملغي" },
  rmaHint: {
    requested: "نراجع طلبك. يستغرق ذلك عادةً يومًا.",
    approved: "تمت الموافقة. عبّئ المنتجات وأرسلها بالملصق الذي وصلك بالبريد.",
    "shipped-back": "طردك في طريقه إلينا.",
    received: "استلمنا منتجاتك ونعالج الاسترداد.",
    refunded: "تم إصدار استردادك.",
    rejected: "تعذّر قبول هذا الإرجاع.",
    cancelled: "ألغيت هذا الطلب.",
  },
  rejectionReason: "السبب",
  cancelRequest: "إلغاء الطلب",
  cancelRequestTitle: "إلغاء طلب الإرجاع؟",
  cancelRequestText: "ستبقى المنتجات لديك ولن يُصدر أي استرداد.",
  keepRequest: "إبقاء الطلب",
  refundTotal: "الاسترداد",
  wishlistTitle: "المفضلة",
  wishlistEmpty: "مفضلتك فارغة",
  wishlistEmptyText: "احفظ ما يعجبك وعُد إليه لاحقًا.",
  moveToCart: "انقل إلى السلة",
  notifyMe: "أعلمني عند توفره",
  notifying: "سنراسلك عبر البريد",
  remove: "إزالة",
  inStock: "متوفر",
  lowStock: (n) => `بقي ${n} فقط`,
  outOfStock: "غير متوفر",
  unavailable: "لم يعد متاحًا",
  priceDropped: "انخفض السعر",
  was: "كان",
  savedOn: "حُفظ في",
  backInStock: (n) => (n === 1 ? "منتج محفوظ عاد إلى المخزون" : `${n} منتجات محفوظة عادت إلى المخزون`),
  movedToCart: "تم النقل إلى السلة",
  addressesTitle: "دفتر العناوين",
  addAddress: "إضافة عنوان",
  editAddress: "تعديل العنوان",
  newAddress: "عنوان جديد",
  noAddresses: "لا توجد عناوين محفوظة",
  noAddressesText: "احفظ عنوانًا لإتمام الشراء أسرع.",
  makeDefault: "تعيين كافتراضي",
  defaultAddress: "افتراضي",
  edit: "تعديل",
  delete: "حذف",
  deleteTitle: "حذف هذا العنوان؟",
  deleteText: "سيُحذف من دفتر عناوينك. لا تتأثر الطلبات السابقة.",
  fullName: "الاسم الكامل",
  phone: "الهاتف",
  line1: "العنوان، السطر 1",
  line2: "العنوان، السطر 2 (اختياري)",
  city: "المدينة",
  region: "المنطقة (اختياري)",
  postalCode: "الرمز البريدي",
  country: "الدولة",
  required: "هذا الحقل مطلوب.",
  invalid: "هذه القيمة تبدو غير صحيحة.",
  setDefaultCheck: "استخدمه كعنواني الافتراضي",
  recentTitle: "شاهدتها مؤخرًا",
  recentEmpty: "لم تشاهد شيئًا بعد",
  recentEmptyText: "ستظهر هنا المنتجات التي تتصفحها.",
  clearAll: "مسح الكل",
  viewProduct: "عرض المنتج",
};

export const STORE_ACCOUNT_STRINGS = { en, ar };

export type StoreAccountLabels = Partial<StoreAccountStrings>;

export function useStoreAccountStrings(labels?: () => StoreAccountLabels | undefined) {
  const nq = useNasaq();
  const locale = computed(() => nq.locale.value);
  const ar = computed(() => locale.value.startsWith("ar"));
  const t = computed(() => ({ ...STORE_ACCOUNT_STRINGS[ar.value ? "ar" : "en"], ...labels?.() }) as StoreAccountStrings);
  return { t, ar, locale };
}
