// Strings of the profile form, English and Arabic. Pass `labels` to override any of them.

export const PROFILE_STRINGS = {
  en: {
    name: "Display name",
    nameHelp: "Shown on your profile and next to your activity.",
    nameRequired: "Enter your name.",
    username: "Username",
    usernameHelp: "3 to 30 letters, numbers, dots, dashes or underscores.",
    usernameFormat: "Use 3 to 30 letters, numbers, dots, dashes or underscores. Start and end with a letter or number.",
    usernameChecking: "Checking availability",
    usernameAvailable: (username: string) => `⁦${username}⁩ is available.`,
    usernameTaken: "That username is taken. Try another one.",
    usernameCheckFailed: "Availability could not be checked. It will be verified when you save.",
    email: "Email",
    emailHelp: "Used to sign in and for account notices.",
    verified: "Verified",
    unverified: "Not verified",
    resend: "Resend verification email",
    resending: "Sending",
    resent: (email: string) => `Verification email sent to ⁦${email}⁩.`,
    resendFailed: "The email could not be sent. Try again.",
    changeEmail: "Change email",
    changeEmailTitle: "Change your email",
    changeEmailDescription: "We send a confirmation link to the new address. Enter your password to continue.",
    newEmail: "New email",
    emailInvalid: "Enter a valid email address.",
    emailSame: "That is already your email.",
    currentPassword: "Current password",
    passwordRequired: "Enter your password.",
    sendConfirmation: "Send confirmation link",
    changeEmailFailed: "Your email could not be changed. Try again.",
    pendingEmail: (email: string) => `We sent a confirmation link to ⁦${email}⁩. Your email changes once you confirm it.`,
    phone: "Phone",
    phoneHelp: "Used to recover your account. Never shown to others.",
    bio: "Bio",
    bioHelp: "A short line about you.",
    language: "Language",
    timezone: "Time zone",
    timezoneSearch: "Search time zones",
    timezoneEmpty: "No time zone found.",
    clear: "Clear",
    open: "Open list",
    unsaved: "You have unsaved changes",
    discard: "Discard",
    save: "Save changes",
    cancel: "Cancel",
    saved: "Profile updated.",
    saveFailed: "Your profile could not be saved. Try again.",
    dismiss: "Dismiss",
    publicProfile: "Public profile",
    publicProfileHint: "Everyone can see this on your profile page.",
    account: "Account",
    accountHint: "Private. Used to sign in and to recover your account.",
    preferences: "Preferences",
    preferencesHint: "How dates, times and the interface are shown to you.",
    location: "Location",
    locationHelp: "City and country, as you want it shown.",
    website: "Website",
    websiteHelp: "Your site or portfolio.",
    websiteInvalid: "Enter a full link that starts with https://.",
    viewProfile: "View public profile",
    preview: "Profile preview",
  },
  ar: {
    name: "الاسم المعروض",
    nameHelp: "يظهر في ملفك الشخصي وبجانب نشاطك.",
    nameRequired: "أدخل اسمك.",
    username: "اسم المستخدم",
    usernameHelp: "من 3 إلى 30 حرفًا أو رقمًا أو نقطة أو شرطة أو شرطة سفلية.",
    usernameFormat: "استخدم من 3 إلى 30 حرفًا أو رقمًا أو نقطة أو شرطة أو شرطة سفلية، وابدأ وانتهِ بحرف أو رقم.",
    usernameChecking: "جارٍ التحقق من التوفر",
    usernameAvailable: (username: string) => `⁦${username}⁩ متاح.`,
    usernameTaken: "اسم المستخدم هذا مستخدم بالفعل. جرّب اسمًا آخر.",
    usernameCheckFailed: "تعذّر التحقق من التوفر. سيتم التحقق منه عند الحفظ.",
    email: "البريد الإلكتروني",
    emailHelp: "يُستخدم لتسجيل الدخول وإشعارات الحساب.",
    verified: "موثّق",
    unverified: "غير موثّق",
    resend: "إعادة إرسال رسالة التوثيق",
    resending: "جارٍ الإرسال",
    resent: (email: string) => `أُرسلت رسالة التوثيق إلى ⁦${email}⁩.`,
    resendFailed: "تعذّر إرسال الرسالة. حاول مرة أخرى.",
    changeEmail: "تغيير البريد",
    changeEmailTitle: "تغيير بريدك الإلكتروني",
    changeEmailDescription: "نرسل رابط تأكيد إلى العنوان الجديد. أدخل كلمة المرور للمتابعة.",
    newEmail: "البريد الجديد",
    emailInvalid: "أدخل بريدًا إلكترونيًا صحيحًا.",
    emailSame: "هذا هو بريدك الحالي بالفعل.",
    currentPassword: "كلمة المرور الحالية",
    passwordRequired: "أدخل كلمة المرور.",
    sendConfirmation: "إرسال رابط التأكيد",
    changeEmailFailed: "تعذّر تغيير بريدك. حاول مرة أخرى.",
    pendingEmail: (email: string) => `أرسلنا رابط تأكيد إلى ⁦${email}⁩. يتغير بريدك بعد أن تؤكده.`,
    phone: "الهاتف",
    phoneHelp: "يُستخدم لاستعادة حسابك. لا يظهر للآخرين.",
    bio: "نبذة",
    bioHelp: "سطر قصير عنك.",
    language: "اللغة",
    timezone: "المنطقة الزمنية",
    timezoneSearch: "ابحث عن منطقة زمنية",
    timezoneEmpty: "لا توجد منطقة زمنية مطابقة.",
    clear: "مسح",
    open: "فتح القائمة",
    unsaved: "لديك تغييرات غير محفوظة",
    discard: "تجاهل",
    save: "حفظ التغييرات",
    cancel: "إلغاء",
    saved: "تم تحديث الملف الشخصي.",
    saveFailed: "تعذّر حفظ ملفك الشخصي. حاول مرة أخرى.",
    dismiss: "تجاهل",
    publicProfile: "الملف العام",
    publicProfileHint: "يراه الجميع في صفحة ملفك الشخصي.",
    account: "الحساب",
    accountHint: "خاص. يُستخدم لتسجيل الدخول واستعادة حسابك.",
    preferences: "التفضيلات",
    preferencesHint: "كيف تظهر لك التواريخ والأوقات والواجهة.",
    location: "الموقع",
    locationHelp: "المدينة والبلد، كما تريد أن يظهرا.",
    website: "الموقع الإلكتروني",
    websiteHelp: "موقعك أو معرض أعمالك.",
    websiteInvalid: "أدخل رابطًا كاملًا يبدأ بـ https://.",
    viewProfile: "عرض الملف العام",
    preview: "معاينة الملف",
  },
};

export type ProfileFormLabels = Partial<(typeof PROFILE_STRINGS)["en"]>;
export const profileStrings = (locale: string) => PROFILE_STRINGS[locale.startsWith("ar") ? "ar" : "en"];
