import type { KpiStatus, MarginBand } from "./business-reports-math";

export const STRINGS = {
  en: {
    revenue: "Revenue",
    cost: "Cost",
    profit: "Profit",
    margin: "Margin",
    losing: (n: number) => (n === 1 ? "1 loses money" : `${n} lose money`),
    breakdown: "Where the revenue goes",
    band: { loss: "Loss", thin: "Thin", healthy: "Healthy" } as Record<MarginBand, string>,
    noRevenue: "No revenue",
    trend: "Trend",
    hours: "Hours",
    subject: "Project",
    empty: "Nothing to report for this period.",
    total: "Total",
    kpiTeam: "Team attainment",
    kpiAhead: "At or above target",
    kpiBehind: "Behind target",
    kpiOf: (actual: string, target: string) => `${actual} of ${target}`,
    kpiStatus: { ahead: "Ahead", "on-track": "On track", behind: "Behind" } as Record<KpiStatus, string>,
    attainment: (name: string, pct: string) => `${name}: ${pct} of target`,
    moreFor: (name: string) => `Actions for ${name}`,
    employee: "Employee",
    target: "Target",
    actual: "Actual",
    view: "View",
    chart: "Chart",
    table: "Table",
    stage: "Stage",
    deals: "Deals",
    value: "Value",
    average: "Average deal",
    fromPrevious: "From previous",
    fromFirst: "From first",
    pipelineValue: "Pipeline value",
    winRate: "Win rate",
    won: "Won",
    open: "Open",
    firstResponse: "First response",
    resolution: "Resolution time",
    csat: "Satisfaction",
    sla: "Within SLA",
    volume: "Ticket volume",
    created: "Created",
    resolved: "Resolved",
    byStatus: "Tickets by status",
    agents: "Agents",
    agent: "Agent",
    assigned: "Assigned",
    resolvedShort: "Resolved",
  },
  ar: {
    revenue: "الإيرادات",
    cost: "التكلفة",
    profit: "الربح",
    margin: "الهامش",
    losing: (n: number) => (n === 1 ? "واحد يخسر" : `${n} تخسر`),
    breakdown: "أين تذهب الإيرادات",
    band: { loss: "خسارة", thin: "ضعيف", healthy: "جيد" } as Record<MarginBand, string>,
    noRevenue: "بلا إيرادات",
    trend: "الاتجاه",
    hours: "الساعات",
    subject: "المشروع",
    empty: "لا شيء للإبلاغ عنه في هذه الفترة.",
    total: "الإجمالي",
    kpiTeam: "تحقيق الفريق",
    kpiAhead: "بلغ الهدف أو تجاوزه",
    kpiBehind: "دون الهدف",
    kpiOf: (actual: string, target: string) => `${actual} من ${target}`,
    kpiStatus: { ahead: "متقدّم", "on-track": "على المسار", behind: "متأخر" } as Record<KpiStatus, string>,
    attainment: (name: string, pct: string) => `${name}: ${pct} من الهدف`,
    moreFor: (name: string) => `إجراءات ${name}`,
    employee: "الموظف",
    target: "الهدف",
    actual: "الفعلي",
    view: "العرض",
    chart: "مخطط",
    table: "جدول",
    stage: "المرحلة",
    deals: "الصفقات",
    value: "القيمة",
    average: "متوسط الصفقة",
    fromPrevious: "من السابقة",
    fromFirst: "من الأولى",
    pipelineValue: "قيمة المسار",
    winRate: "نسبة الفوز",
    won: "مكسوبة",
    open: "مفتوحة",
    firstResponse: "أول رد",
    resolution: "زمن الحل",
    csat: "الرضا",
    sla: "ضمن اتفاقية الخدمة",
    volume: "حجم التذاكر",
    created: "المُنشأة",
    resolved: "المحلولة",
    byStatus: "التذاكر حسب الحالة",
    agents: "الموظفون",
    agent: "الموظف",
    assigned: "المُسندة",
    resolvedShort: "المحلولة",
  },
};

export type BusinessReportsLabels = typeof STRINGS.en;
