export const TWO_FACTOR_STRINGS = {
  en: {
    title: "Two-factor authentication",
    description: "Ask for a code from an authenticator app each time you sign in.",
    step: (n: number, total: number) => `Step ${n} of ${total}`,
    scanTitle: "Scan the QR code",
    scanBody: "Open an authenticator app such as 1Password, Authy or Google Authenticator and scan this code.",
    qrLabel: "QR code for your authenticator app",
    cantScan: "Can't scan? Enter this key instead",
    keyLabel: "Setup key",
    copyKey: "Copy setup key",
    next: "Next",
    verifyTitle: "Enter the 6-digit code",
    verifyBody: "Type the code your authenticator app shows now to confirm it is set up.",
    codeLabel: "Verification code",
    boxLabel: (i: number, n: number) => `Digit ${i + 1} of ${n}`,
    verify: "Verify and continue",
    back: "Back",
    genericError: "Something went wrong. Try again.",
    recoveryTitle: "Save your recovery codes",
    recoveryBody: "If you lose your phone, each of these codes lets you sign in once. Store them somewhere safe. They will not be shown again.",
    recoveryList: "Recovery codes",
    copyAll: "Copy all",
    download: "Download .txt",
    saved: "I saved these recovery codes",
    finish: "Finish",
    fileHeader: "Recovery codes",
    enabledTitle: "Two-factor authentication is on",
    enabledBody: "You will be asked for a code from your authenticator app when you sign in.",
    statusOn: "Enabled",
    remaining: (n: number) => (n === 1 ? "1 recovery code left" : `${n} recovery codes left`),
    regenerate: "Regenerate recovery codes",
    regenTitle: "Regenerate recovery codes?",
    regenBody: "Your current recovery codes stop working. Confirm to get a new set.",
    regenConfirm: "Regenerate",
    regenDone: "Your new recovery codes",
    disable: "Disable two-factor",
    disableTitle: "Disable two-factor authentication?",
    disableBody: "Your account will be protected by your password alone.",
    disableConfirm: "Disable",
    password: "Password",
    authCode: "Authentication code",
    confirmPassword: "Enter your password to continue.",
    confirmCode: "Enter a code from your authenticator app to continue.",
    cancel: "Cancel",
  },
  ar: {
    title: "المصادقة الثنائية",
    description: "اطلب رمزًا من تطبيق المصادقة في كل مرة تسجّل فيها الدخول.",
    step: (n: number, total: number) => `الخطوة ${n} من ${total}`,
    scanTitle: "امسح رمز QR",
    scanBody: "افتح تطبيق مصادقة مثل 1Password أو Authy أو Google Authenticator وامسح هذا الرمز.",
    qrLabel: "رمز QR لتطبيق المصادقة",
    cantScan: "لا يمكنك المسح؟ أدخل هذا المفتاح بدلًا من ذلك",
    keyLabel: "مفتاح الإعداد",
    copyKey: "نسخ مفتاح الإعداد",
    next: "التالي",
    verifyTitle: "أدخل الرمز المكوّن من 6 أرقام",
    verifyBody: "اكتب الرمز الذي يعرضه تطبيق المصادقة الآن للتأكد من اكتمال الإعداد.",
    codeLabel: "رمز التحقق",
    boxLabel: (i: number, n: number) => `الخانة ${i + 1} من ${n}`,
    verify: "تحقّق وتابع",
    back: "رجوع",
    genericError: "حدث خطأ ما. حاول مرة أخرى.",
    recoveryTitle: "احفظ رموز الاسترداد",
    recoveryBody: "إذا فقدت هاتفك، يتيح لك كل رمز من هذه الرموز تسجيل الدخول مرة واحدة. احفظها في مكان آمن. لن تُعرض مرة أخرى.",
    recoveryList: "رموز الاسترداد",
    copyAll: "نسخ الكل",
    download: "تنزيل .txt",
    saved: "لقد حفظت رموز الاسترداد",
    finish: "إنهاء",
    fileHeader: "رموز الاسترداد",
    enabledTitle: "المصادقة الثنائية مفعّلة",
    enabledBody: "سيُطلب منك رمز من تطبيق المصادقة عند تسجيل الدخول.",
    statusOn: "مفعّلة",
    remaining: (n: number) => (n === 1 ? "بقي رمز استرداد واحد" : `بقي ${n} رموز استرداد`),
    regenerate: "إعادة إنشاء رموز الاسترداد",
    regenTitle: "إعادة إنشاء رموز الاسترداد؟",
    regenBody: "ستتوقف رموز الاسترداد الحالية عن العمل. أكّد للحصول على مجموعة جديدة.",
    regenConfirm: "إعادة الإنشاء",
    regenDone: "رموز الاسترداد الجديدة",
    disable: "تعطيل المصادقة الثنائية",
    disableTitle: "تعطيل المصادقة الثنائية؟",
    disableBody: "سيُحمى حسابك بكلمة المرور وحدها.",
    disableConfirm: "تعطيل",
    password: "كلمة المرور",
    authCode: "رمز المصادقة",
    confirmPassword: "أدخل كلمة المرور للمتابعة.",
    confirmCode: "أدخل رمزًا من تطبيق المصادقة للمتابعة.",
    cancel: "إلغاء",
  },
};

export type TwoFactorLabels = (typeof TWO_FACTOR_STRINGS)["en"];

/** What a callback returns: nothing on success, or a message to show. */
export type TwoFactorResult = void | { error?: string };
