import type { TableDensity } from "../table";

export const STRINGS = {
  en: {
    search: "Search…",
    clearSearch: "Clear search",
    view: "View",
    columns: "Columns",
    selectAll: "Select all rows on this page",
    selectRow: (name: string) => `Select ${name}`,
    actions: "Actions",
    rowActions: (name: string) => `Actions for ${name}`,
    selected: (n: string) => `${n} selected`,
    clearSelection: "Clear selection",
    range: (from: string, to: string, total: string) => `${from}–${to} of ${total}`,
    previous: "Previous page",
    next: "Next page",
    pagination: "Pagination",
    empty: "Nothing here yet",
    noResults: "No matching results",
    noResultsHint: "Try a different search or clear the filters.",
    clearFilters: "Clear filters",
    error: "Couldn't load this list",
    retry: "Try again",
    loading: "Loading…",
    reset: "Reset",
    moreActions: "More actions",
    editCell: (column: string, row: string) => `${column}, ${row}`,
    invalidNumber: "Enter a number",
    invalidDate: "Enter a date",
    saving: "Saving…",
    saved: "Saved",
    saveFailed: "Couldn't save the change",
    saveFailedFor: (message: string) => `Couldn't save: ${message}`,
    expandRow: (name: string) => `Show details for ${name}`,
    details: (name: string) => `Details for ${name}`,
    sortPriority: (n: string, dir: string) => `sort ${n}, ${dir}`,
    ascending: "ascending",
    descending: "descending",
    multiSortHint: "Shift-click to sort by more columns",
    resize: (name: string) => `Resize ${name}`,
    pin: "Pin",
    pinStart: "Pin to start",
    pinEnd: "Pin to end",
    unpin: "Unpin",
    density: "Density",
    densities: { compact: "Compact", default: "Default", comfortable: "Comfortable" } as Record<TableDensity, string>,
    rowsPerPage: "Rows per page",
    rangeFrom: "From",
    rangeTo: "To",
    rangeAtLeast: (v: string) => `≥ ${v}`,
    rangeAtMost: (v: string) => `≤ ${v}`,
  },
  ar: {
    search: "ابحث…",
    clearSearch: "مسح البحث",
    view: "العرض",
    columns: "الأعمدة",
    selectAll: "تحديد كل صفوف هذه الصفحة",
    selectRow: (name: string) => `تحديد ${name}`,
    actions: "الإجراءات",
    rowActions: (name: string) => `إجراءات ${name}`,
    selected: (n: string) => `${n} محدد`,
    clearSelection: "إلغاء التحديد",
    range: (from: string, to: string, total: string) => `${from}–${to} من ${total}`,
    previous: "الصفحة السابقة",
    next: "الصفحة التالية",
    pagination: "التنقل بين الصفحات",
    empty: "لا شيء هنا بعد",
    noResults: "لا نتائج مطابقة",
    noResultsHint: "جرّب بحثًا آخر أو امسح عوامل التصفية.",
    clearFilters: "مسح التصفية",
    error: "تعذّر تحميل هذه القائمة",
    retry: "إعادة المحاولة",
    loading: "جارٍ التحميل…",
    reset: "إعادة الضبط",
    moreActions: "مزيد من الإجراءات",
    editCell: (column: string, row: string) => `${column}، ${row}`,
    invalidNumber: "أدخل رقمًا",
    invalidDate: "أدخل تاريخًا",
    saving: "جارٍ الحفظ…",
    saved: "تم الحفظ",
    saveFailed: "تعذّر حفظ التغيير",
    saveFailedFor: (message: string) => `تعذّر الحفظ: ${message}`,
    expandRow: (name: string) => `إظهار تفاصيل ${name}`,
    details: (name: string) => `تفاصيل ${name}`,
    sortPriority: (n: string, dir: string) => `ترتيب ${n}، ${dir}`,
    ascending: "تصاعدي",
    descending: "تنازلي",
    multiSortHint: "اضغط مع Shift للترتيب حسب أعمدة أخرى",
    resize: (name: string) => `تغيير عرض ${name}`,
    pin: "التثبيت",
    pinStart: "تثبيت في البداية",
    pinEnd: "تثبيت في النهاية",
    unpin: "إلغاء التثبيت",
    density: "الكثافة",
    densities: { compact: "مضغوطة", default: "عادية", comfortable: "مريحة" } as Record<TableDensity, string>,
    rowsPerPage: "صفوف في الصفحة",
    rangeFrom: "من",
    rangeTo: "إلى",
    rangeAtLeast: (v: string) => `≥ ${v}`,
    rangeAtMost: (v: string) => `≤ ${v}`,
  },
};
export type DataTableLabels = typeof STRINGS.en;

export function dataTableStrings(locale: string, overrides?: Partial<DataTableLabels>): DataTableLabels {
  return { ...STRINGS[locale.startsWith("ar") ? "ar" : "en"], ...overrides };
}
