import type { ApprovalKind, ApprovalStatus } from "./approval-queue-logic";

export const STRINGS = {
  en: {
    title: "Approvals",
    pending: "Pending",
    decided: "Decided",
    all: "All",
    filter: "Filter the queue",
    waiting: (n: number) => (n === 1 ? "1 waiting for you" : `${n} waiting for you`),
    nothingWaiting: "Nothing is waiting for you",
    emptyTitle: "The queue is empty",
    emptyBody: "Requests that need a decision show up here.",
    emptyPending: "You are all caught up",
    emptyPendingBody: "Nothing needs a decision right now.",
    kind: { action: "Action", review: "Review", moderation: "Moderation", request: "Request" } satisfies Record<ApprovalKind, string>,
    status: { pending: "Pending", approved: "Approved", rejected: "Rejected", expired: "Expired", converted: "Converted" } satisfies Record<ApprovalStatus, string>,
    by: "By",
    requested: "Requested",
    expires: "Expires",
    expired: "Expired",
    decidedBy: "Decided by",
    reason: "Reason",
    args: "Arguments",
    redacted: "Hidden",
    criteria: "Criteria",
    pass: "Pass",
    fail: "Fail",
    unmet: (n: number) => (n === 1 ? "1 criterion not met" : `${n} criteria not met`),
    approve: "Approve",
    approveFor: (t: string) => `Approve ${t}`,
    reject: "Reject",
    rejectFor: (t: string) => `Reject ${t}`,
    convert: "Convert",
    convertFor: (t: string) => `Convert ${t}`,
    blocked: "Fix the unmet criteria before approving.",
    rejectTitle: (t: string) => `Reject ${t}?`,
    rejectBody: "The person who asked will see your reason.",
    reasonLabel: "Reason",
    reasonPlaceholder: "Say why this is rejected",
    reasonRequired: "Give a reason.",
    cancel: "Cancel",
    failed: "Could not save the decision. Try again.",
    list: "Approval requests",
  },
  ar: {
    title: "الموافقات",
    pending: "قيد الانتظار",
    decided: "تم البت فيها",
    all: "الكل",
    filter: "تصفية الطابور",
    waiting: (n: number) => (n === 1 ? "طلب واحد ينتظرك" : n === 2 ? "طلبان ينتظرانك" : n <= 10 ? `${n} طلبات تنتظرك` : `${n} طلبًا ينتظرك`),
    nothingWaiting: "لا شيء ينتظرك",
    emptyTitle: "الطابور فارغ",
    emptyBody: "تظهر هنا الطلبات التي تحتاج إلى قرار.",
    emptyPending: "لا شيء متأخر",
    emptyPendingBody: "لا شيء يحتاج إلى قرار الآن.",
    kind: { action: "إجراء", review: "مراجعة", moderation: "إشراف", request: "طلب" } satisfies Record<ApprovalKind, string>,
    status: { pending: "قيد الانتظار", approved: "تمت الموافقة", rejected: "مرفوض", expired: "منتهي", converted: "تم التحويل" } satisfies Record<ApprovalStatus, string>,
    by: "بواسطة",
    requested: "طُلب",
    expires: "ينتهي",
    expired: "انتهى",
    decidedBy: "قرار",
    reason: "السبب",
    args: "المعاملات",
    redacted: "مخفي",
    criteria: "المعايير",
    pass: "ناجح",
    fail: "غير ناجح",
    unmet: (n: number) => (n === 1 ? "معيار واحد غير مستوفى" : n === 2 ? "معياران غير مستوفيين" : n <= 10 ? `${n} معايير غير مستوفاة` : `${n} معيارًا غير مستوفى`),
    approve: "موافقة",
    approveFor: (t: string) => `الموافقة على ${t}`,
    reject: "رفض",
    rejectFor: (t: string) => `رفض ${t}`,
    convert: "تحويل",
    convertFor: (t: string) => `تحويل ${t}`,
    blocked: "عالج المعايير غير المستوفاة قبل الموافقة.",
    rejectTitle: (t: string) => `رفض ${t}؟`,
    rejectBody: "سيرى صاحب الطلب السبب الذي تكتبه.",
    reasonLabel: "السبب",
    reasonPlaceholder: "اكتب سبب الرفض",
    reasonRequired: "اكتب سببًا.",
    cancel: "إلغاء",
    failed: "تعذّر حفظ القرار. حاول مرة أخرى.",
    list: "طلبات الموافقة",
  },
};
export const strings = (locale: string) => STRINGS[locale.startsWith("ar") ? "ar" : "en"];

export type Strings = typeof STRINGS.en;
export type Labels = Partial<Strings>;
