import { TTL_AUTO, type DnsErrorCode, type TtlUnits } from "./format";

export const DNS_STRINGS = {
  en: {
    title: "DNS records",
    description: (zone: string) => `Records for ${zone}. Changes can take a few minutes to reach everyone.`,
    add: "Add record",
    search: "Search records",
    typeFilter: "Type",
    table: "DNS records",
    type: "Type",
    name: "Name",
    content: "Content",
    ttl: "TTL",
    proxy: "Proxy",
    actions: "Actions",
    proxied: "Proxied",
    dnsOnly: "DNS only",
    proxyFor: (name: string) => `Proxy for ${name}`,
    edit: "Edit",
    remove: "Delete",
    emptyTitle: "No DNS records yet",
    emptyBody: "Add an A or CNAME record to point your domain at a server.",
    addTitle: "Add a DNS record",
    editTitle: "Edit DNS record",
    formBody: "Names are relative to the zone. Use @ for the root.",
    nameLabel: "Name",
    namePlaceholder: "@ or www",
    nameHint: (full: string) => `Full name: ${full}`,
    contentLabel: "Content",
    contentPlaceholder: { A: "203.0.113.10", AAAA: "2001:db8::1", CNAME: "target.example.com", MX: "mail.example.com", TXT: "v=spf1 include:_spf.example.com ~all", NS: "ns1.example.com", SRV: "target.example.com", CAA: '0 issue "letsencrypt.org"' } as Record<string, string>,
    priority: "Priority",
    ttlLabel: "TTL",
    proxyLabel: "Proxy through the network",
    proxyHint: "Hides the origin address and adds caching and protection. Only for A, AAAA and CNAME.",
    commentLabel: "Comment",
    commentPlaceholder: "What this record is for",
    cancel: "Cancel",
    save: "Save record",
    saveAdd: "Add record",
    deleteTitle: (name: string) => `Delete ${name}?`,
    deleteBody: "Anything that relies on this record stops resolving once the change spreads. This cannot be undone.",
    deleteConfirm: "Delete record",
    genericError: "Something went wrong. Try again.",
    errors: {
      name: "Use letters, digits, hyphens and dots, or @ for the root.",
      content: "Enter the record content.",
      ipv4: "Enter a valid IPv4 address, like 203.0.113.10.",
      ipv6: "Enter a valid IPv6 address, like 2001:db8::1.",
      hostname: "Enter a valid host name, like target.example.com.",
      priority: "Priority is a whole number from 0 to 65535.",
      ttl: "TTL is Auto or between 30 seconds and 1 day.",
      cnameApex: "A CNAME cannot sit at the root of the zone.",
      conflict: "A CNAME cannot share a name with another record.",
      duplicate: "An identical record already exists.",
    } satisfies Record<DnsErrorCode, string>,
    ttlUnits: {
      auto: "Auto",
      seconds: (n: number) => `${n} sec`,
      minutes: (n: number) => `${n} min`,
      hours: (n: number) => (n === 1 ? "1 hour" : `${n} hours`),
      days: (n: number) => (n === 1 ? "1 day" : `${n} days`),
    } satisfies TtlUnits,
  },
  ar: {
    title: "سجلات DNS",
    description: (zone: string) => `سجلات ${zone}. قد يستغرق وصول التغييرات إلى الجميع بضع دقائق.`,
    add: "إضافة سجل",
    search: "ابحث في السجلات",
    typeFilter: "النوع",
    table: "سجلات DNS",
    type: "النوع",
    name: "الاسم",
    content: "المحتوى",
    ttl: "TTL",
    proxy: "الوكيل",
    actions: "إجراءات",
    proxied: "عبر الوكيل",
    dnsOnly: "DNS فقط",
    proxyFor: (name: string) => `الوكيل لـ ${name}`,
    edit: "تعديل",
    remove: "حذف",
    emptyTitle: "لا توجد سجلات DNS بعد",
    emptyBody: "أضف سجل A أو CNAME لتوجيه نطاقك إلى خادم.",
    addTitle: "إضافة سجل DNS",
    editTitle: "تعديل سجل DNS",
    formBody: "الأسماء نسبية إلى النطاق. استخدم @ للجذر.",
    nameLabel: "الاسم",
    namePlaceholder: "@ أو www",
    nameHint: (full: string) => `الاسم الكامل: ${full}`,
    contentLabel: "المحتوى",
    contentPlaceholder: { A: "203.0.113.10", AAAA: "2001:db8::1", CNAME: "target.example.com", MX: "mail.example.com", TXT: "v=spf1 include:_spf.example.com ~all", NS: "ns1.example.com", SRV: "target.example.com", CAA: '0 issue "letsencrypt.org"' } as Record<string, string>,
    priority: "الأولوية",
    ttlLabel: "TTL",
    proxyLabel: "المرور عبر الشبكة",
    proxyHint: "يخفي عنوان الخادم الأصلي ويضيف التخزين المؤقت والحماية. لسجلات A وAAAA وCNAME فقط.",
    commentLabel: "تعليق",
    commentPlaceholder: "الغرض من هذا السجل",
    cancel: "إلغاء",
    save: "حفظ السجل",
    saveAdd: "إضافة السجل",
    deleteTitle: (name: string) => `حذف ${name}؟`,
    deleteBody: "أي شيء يعتمد على هذا السجل يتوقف عن العمل بعد انتشار التغيير. لا يمكن التراجع.",
    deleteConfirm: "حذف السجل",
    genericError: "حدث خطأ ما. حاول مرة أخرى.",
    errors: {
      name: "استخدم أحرفًا وأرقامًا وشرطات ونقاطًا، أو @ للجذر.",
      content: "أدخل محتوى السجل.",
      ipv4: "أدخل عنوان IPv4 صالحًا مثل 203.0.113.10.",
      ipv6: "أدخل عنوان IPv6 صالحًا مثل 2001:db8::1.",
      hostname: "أدخل اسم مضيف صالحًا مثل target.example.com.",
      priority: "الأولوية عدد صحيح من 0 إلى 65535.",
      ttl: "TTL تلقائي أو بين 30 ثانية ويوم واحد.",
      cnameApex: "لا يمكن وضع CNAME في جذر النطاق.",
      conflict: "لا يمكن أن يشترك CNAME في الاسم مع سجل آخر.",
      duplicate: "يوجد سجل مطابق بالفعل.",
    } satisfies Record<DnsErrorCode, string>,
    ttlUnits: {
      auto: "تلقائي",
      seconds: (n: number) => `${n} ثانية`,
      minutes: (n: number) => `${n} دقيقة`,
      hours: (n: number) => (n === 1 ? "ساعة" : n === 2 ? "ساعتان" : `${n} ساعات`),
      days: (n: number) => (n === 1 ? "يوم" : n === 2 ? "يومان" : `${n} أيام`),
    } satisfies TtlUnits,
  },
};

export type DnsManagementLabels = (typeof DNS_STRINGS)["en"];
