import { formatNumber } from "../numeric";
import type { PortalRequestStatus, PortalTaskStatus } from "./portal-logic";

export const STRINGS = {
  en: {
    tabs: { overview: "Overview", board: "Board", requests: "Requests", time: "Time", invoices: "Invoices", activity: "Activity" },
    progress: "Progress",
    tasksDone: (done: number, total: number) => `${done} of ${total} tasks done`,
    percentDone: "done",
    hoursUsed: "Hours used",
    hoursBudget: "Budget",
    hoursLeft: "Hours left",
    openIssues: "Open issues",
    pendingRequests: "Waiting for a reply",
    weekly: "Hours per week",
    weeklyLabel: (n: number) => `Hours in the last ${n} weeks`,
    budgetUsed: (used: string, budget: string) => `${used} of ${budget} hours used`,
    overBudget: "Over budget",
    noBudget: "No hours budget set",
    weekOf: "Week of",
    hours: "Hours",
    boardNote: "A read-only view of the board.",
    columns: { todo: "To do", doing: "In progress", review: "In review", done: "Done" } as Record<PortalTaskStatus, string>,
    noCards: "Nothing here",
    unassigned: "Unassigned",
    requests: "Requests",
    newRequest: "Ask for something",
    requestTitle: "What do you need?",
    requestDetails: "Details",
    requestDetailsOptional: "(optional)",
    send: "Send request",
    titleRequired: "Tell us what you need.",
    sent: "Sent. We will reply here.",
    noRequests: "No requests yet",
    noRequestsBody: "Ask for a change or a new feature and it shows up here.",
    requestStatus: { pending: "Waiting", accepted: "Accepted", declined: "Declined", done: "Done" } as Record<PortalRequestStatus, string>,
    by: "By",
    timeTitle: "Time",
    total: "Total hours",
    weeksTable: "Hours by week",
    noTime: "No hours logged yet",
    invoices: "Invoices",
    noInvoices: "No invoices yet",
    noInvoicesBody: "Invoices appear here once they are sent to you.",
    activity: "Activity",
    noActivity: "Nothing has happened yet",
    due: "Due",
  },
  ar: {
    tabs: { overview: "نظرة عامة", board: "اللوحة", requests: "الطلبات", time: "الوقت", invoices: "الفواتير", activity: "النشاط" },
    progress: "التقدم",
    tasksDone: (done: number, total: number) => `أُنجزت ${formatNumber(done, "ar")} من ${formatNumber(total, "ar")} مهمة`,
    percentDone: "مكتمل",
    hoursUsed: "الساعات المستخدمة",
    hoursBudget: "الميزانية",
    hoursLeft: "الساعات المتبقية",
    openIssues: "مشكلات مفتوحة",
    pendingRequests: "بانتظار الرد",
    weekly: "الساعات في الأسبوع",
    weeklyLabel: (n: number) => `الساعات في آخر ${formatNumber(n, "ar")} أسابيع`,
    budgetUsed: (used: string, budget: string) => `استُخدمت ${used} من ${budget} ساعة`,
    overBudget: "تجاوزت الميزانية",
    noBudget: "لا توجد ميزانية ساعات",
    weekOf: "أسبوع",
    hours: "الساعات",
    boardNote: "عرض للقراءة فقط للوحة.",
    columns: { todo: "للتنفيذ", doing: "قيد التنفيذ", review: "قيد المراجعة", done: "منجز" } as Record<PortalTaskStatus, string>,
    noCards: "لا شيء هنا",
    unassigned: "بلا مسؤول",
    requests: "الطلبات",
    newRequest: "اطلب شيئًا",
    requestTitle: "ماذا تحتاج؟",
    requestDetails: "التفاصيل",
    requestDetailsOptional: "(اختياري)",
    send: "إرسال الطلب",
    titleRequired: "أخبرنا بما تحتاجه.",
    sent: "أُرسل. سنرد عليك هنا.",
    noRequests: "لا طلبات بعد",
    noRequestsBody: "اطلب تعديلًا أو ميزة جديدة وستظهر هنا.",
    requestStatus: { pending: "بانتظار الرد", accepted: "مقبول", declined: "مرفوض", done: "منجز" } as Record<PortalRequestStatus, string>,
    by: "بواسطة",
    timeTitle: "الوقت",
    total: "إجمالي الساعات",
    weeksTable: "الساعات حسب الأسبوع",
    noTime: "لم تُسجَّل ساعات بعد",
    invoices: "الفواتير",
    noInvoices: "لا فواتير بعد",
    noInvoicesBody: "تظهر الفواتير هنا بعد إرسالها إليك.",
    activity: "النشاط",
    noActivity: "لم يحدث شيء بعد",
    due: "الاستحقاق",
  },
};

export type PortalStrings = typeof STRINGS.en;
export type ClientPortalLabels = Partial<PortalStrings>;
export type ClientPortalTab = keyof PortalStrings["tabs"];
