import { computed, type ComputedRef } from "vue";
import { useNasaq } from "../../provider";
import type { JobStatus, PackageKind, ServiceAction, ServiceState, SshKeyProblem } from "./format";

export const SERVER_ADMIN_STRINGS = {
  en: {
    genericError: "Something went wrong. Try again.",
    cancel: "Cancel",
    dismiss: "Dismiss",
    search: "Search…",
    // services
    servicesTitle: "Services",
    servicesDescription: "Systemd units on this server. Start, stop, restart or choose what runs at boot.",
    servicesTable: "Service units",
    service: "Service",
    state: "State",
    boot: "At boot",
    memory: "Memory",
    since: "Since",
    states: { active: "Running", inactive: "Stopped", failed: "Failed", activating: "Starting", deactivating: "Stopping", reloading: "Reloading" } satisfies Record<ServiceState, string>,
    enabledAtBoot: "Enabled",
    disabledAtBoot: "Disabled",
    actions: { start: "Start", stop: "Stop", restart: "Restart", reload: "Reload", enable: "Enable at boot", disable: "Disable at boot" } satisfies Record<ServiceAction, string>,
    viewLogs: "View logs",
    working: "Working",
    confirmAction: (action: string, name: string) => `${action} ${name}?`,
    confirmStop: "Anything that depends on this service stops working until it is started again.",
    confirmRestart: "The service is interrupted for a moment while it restarts.",
    confirmDisable: "The service will not start by itself after a reboot.",
    servicesEmpty: "No services",
    // packages
    packagesTitle: "Package updates",
    packagesDescription: "Updates waiting on this server.",
    packagesTable: "Available updates",
    package: "Package",
    version: "Version",
    kind: "Type",
    size: "Size",
    kinds: { security: "Security", kernel: "Kernel", regular: "Update" } satisfies Record<PackageKind, string>,
    upToDate: "Everything is up to date",
    upToDateBody: "There are no updates waiting.",
    lastChecked: "Last checked",
    neverChecked: "Not checked yet",
    checkNow: "Check for updates",
    checking: "Checking",
    updateAll: "Update all",
    updateAllTitle: (n: number) => `Update ${n} packages?`,
    updateAllBody: "Services that use an updated library may restart.",
    updateSelected: "Update selected",
    updateOne: "Update",
    updating: "Updating",
    securityCount: (n: number) => `${n} security`,
    totalCount: (n: number) => (n === 1 ? "1 update" : `${n} updates`),
    download: (size: string) => `${size} to download`,
    rebootTitle: "A restart is needed",
    rebootBody: "A kernel or core library was updated. Restart the server to use it.",
    reboot: "Restart server",
    rebootConfirmTitle: "Restart the server?",
    rebootConfirmBody: "Everything on it is offline for a minute or two.",
    // ssh
    sshTitle: "SSH keys",
    sshDescription: "Which keys can sign in to which server. Tick a box to install or remove a key.",
    sshTable: "SSH keys by server",
    sshKey: "Key",
    sshCoverage: (n: number, total: number) => `${n} of ${total}`,
    sshServers: "Servers",
    addKey: "Add key",
    addKeyTitle: "Add an SSH key",
    addKeyBody: "Paste the public key, the one that ends in .pub. Never paste a private key.",
    keyName: "Name",
    keyNamePlaceholder: "Laptop",
    keyNameRequired: "Give the key a name.",
    publicKey: "Public key",
    keyProblems: {
      empty: "Paste the public key.",
      format: "A public key is one line: the type, the key, and an optional comment.",
      type: "This key type is not recognised. Use ssh-ed25519, ssh-rsa or ecdsa.",
      body: "The key text looks damaged. Copy it again.",
      private: "That is a private key. Never paste it. Paste the .pub file instead.",
    } satisfies Record<SshKeyProblem, string>,
    keyDetected: (type: string, comment: string) => (comment ? `${type} key, ${comment}` : `${type} key`),
    addedOn: "Added",
    lastUsed: "Last used",
    never: "Never",
    installOnAll: "Install on all servers",
    removeFromAll: "Remove from all servers",
    deleteKey: "Delete key",
    deleteKeyTitle: (name: string) => `Delete ${name}?`,
    deleteKeyBody: "The key is removed from every server it is installed on. Anyone using it can no longer sign in.",
    installedOn: (key: string, server: string) => `${key} on ${server}`,
    noKeys: "No SSH keys yet",
    noKeysBody: "Add a public key, then choose the servers it can sign in to.",
    // jobs
    jobsTitle: "Job queue",
    jobsDescription: "Background work, by status. Retry what failed, or forget it.",
    jobsTable: "Jobs",
    job: "Job",
    queue: "Queue",
    attempts: "Attempts",
    when: "When",
    status: "Status",
    jobStatuses: { waiting: "Waiting", active: "Running", delayed: "Delayed", completed: "Done", failed: "Failed" } satisfies Record<JobStatus, string>,
    retry: "Retry",
    forget: "Forget",
    retryFailed: "Retry all failed",
    forgetFailed: "Forget all failed",
    forgetTitle: (n: number) => (n === 1 ? "Forget this job?" : `Forget ${n} jobs?`),
    forgetBody: "They are removed from the queue and the history. This cannot be undone.",
    retryTitle: (n: number) => (n === 1 ? "Retry this job?" : `Retry ${n} jobs?`),
    retryBody: "They go back to the queue and run again.",
    details: "Details",
    errorLabel: "Error",
    payloadLabel: "Payload",
    noError: "No error recorded.",
    close: "Close",
    jobsEmpty: "No jobs",
    of: (a: number, b: number) => `${a}/${b}`,
    queueFilter: "Queue",
    statusGroup: "Job status",
  },
  ar: {
    genericError: "حدث خطأ ما. حاول مرة أخرى.",
    cancel: "إلغاء",
    dismiss: "إغلاق",
    search: "بحث…",
    servicesTitle: "الخدمات",
    servicesDescription: "وحدات systemd على هذا الخادم. شغّلها أو أوقفها أو أعد تشغيلها أو اختر ما يعمل عند الإقلاع.",
    servicesTable: "وحدات الخدمات",
    service: "الخدمة",
    state: "الحالة",
    boot: "عند الإقلاع",
    memory: "الذاكرة",
    since: "منذ",
    states: { active: "تعمل", inactive: "متوقفة", failed: "فشلت", activating: "قيد البدء", deactivating: "قيد الإيقاف", reloading: "قيد إعادة التحميل" } satisfies Record<ServiceState, string>,
    enabledAtBoot: "مفعّلة",
    disabledAtBoot: "معطّلة",
    actions: { start: "تشغيل", stop: "إيقاف", restart: "إعادة التشغيل", reload: "إعادة تحميل الإعدادات", enable: "تفعيل عند الإقلاع", disable: "تعطيل عند الإقلاع" } satisfies Record<ServiceAction, string>,
    viewLogs: "عرض السجلات",
    working: "جارٍ التنفيذ",
    confirmAction: (action: string, name: string) => `${action}: ${name}؟`,
    confirmStop: "كل ما يعتمد على هذه الخدمة يتوقف عن العمل إلى أن تُشغَّل من جديد.",
    confirmRestart: "تتوقف الخدمة لحظة أثناء إعادة التشغيل.",
    confirmDisable: "لن تبدأ الخدمة وحدها بعد إعادة تشغيل الخادم.",
    servicesEmpty: "لا توجد خدمات",
    packagesTitle: "تحديثات الحزم",
    packagesDescription: "التحديثات المتاحة لهذا الخادم.",
    packagesTable: "التحديثات المتاحة",
    package: "الحزمة",
    version: "الإصدار",
    kind: "النوع",
    size: "الحجم",
    kinds: { security: "أمني", kernel: "النواة", regular: "تحديث" } satisfies Record<PackageKind, string>,
    upToDate: "كل شيء محدَّث",
    upToDateBody: "لا توجد تحديثات بانتظارك.",
    lastChecked: "آخر فحص",
    neverChecked: "لم يُفحص بعد",
    checkNow: "فحص التحديثات",
    checking: "جارٍ الفحص",
    updateAll: "تحديث الكل",
    updateAllTitle: (n: number) => `تحديث ${n} حزمة؟`,
    updateAllBody: "قد تُعاد تشغيل الخدمات التي تستخدم مكتبة محدَّثة.",
    updateSelected: "تحديث المحدد",
    updateOne: "تحديث",
    updating: "جارٍ التحديث",
    securityCount: (n: number) => `${n} أمنية`,
    totalCount: (n: number) => (n === 1 ? "تحديث واحد" : n === 2 ? "تحديثان" : n <= 10 ? `${n} تحديثات` : `${n} تحديثًا`),
    download: (size: string) => `${size} للتنزيل`,
    rebootTitle: "يلزم إعادة التشغيل",
    rebootBody: "حُدِّثت النواة أو مكتبة أساسية. أعد تشغيل الخادم لتفعيلها.",
    reboot: "إعادة تشغيل الخادم",
    rebootConfirmTitle: "إعادة تشغيل الخادم؟",
    rebootConfirmBody: "كل ما عليه يتوقف دقيقة أو دقيقتين.",
    sshTitle: "مفاتيح SSH",
    sshDescription: "أي مفتاح يمكنه الدخول إلى أي خادم. علّم المربع لتثبيت المفتاح أو إزالته.",
    sshTable: "مفاتيح SSH حسب الخادم",
    sshKey: "المفتاح",
    sshCoverage: (n: number, total: number) => `${n} من ${total}`,
    sshServers: "الخوادم",
    addKey: "إضافة مفتاح",
    addKeyTitle: "إضافة مفتاح SSH",
    addKeyBody: "الصق المفتاح العام، وهو الذي ينتهي بـ .pub. لا تلصق المفتاح الخاص أبدًا.",
    keyName: "الاسم",
    keyNamePlaceholder: "الحاسوب المحمول",
    keyNameRequired: "أعطِ المفتاح اسمًا.",
    publicKey: "المفتاح العام",
    keyProblems: {
      empty: "الصق المفتاح العام.",
      format: "المفتاح العام سطر واحد: النوع ثم المفتاح ثم تعليق اختياري.",
      type: "نوع المفتاح غير معروف. استخدم ssh-ed25519 أو ssh-rsa أو ecdsa.",
      body: "نص المفتاح يبدو تالفًا. انسخه مرة أخرى.",
      private: "هذا مفتاح خاص. لا تلصقه أبدًا. الصق ملف .pub بدلًا منه.",
    } satisfies Record<SshKeyProblem, string>,
    keyDetected: (type: string, comment: string) => (comment ? `مفتاح ${type}، ${comment}` : `مفتاح ${type}`),
    addedOn: "أُضيف",
    lastUsed: "آخر استخدام",
    never: "أبدًا",
    installOnAll: "تثبيت على كل الخوادم",
    removeFromAll: "إزالة من كل الخوادم",
    deleteKey: "حذف المفتاح",
    deleteKeyTitle: (name: string) => `حذف ${name}؟`,
    deleteKeyBody: "يُزال المفتاح من كل خادم ثُبِّت عليه، ولا يستطيع من يستخدمه الدخول بعد الآن.",
    installedOn: (key: string, server: string) => `${key} على ${server}`,
    noKeys: "لا توجد مفاتيح SSH بعد",
    noKeysBody: "أضف مفتاحًا عامًا ثم اختر الخوادم التي يمكنه الدخول إليها.",
    jobsTitle: "طابور المهام",
    jobsDescription: "العمل في الخلفية حسب الحالة. أعد محاولة ما فشل أو انسَه.",
    jobsTable: "المهام",
    job: "المهمة",
    queue: "الطابور",
    attempts: "المحاولات",
    when: "الوقت",
    status: "الحالة",
    jobStatuses: { waiting: "بالانتظار", active: "تعمل", delayed: "مؤجلة", completed: "منتهية", failed: "فاشلة" } satisfies Record<JobStatus, string>,
    retry: "إعادة المحاولة",
    forget: "نسيان",
    retryFailed: "إعادة محاولة كل الفاشلة",
    forgetFailed: "نسيان كل الفاشلة",
    forgetTitle: (n: number) => (n === 1 ? "نسيان هذه المهمة؟" : `نسيان ${n} مهام؟`),
    forgetBody: "تُزال من الطابور ومن السجل. لا يمكن التراجع.",
    retryTitle: (n: number) => (n === 1 ? "إعادة محاولة هذه المهمة؟" : `إعادة محاولة ${n} مهام؟`),
    retryBody: "تعود إلى الطابور وتعمل من جديد.",
    details: "التفاصيل",
    errorLabel: "الخطأ",
    payloadLabel: "البيانات",
    noError: "لا يوجد خطأ مسجَّل.",
    close: "إغلاق",
    jobsEmpty: "لا توجد مهام",
    of: (a: number, b: number) => `${a}/${b}`,
    queueFilter: "الطابور",
    statusGroup: "حالة المهام",
  },
};

export type ServerAdminLabels = (typeof SERVER_ADMIN_STRINGS)["en"];

export function useServerAdminLabels(override: () => Partial<ServerAdminLabels> | undefined): ComputedRef<ServerAdminLabels> {
  const nq = useNasaq();
  return computed(() => ({ ...SERVER_ADMIN_STRINGS[nq.locale.value.startsWith("ar") ? "ar" : "en"], ...override() }) as ServerAdminLabels);
}
